---------------------------------------------------------
           PHAML   Version 1.9.1

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  300
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 2
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    SLAVES
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree                      3
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             CG_SOLVER
  preconditioner     MG_PRECONDITION
  mg_cycles                   2
  mg_tol             MG_NO_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_NONE
  krylov_iter               100
  krylov_tol         KRYLOV_ERREST_TOL
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =          98
   degrees of freedom I own =          98
   min and max degree       =           3          3

Norms of error:
   energy norm of error       7.2827782755E-03
   energy error estimate      4.3300799845E-03
      effectivity             5.9456430234E-01
  Component           1
   Linf norm of error         4.7528204810E-04
   Linf error estimate        8.9862912630E-04
      effectivity             1.8907281053E+00
  Component           2
   Linf norm of error         7.9720934633E-04
   Linf error estimate        1.4963601204E-03
      effectivity             1.8769977137E+00

My Grid:
   number of vertices       =          19
   number of vertices I own =          19
   number of elements       =          44
   number of leaf elements  =          26
   leaf elements I own      =          26
   number of levels         =           3
   degrees of freedom       =         266
   degrees of freedom I own =         266
   min and max degree       =           3          3

Norms of error:
   energy norm of error       1.1845454325E-03
      reduced by              1.6265021228E-01
   energy error estimate      9.5440542456E-04
      reduced by              2.2041288567E-01
      effectivity             8.0571449468E-01
  Component           1
   Linf norm of error         4.7056108466E-05
      reduced by              9.9006702766E-02
   Linf error estimate        7.8898927262E-05
      reduced by              8.7799209877E-02
      effectivity             1.6766989416E+00
  Component           2
   Linf norm of error         1.1992451296E-04
      reduced by              1.5043039009E-01
   Linf error estimate        1.9217939982E-04
      reduced by              1.2843124940E-01
      effectivity             1.6025030670E+00

My Grid:
   number of vertices       =          33
   number of vertices I own =          33
   number of elements       =          88
   number of leaf elements  =          48
   leaf elements I own      =          48
   number of levels         =           4
   degrees of freedom       =         482
   degrees of freedom I own =         482
   min and max degree       =           3          3

Norms of error:
   energy norm of error       3.7462426681E-04
      reduced by              3.1625993950E-01
   energy error estimate      2.8883865667E-04
      reduced by              3.0263727473E-01
      effectivity             7.7100893418E-01
  Component           1
   Linf norm of error         3.6064432268E-05
      reduced by              7.6641340399E-01
   Linf error estimate        7.7395284252E-05
      reduced by              9.8094216155E-01
      effectivity             2.1460280777E+00
  Component           2
   Linf norm of error         8.2813118048E-06
      reduced by              6.9054370960E-02
   Linf error estimate        2.3873121474E-05
      reduced by              1.2422310349E-01
      effectivity             2.8827705122E+00

My Grid:
   number of vertices       =          69
   number of vertices I own =          69
   number of elements       =         220
   number of leaf elements  =         114
   leaf elements I own      =         114
   number of levels         =           5
   degrees of freedom       =        1094
   degrees of freedom I own =        1094
   min and max degree       =           3          3

Norms of error:
   energy norm of error       1.3195959949E-04
      reduced by              3.5224519921E-01
   energy error estimate      1.0024449167E-04
      reduced by              3.4706051061E-01
      effectivity             7.5966047225E-01
  Component           1
   Linf norm of error         2.5634951426E-06
      reduced by              7.1080978720E-02
   Linf error estimate        5.1597968715E-06
      reduced by              6.6668104154E-02
      effectivity             2.0127976003E+00
  Component           2
   Linf norm of error         8.1232859404E-06
      reduced by              9.8091777388E-01
   Linf error estimate        1.2389782073E-05
      reduced by              5.1898458636E-01
      effectivity             1.5252180170E+00

My Grid:
   number of vertices       =         114
   number of vertices I own =         114
   number of elements       =         380
   number of leaf elements  =         194
   leaf elements I own      =         194
   number of levels         =           6
   degrees of freedom       =        1844
   degrees of freedom I own =        1844
   min and max degree       =           3          3

Norms of error:
   energy norm of error       4.3205052092E-05
      reduced by              3.2741120963E-01
   energy error estimate      3.4820720182E-05
      reduced by              3.4735794060E-01
      effectivity             8.0594093737E-01
  Component           1
   Linf norm of error         2.4093560267E-06
      reduced by              9.3987150069E-01
   Linf error estimate        4.2589133013E-06
      reduced by              8.2540328764E-01
      effectivity             1.7676562758E+00
  Component           2
   Linf norm of error         5.0797316910E-07
      reduced by              6.2532966687E-02
   Linf error estimate        1.4900688191E-06
      reduced by              1.2026594256E-01
      effectivity             2.9333612674E+00

My Grid:
   number of vertices       =         261
   number of vertices I own =         261
   number of elements       =         944
   number of leaf elements  =         476
   leaf elements I own      =         476
   number of levels         =           7
   degrees of freedom       =        4418
   degrees of freedom I own =        4418
   min and max degree       =           3          3

Norms of error:
   energy norm of error       1.5435052367E-05
      reduced by              3.5725109956E-01
   energy error estimate      1.1217906275E-05
      reduced by              3.2216181103E-01
      effectivity             7.2678122553E-01
  Component           1
   Linf norm of error         1.7695352605E-07
      reduced by              7.3444324581E-02
   Linf error estimate        3.4457351775E-07
      reduced by              8.0906441002E-02
      effectivity             1.9472543183E+00
  Component           2
   Linf norm of error         5.1174552033E-07
      reduced by              1.0074262805E+00
   Linf error estimate        7.9416622377E-07
      reduced by              5.3297284903E-01
      effectivity             1.5518772363E+00

My Grid:
   number of vertices       =         421
   number of vertices I own =         421
   number of elements       =        1544
   number of leaf elements  =         776
   leaf elements I own      =         776
   number of levels         =           8
   degrees of freedom       =        7178
   degrees of freedom I own =        7178
   min and max degree       =           3          3

Norms of error:
   energy norm of error       5.3488265825E-06
      reduced by              3.4653763755E-01
   energy error estimate      4.3581493894E-06
      reduced by              3.8849935831E-01
      effectivity             8.1478606984E-01
  Component           1
   Linf norm of error         1.5855861513E-07
      reduced by              8.9604665509E-01
   Linf error estimate        2.8535094413E-07
      reduced by              8.2812790140E-01
      effectivity             1.7996558806E+00
  Component           2
   Linf norm of error         3.1676485018E-08
      reduced by              6.1898900449E-02
   Linf error estimate        9.3114502791E-08
      reduced by              1.1724812766E-01
      effectivity             2.9395465670E+00

My Grid:
   number of vertices       =         421
   number of vertices I own =         421
   number of elements       =        1544
   number of leaf elements  =         776
   leaf elements I own      =         776
   number of levels         =           8
   degrees of freedom       =        7178
   degrees of freedom I own =        7178
   min and max degree       =           3          3

Norms of error:
   energy norm of error       5.3488265825E-06
   energy error estimate      4.3581493894E-06
      effectivity             8.1478606984E-01
  Component           1
   Linf norm of error         1.5855861513E-07
   Linf error estimate        2.8535094413E-07
      effectivity             1.7996558806E+00
  Component           2
   Linf norm of error         3.1676485018E-08
   Linf error estimate        9.3114502791E-08
      effectivity             2.9395465670E+00

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
Linf errors from query  1.585586151265E-07 3.167648501834E-08
