---------------------------------------------------------
           PHAML   Version 1.11.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  300
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 2
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         false
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree                      3
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             CG_SOLVER
  preconditioner     MG_PRECONDITION
  mg_cycles                   2
  mg_tol             MG_NO_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_NONE
  krylov_iter               100
  krylov_tol         KRYLOV_ERREST_TOL
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =          98
   min and max degree      =           3          3

Norms of error:
   energy norm of error       7.2826682435E-03
   energy error estimate      7.2475365048E-03
      effectivity             9.9517597979E-01
  Component           1
   Linf norm of error         4.7519868165E-04
   Linf error estimate        5.2470252984E-04
      effectivity             1.1041750537E+00
  Component           2
   Linf norm of error         7.9515255555E-04
   Linf error estimate        8.3178421043E-04
      effectivity             1.0460687130E+00

Total Grid:
   number of vertices      =          19
   number of leaf elements =          26
   number of levels        =           3
   degrees of freedom      =         266
   min and max degree      =           3          3

Norms of error:
   energy norm of error       1.1845432850E-03
      reduced by              1.6265237484E-01
   energy error estimate      1.5924981851E-03
      reduced by              2.1972958454E-01
      effectivity             1.3443984744E+00
  Component           1
   Linf norm of error         4.7046448031E-05
      reduced by              9.9003742744E-02
   Linf error estimate        4.3829996402E-05
      reduced by              8.3533038072E-02
      effectivity             9.3163242363E-01
  Component           2
   Linf norm of error         1.1992133590E-04
      reduced by              1.5081550711E-01
   Linf error estimate        1.0675871510E-04
      reduced by              1.2834905227E-01
      effectivity             8.9023954164E-01

Total Grid:
   number of vertices      =          33
   number of leaf elements =          48
   number of levels        =           4
   degrees of freedom      =         482
   min and max degree      =           3          3

Norms of error:
   energy norm of error       3.7462342134E-04
      reduced by              3.1625979911E-01
   energy error estimate      4.8872802444E-04
      reduced by              3.0689392867E-01
      effectivity             1.3045848086E+00
  Component           1
   Linf norm of error         3.6063996565E-05
      reduced by              7.6656151685E-01
   Linf error estimate        4.5127867780E-05
      reduced by              1.0296114872E+00
      effectivity             1.2513274201E+00
  Component           2
   Linf norm of error         8.1593541974E-06
      reduced by              6.8039220348E-02
   Linf error estimate        1.3257410934E-05
      reduced by              1.2418106495E-01
      effectivity             1.6248113041E+00

Total Grid:
   number of vertices      =          55
   number of leaf elements =          90
   number of levels        =           5
   degrees of freedom      =         866
   min and max degree      =           3          3

Norms of error:
   energy norm of error       1.6318846461E-04
      reduced by              4.3560667944E-01
   energy error estimate      2.3412302924E-04
      reduced by              4.7904563997E-01
      effectivity             1.4346787918E+00
  Component           1
   Linf norm of error         4.2236665041E-06
      reduced by              1.1711587473E-01
   Linf error estimate        4.0100615410E-06
      reduced by              8.8859982496E-02
      effectivity             9.4942665032E-01
  Component           2
   Linf norm of error         8.1244930342E-06
      reduced by              9.9572746049E-01
   Linf error estimate        7.0714486465E-06
      reduced by              5.3339590073E-01
      effectivity             8.7038644955E-01

Total Grid:
   number of vertices      =         114
   number of leaf elements =         194
   number of levels        =           6
   degrees of freedom      =        1844
   min and max degree      =           3          3

Norms of error:
   energy norm of error       4.3205027443E-05
      reduced by              2.6475540135E-01
   energy error estimate      5.9015724879E-05
      reduced by              2.5207142190E-01
      effectivity             1.3659457793E+00
  Component           1
   Linf norm of error         2.4093885305E-06
      reduced by              5.7044952013E-01
   Linf error estimate        2.4852135020E-06
      reduced by              6.1974447937E-01
      effectivity             1.0314706286E+00
  Component           2
   Linf norm of error         5.1095373686E-07
      reduced by              6.2890537872E-02
   Linf error estimate        8.2757155921E-07
      reduced by              1.1702998927E-01
      effectivity             1.6196604497E+00

Total Grid:
   number of vertices      =         252
   number of leaf elements =         461
   number of levels        =           7
   degrees of freedom      =        4274
   min and max degree      =           3          3

Norms of error:
   energy norm of error       1.6128753653E-05
      reduced by              1.8665366749E-01
   energy error estimate      2.0374326238E-05
      reduced by              1.7261777501E-01
      effectivity             1.2632300472E+00
  Component           1
   Linf norm of error         2.1741035572E-07
      reduced by              9.0234660359E-02
   Linf error estimate        2.0976104498E-07
      reduced by              8.4403631642E-02
      effectivity             9.6481625395E-01
  Component           2
   Linf norm of error         5.1183562543E-07
      reduced by              1.0017259656E+00
   Linf error estimate        4.4194079065E-07
      reduced by              5.3402124050E-01
      effectivity             8.6344280995E-01

Total Grid:
   number of vertices      =         421
   number of leaf elements =         776
   number of levels        =           8
   degrees of freedom      =        7178
   min and max degree      =           3          3

Norms of error:
   energy norm of error       5.3488192542E-06
      reduced by              3.3163252223E-01
   energy error estimate      7.3945525359E-06
      reduced by              3.6293482540E-01
      effectivity             1.3824644626E+00
  Component           1
   Linf norm of error         1.5856228952E-07
      reduced by              7.2932261666E-01
   Linf error estimate        1.6658547494E-07
      reduced by              7.9416783494E-01
      effectivity             1.0505995811E+00
  Component           2
   Linf norm of error         3.1909628551E-08
      reduced by              6.2343508277E-02
   Linf error estimate        5.1709803421E-08
      reduced by              1.1700617937E-01
      effectivity             1.6205078457E+00

Total Grid:
   number of vertices      =         421
   number of leaf elements =         776
   number of levels        =           8
   degrees of freedom      =        7178
   min and max degree      =           3          3

Norms of error:
   energy norm of error       5.3488192542E-06
   energy error estimate      7.3945525359E-06
      effectivity             1.3824644626E+00
  Component           1
   Linf norm of error         1.5856228952E-07
   Linf error estimate        1.6658547494E-07
      effectivity             1.0505995811E+00
  Component           2
   Linf norm of error         3.1909628551E-08
   Linf error estimate        5.1709803421E-08
      effectivity             1.6205078457E+00

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
Linf errors from query  1.585622895206E-07 3.190962855060E-08
