---------------------------------------------------------
           PHAML   Version 1.11.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  300
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 2
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         false
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    SLAVES
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                   5
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =          18
   degrees of freedom I own =          18
   min and max degree       =           1          1

Norms of error:
   energy norm of error       9.2477317950E-01
   energy error estimate      8.9581543692E-01
      effectivity             9.6868665395E-01
  Component           1
   Linf norm of error         1.7164943122E-01
   Linf error estimate        1.2935342019E-01
      effectivity             7.5359073009E-01
  Component           2
   Linf norm of error         3.6384112011E-01
   Linf error estimate        2.6040344091E-01
      effectivity             7.1570646228E-01

My Grid:
   number of vertices       =          18
   number of vertices I own =          18
   number of elements       =          38
   number of leaf elements  =          23
   leaf elements I own      =          23
   number of levels         =           3
   degrees of freedom       =          36
   degrees of freedom I own =          36
   min and max degree       =           1          1

Norms of error:
   energy norm of error       4.4554045644E-01
      reduced by              4.8178349709E-01
   energy error estimate      4.8746482868E-01
      reduced by              5.4415765635E-01
      effectivity             1.0940977898E+00
  Component           1
   Linf norm of error         6.9347028310E-02
      reduced by              4.0400383397E-01
   Linf error estimate        6.2141614283E-02
      reduced by              4.8040178753E-01
      effectivity             8.9609628267E-01
  Component           2
   Linf norm of error         1.1646812764E-01
      reduced by              3.2010710501E-01
   Linf error estimate        7.4461903954E-02
      reduced by              2.8594823361E-01
      effectivity             6.3933288413E-01

My Grid:
   number of vertices       =          36
   number of vertices I own =          36
   number of elements       =          98
   number of leaf elements  =          53
   leaf elements I own      =          53
   number of levels         =           5
   degrees of freedom       =          72
   degrees of freedom I own =          72
   min and max degree       =           1          1

Norms of error:
   energy norm of error       2.5435718847E-01
      reduced by              5.7089582954E-01
   energy error estimate      3.1716655067E-01
      reduced by              6.5064499429E-01
      effectivity             1.2469337021E+00
  Component           1
   Linf norm of error         3.4994355583E-02
      reduced by              5.0462660673E-01
   Linf error estimate        2.3897500554E-02
      reduced by              3.8456517150E-01
      effectivity             6.8289586008E-01
  Component           2
   Linf norm of error         3.5849800267E-02
      reduced by              3.0780781827E-01
   Linf error estimate        2.7977341518E-02
      reduced by              3.7572691582E-01
      effectivity             7.8040439027E-01

My Grid:
   number of vertices       =          77
   number of vertices I own =          77
   number of elements       =         244
   number of leaf elements  =         126
   leaf elements I own      =         126
   number of levels         =           6
   degrees of freedom       =         154
   degrees of freedom I own =         154
   min and max degree       =           1          1

Norms of error:
   energy norm of error       1.7669269687E-01
      reduced by              6.9466366542E-01
   energy error estimate      2.0407487978E-01
      reduced by              6.4343128034E-01
      effectivity             1.1549706547E+00
  Component           1
   Linf norm of error         1.4646412483E-02
      reduced by              4.1853642507E-01
   Linf error estimate        9.8456512735E-03
      reduced by              4.1199502229E-01
      effectivity             6.7222272243E-01
  Component           2
   Linf norm of error         1.8918115097E-02
      reduced by              5.2770489532E-01
   Linf error estimate        1.0070950771E-02
      reduced by              3.5996811078E-01
      effectivity             5.3234430172E-01

My Grid:
   number of vertices       =         149
   number of vertices I own =         149
   number of elements       =         504
   number of leaf elements  =         256
   leaf elements I own      =         256
   number of levels         =           7
   degrees of freedom       =         298
   degrees of freedom I own =         298
   min and max degree       =           1          1

Norms of error:
   energy norm of error       1.2048830933E-01
      reduced by              6.8190882514E-01
   energy error estimate      1.4287218730E-01
      reduced by              7.0009688334E-01
      effectivity             1.1857763470E+00
  Component           1
   Linf norm of error         9.1734279192E-03
      reduced by              6.2632592996E-01
   Linf error estimate        5.5476518746E-03
      reduced by              5.6346215405E-01
      effectivity             6.0475232633E-01
  Component           2
   Linf norm of error         8.5181059955E-03
      reduced by              4.5026187608E-01
   Linf error estimate        5.1939221959E-03
      reduced by              5.1573305380E-01
      effectivity             6.0975082943E-01

My Grid:
   number of vertices       =         330
   number of vertices I own =         330
   number of elements       =        1196
   number of leaf elements  =         602
   leaf elements I own      =         602
   number of levels         =           9
   degrees of freedom       =         660
   degrees of freedom I own =         660
   min and max degree       =           1          1

Norms of error:
   energy norm of error       7.7558002089E-02
      reduced by              6.4369732233E-01
   energy error estimate      9.3271311240E-02
      reduced by              6.5283042839E-01
      effectivity             1.2026007469E+00
  Component           1
   Linf norm of error         3.4856482593E-03
      reduced by              3.7997227319E-01
   Linf error estimate        2.2220540951E-03
      reduced by              4.0053956978E-01
      effectivity             6.3748661075E-01
  Component           2
   Linf norm of error         4.2288800005E-03
      reduced by              4.9645778096E-01
   Linf error estimate        2.1866371460E-03
      reduced by              4.2099921091E-01
      effectivity             5.1707240350E-01

My Grid:
   number of vertices       =         330
   number of vertices I own =         330
   number of elements       =        1196
   number of leaf elements  =         602
   leaf elements I own      =         602
   number of levels         =           9
   degrees of freedom       =         660
   degrees of freedom I own =         660
   min and max degree       =           1          1

Norms of error:
   energy norm of error       7.7558002089E-02
   energy error estimate      9.3271311240E-02
      effectivity             1.2026007469E+00
  Component           1
   Linf norm of error         3.4856482593E-03
   Linf error estimate        2.2220540951E-03
      effectivity             6.3748661075E-01
  Component           2
   Linf norm of error         4.2288800005E-03
   Linf error estimate        2.1866371460E-03
      effectivity             5.1707240350E-01

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           5
termination condition:
  maximum vertices achieved
---------------------------------------------------------
Linf errors from query  3.485648259349E-03 4.228880000532E-03
