---------------------------------------------------------
           PHAML   Version 1.11.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  300
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 2
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         false
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                   5
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =          18
   min and max degree      =           1          1

Norms of error:
   energy norm of error       9.2477317950E-01
   energy error estimate      8.9581543692E-01
      effectivity             9.6868665395E-01
  Component           1
   Linf norm of error         1.7164943122E-01
   Linf error estimate        1.2935342019E-01
      effectivity             7.5359073009E-01
  Component           2
   Linf norm of error         3.6384112011E-01
   Linf error estimate        2.6040344091E-01
      effectivity             7.1570646228E-01

Total Grid:
   number of vertices      =          18
   number of leaf elements =          23
   number of levels        =           3
   degrees of freedom      =          36
   min and max degree      =           1          1

Norms of error:
   energy norm of error       4.4554045422E-01
      reduced by              4.8178349469E-01
   energy error estimate      4.8746476028E-01
      reduced by              5.4415758000E-01
      effectivity             1.0940976418E+00
  Component           1
   Linf norm of error         6.9346714150E-02
      reduced by              4.0400200372E-01
   Linf error estimate        6.2141612186E-02
      reduced by              4.8040177131E-01
      effectivity             8.9610031200E-01
  Component           2
   Linf norm of error         1.1646746066E-01
      reduced by              3.2010527185E-01
   Linf error estimate        7.4461902511E-02
      reduced by              2.8594822807E-01
      effectivity             6.3933653303E-01

Total Grid:
   number of vertices      =          36
   number of leaf elements =          53
   number of levels        =           5
   degrees of freedom      =          72
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.5435718865E-01
      reduced by              5.7089583279E-01
   energy error estimate      3.1716656007E-01
      reduced by              6.5064510487E-01
      effectivity             1.2469337381E+00
  Component           1
   Linf norm of error         3.4994424863E-02
      reduced by              5.0462989188E-01
   Linf error estimate        2.3897500161E-02
      reduced by              3.8456517815E-01
      effectivity             6.8289449688E-01
  Component           2
   Linf norm of error         3.5848558406E-02
      reduced by              3.0779891827E-01
   Linf error estimate        2.7977341174E-02
      reduced by              3.7572691847E-01
      effectivity             7.8043141533E-01

Total Grid:
   number of vertices      =          77
   number of leaf elements =         126
   number of levels        =           6
   degrees of freedom      =         154
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.7669269687E-01
      reduced by              6.9466366491E-01
   energy error estimate      2.0407487978E-01
      reduced by              6.4343126125E-01
      effectivity             1.1549706547E+00
  Component           1
   Linf norm of error         1.4646412485E-02
      reduced by              4.1853559653E-01
   Linf error estimate        9.8456512735E-03
      reduced by              4.1199502907E-01
      effectivity             6.7222272234E-01
  Component           2
   Linf norm of error         1.8918115087E-02
      reduced by              5.2772317574E-01
   Linf error estimate        1.0070950771E-02
      reduced by              3.5996811521E-01
      effectivity             5.3234430199E-01

Total Grid:
   number of vertices      =         149
   number of leaf elements =         256
   number of levels        =           7
   degrees of freedom      =         298
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.2048830934E-01
      reduced by              6.8190882516E-01
   energy error estimate      1.4287217986E-01
      reduced by              7.0009684687E-01
      effectivity             1.1857762852E+00
  Component           1
   Linf norm of error         9.1734151295E-03
      reduced by              6.2632505664E-01
   Linf error estimate        5.5476518786E-03
      reduced by              5.6346215446E-01
      effectivity             6.0475316992E-01
  Component           2
   Linf norm of error         8.5181157645E-03
      reduced by              4.5026239269E-01
   Linf error estimate        5.1939221437E-03
      reduced by              5.1573304862E-01
      effectivity             6.0975012401E-01

Total Grid:
   number of vertices      =         330
   number of leaf elements =         602
   number of levels        =           9
   degrees of freedom      =         660
   min and max degree      =           1          1

Norms of error:
   energy norm of error       7.7558002089E-02
      reduced by              3.2184866115E-01
   energy error estimate      9.3271311282E-02
      reduced by              3.2641523135E-01
      effectivity             1.2026007474E+00
  Component           1
   Linf norm of error         3.4856481160E-03
      reduced by              3.7997278732E-01
   Linf error estimate        2.2220540949E-03
      reduced by              4.0053956944E-01
      effectivity             6.3748663690E-01
  Component           2
   Linf norm of error         4.2288804190E-03
      reduced by              4.9645726073E-01
   Linf error estimate        2.1866371460E-03
      reduced by              4.2099921514E-01
      effectivity             5.1707235233E-01

Total Grid:
   number of vertices      =         330
   number of leaf elements =         602
   number of levels        =           9
   degrees of freedom      =         660
   min and max degree      =           1          1

Norms of error:
   energy norm of error       7.7558002089E-02
   energy error estimate      9.3271311282E-02
      effectivity             1.2026007474E+00
  Component           1
   Linf norm of error         3.4856481160E-03
   Linf error estimate        2.2220540949E-03
      effectivity             6.3748663690E-01
  Component           2
   Linf norm of error         4.2288804190E-03
   Linf error estimate        2.1866371460E-03
      effectivity             5.1707235233E-01

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           5
termination condition:
  maximum vertices achieved
---------------------------------------------------------
Linf errors from query  3.485648116008E-03 4.228880419021E-03
