---------------------------------------------------------
           PHAML   Version 1.11.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  300
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 2
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         false
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    SLAVES
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree                      3
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             CG_SOLVER
  preconditioner     MG_PRECONDITION
  mg_cycles                   2
  mg_tol             MG_NO_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_NONE
  krylov_iter               100
  krylov_tol         KRYLOV_ERREST_TOL
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =          98
   degrees of freedom I own =          98
   min and max degree       =           3          3

Norms of error:
   energy norm of error       7.2827182474E-03
   energy error estimate      7.2483291106E-03
      effectivity             9.9527798061E-01
  Component           1
   Linf norm of error         4.7589831686E-04
   Linf error estimate        5.2312724303E-04
      effectivity             1.0992416331E+00
  Component           2
   Linf norm of error         7.9447284784E-04
   Linf error estimate        8.3300577127E-04
      effectivity             1.0485012465E+00

My Grid:
   number of vertices       =          19
   number of vertices I own =          19
   number of elements       =          44
   number of leaf elements  =          26
   leaf elements I own      =          26
   number of levels         =           3
   degrees of freedom       =         266
   degrees of freedom I own =         266
   min and max degree       =           3          3

Norms of error:
   energy norm of error       1.1845432830E-03
      reduced by              1.6265125778E-01
   energy error estimate      1.5925007831E-03
      reduced by              2.1970591550E-01
      effectivity             1.3444006698E+00
  Component           1
   Linf norm of error         4.7046401182E-05
      reduced by              9.8858095345E-02
   Linf error estimate        4.3829992619E-05
      reduced by              8.3784572879E-02
      effectivity             9.3163327092E-01
  Component           2
   Linf norm of error         1.1992141064E-04
      reduced by              1.5094463073E-01
   Linf error estimate        1.0675855914E-04
      reduced by              1.2816064764E-01
      effectivity             8.9023768622E-01

My Grid:
   number of vertices       =          33
   number of vertices I own =          33
   number of elements       =          88
   number of leaf elements  =          48
   leaf elements I own      =          48
   number of levels         =           4
   degrees of freedom       =         482
   degrees of freedom I own =         482
   min and max degree       =           3          3

Norms of error:
   energy norm of error       3.7462342145E-04
      reduced by              3.1625979972E-01
   energy error estimate      4.8872777421E-04
      reduced by              3.0689327089E-01
      effectivity             1.3045841403E+00
  Component           1
   Linf norm of error         3.6064009136E-05
      reduced by              7.6656254739E-01
   Linf error estimate        4.5127881365E-05
      reduced by              1.0296118860E+00
      effectivity             1.2513273606E+00
  Component           2
   Linf norm of error         8.1633605886E-06
      reduced by              6.8072586413E-02
   Linf error estimate        1.3257484943E-05
      reduced by              1.2418193961E-01
      effectivity             1.6240229498E+00

My Grid:
   number of vertices       =          55
   number of vertices I own =          55
   number of elements       =         172
   number of leaf elements  =          90
   leaf elements I own      =          90
   number of levels         =           5
   degrees of freedom       =         866
   degrees of freedom I own =         866
   min and max degree       =           3          3

Norms of error:
   energy norm of error       1.6318846501E-04
      reduced by              4.3560668038E-01
   energy error estimate      2.3412253350E-04
      reduced by              4.7904487091E-01
      effectivity             1.4346757505E+00
  Component           1
   Linf norm of error         4.2237038063E-06
      reduced by              1.1711686824E-01
   Linf error estimate        4.0101928074E-06
      reduced by              8.8862864512E-02
      effectivity             9.4944934384E-01
  Component           2
   Linf norm of error         8.1245886780E-06
      reduced by              9.9525049639E-01
   Linf error estimate        7.0714588228E-06
      reduced by              5.3339369066E-01
      effectivity             8.7037745577E-01

My Grid:
   number of vertices       =         114
   number of vertices I own =         114
   number of elements       =         380
   number of leaf elements  =         194
   leaf elements I own      =         194
   number of levels         =           6
   degrees of freedom       =        1844
   degrees of freedom I own =        1844
   min and max degree       =           3          3

Norms of error:
   energy norm of error       4.3205027462E-05
      reduced by              2.6475540081E-01
   energy error estimate      5.9015697170E-05
      reduced by              2.5207183728E-01
      effectivity             1.3659451373E+00
  Component           1
   Linf norm of error         2.4093777573E-06
      reduced by              5.7044193150E-01
   Linf error estimate        2.4852122739E-06
      reduced by              6.1972388692E-01
      effectivity             1.0314747309E+00
  Component           2
   Linf norm of error         5.1087195727E-07
      reduced by              6.2879731825E-02
   Linf error estimate        8.2757137943E-07
      reduced by              1.1702979543E-01
      effectivity             1.6199193705E+00

My Grid:
   number of vertices       =         251
   number of vertices I own =         251
   number of elements       =         912
   number of leaf elements  =         460
   leaf elements I own      =         460
   number of levels         =           7
   degrees of freedom       =        4262
   degrees of freedom I own =        4262
   min and max degree       =           3          3

Norms of error:
   energy norm of error       1.6188947645E-05
      reduced by              3.7470055213E-01
   energy error estimate      2.0509069398E-05
      reduced by              3.4751888704E-01
      effectivity             1.2668562434E+00
  Component           1
   Linf norm of error         2.1742348810E-07
      reduced by              9.0240514358E-02
   Linf error estimate        2.0976095581E-07
      reduced by              8.4403637472E-02
      effectivity             9.6475756892E-01
  Component           2
   Linf norm of error         5.1188590156E-07
      reduced by              1.0019847327E+00
   Linf error estimate        4.4194075242E-07
      reduced by              5.3402131031E-01
      effectivity             8.6335793011E-01

My Grid:
   number of vertices       =         421
   number of vertices I own =         421
   number of elements       =        1544
   number of leaf elements  =         776
   leaf elements I own      =         776
   number of levels         =           8
   degrees of freedom       =        7178
   degrees of freedom I own =        7178
   min and max degree       =           3          3

Norms of error:
   energy norm of error       5.3488192541E-06
      reduced by              3.3039944111E-01
   energy error estimate      7.3945514499E-06
      reduced by              3.6055031588E-01
      effectivity             1.3824642596E+00
  Component           1
   Linf norm of error         1.5856227575E-07
      reduced by              7.2927850223E-01
   Linf error estimate        1.6658548793E-07
      reduced by              7.9416823443E-01
      effectivity             1.0505997542E+00
  Component           2
   Linf norm of error         3.1910619425E-08
      reduced by              6.2339320789E-02
   Linf error estimate        5.1709762762E-08
      reduced by              1.1700609749E-01
      effectivity             1.6204562523E+00

My Grid:
   number of vertices       =         421
   number of vertices I own =         421
   number of elements       =        1544
   number of leaf elements  =         776
   leaf elements I own      =         776
   number of levels         =           8
   degrees of freedom       =        7178
   degrees of freedom I own =        7178
   min and max degree       =           3          3

Norms of error:
   energy norm of error       5.3488192541E-06
   energy error estimate      7.3945514499E-06
      effectivity             1.3824642596E+00
  Component           1
   Linf norm of error         1.5856227575E-07
   Linf error estimate        1.6658548793E-07
      effectivity             1.0505997542E+00
  Component           2
   Linf norm of error         3.1910619425E-08
   Linf error estimate        5.1709762762E-08
      effectivity             1.6204562523E+00

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
Linf errors from query  1.585622757538E-07 3.191061942465E-08
