---------------------------------------------------------
           PHAML   Version 1.9.1

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  300
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 2
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    SLAVES
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                   5
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =          18
   degrees of freedom I own =          18
   min and max degree       =           1          1

Norms of error:
   energy norm of error       9.2477317950E-01
   energy error estimate      1.8308801788E-01
      effectivity             1.9798153962E-01
  Component           1
   Linf norm of error         1.7164943122E-01
   Linf error estimate        2.7974880474E-02
      effectivity             1.6297683176E-01
  Component           2
   Linf norm of error         3.6384112011E-01
   Linf error estimate        5.2080688181E-02
      effectivity             1.4314129246E-01

My Grid:
   number of vertices       =          18
   number of vertices I own =          18
   number of elements       =          38
   number of leaf elements  =          23
   leaf elements I own      =          23
   number of levels         =           3
   degrees of freedom       =          36
   degrees of freedom I own =          36
   min and max degree       =           1          1

Norms of error:
   energy norm of error       4.4554045644E-01
      reduced by              4.8178349709E-01
   energy error estimate      9.8386658603E-02
      reduced by              5.3737355259E-01
      effectivity             2.2082542041E-01
  Component           1
   Linf norm of error         6.9347028310E-02
      reduced by              4.0400383397E-01
   Linf error estimate        1.2428322857E-02
      reduced by              4.4426723711E-01
      effectivity             1.7921925653E-01
  Component           2
   Linf norm of error         1.1646812764E-01
      reduced by              3.2010710501E-01
   Linf error estimate        1.4892380791E-02
      reduced by              2.8594823361E-01
      effectivity             1.2786657683E-01

My Grid:
   number of vertices       =          41
   number of vertices I own =          41
   number of elements       =         114
   number of leaf elements  =          61
   leaf elements I own      =          61
   number of levels         =           5
   degrees of freedom       =          82
   degrees of freedom I own =          82
   min and max degree       =           1          1

Norms of error:
   energy norm of error       2.4565730414E-01
      reduced by              5.5136924289E-01
   energy error estimate      5.9696946558E-02
      reduced by              6.0675855249E-01
      effectivity             2.4300904370E-01
  Component           1
   Linf norm of error         3.4946376312E-02
      reduced by              5.0393473468E-01
   Linf error estimate        4.7793637867E-03
      reduced by              3.8455420268E-01
      effectivity             1.3676278605E-01
  Component           2
   Linf norm of error         3.2419453474E-02
      reduced by              2.7835472356E-01
   Linf error estimate        4.0954893693E-03
      reduced by              2.7500568424E-01
      effectivity             1.2632814346E-01

My Grid:
   number of vertices       =          78
   number of vertices I own =          78
   number of elements       =         248
   number of leaf elements  =         128
   leaf elements I own      =         128
   number of levels         =           6
   degrees of freedom       =         156
   degrees of freedom I own =         156
   min and max degree       =           1          1

Norms of error:
   energy norm of error       1.7331802057E-01
      reduced by              7.0552765029E-01
   energy error estimate      4.1206830134E-02
      reduced by              6.9026696522E-01
      effectivity             2.3775271607E-01
  Component           1
   Linf norm of error         1.4621577009E-02
      reduced by              4.1840037659E-01
   Linf error estimate        2.0171534928E-03
      reduced by              4.2205481373E-01
      effectivity             1.3795731414E-01
  Component           2
   Linf norm of error         1.8896918077E-02
      reduced by              5.8288823692E-01
   Linf error estimate        2.0142847050E-03
      reduced by              4.9183004115E-01
      effectivity             1.0659329192E-01

My Grid:
   number of vertices       =         153
   number of vertices I own =         153
   number of elements       =         520
   number of leaf elements  =         264
   leaf elements I own      =         264
   number of levels         =           7
   degrees of freedom       =         306
   degrees of freedom I own =         306
   min and max degree       =           1          1

Norms of error:
   energy norm of error       1.1796589968E-01
      reduced by              6.8063262721E-01
   energy error estimate      2.8576451750E-02
      reduced by              6.9348823137E-01
      effectivity             2.4224332478E-01
  Component           1
   Linf norm of error         7.3353800166E-03
      reduced by              5.0168186455E-01
   Linf error estimate        9.5335594545E-04
      reduced by              4.7262439317E-01
      effectivity             1.2996681062E-01
  Component           2
   Linf norm of error         8.5214295796E-03
      reduced by              4.5094282278E-01
   Linf error estimate        1.0388170491E-03
      reduced by              5.1572503454E-01
      effectivity             1.2190642889E-01

My Grid:
   number of vertices       =         322
   number of vertices I own =         322
   number of elements       =        1170
   number of leaf elements  =         589
   leaf elements I own      =         589
   number of levels         =           8
   degrees of freedom       =         644
   degrees of freedom I own =         644
   min and max degree       =           1          1

Norms of error:
   energy norm of error       7.7872500909E-02
      reduced by              6.6012721574E-01
   energy error estimate      1.9146847382E-02
      reduced by              6.7002186099E-01
      effectivity             2.4587430940E-01
  Component           1
   Linf norm of error         3.4854683771E-03
      reduced by              4.7515852883E-01
   Linf error estimate        4.5651162584E-04
      reduced by              4.7884699101E-01
      effectivity             1.3097569005E-01
  Component           2
   Linf norm of error         4.2501071809E-03
      reduced by              4.9875518435E-01
   Linf error estimate        4.6340722041E-04
      reduced by              4.4609127356E-01
      effectivity             1.0903424330E-01

My Grid:
   number of vertices       =         322
   number of vertices I own =         322
   number of elements       =        1170
   number of leaf elements  =         589
   leaf elements I own      =         589
   number of levels         =           8
   degrees of freedom       =         644
   degrees of freedom I own =         644
   min and max degree       =           1          1

Norms of error:
   energy norm of error       7.7872500909E-02
   energy error estimate      1.9146847382E-02
      effectivity             2.4587430940E-01
  Component           1
   Linf norm of error         3.4854683771E-03
   Linf error estimate        4.5651162584E-04
      effectivity             1.3097569005E-01
  Component           2
   Linf norm of error         4.2501071809E-03
   Linf error estimate        4.6340722041E-04
      effectivity             1.0903424330E-01

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           5
termination condition:
  maximum vertices achieved
---------------------------------------------------------
Linf errors from query  3.485468377102E-03 4.250107180905E-03
