---------------------------------------------------------
           PHAML   Version 1.11.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                    500
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    SLAVES
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree                      4
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             LAPACK_SPD_SOLVER
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =          81
   degrees of freedom I own =          81
   min and max degree       =           4          4

Norms of error:
   energy norm of error       8.6271851999E-02
   Linf norm of error         1.0764133692E-02
   L2 norm of error           4.3498770589E-03

My Grid:
   number of vertices       =          17
   number of vertices I own =          17
   number of elements       =          36
   number of leaf elements  =          22
   leaf elements I own      =          22
   number of levels         =           3
   degrees of freedom       =         197
   degrees of freedom I own =         197
   min and max degree       =           4          4

Norms of error:
   energy norm of error       2.2078337577E-02
      reduced by              2.5591588758E-01
   Linf norm of error         5.0395031072E-03
      reduced by              4.6817544742E-01
   L2 norm of error           8.6482540229E-04
      reduced by              1.9881605631E-01

My Grid:
   number of vertices       =          30
   number of vertices I own =          30
   number of elements       =          80
   number of leaf elements  =          44
   leaf elements I own      =          44
   number of levels         =           4
   degrees of freedom       =         381
   degrees of freedom I own =         381
   min and max degree       =           4          4

Norms of error:
   energy norm of error       3.9273114865E-03
      reduced by              1.7788076085E-01
   Linf norm of error         3.5673998139E-04
      reduced by              7.0788721388E-02
   L2 norm of error           8.3499752053E-05
      reduced by              9.6550993798E-02

My Grid:
   number of vertices       =          40
   number of vertices I own =          40
   number of elements       =         112
   number of leaf elements  =          60
   leaf elements I own      =          60
   number of levels         =           5
   degrees of freedom       =         517
   degrees of freedom I own =         517
   min and max degree       =           4          4

Norms of error:
   energy norm of error       1.3846051167E-03
      reduced by              3.5255800858E-01
   Linf norm of error         1.2250075437E-04
      reduced by              3.4338947344E-01
   L2 norm of error           3.2479402728E-05
      reduced by              3.8897603800E-01

My Grid:
   number of vertices       =          40
   number of vertices I own =          40
   number of elements       =         112
   number of leaf elements  =          60
   leaf elements I own      =          60
   number of levels         =           5
   degrees of freedom       =         517
   degrees of freedom I own =         517
   min and max degree       =           4          4

Norms of error:
   energy norm of error       1.3846051167E-03
   Linf norm of error         1.2250075437E-04
   L2 norm of error           3.2479402728E-05

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum equations achieved
---------------------------------------------------------
