---------------------------------------------------------
           PHAML   Version 1.9.1

Output from the master process
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                    500
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree                      4
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             LAPACK_SPD_SOLVER
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =          81
   min and max degree      =           4          4

Norms of error:
   energy norm of error       8.6271851999E-02
   Linf norm of error         1.0764133692E-02
   L2 norm of error           4.3498770589E-03

Total Grid:
   number of vertices      =          19
   number of leaf elements =          24
   number of levels        =           3
   degrees of freedom      =         217
   min and max degree      =           4          4

Norms of error:
   energy norm of error       7.7771499751E-03
      reduced by              9.0147015450E-02
   Linf norm of error         7.0294450970E-04
      reduced by              6.5304327299E-02
   L2 norm of error           1.9281272958E-04
      reduced by              4.4326018176E-02

Total Grid:
   number of vertices      =          28
   number of leaf elements =          40
   number of levels        =           4
   degrees of freedom      =         349
   min and max degree      =           4          4

Norms of error:
   energy norm of error       3.9461930021E-03
      reduced by              5.0740862845E-01
   Linf norm of error         3.5674009990E-04
      reduced by              5.0749396997E-01
   L2 norm of error           8.4281401347E-05
      reduced by              4.3711533741E-01

Total Grid:
   number of vertices      =          40
   number of leaf elements =          60
   number of levels        =           5
   degrees of freedom      =         517
   min and max degree      =           4          4

Norms of error:
   energy norm of error       1.3846051167E-03
      reduced by              3.5087110945E-01
   Linf norm of error         1.2250075437E-04
      reduced by              3.4338935937E-01
   L2 norm of error           3.2479402728E-05
      reduced by              3.8536856541E-01

Total Grid:
   number of vertices      =          40
   number of leaf elements =          60
   number of levels        =           5
   degrees of freedom      =         517
   min and max degree      =           4          4

Norms of error:
   energy norm of error       1.3846051167E-03
   Linf norm of error         1.2250075437E-04
   L2 norm of error           3.2479402728E-05

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum equations achieved
---------------------------------------------------------
