---------------------------------------------------------
           PHAML   Version 1.11.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             MG_SOLVER
  mg_cycles                   5
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.4822035936E+00
   Linf norm of error         8.7914044620E-01
   L2 norm of error           3.5000011056E-01

Total Grid:
   number of vertices      =          29
   number of leaf elements =          40
   number of levels        =           5
   degrees of freedom      =          29
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.4543374672E+00
      reduced by              5.8590579395E-01
   Linf norm of error         2.5755432667E-01
      reduced by              2.9296152598E-01
   L2 norm of error           9.0458952367E-02
      reduced by              2.5845406798E-01

Total Grid:
   number of vertices      =          36
   number of leaf elements =          48
   number of levels        =           6
   degrees of freedom      =          36
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.4268179669E+00
      reduced by              9.8107763776E-01
   Linf norm of error         2.5755738239E-01
      reduced by              1.0000118644E+00
   L2 norm of error           9.0515730235E-02
      reduced by              1.0006276644E+00

Total Grid:
   number of vertices      =          98
   number of leaf elements =         154
   number of levels        =           8
   degrees of freedom      =          98
   min and max degree      =           1          1

Norms of error:
   energy norm of error       7.7955585807E-01
      reduced by              5.4635971523E-01
   Linf norm of error         1.0000025544E-01
      reduced by              3.8826398419E-01
   L2 norm of error           2.5636286883E-02
      reduced by              2.8322465959E-01

Total Grid:
   number of vertices      =         167
   number of leaf elements =         288
   number of levels        =           9
   degrees of freedom      =         167
   min and max degree      =           1          1

Norms of error:
   energy norm of error       4.8553639680E-01
      reduced by              6.2283721144E-01
   Linf norm of error         3.2559958217E-02
      reduced by              3.2559875045E-01
   L2 norm of error           1.2329341421E-02
      reduced by              4.8093319743E-01

Total Grid:
   number of vertices      =         314
   number of leaf elements =         552
   number of levels        =          10
   degrees of freedom      =         314
   min and max degree      =           1          1

Norms of error:
   energy norm of error       3.3436213000E-01
      reduced by              3.4432241558E-01
   Linf norm of error         3.1410221747E-02
      reduced by              9.6468863802E-01
   L2 norm of error           7.8513132491E-03
      reduced by              3.1839953899E-01

Total Grid:
   number of vertices      =         586
   number of leaf elements =        1084
   number of levels        =          11
   degrees of freedom      =         586
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.4878389783E-01
      reduced by              7.4405524881E-01
   Linf norm of error         1.0112107087E-02
      reduced by              3.2193682581E-01
   L2 norm of error           3.0902769027E-03
      reduced by              3.9360000100E-01

Total Grid:
   number of vertices      =         586
   number of leaf elements =        1084
   number of levels        =          11
   degrees of freedom      =         586
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.4878389783E-01
   Linf norm of error         1.0112107087E-02
   L2 norm of error           3.0902769027E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
