---------------------------------------------------------
           PHAML   Version 1.11.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  inc_quad_order             20
  mg_cycles                   5
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.4752250313E+00
   Linf norm of error         9.0800311241E-01
   L2 norm of error           3.6016701275E-01

Total Grid:
   number of vertices      =          29
   number of leaf elements =          40
   number of levels        =           5
   degrees of freedom      =          29
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.4543344549E+00
      reduced by              5.8755645912E-01
   Linf norm of error         2.5753048189E-01
      reduced by              2.8362290654E-01
   L2 norm of error           9.0445814019E-02
      reduced by              2.5112187073E-01

Total Grid:
   number of vertices      =          36
   number of leaf elements =          48
   number of levels        =           6
   degrees of freedom      =          36
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.4268147788E+00
      reduced by              9.8107747774E-01
   Linf norm of error         2.5753349842E-01
      reduced by              1.0000117133E+00
   L2 norm of error           9.0498392111E-02
      reduced by              1.0005813215E+00

Total Grid:
   number of vertices      =          98
   number of leaf elements =         154
   number of levels        =           8
   degrees of freedom      =          98
   min and max degree      =           1          1

Norms of error:
   energy norm of error       7.7955549219E-01
      reduced by              5.4636067959E-01
   Linf norm of error         9.9961109424E-02
      reduced by              3.8814798866E-01
   L2 norm of error           2.5604332149E-02
      reduced by              2.8292582390E-01

Total Grid:
   number of vertices      =         167
   number of leaf elements =         288
   number of levels        =           9
   degrees of freedom      =         167
   min and max degree      =           1          1

Norms of error:
   energy norm of error       4.8553564730E-01
      reduced by              6.2283654231E-01
   Linf norm of error         3.2526920232E-02
      reduced by              3.2539575061E-01
   L2 norm of error           1.2260773020E-02
      reduced by              4.7885541197E-01

Total Grid:
   number of vertices      =         314
   number of leaf elements =         552
   number of levels        =          10
   degrees of freedom      =         314
   min and max degree      =           1          1

Norms of error:
   energy norm of error       3.3434814451E-01
      reduced by              3.4430854498E-01
   Linf norm of error         3.1412668470E-02
      reduced by              9.6574370538E-01
   L2 norm of error           8.0013694694E-03
      reduced by              3.2629955128E-01

Total Grid:
   number of vertices      =         586
   number of leaf elements =        1084
   number of levels        =          11
   degrees of freedom      =         586
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.4876278423E-01
      reduced by              7.4402322343E-01
   Linf norm of error         1.0114163873E-02
      reduced by              3.2197722655E-01
   L2 norm of error           3.3465947006E-03
      reduced by              4.1825273953E-01

Total Grid:
   number of vertices      =         586
   number of leaf elements =        1084
   number of levels        =          11
   degrees of freedom      =         586
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.4876278423E-01
   Linf norm of error         1.0114163873E-02
   L2 norm of error           3.3465947006E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
