---------------------------------------------------------
           PHAML   Version 1.9.1

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  inc_quad_order             20
  mg_cycles                   5
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.4752250313E+00
   Linf norm of error         9.0800311241E-01
   L2 norm of error           3.6016701275E-01

Total Grid:
   number of vertices      =          29
   number of leaf elements =          40
   number of levels        =           5
   degrees of freedom      =          29
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.4543344549E+00
      reduced by              5.8755645912E-01
   Linf norm of error         2.5753048189E-01
      reduced by              2.8362290654E-01
   L2 norm of error           9.0445814019E-02
      reduced by              2.5112187073E-01

Total Grid:
   number of vertices      =          36
   number of leaf elements =          48
   number of levels        =           6
   degrees of freedom      =          36
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.4268147679E+00
      reduced by              9.8107747022E-01
   Linf norm of error         2.5753329890E-01
      reduced by              1.0000109385E+00
   L2 norm of error           9.0507967083E-02
      reduced by              1.0006871856E+00

Total Grid:
   number of vertices      =          82
   number of leaf elements =         132
   number of levels        =           7
   degrees of freedom      =          82
   min and max degree      =           1          1

Norms of error:
   energy norm of error       8.2034358475E-01
      reduced by              5.7494750070E-01
   Linf norm of error         9.9967169317E-02
      reduced by              3.8817181990E-01
   L2 norm of error           2.7280186999E-02
      reduced by              3.0141199585E-01

Total Grid:
   number of vertices      =         145
   number of leaf elements =         246
   number of levels        =           8
   degrees of freedom      =         145
   min and max degree      =           1          1

Norms of error:
   energy norm of error       5.1482074978E-01
      reduced by              6.2756722836E-01
   Linf norm of error         3.8240668607E-02
      reduced by              3.8253227403E-01
   L2 norm of error           1.3340812986E-02
      reduced by              4.8902938190E-01

Total Grid:
   number of vertices      =         334
   number of leaf elements =         588
   number of levels        =          10
   degrees of freedom      =         334
   min and max degree      =           1          1

Norms of error:
   energy norm of error       3.7046865785E-01
      reduced by              3.5980354133E-01
   Linf norm of error         3.0340480836E-02
      reduced by              7.9340874365E-01
   L2 norm of error           5.8288479359E-03
      reduced by              2.1845924764E-01

Total Grid:
   number of vertices      =         626
   number of leaf elements =        1166
   number of levels        =          11
   degrees of freedom      =         626
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.4614941196E-01
      reduced by              6.6442708917E-01
   Linf norm of error         1.0118609791E-02
      reduced by              3.3350195884E-01
   L2 norm of error           3.3531401387E-03
      reduced by              5.7526636063E-01

Total Grid:
   number of vertices      =         626
   number of leaf elements =        1166
   number of levels        =          11
   degrees of freedom      =         626
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.4614941196E-01
   Linf norm of error         1.0118609791E-02
   L2 norm of error           3.3531401387E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
