---------------------------------------------------------
           PHAML   Version 1.11.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         false
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  PHASES
  print_solver_who   MASTER
  print_error_when   NEVER
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     MASTER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             default
  preconditioner     default
  eigensolver        SLEPC_KRYLOV_SCHUR
  num_eval                    1
  lambda0             3.5000000000E+01
  scale_evec         SCALE_LINF
  transformation     ST_NONE
  eigen_ncv          default
  eigen_maxit              200
  eigen_tol          1.0000000000E-10
  harmonic_extraction  false
  true_residual        false
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Solver information:
   number of column vectors   =          16
   maximum iterations allowed =         200
   number of iterations used  =           1
   number of converged eigens =           1
   eigensolver L2 residual    =   3.2751579226E-14
   eigensolver eval errest    =   1.1739597238E-15

Eigenvalues and error estimates:
     9.1115740741E+01  1.0829488805E+04

Total Grid:
   number of vertices      =          25
   number of leaf elements =          36
   number of levels        =           4
   degrees of freedom      =          25
   min and max degree      =           1          1

Solver information:
   number of column vectors   =          16
   maximum iterations allowed =         200
   number of iterations used  =           1
   number of converged eigens =           1
   eigensolver L2 residual    =   9.5081580760E-13
   eigensolver eval errest    =   7.6577760863E-14

Eigenvalues and error estimates:
     1.4061093547E+01  8.4928851294E+01

Total Grid:
   number of vertices      =          39
   number of leaf elements =          64
   number of levels        =           6
   degrees of freedom      =          39
   min and max degree      =           1          1

Solver information:
   number of column vectors   =          16
   maximum iterations allowed =         200
   number of iterations used  =           5
   number of converged eigens =           1
   eigensolver L2 residual    =   8.3114161304E-09
   eigensolver eval errest    =   1.1942882990E-10

Eigenvalues and error estimates:
     3.3088333205E+01  2.9645952314E+01

Total Grid:
   number of vertices      =          73
   number of leaf elements =         128
   number of levels        =           8
   degrees of freedom      =          73
   min and max degree      =           1          1

Solver information:
   number of column vectors   =          16
   maximum iterations allowed =         200
   number of iterations used  =           1
   number of converged eigens =           1
   eigensolver L2 residual    =   3.0670211829E-11
   eigensolver eval errest    =   4.5961831069E-13

Eigenvalues and error estimates:
     2.4832738640E+01  7.9714789231E+00

Total Grid:
   number of vertices      =         169
   number of leaf elements =         320
   number of levels        =          11
   degrees of freedom      =         169
   min and max degree      =           1          1

Solver information:
   number of column vectors   =          16
   maximum iterations allowed =         200
   number of iterations used  =          12
   number of converged eigens =           1
   eigensolver L2 residual    =   3.0269829919E-10
   eigensolver eval errest    =   1.5377600727E-12

Eigenvalues and error estimates:
     3.9832815680E+01  7.2213155132E+00

Total Grid:
   number of vertices      =         295
   number of leaf elements =         572
   number of levels        =          11
   degrees of freedom      =         295
   min and max degree      =           1          1

Solver information:
   number of column vectors   =          16
   maximum iterations allowed =         200
   number of iterations used  =         126
   number of converged eigens =           1
   eigensolver L2 residual    =   6.2637013149E-09
   eigensolver eval errest    =   2.8415045814E-11

Eigenvalues and error estimates:
     3.5427543805E+01  1.7568490575E+00

Total Grid:
   number of vertices      =         627
   number of leaf elements =        1236
   number of levels        =          13
   degrees of freedom      =         627
   min and max degree      =           1          1

Solver information:
   number of column vectors   =          16
   maximum iterations allowed =         200
   number of iterations used  =          73
   number of converged eigens =           1
   eigensolver L2 residual    =   1.0175483698E-08
   eigensolver eval errest    =   2.3434282044E-11

Eigenvalues and error estimates:
     3.4546112477E+01  5.6277177396E-01

Total Grid:
   number of vertices      =         627
   number of leaf elements =        1236
   number of levels        =          13
   degrees of freedom      =         627
   min and max degree      =           1          1

Eigenvalues and error estimates:
     3.4546112477E+01  5.6277177396E-01

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
