---------------------------------------------------------
           PHAML   Version 1.11.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         false
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  PHASES
  print_solver_who   MASTER
  print_error_when   NEVER
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     MASTER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             default
  preconditioner     default
  eigensolver        SLEPC_KRYLOV_SCHUR
  num_eval                    5
  lambda0            -infinity
  scale_evec         SCALE_LINF
  transformation     ST_NONE
  eigen_ncv          default
  eigen_maxit        default
  eigen_tol          1.0000000000E-10
  harmonic_extraction  false
  true_residual        false
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Solver information:
   number of column vectors   =          20
   maximum iterations allowed =         100
   number of iterations used  =           1
   number of converged eigens =           1
   eigensolver L2 residual    =   3.2751579226E-14
   eigensolver eval errest    =   1.1739597238E-15

Eigenvalues and error estimates:
     9.1115740741E+01  1.0829488805E+04
     0.0000000000E+00  0.0000000000E+00
     0.0000000000E+00  0.0000000000E+00
     0.0000000000E+00  0.0000000000E+00
     0.0000000000E+00  0.0000000000E+00

Total Grid:
   number of vertices      =          25
   number of leaf elements =          36
   number of levels        =           4
   degrees of freedom      =          25
   min and max degree      =           1          1

Solver information:
   number of column vectors   =          20
   maximum iterations allowed =         100
   number of iterations used  =           1
   number of converged eigens =           5
   eigensolver L2 residual    =   5.3642308645E-13
                                  1.3006563315E-13
                                  5.8335500114E-14
                                  9.5667249867E-14
                                  4.6545049364E-13
   eigensolver eval errest    =   4.3202982646E-14
                                  2.2765962849E-15
                                  7.7419684138E-16
                                  1.2770564648E-15
                                  7.3059726265E-15

Eigenvalues and error estimates:
     1.4061093547E+01  8.4928851294E+01
     5.7203186212E+01  4.1200755857E+02
     6.0839949179E+01  2.1781982797E+02
     6.0964210197E+01  2.1858713736E+02
     6.1664150437E+01  4.2284691935E+02

Total Grid:
   number of vertices      =          45
   number of leaf elements =          76
   number of levels        =           6
   degrees of freedom      =          45
   min and max degree      =           1          1

Solver information:
   number of column vectors   =          20
   maximum iterations allowed =         100
   number of iterations used  =           4
   number of converged eigens =           5
   eigensolver L2 residual    =   1.2799585527E-12
                                  1.9250551450E-12
                                  1.9540295582E-13
                                  3.7682549847E-11
                                  1.5736356544E-10
   eigensolver eval errest    =   7.6477438119E-14
                                  5.1051404362E-14
                                  4.0147348438E-15
                                  5.4096682169E-13
                                  1.7842712674E-12

Eigenvalues and error estimates:
     1.0512385008E+01  6.4989342290E+00
     2.1949598689E+01  1.2990623776E+01
     2.6851576528E+01  1.4529435008E+01
     3.3100729807E+01  3.4936679440E+01
     3.7018824366E+01  3.0915366459E+01

Total Grid:
   number of vertices      =          73
   number of leaf elements =         128
   number of levels        =           8
   degrees of freedom      =          73
   min and max degree      =           1          1

Solver information:
   number of column vectors   =          20
   maximum iterations allowed =         100
   number of iterations used  =           7
   number of converged eigens =           5
   eigensolver L2 residual    =   1.3198295613E-11
                                  4.9028306399E-09
                                  1.9972032528E-11
                                  3.8447284918E-13
                                  3.0908009782E-09
   eigensolver eval errest    =   4.4207210746E-13
                                  1.0279565288E-10
                                  2.9929730851E-13
                                  6.0946327793E-15
                                  3.5333705648E-11

Eigenvalues and error estimates:
     1.0601014739E+01  3.1704556091E+00
     1.9267775149E+01  6.2905236803E+00
     2.4832738640E+01  7.9714789231E+00
     2.6800657868E+01  8.2386679637E+00
     3.3644264951E+01  1.3851525408E+01

Total Grid:
   number of vertices      =         151
   number of leaf elements =         284
   number of levels        =          10
   degrees of freedom      =         151
   min and max degree      =           1          1

Solver information:
   number of column vectors   =          20
   maximum iterations allowed =         100
   number of iterations used  =          18
   number of converged eigens =           5
   eigensolver L2 residual    =   4.3359553980E-11
                                  1.2469755884E-09
                                  5.8073892458E-10
                                  5.1995731556E-09
                                  5.7439873119E-10
   eigensolver eval errest    =   8.4351270456E-13
                                  1.5011212704E-11
                                  4.9336808345E-12
                                  4.3125759933E-11
                                  3.3980600520E-12

Eigenvalues and error estimates:
     9.9455814397E+00  9.5282426534E-01
     1.7277081777E+01  1.7581723912E+00
     2.2769813038E+01  2.3532132612E+00
     2.4860987763E+01  3.4185244179E+00
     3.6793713071E+01  4.5982704048E+00

Total Grid:
   number of vertices      =         301
   number of leaf elements =         584
   number of levels        =          12
   degrees of freedom      =         301
   min and max degree      =           1          1

Solver information:
   number of column vectors   =          20
   maximum iterations allowed =         100
   number of iterations used  =          45
   number of converged eigens =           5
   eigensolver L2 residual    =   3.4925406687E-09
                                  1.0848907847E-08
                                  6.8170049798E-09
                                  2.4809868530E-12
                                  9.1357583465E-09
   eigensolver eval errest    =   4.0234116886E-11
                                  8.2779285586E-11
                                  3.9577753715E-11
                                  1.4569324574E-14
                                  4.8317258671E-11

Eigenvalues and error estimates:
     9.7651472267E+00  3.9239507071E-01
     1.7028073564E+01  8.3372484008E-01
     2.2321001234E+01  8.8984558484E-01
     2.4454510211E+01  1.4415507300E+00
     2.9801498553E+01  1.8334872546E+00

Total Grid:
   number of vertices      =         597
   number of leaf elements =        1176
   number of levels        =          13
   degrees of freedom      =         597
   min and max degree      =           1          1

Solver information:
   number of column vectors   =          20
   maximum iterations allowed =         100
   number of iterations used  =          73
   number of converged eigens =           5
   eigensolver L2 residual    =   1.1513916227E-08
                                  1.0525359623E-08
                                  1.2670549094E-08
                                  6.8098760211E-09
                                  3.5517011491E-11
   eigensolver eval errest    =   9.6542245608E-11
                                  5.3219742909E-11
                                  5.0048939932E-11
                                  2.6477572219E-11
                                  1.0979157385E-13

Eigenvalues and error estimates:
     9.7148730504E+00  1.8359275335E-01
     1.6867201838E+01  3.4548339962E-01
     2.2091975216E+01  3.9020166811E-01
     2.4071877996E+01  5.9528012869E-01
     2.9323448036E+01  6.1285994364E-01

Total Grid:
   number of vertices      =         597
   number of leaf elements =        1176
   number of levels        =          13
   degrees of freedom      =         597
   min and max degree      =           1          1

Eigenvalues and error estimates:
     9.7148730504E+00  1.8359275335E-01
     1.6867201838E+01  3.4548339962E-01
     2.2091975216E+01  3.9020166811E-01
     2.4071877996E+01  5.9528012869E-01
     2.9323448036E+01  6.1285994364E-01

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
