---------------------------------------------------------
           PHAML   Version 1.11.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         false
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_solver_when  PHASES
  print_solver_who   SLAVES
  print_error_when   NEVER
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     SLAVES
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             default
  preconditioner     default
  eigensolver        SLEPC_KRYLOV_SCHUR
  num_eval                    5
  lambda0            -infinity
  scale_evec         SCALE_LINF
  transformation     ST_NONE
  eigen_ncv          default
  eigen_maxit        default
  eigen_tol          1.0000000000E-10
  harmonic_extraction  false
  true_residual        false
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

Solver information:
   number of column vectors   =          20
   maximum iterations allowed =         100
   number of iterations used  =           1
   number of converged eigens =           1
   eigensolver L2 residual    =   3.2751579226E-14
   eigensolver eval errest    =   1.1739597238E-15

Eigenvalues and error estimates:
     9.1115740741E+01  1.0829488805E+04
     0.0000000000E+00  0.0000000000E+00
     0.0000000000E+00  0.0000000000E+00
     0.0000000000E+00  0.0000000000E+00
     0.0000000000E+00  0.0000000000E+00

My Grid:
   number of vertices       =          25
   number of vertices I own =          25
   number of elements       =          64
   number of leaf elements  =          36
   leaf elements I own      =          36
   number of levels         =           4
   degrees of freedom       =          25
   degrees of freedom I own =          25
   min and max degree       =           1          1

Solver information:
   number of column vectors   =          20
   maximum iterations allowed =         100
   number of iterations used  =           1
   number of converged eigens =           5
   eigensolver L2 residual    =   5.3642308645E-13
                                  1.3006563315E-13
                                  5.8335500114E-14
                                  9.5667249867E-14
                                  4.6545049364E-13
   eigensolver eval errest    =   4.3202982646E-14
                                  2.2765962849E-15
                                  7.7419684138E-16
                                  1.2770564648E-15
                                  7.3059726265E-15

Eigenvalues and error estimates:
     1.4061093547E+01  8.4928851294E+01
     5.7203186212E+01  4.1200755857E+02
     6.0839949179E+01  2.1781982797E+02
     6.0964210197E+01  2.1858713736E+02
     6.1664150437E+01  4.2284691935E+02

My Grid:
   number of vertices       =          45
   number of vertices I own =          45
   number of elements       =         144
   number of leaf elements  =          76
   leaf elements I own      =          76
   number of levels         =           6
   degrees of freedom       =          45
   degrees of freedom I own =          45
   min and max degree       =           1          1

Solver information:
   number of column vectors   =          20
   maximum iterations allowed =         100
   number of iterations used  =           4
   number of converged eigens =           5
   eigensolver L2 residual    =   1.2799585527E-12
                                  1.9250551450E-12
                                  1.9540295582E-13
                                  3.7682549847E-11
                                  1.5736356544E-10
   eigensolver eval errest    =   7.6477438119E-14
                                  5.1051404362E-14
                                  4.0147348438E-15
                                  5.4096682169E-13
                                  1.7842712674E-12

Eigenvalues and error estimates:
     1.0512385008E+01  6.4989342290E+00
     2.1949598689E+01  1.2990623776E+01
     2.6851576528E+01  1.4529435008E+01
     3.3100729807E+01  3.4936679440E+01
     3.7018824366E+01  3.0915366459E+01

My Grid:
   number of vertices       =          73
   number of vertices I own =          73
   number of elements       =         248
   number of leaf elements  =         128
   leaf elements I own      =         128
   number of levels         =           8
   degrees of freedom       =          73
   degrees of freedom I own =          73
   min and max degree       =           1          1

Solver information:
   number of column vectors   =          20
   maximum iterations allowed =         100
   number of iterations used  =           7
   number of converged eigens =           5
   eigensolver L2 residual    =   1.3198295613E-11
                                  4.9028306399E-09
                                  1.9972032528E-11
                                  3.8447284918E-13
                                  3.0908009782E-09
   eigensolver eval errest    =   4.4207210746E-13
                                  1.0279565288E-10
                                  2.9929730851E-13
                                  6.0946327793E-15
                                  3.5333705648E-11

Eigenvalues and error estimates:
     1.0601014739E+01  3.1704556091E+00
     1.9267775149E+01  6.2905236803E+00
     2.4832738640E+01  7.9714789231E+00
     2.6800657868E+01  8.2386679637E+00
     3.3644264951E+01  1.3851525408E+01

My Grid:
   number of vertices       =         151
   number of vertices I own =         151
   number of elements       =         560
   number of leaf elements  =         284
   leaf elements I own      =         284
   number of levels         =          10
   degrees of freedom       =         151
   degrees of freedom I own =         151
   min and max degree       =           1          1

Solver information:
   number of column vectors   =          20
   maximum iterations allowed =         100
   number of iterations used  =          18
   number of converged eigens =           5
   eigensolver L2 residual    =   4.3359553980E-11
                                  1.2469755884E-09
                                  5.8073892458E-10
                                  5.1995731556E-09
                                  5.7439873119E-10
   eigensolver eval errest    =   8.4351270456E-13
                                  1.5011212704E-11
                                  4.9336808345E-12
                                  4.3125759933E-11
                                  3.3980600520E-12

Eigenvalues and error estimates:
     9.9455814397E+00  9.5282426534E-01
     1.7277081777E+01  1.7581723912E+00
     2.2769813038E+01  2.3532132612E+00
     2.4860987763E+01  3.4185244179E+00
     3.6793713071E+01  4.5982704048E+00

My Grid:
   number of vertices       =         301
   number of vertices I own =         301
   number of elements       =        1160
   number of leaf elements  =         584
   leaf elements I own      =         584
   number of levels         =          12
   degrees of freedom       =         301
   degrees of freedom I own =         301
   min and max degree       =           1          1

Solver information:
   number of column vectors   =          20
   maximum iterations allowed =         100
   number of iterations used  =          50
   number of converged eigens =           5
   eigensolver L2 residual    =   1.8708606243E-09
                                  8.8010390868E-09
                                  5.6934619798E-09
                                  8.2352478281E-09
                                  9.9813081294E-09
   eigensolver eval errest    =   2.1552340309E-11
                                  6.7153647014E-11
                                  3.3054755965E-11
                                  4.8360594260E-11
                                  5.2789207909E-11

Eigenvalues and error estimates:
     9.7651472267E+00  3.9239507068E-01
     1.7028073564E+01  8.3372484002E-01
     2.2321001234E+01  8.8984558475E-01
     2.4454510211E+01  1.4415507298E+00
     2.9801498553E+01  1.8334872547E+00

My Grid:
   number of vertices       =         597
   number of vertices I own =         597
   number of elements       =        2344
   number of leaf elements  =        1176
   leaf elements I own      =        1176
   number of levels         =          13
   degrees of freedom       =         597
   degrees of freedom I own =         597
   min and max degree       =           1          1

Solver information:
   number of column vectors   =          20
   maximum iterations allowed =         100
   number of iterations used  =          71
   number of converged eigens =           5
   eigensolver L2 residual    =   3.2591917637E-09
                                  5.3968642328E-09
                                  6.3749288365E-09
                                  8.6979809532E-12
                                  9.6228221290E-09
   eigensolver eval errest    =   2.7327773238E-11
                                  2.7288352824E-11
                                  2.5181105258E-11
                                  3.3818738863E-14
                                  2.9746443804E-11

Eigenvalues and error estimates:
     9.7148730504E+00  1.8359275385E-01
     1.6867201838E+01  3.4548339959E-01
     2.2091975216E+01  3.9020166811E-01
     2.4071877996E+01  5.9528012872E-01
     2.9323448036E+01  6.1285994361E-01

My Grid:
   number of vertices       =         597
   number of vertices I own =         597
   number of elements       =        2344
   number of leaf elements  =        1176
   leaf elements I own      =        1176
   number of levels         =          13
   degrees of freedom       =         597
   degrees of freedom I own =         597
   min and max degree       =           1          1

Eigenvalues and error estimates:
     9.7148730504E+00  1.8359275385E-01
     1.6867201838E+01  3.4548339959E-01
     2.2091975216E+01  3.9020166811E-01
     2.4071877996E+01  5.9528012872E-01
     2.9323448036E+01  6.1285994361E-01

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
