---------------------------------------------------------
           PHAML   Version 1.11.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         false
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_solver_when  PHASES
  print_solver_who   SLAVES
  print_error_when   NEVER
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     SLAVES
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             default
  preconditioner     default
  eigensolver        SLEPC_LANCZOS
  num_eval                    5
  lambda0             3.5000000000E+01
  scale_evec         SCALE_LINF
  transformation     ST_SHIFT_INVERT
  st_shift           lambda0
  eigen_ncv          default
  eigen_maxit        default
  eigen_tol          1.0000000000E-10
  harmonic_extraction  false
  true_residual        false
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

Solver information:
   number of column vectors   =          20
   maximum iterations allowed =         100
   number of iterations used  =           1
   number of converged eigens =           1
   eigensolver L2 residual    =   1.3655743203E-14
   eigensolver eval errest    =   4.8948151196E-16

Eigenvalues and error estimates:
     9.1115740741E+01  1.0829488805E+04
     0.0000000000E+00  0.0000000000E+00
     0.0000000000E+00  0.0000000000E+00
     0.0000000000E+00  0.0000000000E+00
     0.0000000000E+00  0.0000000000E+00

My Grid:
   number of vertices       =          25
   number of vertices I own =          25
   number of elements       =          64
   number of leaf elements  =          36
   leaf elements I own      =          36
   number of levels         =           4
   degrees of freedom       =          25
   degrees of freedom I own =          25
   min and max degree       =           1          1

Solver information:
   number of column vectors   =          20
   maximum iterations allowed =         100
   number of iterations used  =         100
   number of converged eigens =           4
   eigensolver L2 residual    =   5.1895133431E-14
                                  3.3792967439E-14
                                  5.7275576574E-13
                                  1.2731519545E-12
   eigensolver eval errest    =   8.1457519001E-16
                                  3.6805622046E-16
                                  3.5427998772E-15
                                  7.1140741210E-15

Eigenvalues and error estimates:
     6.1664150437E+01  4.2284691935E+02
     7.1222625882E+01  2.8460853100E+02
     1.6942096408E+02  8.3383645829E+02
     2.5135438682E+02  3.1226910041E+03
     0.0000000000E+00  0.0000000000E+00

My Grid:
   number of vertices       =          37
   number of vertices I own =          37
   number of elements       =         104
   number of leaf elements  =          56
   leaf elements I own      =          56
   number of levels         =           4
   degrees of freedom       =          37
   degrees of freedom I own =          37
   min and max degree       =           1          1

Solver information:
   number of column vectors   =          20
   maximum iterations allowed =         100
   number of iterations used  =           1
   number of converged eigens =           5
   eigensolver L2 residual    =   7.3279765024E-14
                                  7.5017075275E-15
                                  8.9062703126E-12
                                  3.1850567673E-11
                                  5.9374741874E-12
   eigensolver eval errest    =   5.9054955742E-15
                                  1.3097080422E-16
                                  1.1799116055E-13
                                  4.2492200932E-13
                                  9.2425982714E-14

Eigenvalues and error estimates:
     1.4056367185E+01  6.8701395599E+01
     5.7149626596E+01  3.0014921099E+02
     6.0748364849E+01  2.0623870380E+02
     6.0911389430E+01  2.0873357681E+02
     6.1581008563E+01  2.8696999180E+02

My Grid:
   number of vertices       =          73
   number of vertices I own =          73
   number of elements       =         248
   number of leaf elements  =         128
   leaf elements I own      =         128
   number of levels         =           8
   degrees of freedom       =          73
   degrees of freedom I own =          73
   min and max degree       =           1          1

Solver information:
   number of column vectors   =          20
   maximum iterations allowed =         100
   number of iterations used  =           1
   number of converged eigens =           5
   eigensolver L2 residual    =   6.3240953212E-12
                                  1.0747420912E-13
                                  4.5937360416E-15
                                  3.1242743411E-13
                                  9.1916039607E-12
   eigensolver eval errest    =   2.0915795332E-13
                                  1.4653480380E-15
                                  4.7827897881E-17
                                  3.0056999188E-15
                                  6.2745360521E-14

Eigenvalues and error estimates:
     1.0432947223E+01  3.4188246474E+00
     2.6671828032E+01  7.1101830990E+00
     3.3549123274E+01  1.3331483713E+01
     3.9557764226E+01  1.7085254287E+01
     4.7536846840E+01  1.4899090776E+01

My Grid:
   number of vertices       =         147
   number of vertices I own =         147
   number of elements       =         544
   number of leaf elements  =         276
   leaf elements I own      =         276
   number of levels         =          10
   degrees of freedom       =         147
   degrees of freedom I own =         147
   min and max degree       =           1          1

Solver information:
   number of column vectors   =          20
   maximum iterations allowed =         100
   number of iterations used  =           2
   number of converged eigens =           5
   eigensolver L2 residual    =   6.8452825960E-11
                                  6.4601661215E-12
                                  1.9325554794E-13
                                  6.1110758821E-12
                                  2.7793227992E-14
   eigensolver eval errest    =   1.2926700954E-12
                                  5.5808015865E-14
                                  1.3238141489E-15
                                  3.7457647726E-14
                                  1.5334407005E-16

Eigenvalues and error estimates:
     9.9343761417E+00  9.0769832467E-01
     2.4924762154E+01  3.1430015534E+00
     3.2930581335E+01  4.8694730316E+00
     3.6814461565E+01  4.4331879396E+00
     4.1429156835E+01  8.7846350692E+00

My Grid:
   number of vertices       =         339
   number of vertices I own =         339
   number of elements       =        1304
   number of leaf elements  =         656
   leaf elements I own      =         656
   number of levels         =          12
   degrees of freedom       =         339
   degrees of freedom I own =         339
   min and max degree       =           1          1

Solver information:
   number of column vectors   =          20
   maximum iterations allowed =         100
   number of iterations used  =         100
   number of converged eigens =           2
   eigensolver L2 residual    =   2.7974508842E-11
                                  3.3469542992E-14
   eigensolver eval errest    =   1.5268365488E-13
                                  1.2028579836E-16

Eigenvalues and error estimates:
     2.4311279848E+01  1.0512501652E+00
     3.9161992874E+01  1.8050538415E+00
     0.0000000000E+00  0.0000000000E+00
     0.0000000000E+00  0.0000000000E+00
     0.0000000000E+00  0.0000000000E+00

My Grid:
   number of vertices       =         595
   number of vertices I own =         595
   number of elements       =        2336
   number of leaf elements  =        1172
   leaf elements I own      =        1172
   number of levels         =          13
   degrees of freedom       =         595
   degrees of freedom I own =         595
   min and max degree       =           1          1

Solver information:
   number of column vectors   =          20
   maximum iterations allowed =         100
   number of iterations used  =         100
   number of converged eigens =           3
   eigensolver L2 residual    =   6.2399455675E-13
                                  4.7104561176E-14
                                  8.0170612519E-14
   eigensolver eval errest    =   2.3421820858E-15
                                  1.5263253931E-16
                                  1.9283996005E-16

Eigenvalues and error estimates:
     2.4073303237E+01  4.7686862929E-01
     3.4774176521E+01  1.2347285415E+00
     3.8601979001E+01  8.2981141536E-01
     0.0000000000E+00  0.0000000000E+00
     0.0000000000E+00  0.0000000000E+00

My Grid:
   number of vertices       =         595
   number of vertices I own =         595
   number of elements       =        2336
   number of leaf elements  =        1172
   leaf elements I own      =        1172
   number of levels         =          13
   degrees of freedom       =         595
   degrees of freedom I own =         595
   min and max degree       =           1          1

Eigenvalues and error estimates:
     2.4073303237E+01  4.7686862929E-01
     3.4774176521E+01  1.2347285415E+00
     3.8601979001E+01  8.2981141536E-01
     0.0000000000E+00  0.0000000000E+00
     0.0000000000E+00  0.0000000000E+00

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
