---------------------------------------------------------
           PHAML   Version 1.11.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         false
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_solver_when  PHASES
  print_solver_who   SLAVES
  print_error_when   NEVER
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     SLAVES
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             default
  preconditioner     default
  eigensolver        SLEPC_LAPACK
  num_eval                    1
  lambda0            -infinity
  scale_evec         SCALE_LINF
  transformation     ST_NONE
  eigen_ncv          default
  eigen_maxit        default
  eigen_tol          1.0000000000E-10
  harmonic_extraction  false
  true_residual        false
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

Solver information:
   number of column vectors   =           1
   maximum iterations allowed =           0
   number of iterations used  =           1
   number of converged eigens =           1
   eigensolver L2 residual    =   3.2751579226E-14
   eigensolver eval errest    =   1.1739597238E-15

Eigenvalues and error estimates:
     9.1115740741E+01  1.0829488805E+04

My Grid:
   number of vertices       =          25
   number of vertices I own =          25
   number of elements       =          64
   number of leaf elements  =          36
   leaf elements I own      =          36
   number of levels         =           4
   degrees of freedom       =          25
   degrees of freedom I own =          25
   min and max degree       =           1          1

Solver information:
   number of column vectors   =          13
   maximum iterations allowed =           0
   number of iterations used  =           1
   number of converged eigens =           1
   eigensolver L2 residual    =   1.1819963900E-13
   eigensolver eval errest    =   9.5196815380E-15

Eigenvalues and error estimates:
     1.4061093547E+01  8.4928851294E+01

My Grid:
   number of vertices       =          39
   number of vertices I own =          39
   number of elements       =         120
   number of leaf elements  =          64
   leaf elements I own      =          64
   number of levels         =           6
   degrees of freedom       =          39
   degrees of freedom I own =          39
   min and max degree       =           1          1

Solver information:
   number of column vectors   =          27
   maximum iterations allowed =           0
   number of iterations used  =           1
   number of converged eigens =           1
   eigensolver L2 residual    =   8.9034018104E-14
   eigensolver eval errest    =   5.3196995163E-15

Eigenvalues and error estimates:
     1.0511584737E+01  6.7277954652E+00

My Grid:
   number of vertices       =          77
   number of vertices I own =          77
   number of elements       =         264
   number of leaf elements  =         136
   leaf elements I own      =         136
   number of levels         =           9
   degrees of freedom       =          77
   degrees of freedom I own =          77
   min and max degree       =           1          1

Solver information:
   number of column vectors   =          61
   maximum iterations allowed =           0
   number of iterations used  =           1
   number of converged eigens =           1
   eigensolver L2 residual    =   5.1592802101E-14
   eigensolver eval errest    =   1.3983108147E-15

Eigenvalues and error estimates:
     1.0547745784E+01  2.8239005001E+00

My Grid:
   number of vertices       =         145
   number of vertices I own =         145
   number of elements       =         536
   number of leaf elements  =         272
   leaf elements I own      =         272
   number of levels         =          11
   degrees of freedom       =         145
   degrees of freedom I own =         145
   min and max degree       =           1          1

Solver information:
   number of column vectors   =         129
   maximum iterations allowed =           0
   number of iterations used  =           1
   number of converged eigens =           1
   eigensolver L2 residual    =   5.3486261339E-14
   eigensolver eval errest    =   8.9546575368E-16

Eigenvalues and error estimates:
     9.8891490073E+00  8.1290972559E-01

My Grid:
   number of vertices       =         353
   number of vertices I own =         353
   number of elements       =        1368
   number of leaf elements  =         688
   leaf elements I own      =         688
   number of levels         =          13
   degrees of freedom       =         353
   degrees of freedom I own =         353
   min and max degree       =           1          1

Solver information:
   number of column vectors   =         337
   maximum iterations allowed =           0
   number of iterations used  =           1
   number of converged eigens =           1
   eigensolver L2 residual    =   1.4694454501E-13
   eigensolver eval errest    =   1.5151416778E-15

Eigenvalues and error estimates:
     9.7501095364E+00  2.6878572927E-01

My Grid:
   number of vertices       =         625
   number of vertices I own =         625
   number of elements       =        2456
   number of leaf elements  =        1232
   leaf elements I own      =        1232
   number of levels         =          14
   degrees of freedom       =         625
   degrees of freedom I own =         625
   min and max degree       =           1          1

Solver information:
   number of column vectors   =         609
   maximum iterations allowed =           0
   number of iterations used  =           1
   number of converged eigens =           1
   eigensolver L2 residual    =   3.4335196008E-13
   eigensolver eval errest    =   2.3276362307E-15

Eigenvalues and error estimates:
     9.7100820081E+00  1.7331511558E-01

My Grid:
   number of vertices       =         625
   number of vertices I own =         625
   number of elements       =        2456
   number of leaf elements  =        1232
   leaf elements I own      =        1232
   number of levels         =          14
   degrees of freedom       =         625
   degrees of freedom I own =         625
   min and max degree       =           1          1

Eigenvalues and error estimates:
     9.7100820081E+00  1.7331511558E-01

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
