#! /bin/sh

set -e

if [ "$SPKG_LOCAL" = "" ]; then
   echo "SPKG_LOCAL undefined ... exiting";
   echo "Maybe run 'qsnake --shell'?"
   exit 1
fi

cmake -DCMAKE_INSTALL_PREFIX="$SPKG_LOCAL" .
make
make install
