---------------------------------------------------------
           PHAML   Version 1.11.0

Output from the master process
  PDE id is     0
  Number of slave processors is     1
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  false
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   FINAL
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    HIERARCHICAL_COEFFICIENT
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           false
  partition_method   RTK
  ignore_quad_err    true
  solver             PETSC_CG_SOLVER
  preconditioner     PETSC_SOR_PRECONDITION
  petsc_matrix_free  false
  petsc_rtol         default
  petsc_atol         default
  petsc_dtol         default
  petsc_maxits       default
  petsc_sor_omega    default
  petsc_sor_its      default
  petsc_sor_lits     default
---------------------------------------------------------

Total Grid:
   number of vertices      =          26
   number of leaf elements =          44
   number of levels        =           1
   degrees of freedom      =          26
   min and max degree      =           1          1

Total Grid:
   number of vertices      =          45
   number of leaf elements =         136
   number of levels        =           4
   degrees of freedom      =          45
   min and max degree      =           1          1

Total Grid:
   number of vertices      =         108
   number of leaf elements =         362
   number of levels        =           6
   degrees of freedom      =         108
   min and max degree      =           1          1

Total Grid:
   number of vertices      =         221
   number of leaf elements =         871
   number of levels        =           7
   degrees of freedom      =         221
   min and max degree      =           1          1

Total Grid:
   number of vertices      =         420
   number of leaf elements =        1874
   number of levels        =          10
   degrees of freedom      =         420
   min and max degree      =           1          1

Total Grid:
   number of vertices      =         870
   number of leaf elements =        4108
   number of levels        =          12
   degrees of freedom      =         870
   min and max degree      =           1          1

Total Grid:
   number of vertices      =        1743
   number of leaf elements =        8647
   number of levels        =          13
   degrees of freedom      =        1743
   min and max degree      =           1          1

Total Grid:
   number of vertices      =        1743
   number of leaf elements =        8647
   number of levels        =          13
   degrees of freedom      =        1743
   min and max degree      =           1          1

Norms of error:
   energy norm of error       3.4402851680E+00
   Linf norm of error         3.0172592540E-01

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
