---------------------------------------------------------
           PHAML   Version 1.11.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  false
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   FINAL
  print_error_who    SLAVES
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    HIERARCHICAL_COEFFICIENT
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           false
  partition_method   RTK
  ignore_quad_err    true
  solver             PETSC_CG_SOLVER
  preconditioner     PETSC_SOR_PRECONDITION
  petsc_matrix_free  false
  petsc_rtol         default
  petsc_atol         default
  petsc_dtol         default
  petsc_maxits       default
  petsc_sor_omega    default
  petsc_sor_its      default
  petsc_sor_lits     default
---------------------------------------------------------

My Grid:
   number of vertices       =          14
   number of vertices I own =          14
   number of elements       =          24
   number of leaf elements  =          24
   leaf elements I own      =          24
   number of levels         =           1
   degrees of freedom       =          14
   degrees of freedom I own =          14
   min and max degree       =           1          1

My Grid:
   number of vertices       =          35
   number of vertices I own =          35
   number of elements       =         144
   number of leaf elements  =          84
   leaf elements I own      =          84
   number of levels         =           4
   degrees of freedom       =          35
   degrees of freedom I own =          35
   min and max degree       =           1          1

My Grid:
   number of vertices       =          59
   number of vertices I own =          59
   number of elements       =         330
   number of leaf elements  =         177
   leaf elements I own      =         177
   number of levels         =           6
   degrees of freedom       =          59
   degrees of freedom I own =          59
   min and max degree       =           1          1

My Grid:
   number of vertices       =         120
   number of vertices I own =         120
   number of elements       =         798
   number of leaf elements  =         411
   leaf elements I own      =         411
   number of levels         =           7
   degrees of freedom       =         120
   degrees of freedom I own =         120
   min and max degree       =           1          1

My Grid:
   number of vertices       =         232
   number of vertices I own =         232
   number of elements       =        1814
   number of leaf elements  =         919
   leaf elements I own      =         919
   number of levels         =           9
   degrees of freedom       =         232
   degrees of freedom I own =         232
   min and max degree       =           1          1

My Grid:
   number of vertices       =         477
   number of vertices I own =         477
   number of elements       =        3996
   number of leaf elements  =        2010
   leaf elements I own      =        2010
   number of levels         =          10
   degrees of freedom       =         477
   degrees of freedom I own =         477
   min and max degree       =           1          1

My Grid:
   number of vertices       =         927
   number of vertices I own =         927
   number of elements       =        8442
   number of leaf elements  =        4233
   leaf elements I own      =        4233
   number of levels         =          11
   degrees of freedom       =         927
   degrees of freedom I own =         927
   min and max degree       =           1          1

My Grid:
   number of vertices       =        1860
   number of vertices I own =        1860
   number of elements       =       17788
   number of leaf elements  =        8906
   leaf elements I own      =        8906
   number of levels         =          13
   degrees of freedom       =        1860
   degrees of freedom I own =        1860
   min and max degree       =           1          1

My Grid:
   number of vertices       =        1860
   number of vertices I own =        1860
   number of elements       =       17788
   number of leaf elements  =        8906
   leaf elements I own      =        8906
   number of levels         =          13
   degrees of freedom       =        1860
   degrees of freedom I own =        1860
   min and max degree       =           1          1

Norms of error:
   energy norm of error       1.3305935806E+00
   Linf norm of error         1.5540031641E-01

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           7
termination condition:
  maximum vertices achieved
---------------------------------------------------------
