Warning:  Unknown switch --.
---------------------------------------------------------
           PHAML   Version 1.11.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  false
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   FINAL
  print_error_who    SLAVES
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    HIERARCHICAL_COEFFICIENT
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           false
  partition_method   RTK
  ignore_quad_err    true
  solver             PETSC_CG_SOLVER
  preconditioner     PETSC_SOR_PRECONDITION
  petsc_matrix_free  false
  petsc_rtol         default
  petsc_atol         default
  petsc_dtol         default
  petsc_maxits       default
  petsc_sor_omega    default
  petsc_sor_its      default
  petsc_sor_lits     default
---------------------------------------------------------

My Grid:
   number of vertices       =          51
   number of vertices I own =          51
   number of elements       =         129
   number of leaf elements  =         129
   leaf elements I own      =         129
   number of levels         =           1
   degrees of freedom       =          51
   degrees of freedom I own =          51
   min and max degree       =           1          1

My Grid:
   number of vertices       =         103
   number of vertices I own =         103
   number of elements       =         601
   number of leaf elements  =         365
   leaf elements I own      =         365
   number of levels         =           4
   degrees of freedom       =         103
   degrees of freedom I own =         103
   min and max degree       =           1          1

My Grid:
   number of vertices       =         245
   number of vertices I own =         245
   number of elements       =        1791
   number of leaf elements  =         960
   leaf elements I own      =         960
   number of levels         =           7
   degrees of freedom       =         245
   degrees of freedom I own =         245
   min and max degree       =           1          1

My Grid:
   number of vertices       =         417
   number of vertices I own =         417
   number of elements       =        3319
   number of leaf elements  =        1724
   leaf elements I own      =        1724
   number of levels         =           8
   degrees of freedom       =         417
   degrees of freedom I own =         417
   min and max degree       =           1          1

My Grid:
   number of vertices       =         842
   number of vertices I own =         842
   number of elements       =        7461
   number of leaf elements  =        3795
   leaf elements I own      =        3795
   number of levels         =          10
   degrees of freedom       =         842
   degrees of freedom I own =         842
   min and max degree       =           1          1

My Grid:
   number of vertices       =        1702
   number of vertices I own =        1702
   number of elements       =       15947
   number of leaf elements  =        8038
   leaf elements I own      =        8038
   number of levels         =          11
   degrees of freedom       =        1702
   degrees of freedom I own =        1702
   min and max degree       =           1          1

My Grid:
   number of vertices       =        1702
   number of vertices I own =        1702
   number of elements       =       15947
   number of leaf elements  =        8038
   leaf elements I own      =        8038
   number of levels         =          11
   degrees of freedom       =        1702
   degrees of freedom I own =        1702
   min and max degree       =           1          1

Norms of error:
   energy norm of error       5.3073882298E+01
   Linf norm of error         4.8224242529E+00

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           5
termination condition:
  maximum vertices achieved
---------------------------------------------------------
