---------------------------------------------------------
           PHAML   Version 1.9.1

Output from the master process
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   NEVER
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     MASTER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             PETSC_GMRES_SOLVER
  preconditioner     PETSC_SOR_PRECONDITION
  petsc_matrix_free  false
  petsc_rtol         default
  petsc_atol         default
  petsc_dtol         default
  petsc_maxits       default
  petsc_gmres_max_steps  default
  petsc_sor_omega    default
  petsc_sor_its      default
  petsc_sor_lits     default
  eigensolver        BLOPEX_SOLVER
  num_eval                    3
  lambda0             3.0000000000E+01
  scale_evec         SCALE_LINF
  lambda0_side       EIGEN_BOTH
  transformation     SHIFT_SQUARE
  blopex_maxit              100
  blopex_atol         1.0000000000E-06
  blopex_rtol         1.0000000000E-06
---------------------------------------------------------

Total Grid:
   number of vertices      =         145
   number of leaf elements =         256
   number of levels        =           1
   degrees of freedom      =         145
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      5.7950265898E-01
      effectivity             5.7950265898E-01
   Linf error estimate        1.1151087237E-01
      effectivity             1.1151087237E-01
 Eigenvector           2
   energy error estimate      7.6406595191E-01
   Linf error estimate        1.8071932971E-01
 Eigenvector           3
   energy error estimate      8.0380180353E-01
   Linf error estimate        2.0223633432E-01

Total Grid:
   number of vertices      =         290
   number of leaf elements =         546
   number of levels        =           6
   degrees of freedom      =         290
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      2.2472723631E-01
      reduced by              3.8779327898E-01
      effectivity             2.2472723631E-01
   Linf error estimate        1.4353568567E-02
      reduced by              1.2871900527E-01
      effectivity             1.4353568567E-02
 Eigenvector           2
   energy error estimate      2.5436169441E-01
      reduced by              3.3290541710E-01
   Linf error estimate        1.7277015588E-02
      reduced by              9.5601370458E-02
 Eigenvector           3
   energy error estimate      3.1559092979E-01
      reduced by              3.9262281872E-01
   Linf error estimate        2.1524359469E-02
      reduced by              1.0643171288E-01

Eigenvalues and error estimates:
     2.4134192316E+01  1.6511656502E-01
     2.4754320205E+01  1.9614996331E-01
     2.8152611249E+01  2.5840299843E-01

Total Grid:
   number of vertices      =         650
   number of leaf elements =        1266
   number of levels        =           8
   degrees of freedom      =         650
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      1.3839300407E-01
      reduced by              6.1582657423E-01
      effectivity             1.3839300407E-01
   Linf error estimate        4.3453783825E-03
      reduced by              3.0273853934E-01
      effectivity             4.3453783825E-03
 Eigenvector           2
   energy error estimate      1.3032795350E-01
      reduced by              5.1237256381E-01
   Linf error estimate        5.1418863662E-03
      reduced by              2.9761426908E-01
 Eigenvector           3
   energy error estimate      1.8131365699E-01
      reduced by              5.7452112807E-01
   Linf error estimate        8.0958634872E-03
      reduced by              3.7612564029E-01

Eigenvalues and error estimates:
     2.4186639028E+01  6.2210041265E-02
     2.4896128408E+01  6.2180731096E-02
     3.1640225752E+01  8.2942343638E-02

Total Grid:
   number of vertices      =        1295
   number of leaf elements =        2556
   number of levels        =           9
   degrees of freedom      =        1295
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      9.2019883289E-02
      reduced by              6.6491716042E-01
      effectivity             9.2019883289E-02
   Linf error estimate        2.2060333577E-03
      reduced by              5.0767347824E-01
      effectivity             2.2060333577E-03
 Eigenvector           2
   energy error estimate      8.4127374927E-02
      reduced by              6.4550522484E-01
   Linf error estimate        2.3912550154E-03
      reduced by              4.6505403758E-01
 Eigenvector           3
   energy error estimate      1.1679402554E-01
      reduced by              6.4415459638E-01
   Linf error estimate        2.9131595993E-03
      reduced by              3.5983309302E-01

Eigenvalues and error estimates:
     2.4040662368E+01  2.6995627669E-02
     2.4777526481E+01  2.4237435232E-02
     3.1212306619E+01  3.4352386563E-02

Total Grid:
   number of vertices      =        1295
   number of leaf elements =        2556
   number of levels        =           9
   degrees of freedom      =        1295
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      9.2019883289E-02
      effectivity             9.2019883289E-02
   Linf error estimate        2.2060333577E-03
      effectivity             2.2060333577E-03
 Eigenvector           2
   energy error estimate      8.4127374927E-02
   Linf error estimate        2.3912550154E-03
 Eigenvector           3
   energy error estimate      1.1679402554E-01
   Linf error estimate        2.9131595993E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
