---------------------------------------------------------
           PHAML   Version 1.9.1

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     MASTER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             PETSC_CG_SOLVER
  preconditioner     PETSC_SOR_PRECONDITION
  petsc_matrix_free  false
  petsc_rtol         default
  petsc_atol         default
  petsc_dtol         default
  petsc_maxits       default
  petsc_sor_omega    default
  petsc_sor_its      default
  petsc_sor_lits     default
  eigensolver        BLOPEX_SOLVER
  num_eval                    1
  lambda0            -infinity
  scale_evec         SCALE_L2
  blopex_maxit              100
  blopex_atol         1.0000000000E-06
  blopex_rtol         1.0000000000E-06
---------------------------------------------------------

Total Grid:
   number of vertices      =         145
   number of leaf elements =         256
   number of levels        =           1
   degrees of freedom      =         145
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       9.2329120106E-01
   energy error estimate      2.8332650670E-01
      effectivity             3.0686581479E-01
   Linf norm of error         2.3597609260E-01
   Linf error estimate        8.3800676562E-02
      effectivity             3.5512358747E-01

Total Grid:
   number of vertices      =         301
   number of leaf elements =         568
   number of levels        =           7
   degrees of freedom      =         301
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       2.1594447999E+00
      reduced by              2.3388556042E+00
   energy error estimate      1.3554177121E-02
      reduced by              4.7839424836E-02
      effectivity             6.2766953440E-03
   Linf norm of error         8.4467034522E-01
      reduced by              3.5794742421E+00
   Linf error estimate        6.1268822509E-04
      reduced by              7.3112563075E-03
      effectivity             7.2535780208E-04

Eigenvalues and error estimates:
     9.8395691436E+00  8.4604158997E-03

Total Grid:
   number of vertices      =         593
   number of leaf elements =        1152
   number of levels        =           8
   degrees of freedom      =         593
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       2.3130645782E+00
      reduced by              5.3556927649E-01
   energy error estimate      4.7215775384E-03
      reduced by              1.7417425994E-01
      effectivity             2.0412649015E-03
   Linf norm of error         9.0552427970E-01
      reduced by              1.0720445968E+00
   Linf error estimate        1.2727658427E-04
      reduced by              2.0773466677E-01
      effectivity             1.4055568373E-04

Eigenvalues and error estimates:
     9.7150685417E+00  1.9822586721E-03

Total Grid:
   number of vertices      =        1209
   number of leaf elements =        2384
   number of levels        =           9
   degrees of freedom      =        1209
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       2.3914406542E+00
      reduced by              1.0338840846E+00
   energy error estimate      2.1014492843E-03
      reduced by              4.4507355163E-01
      effectivity             8.7873779372E-04
   Linf norm of error         9.3634635724E-01
      reduced by              1.0340378256E+00
   Linf error estimate        3.4992755075E-05
      reduced by              2.7493474369E-01
      effectivity             3.7371593112E-05

Eigenvalues and error estimates:
     9.6851931226E+00  5.8241025668E-04

Total Grid:
   number of vertices      =        1209
   number of leaf elements =        2384
   number of levels        =           9
   degrees of freedom      =        1209
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       2.3914406542E+00
   energy error estimate      2.1014492843E-03
      effectivity             8.7873779372E-04
   Linf norm of error         9.3634635724E-01
   Linf error estimate        3.4992755075E-05
      effectivity             3.7371593112E-05

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
