---------------------------------------------------------
           PHAML   Version 1.9.1

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     MASTER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             PETSC_CG_SOLVER
  preconditioner     PETSC_SOR_PRECONDITION
  petsc_matrix_free  false
  petsc_rtol         default
  petsc_atol         default
  petsc_dtol         default
  petsc_maxits       default
  petsc_sor_omega    default
  petsc_sor_its      default
  petsc_sor_lits     default
  eigensolver        BLOPEX_SOLVER
  num_eval                    1
  lambda0            -infinity
  scale_evec         SCALE_LINF
  blopex_maxit                1
  blopex_atol         1.0000000000E-01
  blopex_rtol         1.0000000000E-02
---------------------------------------------------------

Total Grid:
   number of vertices      =         145
   number of leaf elements =         256
   number of levels        =           1
   degrees of freedom      =         145
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       2.4801043944E+00
   energy error estimate      1.0482191532E+00
      effectivity             4.2265122209E-01
   Linf norm of error         3.2056754851E-01
   Linf error estimate        1.4165759657E-01
      effectivity             4.4189624692E-01

Total Grid:
   number of vertices      =         299
   number of leaf elements =         547
   number of levels        =           5
   degrees of freedom      =         299
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       7.3967839993E-01
      reduced by              2.9824486486E-01
   energy error estimate      1.8030524249E-01
      reduced by              1.7201101692E-01
      effectivity             2.4376167063E-01
   Linf norm of error         9.2328763598E-02
      reduced by              2.8801656321E-01
   Linf error estimate        1.6004010025E-02
      reduced by              1.1297671578E-01
      effectivity             1.7333720719E-01

Eigenvalues and error estimates:
     1.0296733308E+01  2.1979543530E-01

Total Grid:
   number of vertices      =         582
   number of leaf elements =        1110
   number of levels        =           8
   degrees of freedom      =         582
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       3.4404878317E-01
      reduced by              2.3256646618E-01
   energy error estimate      6.8425011111E-02
      reduced by              1.8974770274E-01
      effectivity             1.9888171230E-01
   Linf norm of error         6.4521398055E-02
      reduced by              6.9882229048E-01
   Linf error estimate        2.3646209654E-03
      reduced by              1.4775177981E-01
      effectivity             3.6648631875E-02

Eigenvalues and error estimates:
     9.7875360884E+00  4.3680708065E-02

Total Grid:
   number of vertices      =        1162
   number of leaf elements =        2268
   number of levels        =           9
   degrees of freedom      =        1162
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       2.4294969793E-01
      reduced by              7.0614898181E-01
   energy error estimate      4.0000865528E-02
      reduced by              5.8459421311E-01
      effectivity             1.6464669793E-01
   Linf norm of error         5.4575895784E-02
      reduced by              8.4585730361E-01
   Linf error estimate        8.1177455984E-04
      reduced by              3.4330007715E-01
      effectivity             1.4874232446E-02

Eigenvalues and error estimates:
     9.7204227232E+00  1.7804958979E-02

Total Grid:
   number of vertices      =        1162
   number of leaf elements =        2268
   number of levels        =           9
   degrees of freedom      =        1162
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       2.4294969793E-01
   energy error estimate      4.0000865528E-02
      effectivity             1.6464669793E-01
   Linf norm of error         5.4575895784E-02
   Linf error estimate        8.1177455984E-04
      effectivity             1.4874232446E-02

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
