---------------------------------------------------------
           PHAML   Version 1.9.1

Output from the master process
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   NEVER
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     MASTER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             PETSC_GMRES_SOLVER
  preconditioner     PETSC_SOR_PRECONDITION
  petsc_matrix_free  false
  petsc_rtol         default
  petsc_atol         default
  petsc_dtol         default
  petsc_maxits       default
  petsc_gmres_max_steps  default
  petsc_sor_omega    default
  petsc_sor_its      default
  petsc_sor_lits     default
  eigensolver        BLOPEX_SOLVER
  num_eval                    3
  lambda0             3.0000000000E+01
  scale_evec         SCALE_LINF
  lambda0_side       EIGEN_RIGHT
  transformation     SHIFT_INVERT
  blopex_maxit              100
  blopex_atol         1.0000000000E-06
  blopex_rtol         1.0000000000E-06
---------------------------------------------------------

Total Grid:
   number of vertices      =         145
   number of leaf elements =         256
   number of levels        =           1
   degrees of freedom      =         145
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      1.0669297096E+00
      effectivity             1.0669297096E+00
   Linf error estimate        2.1437005477E-01
      effectivity             2.1437005477E-01
 Eigenvector           2
   energy error estimate      1.0561875830E+00
   Linf error estimate        2.2067704547E-01
 Eigenvector           3
   energy error estimate      1.1357481358E+01
   Linf error estimate        1.7185982377E+00

Total Grid:
   number of vertices      =         294
   number of leaf elements =         550
   number of levels        =           6
   degrees of freedom      =         294
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      3.6010801539E-01
      reduced by              3.3751803155E-01
      effectivity             3.6010801539E-01
   Linf error estimate        3.8964361593E-02
      reduced by              1.8176214786E-01
      effectivity             3.8964361593E-02
 Eigenvector           2
   energy error estimate      4.2663360915E-01
      reduced by              4.0393734598E-01
   Linf error estimate        1.4767022720E-01
      reduced by              6.6916895177E-01
 Eigenvector           3
   energy error estimate      4.9010395458E-01
      reduced by              4.3152521157E-02
   Linf error estimate        7.5673053288E-02
      reduced by              4.4031846203E-02

Eigenvalues and error estimates:
     3.0480576931E+01  3.7409913878E-01
     3.2430371868E+01  5.7129002358E-01
     3.6624421754E+01  5.2037391630E-01

Total Grid:
   number of vertices      =         591
   number of leaf elements =        1148
   number of levels        =           8
   degrees of freedom      =         591
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      2.1079714807E-01
      reduced by              5.8537199691E-01
      effectivity             2.1079714807E-01
   Linf error estimate        9.2162408367E-03
      reduced by              2.3653000999E-01
      effectivity             9.2162408367E-03
 Eigenvector           2
   energy error estimate      2.1064038650E-01
      reduced by              4.9372665909E-01
   Linf error estimate        8.1069013496E-03
      reduced by              5.4898685425E-02
 Eigenvector           3
   energy error estimate      2.8733122940E-01
      reduced by              5.8626588647E-01
   Linf error estimate        1.6112209634E-02
      reduced by              2.1291871986E-01

Eigenvalues and error estimates:
     3.1382273819E+01  1.2196835994E-01
     3.4694369154E+01  9.6939653532E-02
     3.6860092988E+01  1.8207486048E-01

Total Grid:
   number of vertices      =        1267
   number of leaf elements =        2500
   number of levels        =           9
   degrees of freedom      =        1267
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      1.3106528034E-01
      reduced by              6.2176021608E-01
      effectivity             1.3106528034E-01
   Linf error estimate        3.3855802141E-03
      reduced by              3.6734936446E-01
      effectivity             3.3855802141E-03
 Eigenvector           2
   energy error estimate      1.3925475932E-01
      reduced by              6.6110189803E-01
   Linf error estimate        3.2838851605E-03
      reduced by              4.0507279156E-01
 Eigenvector           3
   energy error estimate      1.6206291298E-01
      reduced by              5.6402818906E-01
   Linf error estimate        3.4099907727E-03
      reduced by              2.1164016917E-01

Eigenvalues and error estimates:
     3.1072470701E+01  4.2294526261E-02
     3.4370581521E+01  3.7364719307E-02
     3.6325949933E+01  5.1086135430E-02

Total Grid:
   number of vertices      =        1267
   number of leaf elements =        2500
   number of levels        =           9
   degrees of freedom      =        1267
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      1.3106528034E-01
      effectivity             1.3106528034E-01
   Linf error estimate        3.3855802141E-03
      effectivity             3.3855802141E-03
 Eigenvector           2
   energy error estimate      1.3925475932E-01
   Linf error estimate        3.2838851605E-03
 Eigenvector           3
   energy error estimate      1.6206291298E-01
   Linf error estimate        3.4099907727E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
INFO = 11
