---------------------------------------------------------
           PHAML   Version 1.9.1

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     MASTER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             PETSC_CG_SOLVER
  preconditioner     PETSC_SOR_PRECONDITION
  petsc_matrix_free  false
  petsc_rtol         default
  petsc_atol         default
  petsc_dtol         default
  petsc_maxits       default
  petsc_sor_omega    default
  petsc_sor_its      default
  petsc_sor_lits     default
  eigensolver        BLOPEX_SOLVER
  num_eval                    3
  lambda0            -infinity
  scale_evec         SCALE_LINF
  blopex_maxit              100
  blopex_atol         1.0000000000E-06
  blopex_rtol         1.0000000000E-06
---------------------------------------------------------

Total Grid:
   number of vertices      =         145
   number of leaf elements =         256
   number of levels        =           1
   degrees of freedom      =         145
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       8.5561841322E-01
   energy error estimate      3.3353374079E-01
      effectivity             3.8981599232E-01
   Linf norm of error         1.3374884879E-01
   Linf error estimate        9.8650670117E-02
      effectivity             7.3758145219E-01
 Eigenvector           2
   energy error estimate      6.0198893023E-01
   Linf error estimate        1.1114181693E-01
 Eigenvector           3
   energy error estimate      7.2589535734E-01
   Linf error estimate        1.7696533626E-01

Total Grid:
   number of vertices      =         307
   number of leaf elements =         580
   number of levels        =           6
   degrees of freedom      =         307
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       3.7468637743E-01
      reduced by              4.3791294301E-01
   energy error estimate      1.0327792801E-01
      reduced by              3.0964761696E-01
      effectivity             2.7563833177E-01
   Linf norm of error         2.9613494035E-02
      reduced by              2.2141120693E-01
   Linf error estimate        7.5013654453E-03
      reduced by              7.6039680586E-02
      effectivity             2.5330902987E-01
 Eigenvector           2
   energy error estimate      1.6484867035E-01
      reduced by              2.7384003604E-01
   Linf error estimate        9.1511493401E-03
      reduced by              8.2337589872E-02
 Eigenvector           3
   energy error estimate      2.3636677960E-01
      reduced by              3.2562101027E-01
   Linf error estimate        1.4045659163E-02
      reduced by              7.9369550331E-02

Eigenvalues and error estimates:
     9.8614745421E+00  7.4619467119E-02
     1.7182453393E+01  1.1500678351E-01
     2.4579846521E+01  1.5446169410E-01

Total Grid:
   number of vertices      =         605
   number of leaf elements =        1176
   number of levels        =           8
   degrees of freedom      =         605
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       2.1372991682E-01
      reduced by              2.8521175267E-01
   energy error estimate      5.8890778934E-02
      reduced by              2.8510825144E-01
      effectivity             2.7553830466E-01
   Linf norm of error         1.1101270466E-02
      reduced by              3.7487202464E-01
   Linf error estimate        2.9798732748E-03
      reduced by              3.9724411463E-01
      effectivity             2.6842632868E-01
 Eigenvector           2
   energy error estimate      9.6412581142E-02
      reduced by              2.9242753654E-01
   Linf error estimate        3.6558336741E-03
      reduced by              3.9949448296E-01
 Eigenvector           3
   energy error estimate      1.3225522676E-01
      reduced by              2.7976695156E-01
   Linf error estimate        3.7928675214E-03
      reduced by              2.7003841382E-01

Eigenvalues and error estimates:
     9.7262437749E+00  2.7879536648E-02
     1.6883177546E+01  4.0864466444E-02
     2.4075343482E+01  5.3648197575E-02

Total Grid:
   number of vertices      =        1207
   number of leaf elements =        2380
   number of levels        =           9
   degrees of freedom      =        1207
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       1.3957355648E-01
      reduced by              6.5303705985E-01
   energy error estimate      3.9056674078E-02
      reduced by              6.6320525530E-01
      effectivity             2.7982860839E-01
   Linf norm of error         4.7315663962E-03
      reduced by              4.2621845948E-01
   Linf error estimate        9.8940405099E-04
      reduced by              3.3202890182E-01
      effectivity             2.0910708382E-01
 Eigenvector           2
   energy error estimate      6.5060496811E-02
      reduced by              6.7481334946E-01
   Linf error estimate        1.3521920938E-03
      reduced by              3.6987243248E-01
 Eigenvector           3
   energy error estimate      9.1052141261E-02
      reduced by              6.8845779097E-01
   Linf error estimate        3.3488107439E-03
      reduced by              8.8292320388E-01

Eigenvalues and error estimates:
     9.6879944534E+00  1.1893824210E-02
     1.6800000906E+01  1.8092112744E-02
     2.2005770942E+01  3.2003856797E-02

Total Grid:
   number of vertices      =        1207
   number of leaf elements =        2380
   number of levels        =           9
   degrees of freedom      =        1207
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       1.3957355648E-01
   energy error estimate      3.9056674078E-02
      effectivity             2.7982860839E-01
   Linf norm of error         4.7315663962E-03
   Linf error estimate        9.8940405099E-04
      effectivity             2.0910708382E-01
 Eigenvector           2
   energy error estimate      6.5060496811E-02
   Linf error estimate        1.3521920938E-03
 Eigenvector           3
   energy error estimate      9.1052141261E-02
   Linf error estimate        3.3488107439E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
