---------------------------------------------------------
           PHAML   Version 1.9.1

Output from the master process
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   NEVER
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     MASTER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             PETSC_GMRES_SOLVER
  preconditioner     PETSC_SOR_PRECONDITION
  petsc_matrix_free  false
  petsc_rtol         default
  petsc_atol         default
  petsc_dtol         default
  petsc_maxits       default
  petsc_gmres_max_steps  default
  petsc_sor_omega    default
  petsc_sor_its      default
  petsc_sor_lits     default
  eigensolver        BLOPEX_SOLVER
  num_eval                    3
  lambda0             3.0000000000E+01
  scale_evec         SCALE_LINF
  lambda0_side       EIGEN_LEFT
  transformation     SHIFT_INVERT
  blopex_maxit              100
  blopex_atol         1.0000000000E-06
  blopex_rtol         1.0000000000E-06
---------------------------------------------------------

Total Grid:
   number of vertices      =         145
   number of leaf elements =         256
   number of levels        =           1
   degrees of freedom      =         145
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      3.3353446762E-01
      effectivity             3.3353446762E-01
   Linf error estimate        9.8650832978E-02
      effectivity             9.8650832978E-02
 Eigenvector           2
   energy error estimate      6.0198683624E-01
   Linf error estimate        1.1114177806E-01
 Eigenvector           3
   energy error estimate      7.2589552874E-01
   Linf error estimate        1.7696598835E-01

Total Grid:
   number of vertices      =         307
   number of leaf elements =         580
   number of levels        =           6
   degrees of freedom      =         307
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      1.6513904537E-01
      reduced by              4.9511838027E-01
      effectivity             1.6513904537E-01
   Linf error estimate        9.1594983361E-03
      reduced by              9.2847653280E-02
      effectivity             9.1594983361E-03
 Eigenvector           2
   energy error estimate      2.4677511451E-01
      reduced by              4.0993440331E-01
   Linf error estimate        1.7576134483E-02
      reduced by              1.5814156288E-01
 Eigenvector           3
   energy error estimate      2.3603856862E-01
      reduced by              3.2516878707E-01
   Linf error estimate        1.4010628293E-02
      reduced by              7.9171305308E-02

Eigenvalues and error estimates:
     1.7182653344E+01  1.1522890036E-01
     2.2574077187E+01  1.6964443529E-01
     2.4582290261E+01  1.5573810759E-01

Total Grid:
   number of vertices      =         650
   number of leaf elements =        1266
   number of levels        =           8
   degrees of freedom      =         650
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      1.3112980036E-01
      reduced by              7.9405691166E-01
      effectivity             1.3112980036E-01
   Linf error estimate        3.8894678238E-03
      reduced by              4.2463764729E-01
      effectivity             3.8894678238E-03
 Eigenvector           2
   energy error estimate      1.8351266419E-01
      reduced by              7.4364331488E-01
   Linf error estimate        7.7425361777E-03
      reduced by              4.4051416340E-01
 Eigenvector           3
   energy error estimate      5.0070612306E+00
      reduced by              2.1212894401E+01
   Linf error estimate        4.9432286997E-01
      reduced by              3.5281991616E+01

Eigenvalues and error estimates:
     2.4039937577E+01  5.9319071693E-02
     2.9339065048E+01  8.1722515078E-02
     3.6962924943E+03  7.3281184128E+00

Total Grid:
   number of vertices      =        1350
   number of leaf elements =        2666
   number of levels        =          11
   degrees of freedom      =        1350
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      1.6403557469E-01
      reduced by              1.2509404746E+00
      effectivity             1.6403557469E-01
   Linf error estimate        6.9402064928E-03
      reduced by              1.7843588910E+00
      effectivity             6.9402064928E-03
 Eigenvector           2
   energy error estimate      1.8648552849E-01
      reduced by              1.0161997773E+00
   Linf error estimate        9.2918283309E-03
      reduced by              1.2001013773E+00
 Eigenvector           3
   energy error estimate      2.6310202774E-01
      reduced by              5.2546197384E-02
   Linf error estimate        1.5041119522E-02
      reduced by              3.0427723327E-02

Eigenvalues and error estimates:
     2.2276422169E+01  9.1256770572E-02
     2.4270500691E+01  1.1223516978E-01
     2.9699469207E+01  1.6200054823E-01

Total Grid:
   number of vertices      =        1350
   number of leaf elements =        2666
   number of levels        =          11
   degrees of freedom      =        1350
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      1.6403557469E-01
      effectivity             1.6403557469E-01
   Linf error estimate        6.9402064928E-03
      effectivity             6.9402064928E-03
 Eigenvector           2
   energy error estimate      1.8648552849E-01
   Linf error estimate        9.2918283309E-03
 Eigenvector           3
   energy error estimate      2.6310202774E-01
   Linf error estimate        1.5041119522E-02

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
