---------------------------------------------------------
           PHAML   Version 1.9.1

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  350
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     MASTER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree                      4
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             PETSC_CG_SOLVER
  preconditioner     PETSC_SOR_PRECONDITION
  petsc_matrix_free  false
  petsc_rtol         default
  petsc_atol         default
  petsc_dtol         default
  petsc_maxits       default
  petsc_sor_omega    default
  petsc_sor_its      default
  petsc_sor_lits     default
  eigensolver        BLOPEX_SOLVER
  num_eval                    1
  lambda0            -infinity
  scale_evec         SCALE_LINF
  blopex_maxit              100
  blopex_atol         1.0000000000E-06
  blopex_rtol         1.0000000000E-06
---------------------------------------------------------

Total Grid:
   number of vertices      =         145
   number of leaf elements =         256
   number of levels        =           1
   degrees of freedom      =        2113
   min and max degree      =           4          4

Norms of error:
 Eigenvector           1
   energy norm of error       2.4148519128E-02
   energy error estimate      2.0838288532E-02
      effectivity             8.6292200455E-01
   Linf norm of error         6.7057118781E-03
   Linf error estimate        8.5395460161E-03
      effectivity             1.2734734464E+00

Total Grid:
   number of vertices      =         301
   number of leaf elements =         568
   number of levels        =          11
   degrees of freedom      =        4609
   min and max degree      =           4          4

Norms of error:
 Eigenvector           1
   energy norm of error       8.9665745232E-03
      reduced by              1.8565474918E-01
   energy error estimate      9.3938711137E-04
      reduced by              2.2539929561E-02
      effectivity             1.0476543846E-01
   Linf norm of error         2.8757885071E-03
      reduced by              4.2885655683E-01
   Linf error estimate        1.8315814580E-04
      reduced by              2.1448229854E-02
      effectivity             6.3689713394E-02

Eigenvalues and error estimates:
     9.6592895819E+00  2.1989893527E-07

Total Grid:
   number of vertices      =         558
   number of leaf elements =        1082
   number of levels        =          19
   degrees of freedom      =        8721
   min and max degree      =           4          4

Norms of error:
 Eigenvector           1
   energy norm of error       1.4630393239E-04
      reduced by              1.6316591360E-02
   energy error estimate      1.2842050528E-04
      reduced by              1.3670669282E-01
      effectivity             8.7776523281E-01
   Linf norm of error         8.1659333294E-06
      reduced by              2.8395458529E-03
   Linf error estimate        1.6902517779E-05
      reduced by              9.2283734942E-02
      effectivity             2.0698819226E+00

Eigenvalues and error estimates:
     9.6592582945E+00  6.1618790072E-09

Total Grid:
   number of vertices      =         558
   number of leaf elements =        1082
   number of levels        =          19
   degrees of freedom      =        8721
   min and max degree      =           4          4

Norms of error:
 Eigenvector           1
   energy norm of error       1.4630393239E-04
   energy error estimate      1.2842050528E-04
      effectivity             8.7776523281E-01
   Linf norm of error         8.1659333294E-06
   Linf error estimate        1.6902517779E-05
      effectivity             2.0698819226E+00

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           2
termination condition:
  maximum vertices achieved
---------------------------------------------------------
