---------------------------------------------------------
           PHAML   Version 1.9.1

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     MASTER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             PETSC_CG_SOLVER
  preconditioner     PETSC_SOR_PRECONDITION
  petsc_matrix_free  false
  petsc_rtol         default
  petsc_atol         default
  petsc_dtol         default
  petsc_maxits       default
  petsc_sor_omega    default
  petsc_sor_its      default
  petsc_sor_lits     default
  eigensolver        BLOPEX_SOLVER
  num_eval                    1
  lambda0            -infinity
  scale_evec         SCALE_M
  blopex_maxit              100
  blopex_atol         1.0000000000E-06
  blopex_rtol         1.0000000000E-06
---------------------------------------------------------

Total Grid:
   number of vertices      =         145
   number of leaf elements =         256
   number of levels        =           1
   degrees of freedom      =         145
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       1.2210227036E+00
   energy error estimate      4.5104234878E-01
      effectivity             3.6939718439E-01
   Linf norm of error         3.5231410548E-01
   Linf error estimate        1.3340669896E-01
      effectivity             3.7865840987E-01

Total Grid:
   number of vertices      =         301
   number of leaf elements =         568
   number of levels        =           7
   degrees of freedom      =         301
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       7.0182054936E-01
      reduced by              5.7478091710E-01
   energy error estimate      1.0662108044E-01
      reduced by              2.3638818113E-01
      effectivity             1.5192071611E-01
   Linf norm of error         2.2385353974E-01
      reduced by              6.3538057733E-01
   Linf error estimate        4.8195829187E-03
      reduced by              3.6126993295E-02
      effectivity             2.1530072405E-02

Eigenvalues and error estimates:
     9.8395691436E+00  6.6552080301E-02

Total Grid:
   number of vertices      =         593
   number of leaf elements =        1152
   number of levels        =           8
   degrees of freedom      =         593
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       6.0289558292E-01
      reduced by              4.2952260622E-01
   energy error estimate      6.0947911240E-02
      reduced by              2.8581548315E-01
      effectivity             1.0109198503E-01
   Linf norm of error         2.1970575839E-01
      reduced by              9.8147100396E-01
   Linf error estimate        1.6429343579E-03
      reduced by              3.4088724804E-01
      effectivity             7.4778848305E-03

Eigenvalues and error estimates:
     9.7150685417E+00  2.5587745753E-02

Total Grid:
   number of vertices      =        1209
   number of leaf elements =        2384
   number of levels        =           9
   degrees of freedom      =        1209
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       5.7721742617E-01
      reduced by              9.5740861690E-01
   energy error estimate      4.0233952567E-02
      reduced by              6.6013669293E-01
      effectivity             6.9703288124E-02
   Linf norm of error         2.1870066656E-01
      reduced by              9.9542528225E-01
   Linf error estimate        6.6996470407E-04
      reduced by              4.0778543638E-01
      effectivity             3.0633866581E-03

Eigenvalues and error estimates:
     9.6851931226E+00  1.1150717182E-02

Total Grid:
   number of vertices      =        1209
   number of leaf elements =        2384
   number of levels        =           9
   degrees of freedom      =        1209
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       5.7721742617E-01
   energy error estimate      4.0233952567E-02
      effectivity             6.9703288124E-02
   Linf norm of error         2.1870066656E-01
   Linf error estimate        6.6996470407E-04
      effectivity             3.0633866581E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
