---------------------------------------------------------
           PHAML   Version 1.9.1

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     MASTER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             PETSC_CG_SOLVER
  preconditioner     PETSC_SOR_PRECONDITION
  petsc_matrix_free  false
  petsc_rtol         default
  petsc_atol         default
  petsc_dtol         default
  petsc_maxits       default
  petsc_sor_omega    default
  petsc_sor_its      default
  petsc_sor_lits     default
  eigensolver        BLOPEX_SOLVER
  num_eval                    1
  lambda0            -infinity
  scale_evec         SCALE_LINF
  blopex_maxit              100
  blopex_atol         1.0000000000E-06
  blopex_rtol         1.0000000000E-06
---------------------------------------------------------

Total Grid:
   number of vertices      =         145
   number of leaf elements =         256
   number of levels        =           1
   degrees of freedom      =         145
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       8.5561840019E-01
   energy error estimate      3.3353371599E-01
      effectivity             3.8981596926E-01
   Linf norm of error         1.3374892324E-01
   Linf error estimate        9.8650674733E-02
      effectivity             7.3758107611E-01

Total Grid:
   number of vertices      =         301
   number of leaf elements =         568
   number of levels        =           7
   degrees of freedom      =         301
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       3.5290394270E-01
      reduced by              4.1245483105E-01
   energy error estimate      8.7119150272E-02
      reduced by              2.6120043071E-01
      effectivity             2.4686363549E-01
   Linf norm of error         2.7416520084E-02
      reduced by              2.0498497797E-01
   Linf error estimate        3.9380389583E-03
      reduced by              3.9919027102E-02
      effectivity             1.4363744729E-01

Eigenvalues and error estimates:
     9.8395691436E+00  5.4379121471E-02

Total Grid:
   number of vertices      =         593
   number of leaf elements =        1152
   number of levels        =           8
   degrees of freedom      =         593
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       1.9487215223E-01
      reduced by              2.7609800947E-01
   energy error estimate      4.9969355987E-02
      reduced by              2.8678743899E-01
      effectivity             2.5642122497E-01
   Linf norm of error         7.0083377100E-03
      reduced by              2.5562462664E-01
   Linf error estimate        1.3469923763E-03
      reduced by              3.4204648317E-01
      effectivity             1.9219855435E-01

Eigenvalues and error estimates:
     9.7150685417E+00  2.0978621751E-02

Total Grid:
   number of vertices      =        1209
   number of leaf elements =        2384
   number of levels        =           9
   degrees of freedom      =        1209
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       1.3256927074E-01
      reduced by              6.8028843131E-01
   energy error estimate      3.3013810258E-02
      reduced by              6.6068112358E-01
      effectivity             2.4903063940E-01
   Linf norm of error         4.9274317689E-03
      reduced by              7.0308138288E-01
   Linf error estimate        5.4973688162E-04
      reduced by              4.0812174687E-01
      effectivity             1.1156661470E-01

Eigenvalues and error estimates:
     9.6851931226E+00  9.1496767732E-03

Total Grid:
   number of vertices      =        1209
   number of leaf elements =        2384
   number of levels        =           9
   degrees of freedom      =        1209
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       1.3256927074E-01
   energy error estimate      3.3013810258E-02
      effectivity             2.4903063940E-01
   Linf norm of error         4.9274317689E-03
   Linf error estimate        5.4973688162E-04
      effectivity             1.1156661470E-01

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
