---------------------------------------------------------
           PHAML   Version 1.11.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop            1
  task               REFINE_ONLY
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    NEVER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree                      3
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           1
termination condition:
  one trip refinement
---------------------------------------------------------
---------------------------------------------------------
           PHAML   Version 1.11.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop            1
  task               REFINE_ONLY
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    NEVER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  print_eval_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree                      3
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             default
  preconditioner     default
  eigensolver        SLEPC_KRYLOV_SCHUR
  num_eval                    1
  lambda0            -infinity
  scale_evec         SCALE_LINF
  transformation     ST_NONE
  eigen_ncv          default
  eigen_maxit        default
  eigen_tol          1.0000000000E-10
  harmonic_extraction  false
  true_residual        false
---------------------------------------------------------

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           1
termination condition:
  one trip refinement
---------------------------------------------------------
