---------------------------------------------------------
           PHAML   Version 1.9.1

Output from the master process
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   NEVER
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     MASTER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             LAPACK_INDEFINITE_SOLVER
  eigensolver        ARPACK_SOLVER
  num_eval                    3
  lambda0             5.0000000000E+01
  scale_evec         SCALE_LINF
  lambda0_side       EIGEN_LEFT
  transformation     SHIFT_INVERT
  arpack_ncv                 20
  arpack_maxit              100
  arpack_tol          1.0000000000E-10
---------------------------------------------------------

Total Grid:
   number of vertices      =         145
   number of leaf elements =         256
   number of levels        =           1
   degrees of freedom      =         145
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      1.0561925708E+00
      effectivity             1.0561925708E+00
   Linf error estimate        2.2067626278E-01
      effectivity             2.2067626278E-01
 Eigenvector           2
   energy error estimate      1.5022014751E+00
   Linf error estimate        3.2371124797E-01
 Eigenvector           3
   energy error estimate      1.7397737746E+00
   Linf error estimate        4.1052118999E-01

Total Grid:
   number of vertices      =         313
   number of leaf elements =         592
   number of levels        =           6
   degrees of freedom      =         313
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      6.0924602556E-01
      reduced by              5.7683233382E-01
      effectivity             6.0924602556E-01
   Linf error estimate        5.8502540623E-02
      reduced by              2.6510572495E-01
      effectivity             5.8502540623E-02
 Eigenvector           2
   energy error estimate      5.5827100370E-01
      reduced by              3.7163523864E-01
   Linf error estimate        4.4942588245E-02
      reduced by              1.3883542363E-01
 Eigenvector           3
   energy error estimate      5.3983882963E-01
      reduced by              3.1029254349E-01
   Linf error estimate        3.8198956308E-02
      reduced by              9.3049901539E-02

Eigenvalues and error estimates:
     4.5911044365E+01  5.1310601030E-01
     4.8368752150E+01  4.7121649813E-01
     4.9101379246E+01  3.4613106347E-01

Total Grid:
   number of vertices      =         645
   number of leaf elements =        1256
   number of levels        =           8
   degrees of freedom      =         645
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      3.1565084955E-01
      reduced by              5.1810079394E-01
      effectivity             3.1565084955E-01
   Linf error estimate        1.0517182401E-02
      reduced by              1.7977308829E-01
      effectivity             1.0517182401E-02
 Eigenvector           2
   energy error estimate      3.1608047070E-01
      reduced by              5.6617748120E-01
   Linf error estimate        1.0955663950E-02
      reduced by              2.4377020502E-01
 Eigenvector           3
   energy error estimate      4.1310098422E-01
      reduced by              7.6523021603E-01
   Linf error estimate        2.3115060837E-02
      reduced by              6.0512283765E-01

Eigenvalues and error estimates:
     4.6034746276E+01  1.3871218271E-01
     4.7389527247E+01  1.3857631364E-01
     4.9596465916E+01  2.0775359332E-01

Total Grid:
   number of vertices      =        1287
   number of leaf elements =        2540
   number of levels        =           9
   degrees of freedom      =        1287
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      2.2045246728E-01
      reduced by              6.9840606352E-01
      effectivity             2.2045246728E-01
   Linf error estimate        6.0781493357E-03
      reduced by              5.7792563675E-01
      effectivity             6.0781493357E-03
 Eigenvector           2
   energy error estimate      2.1509460528E-01
      reduced by              6.8050583702E-01
   Linf error estimate        5.2272821231E-03
      reduced by              4.7713056432E-01
 Eigenvector           3
   energy error estimate      2.4230436989E-01
      reduced by              5.8654996997E-01
   Linf error estimate        5.8114149638E-03
      reduced by              2.5141248837E-01

Eigenvalues and error estimates:
     4.5486792720E+01  7.6354137302E-02
     4.6841555649E+01  5.7157140429E-02
     4.8857652364E+01  7.6256589367E-02

Total Grid:
   number of vertices      =        1287
   number of leaf elements =        2540
   number of levels        =           9
   degrees of freedom      =        1287
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      2.2045246728E-01
      effectivity             2.2045246728E-01
   Linf error estimate        6.0781493357E-03
      effectivity             6.0781493357E-03
 Eigenvector           2
   energy error estimate      2.1509460528E-01
   Linf error estimate        5.2272821231E-03
 Eigenvector           3
   energy error estimate      2.4230436989E-01
   Linf error estimate        5.8114149638E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
