---------------------------------------------------------
           PHAML   Version 1.9.1

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     MASTER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                  10
  mg_tol             MG_NO_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
  eigensolver        ARPACK_SOLVER
  num_eval                    1
  lambda0            -infinity
  scale_evec         SCALE_LINF
  arpack_ncv                  5
  arpack_maxit                1
  arpack_tol          1.0000000000E-01
---------------------------------------------------------

Total Grid:
   number of vertices      =         145
   number of leaf elements =         256
   number of levels        =           1
   degrees of freedom      =         145
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       8.5562389759E-01
   energy error estimate      3.3354746408E-01
      effectivity             3.8982953260E-01
   Linf norm of error         1.3375783342E-01
   Linf error estimate        9.8652144015E-02
      effectivity             7.3754292734E-01

Total Grid:
   number of vertices      =         301
   number of leaf elements =         568
   number of levels        =           7
   degrees of freedom      =         301
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       3.5290346269E-01
      reduced by              4.1245162003E-01
   energy error estimate      8.7118983029E-02
      reduced by              2.6118916320E-01
      effectivity             2.4686349735E-01
   Linf norm of error         2.7416149774E-02
      reduced by              2.0496855454E-01
   Linf error estimate        3.9380316022E-03
      reduced by              3.9918357999E-02
      effectivity             1.4363911908E-01

Eigenvalues and error estimates:
     9.8395691436E+00  5.4379041429E-02

Total Grid:
   number of vertices      =         593
   number of leaf elements =        1152
   number of levels        =           8
   degrees of freedom      =         593
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       1.9487204085E-01
      reduced by              2.7609822720E-01
   energy error estimate      4.9969363787E-02
      reduced by              2.8678803430E-01
      effectivity             2.5642141156E-01
   Linf norm of error         7.0081457011E-03
      reduced by              2.5562107585E-01
   Linf error estimate        1.3469907748E-03
      reduced by              3.4204671543E-01
      effectivity             1.9220359168E-01

Eigenvalues and error estimates:
     9.7150685416E+00  2.0978723450E-02

Total Grid:
   number of vertices      =        1209
   number of leaf elements =        2384
   number of levels        =           9
   degrees of freedom      =        1209
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       1.3256921624E-01
      reduced by              6.8028854042E-01
   energy error estimate      3.3013776331E-02
      reduced by              6.6068034150E-01
      effectivity             2.4903048587E-01
   Linf norm of error         4.9281426164E-03
      reduced by              7.0320207749E-01
   Linf error estimate        5.4973620562E-04
      reduced by              4.0812173024E-01
      effectivity             1.1155038488E-01

Eigenvalues and error estimates:
     9.6851931225E+00  9.1496707659E-03

Total Grid:
   number of vertices      =        1209
   number of leaf elements =        2384
   number of levels        =           9
   degrees of freedom      =        1209
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       1.3256921624E-01
   energy error estimate      3.3013776331E-02
      effectivity             2.4903048587E-01
   Linf norm of error         4.9281426164E-03
   Linf error estimate        5.4973620562E-04
      effectivity             1.1155038488E-01

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
