---------------------------------------------------------
           PHAML   Version 1.9.1

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     MASTER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                  10
  mg_tol             MG_NO_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
  eigensolver        ARPACK_SOLVER
  num_eval                    1
  lambda0            -infinity
  scale_evec         SCALE_L2
  arpack_ncv                 20
  arpack_maxit              100
  arpack_tol          1.0000000000E-10
---------------------------------------------------------

Total Grid:
   number of vertices      =         145
   number of leaf elements =         256
   number of levels        =           1
   degrees of freedom      =         145
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       9.2329120008E-01
   energy error estimate      2.8332650253E-01
      effectivity             3.0686581060E-01
   Linf norm of error         2.3597607583E-01
   Linf error estimate        8.3800666136E-02
      effectivity             3.5512356853E-01

Total Grid:
   number of vertices      =         301
   number of leaf elements =         568
   number of levels        =           7
   degrees of freedom      =         301
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       2.1594446839E+00
      reduced by              2.3388554810E+00
   energy error estimate      1.3554173904E-02
      reduced by              4.7839414186E-02
      effectivity             6.2766941915E-03
   Linf norm of error         8.4467043868E-01
      reduced by              3.5794748926E+00
   Linf error estimate        6.1268866422E-04
      reduced by              7.3112624573E-03
      effectivity             7.2535824170E-04

Eigenvalues and error estimates:
     9.8395691435E+00  8.4604056448E-03

Total Grid:
   number of vertices      =         593
   number of leaf elements =        1152
   number of levels        =           8
   degrees of freedom      =         593
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       2.3130645828E+00
      reduced by              5.3556930632E-01
   energy error estimate      4.7215840000E-03
      reduced by              1.7417453964E-01
      effectivity             2.0412676910E-03
   Linf norm of error         9.0552417499E-01
      reduced by              1.0720443543E+00
   Linf error estimate        1.2727679965E-04
      reduced by              2.0773486940E-01
      effectivity             1.4055593783E-04

Eigenvalues and error estimates:
     9.7150685416E+00  1.9822719130E-03

Total Grid:
   number of vertices      =        1209
   number of leaf elements =        2384
   number of levels        =           9
   degrees of freedom      =        1209
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       2.3914406727E+00
      reduced by              1.0338840906E+00
   energy error estimate      2.1014490303E-03
      reduced by              4.4507288873E-01
      effectivity             8.7873768070E-04
   Linf norm of error         9.3634629774E-01
      reduced by              1.0340378795E+00
   Linf error estimate        3.4992756764E-05
      reduced by              2.7493429173E-01
      effectivity             3.7371597292E-05

Eigenvalues and error estimates:
     9.6851931225E+00  5.8241075409E-04

Total Grid:
   number of vertices      =        1209
   number of leaf elements =        2384
   number of levels        =           9
   degrees of freedom      =        1209
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       2.3914406727E+00
   energy error estimate      2.1014490303E-03
      effectivity             8.7873768070E-04
   Linf norm of error         9.3634629774E-01
   Linf error estimate        3.4992756764E-05
      effectivity             3.7371597292E-05

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
