---------------------------------------------------------
           PHAML   Version 1.9.1

Output from the master process
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   NEVER
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     MASTER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             LAPACK_INDEFINITE_SOLVER
  eigensolver        ARPACK_SOLVER
  num_eval                    3
  lambda0             5.0000000000E+01
  scale_evec         SCALE_LINF
  lambda0_side       EIGEN_RIGHT
  transformation     SHIFT_INVERT
  arpack_ncv                 20
  arpack_maxit              100
  arpack_tol          1.0000000000E-10
---------------------------------------------------------

Total Grid:
   number of vertices      =         145
   number of leaf elements =         256
   number of levels        =           1
   degrees of freedom      =         145
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      1.5022014751E+00
      effectivity             1.5022014751E+00
   Linf error estimate        3.2371124796E-01
      effectivity             3.2371124796E-01
 Eigenvector           2
   energy error estimate      1.3182929653E+00
   Linf error estimate        2.0753070496E-01
 Eigenvector           3
   energy error estimate      1.5056819197E+00
   Linf error estimate        2.1094898472E-01

Total Grid:
   number of vertices      =         331
   number of leaf elements =         628
   number of levels        =           5
   degrees of freedom      =         331
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      7.4170172891E-01
      reduced by              4.9374317708E-01
      effectivity             7.4170172891E-01
   Linf error estimate        5.7432983989E-02
      reduced by              1.7742041511E-01
      effectivity             5.7432983989E-02
 Eigenvector           2
   energy error estimate      6.4265149597E-01
      reduced by              4.8748761684E-01
   Linf error estimate        4.4665026916E-02
      reduced by              2.1522129424E-01
 Eigenvector           3
   energy error estimate      6.3392263581E-01
      reduced by              4.2102028822E-01
   Linf error estimate        5.5258614799E-02
      reduced by              2.6195250416E-01

Eigenvalues and error estimates:
     5.1777493614E+01  6.1345245158E-01
     5.3158475264E+01  4.5567364223E-01
     5.5325641138E+01  3.9495372914E-01

Total Grid:
   number of vertices      =         677
   number of leaf elements =        1320
   number of levels        =           7
   degrees of freedom      =         677
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      3.8573878846E-01
      reduced by              5.2007265646E-01
      effectivity             3.8573878846E-01
   Linf error estimate        1.1948060724E-02
      reduced by              2.0803482413E-01
      effectivity             1.1948060724E-02
 Eigenvector           2
   energy error estimate      3.7152076993E-01
      reduced by              5.7810613102E-01
   Linf error estimate        1.2700259781E-02
      reduced by              2.8434461274E-01
 Eigenvector           3
   energy error estimate      4.7483060969E-01
      reduced by              7.4903558080E-01
   Linf error estimate        2.3536988822E-02
      reduced by              4.2594243282E-01

Eigenvalues and error estimates:
     5.1390582564E+01  1.7752017728E-01
     5.3354919710E+01  1.6389406902E-01
     5.5070187145E+01  2.8119241373E-01

Total Grid:
   number of vertices      =        1329
   number of leaf elements =        2624
   number of levels        =           8
   degrees of freedom      =        1329
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      2.6131101985E-01
      reduced by              6.7742998026E-01
      effectivity             2.6131101985E-01
   Linf error estimate        6.6525361567E-03
      reduced by              5.5678794330E-01
      effectivity             6.6525361567E-03
 Eigenvector           2
   energy error estimate      2.5178746449E-01
      reduced by              6.7772109899E-01
   Linf error estimate        5.4943393574E-03
      reduced by              4.3261629699E-01
 Eigenvector           3
   energy error estimate      2.7840365477E-01
      reduced by              5.8632204640E-01
   Linf error estimate        6.7484201536E-03
      reduced by              2.8671552698E-01

Eigenvalues and error estimates:
     5.0800347760E+01  8.8476826995E-02
     5.2681908567E+01  7.9970635759E-02
     5.4117181310E+01  8.6041419584E-02

Total Grid:
   number of vertices      =        1329
   number of leaf elements =        2624
   number of levels        =           8
   degrees of freedom      =        1329
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      2.6131101985E-01
      effectivity             2.6131101985E-01
   Linf error estimate        6.6525361567E-03
      effectivity             6.6525361567E-03
 Eigenvector           2
   energy error estimate      2.5178746449E-01
   Linf error estimate        5.4943393574E-03
 Eigenvector           3
   energy error estimate      2.7840365477E-01
   Linf error estimate        6.7484201536E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
