---------------------------------------------------------
           PHAML   Version 1.9.1

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     MASTER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                  10
  mg_tol             MG_NO_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
  eigensolver        ARPACK_SOLVER
  num_eval                    3
  lambda0            -infinity
  scale_evec         SCALE_LINF
  arpack_ncv                 20
  arpack_maxit              100
  arpack_tol          1.0000000000E-10
---------------------------------------------------------

Total Grid:
   number of vertices      =         145
   number of leaf elements =         256
   number of levels        =           1
   degrees of freedom      =         145
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       8.5561840990E-01
   energy error estimate      3.3353373990E-01
      effectivity             3.8981599279E-01
   Linf norm of error         1.3374885086E-01
   Linf error estimate        9.8650670987E-02
      effectivity             7.3758144726E-01
 Eigenvector           2
   energy error estimate      6.0198892665E-01
   Linf error estimate        1.1114181550E-01
 Eigenvector           3
   energy error estimate      7.2589558900E-01
   Linf error estimate        1.7696540623E-01

Total Grid:
   number of vertices      =         307
   number of leaf elements =         580
   number of levels        =           6
   degrees of freedom      =         307
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       3.7468637972E-01
      reduced by              4.3791294739E-01
   energy error estimate      1.0327792731E-01
      reduced by              3.0964761568E-01
      effectivity             2.7563832822E-01
   Linf norm of error         2.9613504817E-02
      reduced by              2.2141128411E-01
   Linf error estimate        7.5013658953E-03
      reduced by              7.6039684476E-02
      effectivity             2.5330895285E-01
 Eigenvector           2
   energy error estimate      1.6484867943E-01
      reduced by              2.7384005276E-01
   Linf error estimate        9.1511481364E-03
      reduced by              8.2337580101E-02
 Eigenvector           3
   energy error estimate      2.4637517517E-01
      reduced by              3.3940855806E-01
   Linf error estimate        1.7552698193E-02
      reduced by              9.9187172043E-02

Eigenvalues and error estimates:
     9.8614745421E+00  7.4619468796E-02
     1.7182453393E+01  1.1500678749E-01
     2.2570080107E+01  1.6756053615E-01

Total Grid:
   number of vertices      =         599
   number of leaf elements =        1164
   number of levels        =           8
   degrees of freedom      =         599
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       2.1076313013E-01
      reduced by              2.8125272433E-01
   energy error estimate      5.7259114955E-02
      reduced by              2.7720886953E-01
      effectivity             2.7167519727E-01
   Linf norm of error         1.1878963777E-02
      reduced by              4.0113332923E-01
   Linf error estimate        2.2599228015E-03
      reduced by              3.0126817343E-01
      effectivity             1.9024578607E-01
 Eigenvector           2
   energy error estimate      1.1470565321E-01
      reduced by              3.4791195659E-01
   Linf error estimate        3.7040905302E-03
      reduced by              4.0476784716E-01
 Eigenvector           3
   energy error estimate      1.5699207056E-01
      reduced by              3.1860367111E-01
   Linf error estimate        7.1671588599E-03
      reduced by              4.0832234343E-01

Eigenvalues and error estimates:
     9.7246530595E+00  2.4676127320E-02
     2.2114830037E+01  5.2132388923E-02
     2.4101912311E+01  8.9954443993E-02

Total Grid:
   number of vertices      =        1223
   number of leaf elements =        2412
   number of levels        =           9
   degrees of freedom      =        1223
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       1.4014708827E-01
      reduced by              6.6495068747E-01
   energy error estimate      3.8320787727E-02
      reduced by              6.6925218381E-01
      effectivity             2.7343263566E-01
   Linf norm of error         4.9875914582E-03
      reduced by              4.1986755341E-01
   Linf error estimate        1.5653456293E-03
      reduced by              6.9265446957E-01
      effectivity             3.1384800508E-01
 Eigenvector           2
   energy error estimate      6.6644546294E-02
      reduced by              5.8100489758E-01
   Linf error estimate        2.5698497185E-03
      reduced by              6.9378696270E-01
 Eigenvector           3
   energy error estimate      8.0290819832E-02
      reduced by              5.1143232614E-01
   Linf error estimate        1.7646584480E-03
      reduced by              2.4621450180E-01

Eigenvalues and error estimates:
     9.6882359819E+00  1.0689741860E-02
     1.6794933708E+01  1.8813802251E-02
     2.2000901228E+01  2.2179331311E-02

Total Grid:
   number of vertices      =        1223
   number of leaf elements =        2412
   number of levels        =           9
   degrees of freedom      =        1223
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       1.4014708827E-01
   energy error estimate      3.8320787727E-02
      effectivity             2.7343263566E-01
   Linf norm of error         4.9875914582E-03
   Linf error estimate        1.5653456293E-03
      effectivity             3.1384800508E-01
 Eigenvector           2
   energy error estimate      6.6644546294E-02
   Linf error estimate        2.5698497185E-03
 Eigenvector           3
   energy error estimate      8.0290819832E-02
   Linf error estimate        1.7646584480E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
