---------------------------------------------------------
           PHAML   Version 1.9.1

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    SLAVES
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     SLAVES
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                  10
  mg_tol             MG_NO_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
  eigensolver        ARPACK_SOLVER
  num_eval                    1
  lambda0            -infinity
  scale_evec         SCALE_LINF
  arpack_ncv                  5
  arpack_maxit                1
  arpack_tol          1.0000000000E-01
---------------------------------------------------------

My Grid:
   number of vertices       =         145
   number of vertices I own =         145
   number of elements       =         256
   number of leaf elements  =         256
   leaf elements I own      =         256
   number of levels         =           1
   degrees of freedom       =         145
   degrees of freedom I own =         145
   min and max degree       =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       8.5562389759E-01
   energy error estimate      3.3354746408E-01
      effectivity             3.8982953260E-01
   Linf norm of error         1.3375783342E-01
   Linf error estimate        9.8652144015E-02
      effectivity             7.3754292734E-01

My Grid:
   number of vertices       =         301
   number of vertices I own =         301
   number of elements       =         880
   number of leaf elements  =         568
   leaf elements I own      =         568
   number of levels         =           7
   degrees of freedom       =         301
   degrees of freedom I own =         301
   min and max degree       =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       3.5290346269E-01
      reduced by              4.1245162003E-01
   energy error estimate      8.7118983029E-02
      reduced by              2.6118916320E-01
      effectivity             2.4686349735E-01
   Linf norm of error         2.7416149774E-02
      reduced by              2.0496855454E-01
   Linf error estimate        3.9380316022E-03
      reduced by              3.9918357999E-02
      effectivity             1.4363911908E-01

Eigenvalues and error estimates:
     9.8395691436E+00  5.4379041429E-02

My Grid:
   number of vertices       =         593
   number of vertices I own =         593
   number of elements       =        2048
   number of leaf elements  =        1152
   leaf elements I own      =        1152
   number of levels         =           8
   degrees of freedom       =         593
   degrees of freedom I own =         593
   min and max degree       =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       1.9487204081E-01
      reduced by              5.5219645429E-01
   energy error estimate      4.9969363473E-02
      reduced by              5.7357606500E-01
      effectivity             2.5642141000E-01
   Linf norm of error         7.0081398408E-03
      reduced by              2.5562086210E-01
   Linf error estimate        1.3469907292E-03
      reduced by              3.4204670385E-01
      effectivity             1.9220374590E-01

Eigenvalues and error estimates:
     9.7150685416E+00  2.0978723792E-02

My Grid:
   number of vertices       =        1209
   number of vertices I own =        1209
   number of elements       =        4512
   number of leaf elements  =        2384
   leaf elements I own      =        2384
   number of levels         =           9
   degrees of freedom       =        1209
   degrees of freedom I own =        1209
   min and max degree       =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       1.3256921623E-01
      reduced by              6.8028854056E-01
   energy error estimate      3.3013776331E-02
      reduced by              6.6068034564E-01
      effectivity             2.4903048587E-01
   Linf norm of error         4.9281426223E-03
      reduced by              7.0320266637E-01
   Linf error estimate        5.4973620561E-04
      reduced by              4.0812174404E-01
      effectivity             1.1155038475E-01

Eigenvalues and error estimates:
     9.6851931225E+00  9.1496707658E-03

My Grid:
   number of vertices       =        1209
   number of vertices I own =        1209
   number of elements       =        4512
   number of leaf elements  =        2384
   leaf elements I own      =        2384
   number of levels         =           9
   degrees of freedom       =        1209
   degrees of freedom I own =        1209
   min and max degree       =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       1.3256921623E-01
   energy error estimate      3.3013776331E-02
      effectivity             2.4903048587E-01
   Linf norm of error         4.9281426223E-03
   Linf error estimate        5.4973620561E-04
      effectivity             1.1155038475E-01

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
