---------------------------------------------------------
           PHAML   Version 1.9.1

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     MASTER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                  10
  mg_tol             MG_NO_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
  eigensolver        ARPACK_SOLVER
  num_eval                    1
  lambda0            -infinity
  scale_evec         SCALE_M
  arpack_ncv                 20
  arpack_maxit              100
  arpack_tol          1.0000000000E-10
---------------------------------------------------------

Total Grid:
   number of vertices      =         145
   number of leaf elements =         256
   number of levels        =           1
   degrees of freedom      =         145
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       1.2210227005E+00
   energy error estimate      4.5104233769E-01
      effectivity             3.6939717625E-01
   Linf norm of error         3.5231397525E-01
   Linf error estimate        1.3340668104E-01
      effectivity             3.7865849900E-01

Total Grid:
   number of vertices      =         301
   number of leaf elements =         568
   number of levels        =           7
   degrees of freedom      =         301
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       7.0182059777E-01
      reduced by              5.7478095820E-01
   energy error estimate      1.0662102316E-01
      reduced by              2.3638805995E-01
      effectivity             1.5192062402E-01
   Linf norm of error         2.2385246193E-01
      reduced by              6.3537775296E-01
   Linf error estimate        4.8195849278E-03
      reduced by              3.6127013206E-02
      effectivity             2.1530185044E-02

Eigenvalues and error estimates:
     9.8395691435E+00  6.6551979676E-02

Total Grid:
   number of vertices      =         593
   number of leaf elements =        1152
   number of levels        =           8
   degrees of freedom      =         593
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       6.0289559431E-01
      reduced by              4.2952258470E-01
   energy error estimate      6.0947995749E-02
      reduced by              2.8581603300E-01
      effectivity             1.0109212329E-01
   Linf norm of error         2.1970720200E-01
      reduced by              9.8148217852E-01
   Linf error estimate        1.6429371676E-03
      reduced by              3.4088768891E-01
      effectivity             7.4778484846E-03

Eigenvalues and error estimates:
     9.7150685416E+00  2.5587917132E-02

Total Grid:
   number of vertices      =        1209
   number of leaf elements =        2384
   number of levels        =           9
   degrees of freedom      =        1209
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       5.7721742981E-01
      reduced by              9.5740860485E-01
   energy error estimate      4.0233952278E-02
      reduced by              6.6013577287E-01
      effectivity             6.9703287185E-02
   Linf norm of error         2.1870194451E-01
      reduced by              9.9542455832E-01
   Linf error estimate        6.6996481257E-04
      reduced by              4.0778480505E-01
      effectivity             3.0633692538E-03

Eigenvalues and error estimates:
     9.6851931225E+00  1.1150727973E-02

Total Grid:
   number of vertices      =        1209
   number of leaf elements =        2384
   number of levels        =           9
   degrees of freedom      =        1209
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       5.7721742981E-01
   energy error estimate      4.0233952278E-02
      effectivity             6.9703287185E-02
   Linf norm of error         2.1870194451E-01
   Linf error estimate        6.6996481257E-04
      effectivity             3.0633692538E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
