---------------------------------------------------------
           PHAML   Version 1.9.1

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    NEVER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   FINAL
  print_error_who    MASTER
  print_error_what   NEVER
  print_errest_what  LINF_ERREST
  print_time_when    NEVER
  print_eval_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                  10
  mg_tol             MG_NO_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
  eigensolver        ARPACK_SOLVER
  num_eval                    3
  lambda0            -infinity
  scale_evec         SCALE_LINF
  arpack_ncv                 20
  arpack_maxit              100
  arpack_tol          1.0000000000E-10
---------------------------------------------------------

Norms of error:
 Eigenvector           1
   Linf error estimate        1.5653456293E-03
      effectivity             1.5653456293E-03
 Eigenvector           2
   Linf error estimate        1.7646584480E-03
 Eigenvector           3
   Linf error estimate        1.7971541072E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
eigenvalues  9.688235981935E+00 2.200090122755E+01 2.392784111037E+01
error estimates  4.668081811765E-03 1.024034599207E-02 1.312225924900E-02
max linear system residual  1.770439203453E-10
ave linear system residual  4.836619638883E-12
eigensystem residuals  2.823886086749E-11 5.337938890339E-11 1.350046339081E-10
arpack iterations           2
arpack number converged           3
arpack number of OP*x          37
arpack number of B*x         110
arpack number of reorthogonalizatons          36
arpack error flag           0
error estimate for evec 2  1.764658448033E-03
