---------------------------------------------------------
           PHAML   Version 1.9.1

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     MASTER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                  10
  mg_tol             MG_NO_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
  eigensolver        ARPACK_SOLVER
  num_eval                    1
  lambda0            -infinity
  scale_evec         SCALE_LINF
  arpack_ncv                 20
  arpack_maxit              100
  arpack_tol          1.0000000000E-10
---------------------------------------------------------

Total Grid:
   number of vertices      =         145
   number of leaf elements =         256
   number of levels        =           1
   degrees of freedom      =         145
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       8.5561840990E-01
   energy error estimate      3.3353373990E-01
      effectivity             3.8981599279E-01
   Linf norm of error         1.3374885086E-01
   Linf error estimate        9.8650670987E-02
      effectivity             7.3758144726E-01

Total Grid:
   number of vertices      =         301
   number of leaf elements =         568
   number of levels        =           7
   degrees of freedom      =         301
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       3.5290423727E-01
      reduced by              4.1245517065E-01
   energy error estimate      8.7119180194E-02
      reduced by              2.6120050169E-01
      effectivity             2.4686351422E-01
   Linf norm of error         2.7416902346E-02
      reduced by              2.0498794696E-01
   Linf error estimate        3.9380440680E-03
      reduced by              3.9919080414E-02
      effectivity             1.4363563098E-01

Eigenvalues and error estimates:
     9.8395691435E+00  5.4379087142E-02

Total Grid:
   number of vertices      =         593
   number of leaf elements =        1152
   number of levels        =           8
   degrees of freedom      =         593
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       1.9487203889E-01
      reduced by              2.7609761844E-01
   energy error estimate      4.9969366130E-02
      reduced by              2.8678739870E-01
      effectivity             2.5642142615E-01
   Linf norm of error         7.0081896701E-03
      reduced by              2.5561566298E-01
   Linf error estimate        1.3469930856E-03
      reduced by              3.4204621948E-01
      effectivity             1.9220271554E-01

Eigenvalues and error estimates:
     9.7150685416E+00  2.0978737430E-02

Total Grid:
   number of vertices      =        1209
   number of leaf elements =        2384
   number of levels        =           9
   degrees of freedom      =        1209
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       1.3256921685E-01
      reduced by              6.8028855040E-01
   energy error estimate      3.3013775403E-02
      reduced by              6.6068029193E-01
      effectivity             2.4903047771E-01
   Linf norm of error         4.9281348294E-03
      reduced by              7.0319655452E-01
   Linf error estimate        5.4973639421E-04
      reduced by              4.0812117009E-01
      effectivity             1.1155059941E-01

Eigenvalues and error estimates:
     9.6851931225E+00  9.1496760332E-03

Total Grid:
   number of vertices      =        1209
   number of leaf elements =        2384
   number of levels        =           9
   degrees of freedom      =        1209
   min and max degree      =           1          1

Norms of error:
 Eigenvector           1
   energy norm of error       1.3256921685E-01
   energy error estimate      3.3013775403E-02
      effectivity             2.4903047771E-01
   Linf norm of error         4.9281348294E-03
   Linf error estimate        5.4973639421E-04
      effectivity             1.1155059941E-01

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
