---------------------------------------------------------
           PHAML   Version 1.9.1

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    SLAVES
  print_error_what   NEVER
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     SLAVES
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           250
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             LAPACK_INDEFINITE_SOLVER
  eigensolver        ARPACK_SOLVER
  num_eval                    3
  lambda0             5.0000000000E+01
  scale_evec         SCALE_LINF
  lambda0_side       EIGEN_BOTH
  transformation     SHIFT_INVERT
  arpack_ncv                 20
  arpack_maxit              100
  arpack_tol          1.0000000000E-10
---------------------------------------------------------

My Grid:
   number of vertices       =         145
   number of vertices I own =         145
   number of elements       =         256
   number of leaf elements  =         256
   leaf elements I own      =         256
   number of levels         =           1
   degrees of freedom       =         145
   degrees of freedom I own =         145
   min and max degree       =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      1.5022014751E+00
      effectivity             1.5022014751E+00
   Linf error estimate        3.2371124797E-01
      effectivity             3.2371124797E-01
 Eigenvector           2
   energy error estimate      1.7397737746E+00
   Linf error estimate        4.1052118999E-01
 Eigenvector           3
   energy error estimate      1.3182929653E+00
   Linf error estimate        2.0753070496E-01

My Grid:
   number of vertices       =         321
   number of vertices I own =         321
   number of elements       =         960
   number of leaf elements  =         608
   leaf elements I own      =         608
   number of levels         =           6
   degrees of freedom       =         321
   degrees of freedom I own =         321
   min and max degree       =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      5.3886142639E-01
      reduced by              3.5871448358E-01
      effectivity             5.3886142639E-01
   Linf error estimate        4.3595360776E-02
      reduced by              1.3467360510E-01
      effectivity             4.3595360776E-02
 Eigenvector           2
   energy error estimate      5.6282541073E-01
      reduced by              3.2350494009E-01
   Linf error estimate        3.7965822197E-02
      reduced by              9.2482003666E-02
 Eigenvector           3
   energy error estimate      7.0607725297E-01
      reduced by              5.3559965163E-01
   Linf error estimate        5.8795830396E-02
      reduced by              2.8331147628E-01

Eigenvalues and error estimates:
     4.7800218694E+01  4.2523036431E-01
     4.9226359464E+01  3.8365297684E-01
     5.1446360754E+01  5.5764042100E-01

My Grid:
   number of vertices       =         665
   number of vertices I own =         665
   number of elements       =        2336
   number of leaf elements  =        1296
   leaf elements I own      =        1296
   number of levels         =           8
   degrees of freedom       =         665
   degrees of freedom I own =         665
   min and max degree       =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      3.1468421916E-01
      reduced by              5.8397985781E-01
      effectivity             3.1468421916E-01
   Linf error estimate        1.0716561058E-02
      reduced by              2.4581884098E-01
      effectivity             1.0716561058E-02
 Eigenvector           2
   energy error estimate      3.5584029779E-01
      reduced by              6.3223921842E-01
   Linf error estimate        1.2978202484E-02
      reduced by              3.4183909982E-01
 Eigenvector           3
   energy error estimate      4.3875416518E-01
      reduced by              6.2139682780E-01
   Linf error estimate        1.9004579853E-02
      reduced by              3.2323006113E-01

Eigenvalues and error estimates:
     4.7352321580E+01  1.2536167060E-01
     4.9463319495E+01  1.6371721152E-01
     5.1486835416E+01  2.3626155450E-01

My Grid:
   number of vertices       =        1333
   number of vertices I own =        1333
   number of elements       =        5008
   number of leaf elements  =        2632
   leaf elements I own      =        2632
   number of levels         =           9
   degrees of freedom       =        1333
   degrees of freedom I own =        1333
   min and max degree       =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      2.3716230274E-01
      reduced by              7.5365171907E-01
      effectivity             2.3716230274E-01
   Linf error estimate        5.6746516993E-03
      reduced by              5.2952170650E-01
      effectivity             5.6746516993E-03
 Eigenvector           2
   energy error estimate      2.5487949920E-01
      reduced by              7.1627497162E-01
   Linf error estimate        5.3674066553E-03
      reduced by              4.1357088256E-01
 Eigenvector           3
   energy error estimate      3.0104492185E-01
      reduced by              6.8613575834E-01
   Linf error estimate        1.5004672821E-02
      reduced by              7.8952931016E-01

Eigenvalues and error estimates:
     4.8817685248E+01  6.9028331009E-02
     5.0783912475E+01  8.3494978098E-02
     5.2787902113E+01  1.2815890050E-01

My Grid:
   number of vertices       =        1333
   number of vertices I own =        1333
   number of elements       =        5008
   number of leaf elements  =        2632
   leaf elements I own      =        2632
   number of levels         =           9
   degrees of freedom       =        1333
   degrees of freedom I own =        1333
   min and max degree       =           1          1

Norms of error:
 Eigenvector           1
   energy error estimate      2.3716230274E-01
      effectivity             2.3716230274E-01
   Linf error estimate        5.6746516993E-03
      effectivity             5.6746516993E-03
 Eigenvector           2
   energy error estimate      2.5487949920E-01
   Linf error estimate        5.3674066553E-03
 Eigenvector           3
   energy error estimate      3.0104492185E-01
   Linf error estimate        1.5004672821E-02

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           3
termination condition:
  maximum vertices achieved
---------------------------------------------------------
