---------------------------------------------------------
           PHAML   Version 1.9.1

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  350
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     MASTER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree                      4
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             CG_SOLVER
  preconditioner     MG_PRECONDITION
  mg_cycles                   2
  mg_tol             MG_NO_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_NONE
  krylov_iter               100
  krylov_tol          1.0000000000E-10
  eigensolver        ARPACK_SOLVER
  num_eval                    1
  lambda0            -infinity
  scale_evec         SCALE_LINF
  arpack_ncv                 20
  arpack_maxit              100
  arpack_tol          1.0000000000E-10
---------------------------------------------------------

Total Grid:
   number of vertices      =         145
   number of leaf elements =         256
   number of levels        =           1
   degrees of freedom      =        2113
   min and max degree      =           4          4

Norms of error:
 Eigenvector           1
   energy norm of error       2.4148540621E-02
   energy error estimate      2.0838285013E-02
      effectivity             8.6292109077E-01
   Linf norm of error         6.7057031739E-03
   Linf error estimate        8.5395447772E-03
      effectivity             1.2734749147E+00

Total Grid:
   number of vertices      =         301
   number of leaf elements =         568
   number of levels        =          11
   degrees of freedom      =        4609
   min and max degree      =           4          4

Norms of error:
 Eigenvector           1
   energy norm of error       4.4690827089E-04
      reduced by              9.2533184077E-03
   energy error estimate      3.9716031034E-04
      reduced by              9.5295824509E-03
      effectivity             8.8868418018E-01
   Linf norm of error         2.1203060494E-05
      reduced by              3.1619443844E-03
   Linf error estimate        5.6790289766E-05
      reduced by              6.6502713257E-03
      effectivity             2.6784005914E+00

Eigenvalues and error estimates:
     9.6592585572E+00  3.6635481707E-08

Total Grid:
   number of vertices      =         553
   number of leaf elements =        1072
   number of levels        =          11
   degrees of freedom      =        8641
   min and max degree      =           4          4

Norms of error:
 Eigenvector           1
   energy norm of error       6.2697226736E-05
      reduced by              1.4029104140E-01
   energy error estimate      5.7409444693E-05
      reduced by              1.4454980319E-01
      effectivity             9.1566162783E-01
   Linf norm of error         1.4200016463E-06
      reduced by              6.6971541521E-02
   Linf error estimate        4.7358593825E-06
      reduced by              8.3392062306E-02
      effectivity             3.3351083747E+00

Eigenvalues and error estimates:
     9.6592582687E+00  5.4076951588E-09

Total Grid:
   number of vertices      =         553
   number of leaf elements =        1072
   number of levels        =          11
   degrees of freedom      =        8641
   min and max degree      =           4          4

Norms of error:
 Eigenvector           1
   energy norm of error       6.2697226736E-05
   energy error estimate      5.7409444693E-05
      effectivity             9.1566162783E-01
   Linf norm of error         1.4200016463E-06
   Linf error estimate        4.7358593825E-06
      effectivity             3.3351083747E+00

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           2
termination condition:
  maximum vertices achieved
---------------------------------------------------------
