---------------------------------------------------------
           PHAML   Version 1.9.1

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree                      4
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             MUMPS_SPD_SOLVER
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =          81
   min and max degree      =           4          4

Norms of error:
   energy norm of error       8.6271851999E-02
   Linf norm of error         1.0764133692E-02
   L2 norm of error           4.3498770589E-03

Total Grid:
   number of vertices      =          19
   number of leaf elements =          24
   number of levels        =           3
   degrees of freedom      =         217
   min and max degree      =           4          4

Norms of error:
   energy norm of error       7.7771499751E-03
      reduced by              9.0147015450E-02
   Linf norm of error         7.0294450970E-04
      reduced by              6.5304327299E-02
   L2 norm of error           1.9281272958E-04
      reduced by              4.4326018176E-02

Total Grid:
   number of vertices      =          28
   number of leaf elements =          40
   number of levels        =           4
   degrees of freedom      =         349
   min and max degree      =           4          4

Norms of error:
   energy norm of error       3.9461930021E-03
      reduced by              5.0740862845E-01
   Linf norm of error         3.5674009990E-04
      reduced by              5.0749396997E-01
   L2 norm of error           8.4281401347E-05
      reduced by              4.3711533741E-01

Total Grid:
   number of vertices      =          51
   number of leaf elements =          76
   number of levels        =           5
   degrees of freedom      =         657
   min and max degree      =           4          4

Norms of error:
   energy norm of error       8.4877566763E-04
      reduced by              2.1508721625E-01
   Linf norm of error         5.8530721542E-05
      reduced by              1.6407104656E-01
   L2 norm of error           1.6251869740E-05
      reduced by              1.9282866065E-01

Total Grid:
   number of vertices      =         111
   number of leaf elements =         192
   number of levels        =           7
   degrees of freedom      =        1593
   min and max degree      =           4          4

Norms of error:
   energy norm of error       1.9610591733E-04
      reduced by              2.3104563998E-01
   Linf norm of error         1.4914711549E-05
      reduced by              2.5481851506E-01
   L2 norm of error           2.3152497489E-06
      reduced by              1.4246051599E-01

Total Grid:
   number of vertices      =         182
   number of leaf elements =         320
   number of levels        =           7
   degrees of freedom      =        2645
   min and max degree      =           4          4

Norms of error:
   energy norm of error       4.4301734860E-05
      reduced by              1.1295359024E-01
   Linf norm of error         2.7466029586E-06
      reduced by              1.8415394422E-01
   L2 norm of error           3.9318970953E-07
      reduced by              8.4913022820E-02

Total Grid:
   number of vertices      =         363
   number of leaf elements =         670
   number of levels        =           9
   degrees of freedom      =        5469
   min and max degree      =           4          4

Norms of error:
   energy norm of error       1.4419188080E-05
      reduced by              3.2547682670E-01
   Linf norm of error         5.3812322243E-07
      reduced by              1.9592319332E-01
   L2 norm of error           8.9769253647E-08
      reduced by              2.2831028247E-01

Total Grid:
   number of vertices      =         712
   number of leaf elements =        1340
   number of levels        =           9
   degrees of freedom      =       10885
   min and max degree      =           4          4

Norms of error:
   energy norm of error       2.5555686308E-06
      reduced by              1.7723387868E-01
   Linf norm of error         6.6525358403E-08
      reduced by              1.2362476777E-01
   L2 norm of error           1.1682222257E-08
      reduced by              1.3013611880E-01

Total Grid:
   number of vertices      =         712
   number of leaf elements =        1340
   number of levels        =           9
   degrees of freedom      =       10885
   min and max degree      =           4          4

Norms of error:
   energy norm of error       2.5555686308E-06
   Linf norm of error         6.6525358403E-08
   L2 norm of error           1.1682222257E-08

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           7
termination condition:
  maximum vertices achieved
---------------------------------------------------------
