---------------------------------------------------------
           PHAML   Version 1.9.1

Output from the master process
  PDE id is     1
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             MUMPS_NONSYM_SOLVER
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.4894389595E+00
   Linf norm of error         8.6678053008E-01
   L2 norm of error           3.4682818904E-01

Total Grid:
   number of vertices      =          28
   number of leaf elements =          39
   number of levels        =           5
   degrees of freedom      =          28
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.4485272630E+00
      reduced by              5.8186896187E-01
   Linf norm of error         3.1697303276E-01
      reduced by              3.6569007004E-01
   L2 norm of error           9.5549660078E-02
      reduced by              2.7549565779E-01

Total Grid:
   number of vertices      =          36
   number of leaf elements =          48
   number of levels        =           6
   degrees of freedom      =          36
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.4256105276E+00
      reduced by              9.8417928608E-01
   Linf norm of error         2.5754586882E-01
      reduced by              8.1251665663E-01
   L2 norm of error           8.8710368664E-02
      reduced by              9.2842160392E-01

Total Grid:
   number of vertices      =          80
   number of leaf elements =         130
   number of levels        =           7
   degrees of freedom      =          80
   min and max degree      =           1          1

Norms of error:
   energy norm of error       8.1537713854E-01
      reduced by              5.7194943692E-01
   Linf norm of error         9.9823137179E-02
      reduced by              3.8759362609E-01
   L2 norm of error           2.6804262739E-02
      reduced by              3.0215478916E-01

Total Grid:
   number of vertices      =         159
   number of leaf elements =         274
   number of levels        =           8
   degrees of freedom      =         159
   min and max degree      =           1          1

Norms of error:
   energy norm of error       4.9640111424E-01
      reduced by              6.0879940187E-01
   Linf norm of error         3.8219714981E-02
      reduced by              3.8287431212E-01
   L2 norm of error           1.2584088653E-02
      reduced by              4.6948087234E-01

Total Grid:
   number of vertices      =         333
   number of leaf elements =         588
   number of levels        =          10
   degrees of freedom      =         333
   min and max degree      =           1          1

Norms of error:
   energy norm of error       3.5947922848E-01
      reduced by              3.6208543673E-01
   Linf norm of error         3.1407853963E-02
      reduced by              8.2177101474E-01
   L2 norm of error           6.4687553788E-03
      reduced by              2.5702120976E-01

Total Grid:
   number of vertices      =         608
   number of leaf elements =        1130
   number of levels        =          11
   degrees of freedom      =         608
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.4750509988E-01
      reduced by              6.8851015656E-01
   Linf norm of error         1.0108712103E-02
      reduced by              3.2185300261E-01
   L2 norm of error           3.3254258410E-03
      reduced by              5.1407506487E-01

Total Grid:
   number of vertices      =         608
   number of leaf elements =        1130
   number of levels        =          11
   degrees of freedom      =         608
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.4750509988E-01
   Linf norm of error         1.0108712103E-02
   L2 norm of error           3.3254258410E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
