---------------------------------------------------------
           PHAML   Version 1.9.1

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    FREQUENTLY
  print_grid_who     MASTER_ALL
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree                      4
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  postbalance        BALANCE_EQUATIONS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Individual Grids:
   number of vertices       =           9          9          9          9
   number of vertices I own =           9          9          9          9
   number of elements       =           8          8          8          8
   number of leaf elements  =           8          8          8          8
   leaf elements I own      =           8          8          8          8
   number of levels         =           1          1          1          1
   degrees of freedom       =          81         81         81         81
   degrees of freedom I own =          81         81         81         81
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =          81
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =          19         19         19         19
   number of vertices I own =          19         19         19         19
   number of elements       =          40         40         40         40
   number of leaf elements  =          24         24         24         24
   leaf elements I own      =          24         24         24         24
   number of levels         =           3          3          3          3
   degrees of freedom       =         217        217        217        217
   degrees of freedom I own =         217        217        217        217
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =          19
   number of leaf elements =          24
   number of levels        =           3
   degrees of freedom      =         217
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =          19         19         19         19
   number of vertices I own =          19         19         19         19
   number of elements       =          40         40         40         40
   number of leaf elements  =          24         24         24         24
   leaf elements I own      =          24         24         24         24
   number of levels         =           3          3          3          3
   degrees of freedom       =         217        217        217        217
   degrees of freedom I own =         217        217        217        217
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =          19
   number of leaf elements =          24
   number of levels        =           3
   degrees of freedom      =         217
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =          28         28         28         28
   number of vertices I own =          28         28         28         28
   number of elements       =          72         72         72         72
   number of leaf elements  =          40         40         40         40
   leaf elements I own      =          40         40         40         40
   number of levels         =           4          4          4          4
   degrees of freedom       =         349        349        349        349
   degrees of freedom I own =         349        349        349        349
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =          28
   number of leaf elements =          40
   number of levels        =           4
   degrees of freedom      =         349
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =          28         28         28         28
   number of vertices I own =          28         28         28         28
   number of elements       =          72         72         72         72
   number of leaf elements  =          40         40         40         40
   leaf elements I own      =          40         40         40         40
   number of levels         =           4          4          4          4
   degrees of freedom       =         349        349        349        349
   degrees of freedom I own =         349        349        349        349
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =          28
   number of leaf elements =          40
   number of levels        =           4
   degrees of freedom      =         349
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =          51         51         51         51
   number of vertices I own =          51         51         51         51
   number of elements       =         144        144        144        144
   number of leaf elements  =          76         76         76         76
   leaf elements I own      =          76         76         76         76
   number of levels         =           5          5          5          5
   degrees of freedom       =         657        657        657        657
   degrees of freedom I own =         657        657        657        657
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =          51
   number of leaf elements =          76
   number of levels        =           5
   degrees of freedom      =         657
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =          51         51         51         51
   number of vertices I own =          51         51         51         51
   number of elements       =         144        144        144        144
   number of leaf elements  =          76         76         76         76
   leaf elements I own      =          76         76         76         76
   number of levels         =           5          5          5          5
   degrees of freedom       =         657        657        657        657
   degrees of freedom I own =         657        657        657        657
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =          51
   number of leaf elements =          76
   number of levels        =           5
   degrees of freedom      =         657
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =         111        111        111        111
   number of vertices I own =         111        111        111        111
   number of elements       =         376        376        376        376
   number of leaf elements  =         192        192        192        192
   leaf elements I own      =         192        192        192        192
   number of levels         =           7          7          7          7
   degrees of freedom       =        1593       1593       1593       1593
   degrees of freedom I own =        1593       1593       1593       1593
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =         111
   number of leaf elements =         192
   number of levels        =           7
   degrees of freedom      =        1593
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =         111        111        111        111
   number of vertices I own =         111        111        111        111
   number of elements       =         376        376        376        376
   number of leaf elements  =         192        192        192        192
   leaf elements I own      =         192        192        192        192
   number of levels         =           7          7          7          7
   degrees of freedom       =        1593       1593       1593       1593
   degrees of freedom I own =        1593       1593       1593       1593
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =         111
   number of leaf elements =         192
   number of levels        =           7
   degrees of freedom      =        1593
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =          85         99         99         85
   number of vertices I own =          51         38         46         47
   number of elements       =         284        344        344        284
   number of leaf elements  =         146        176        176        146
   leaf elements I own      =          80         80         78         82
   number of levels         =           7          7          7          7
   degrees of freedom       =        1213       1449       1449       1213
   degrees of freedom I own =         690        623        658        674
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =         182
   number of leaf elements =         320
   number of levels        =           7
   degrees of freedom      =        2645
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =          85         99         99         85
   number of vertices I own =          51         38         46         47
   number of elements       =         284        344        344        284
   number of leaf elements  =         146        176        176        146
   leaf elements I own      =          80         80         78         82
   number of levels         =           7          7          7          7
   degrees of freedom       =        1213       1449       1449       1213
   degrees of freedom I own =         690        623        658        674
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =         182
   number of leaf elements =         320
   number of levels        =           7
   degrees of freedom      =        2645
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =         149        163        163        150
   number of vertices I own =         103         75         88         97
   number of elements       =         528        596        596        532
   number of leaf elements  =         268        302        302        270
   leaf elements I own      =         175        160        156        179
   number of levels         =           9          9          9          9
   degrees of freedom       =        2201       2461       2461       2217
   degrees of freedom I own =        1468       1251       1294       1456
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =         363
   number of leaf elements =         670
   number of levels        =           9
   degrees of freedom      =        5469
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =         149        163        163        150
   number of vertices I own =         103         75         88         97
   number of elements       =         528        596        596        532
   number of leaf elements  =         268        302        302        270
   leaf elements I own      =         175        160        156        179
   number of levels         =           9          9          9          9
   degrees of freedom       =        2201       2461       2461       2217
   degrees of freedom I own =        1468       1251       1294       1456
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =         363
   number of leaf elements =         670
   number of levels        =           9
   degrees of freedom      =        5469
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =         261        285        284        267
   number of vertices I own =         195        157        177        183
   number of elements       =         962       1068       1064        986
   number of leaf elements  =         485        538        536        497
   leaf elements I own      =         342        328        320        350
   number of levels         =           9          9          9          9
   degrees of freedom       =        3951       4365       4349       4047
   degrees of freedom I own =        2838       2587       2634       2826
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =         712
   number of leaf elements =        1340
   number of levels        =           9
   degrees of freedom      =       10885
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =         261        285        284        267
   number of vertices I own =         195        157        177        183
   number of elements       =         962       1068       1064        986
   number of leaf elements  =         485        538        536        497
   leaf elements I own      =         342        328        320        350
   number of levels         =           9          9          9          9
   degrees of freedom       =        3951       4365       4349       4047
   degrees of freedom I own =        2838       2587       2634       2826
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =         712
   number of leaf elements =        1340
   number of levels        =           9
   degrees of freedom      =       10885
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =         475        478        475        481
   number of vertices I own =         387        302        329        373
   number of elements       =        1790       1832       1820       1814
   number of leaf elements  =         899        920        914        911
   leaf elements I own      =         708        627        613        722
   number of levels         =          11         11         11         11
   degrees of freedom       =        7291       7429       7381       7387
   degrees of freedom I own =        5802       4961       5000       5818
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =        1391
   number of leaf elements =        2670
   number of levels        =          11
   degrees of freedom      =       21581
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =         475        478        475        481
   number of vertices I own =         387        302        329        373
   number of elements       =        1790       1832       1820       1814
   number of leaf elements  =         899        920        914        911
   leaf elements I own      =         708        627        613        722
   number of levels         =          11         11         11         11
   degrees of freedom       =        7291       7429       7381       7387
   degrees of freedom I own =        5802       4961       5000       5818
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =        1391
   number of leaf elements =        2670
   number of levels        =          11
   degrees of freedom      =       21581
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =         475        478        475        481
   number of vertices I own =         387        302        329        373
   number of elements       =        1790       1832       1820       1814
   number of leaf elements  =         899        920        914        911
   leaf elements I own      =         708        627        613        722
   number of levels         =          11         11         11         11
   degrees of freedom       =        7291       7429       7381       7387
   degrees of freedom I own =        5802       4961       5000       5818
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =        1391
   number of leaf elements =        2670
   number of levels        =          11
   degrees of freedom      =       21581
   min and max degree      =           4          4

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           8
termination condition:
  maximum vertices achieved
---------------------------------------------------------
