---------------------------------------------------------
           PHAML   Version 1.9.1

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER_ALL
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_VERTICES
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Individual Grids:
   number of vertices       =           9          9          9          9
   number of vertices I own =           9          9          9          9
   number of elements       =           8          8          8          8
   number of leaf elements  =           8          8          8          8
   leaf elements I own      =           8          8          8          8
   number of levels         =           1          1          1          1
   degrees of freedom       =           9          9          9          9
   degrees of freedom I own =           9          9          9          9
   min degree               =           1          1          1          1
   max degree               =           1          1          1          1

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Individual Grids:
   number of vertices       =          29         29         29         29
   number of vertices I own =          29         29         29         29
   number of elements       =          72         72         72         72
   number of leaf elements  =          40         40         40         40
   leaf elements I own      =          40         40         40         40
   number of levels         =           5          5          5          5
   degrees of freedom       =          29         29         29         29
   degrees of freedom I own =          29         29         29         29
   min degree               =           1          1          1          1
   max degree               =           1          1          1          1

Total Grid:
   number of vertices      =          29
   number of leaf elements =          40
   number of levels        =           5
   degrees of freedom      =          29
   min and max degree      =           1          1

Individual Grids:
   number of vertices       =          36         36         36         36
   number of vertices I own =          36         36         36         36
   number of elements       =          88         88         88         88
   number of leaf elements  =          48         48         48         48
   leaf elements I own      =          48         48         48         48
   number of levels         =           6          6          6          6
   degrees of freedom       =          36         36         36         36
   degrees of freedom I own =          36         36         36         36
   min degree               =           1          1          1          1
   max degree               =           1          1          1          1

Total Grid:
   number of vertices      =          36
   number of leaf elements =          48
   number of levels        =           6
   degrees of freedom      =          36
   min and max degree      =           1          1

Individual Grids:
   number of vertices       =          82         82         82         82
   number of vertices I own =          82         82         82         82
   number of elements       =         256        256        256        256
   number of leaf elements  =         132        132        132        132
   leaf elements I own      =         132        132        132        132
   number of levels         =           7          7          7          7
   degrees of freedom       =          82         82         82         82
   degrees of freedom I own =          82         82         82         82
   min degree               =           1          1          1          1
   max degree               =           1          1          1          1

Total Grid:
   number of vertices      =          82
   number of leaf elements =         132
   number of levels        =           7
   degrees of freedom      =          82
   min and max degree      =           1          1

Individual Grids:
   number of vertices       =         145        145        145        145
   number of vertices I own =         145        145        145        145
   number of elements       =         484        484        484        484
   number of leaf elements  =         246        246        246        246
   leaf elements I own      =         246        246        246        246
   number of levels         =           8          8          8          8
   degrees of freedom       =         145        145        145        145
   degrees of freedom I own =         145        145        145        145
   min degree               =           1          1          1          1
   max degree               =           1          1          1          1

Total Grid:
   number of vertices      =         145
   number of leaf elements =         246
   number of levels        =           8
   degrees of freedom      =         145
   min and max degree      =           1          1

Individual Grids:
   number of vertices       =         110        160        156        114
   number of vertices I own =          74         93         92         76
   number of elements       =         370        558        546        382
   number of leaf elements  =         189        283        277        195
   leaf elements I own      =         125        173        163        129
   number of levels         =           9         10         10          9
   degrees of freedom       =         110        160        156        114
   degrees of freedom I own =          74         93         92         76
   min degree               =           1          1          1          1
   max degree               =           1          1          1          1

Total Grid:
   number of vertices      =         335
   number of leaf elements =         590
   number of levels        =          10
   degrees of freedom      =         335
   min and max degree      =           1          1

Individual Grids:
   number of vertices       =         170        270        256        176
   number of vertices I own =         128        191        176        131
   number of elements       =         608        990        946        630
   number of leaf elements  =         308        499        477        319
   leaf elements I own      =         234        365        330        237
   number of levels         =          10         11         10         10
   degrees of freedom       =         170        270        256        176
   degrees of freedom I own =         128        191        176        131
   min degree               =           1          1          1          1
   max degree               =           1          1          1          1

Total Grid:
   number of vertices      =         626
   number of leaf elements =        1166
   number of levels        =          11
   degrees of freedom      =         626
   min and max degree      =           1          1

Individual Grids:
   number of vertices       =         305        465        453        306
   number of vertices I own =         242        335        333        242
   number of elements       =        1110       1730       1692       1112
   number of leaf elements  =         559        869        850        560
   leaf elements I own      =         439        649        618        442
   number of levels         =          11         12         12         11
   degrees of freedom       =         305        465        453        306
   degrees of freedom I own =         242        335        333        242
   min degree               =           1          1          1          1
   max degree               =           1          1          1          1

Total Grid:
   number of vertices      =        1152
   number of leaf elements =        2148
   number of levels        =          12
   degrees of freedom      =        1152
   min and max degree      =           1          1

Individual Grids:
   number of vertices       =         305        465        453        306
   number of vertices I own =         242        335        333        242
   number of elements       =        1110       1730       1692       1112
   number of leaf elements  =         559        869        850        560
   leaf elements I own      =         439        649        618        442
   number of levels         =          11         12         12         11
   degrees of freedom       =         305        465        453        306
   degrees of freedom I own =         242        335        333        242
   min degree               =           1          1          1          1
   max degree               =           1          1          1          1

Total Grid:
   number of vertices      =        1152
   number of leaf elements =        2148
   number of levels        =          12
   degrees of freedom      =        1152
   min and max degree      =           1          1

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           7
termination condition:
  maximum vertices achieved
---------------------------------------------------------
