
------------------------------------------------------
          PHAML Version 1.11.0 WARNING
parallel not yet supported in 3D; setting nproc to 1
------------------------------------------------------

---------------------------------------------------------
           PHAML   Version 1.11.0

Output from the master process
  PDE id is     0
  Number of slave processors is     1
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  300
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 2
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         false
  isosceles_right_triangles  false
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_ERR
  print_errest_what  ENERGY_LINF_ERREST
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    HIERARCHICAL_COEFFICIENT
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           false
  partition_method   RTK
  ignore_quad_err    true
  solver             PETSC_CG_SOLVER
  preconditioner     PETSC_SOR_PRECONDITION
  petsc_matrix_free  false
  petsc_rtol         default
  petsc_atol         default
  petsc_dtol         default
  petsc_maxits       default
  petsc_sor_omega    default
  petsc_sor_its      default
  petsc_sor_lits     default
---------------------------------------------------------

Total Grid:
   number of vertices      =          14
   number of leaf elements =          24
   number of levels        =           1
   degrees of freedom      =          14
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.7636148580E+00
   energy error estimate      4.7146053531E+00
      effectivity             2.6732624369E+00
  Component           1
   Linf norm of error         1.3675936017E-01
   Linf error estimate        1.3939211931E+00
      effectivity             1.0192510343E+01
  Component           2
   Linf norm of error         2.7389526367E-01
   Linf error estimate        1.8750000000E+00
      effectivity             6.8456824513E+00

Total Grid:
   number of vertices      =          22
   number of leaf elements =          36
   number of levels        =           3
   degrees of freedom      =          30
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.4490183993E+00
      reduced by              8.2161838950E-01
   energy error estimate      2.7458404139E+00
      reduced by              5.8241150812E-01
      effectivity             1.8949658715E+00
  Component           1
   Linf norm of error         1.1594612198E-01
      reduced by              8.4781123455E-01
   Linf error estimate        7.1782997564E-01
      reduced by              5.1497170657E-01
      effectivity             6.1910649823E+00
  Component           2
   Linf norm of error         2.7389526367E-01
      reduced by              1.0000000000E+00
   Linf error estimate        1.3671875000E+00
      reduced by              7.2916666667E-01
      effectivity             4.9916434540E+00

Total Grid:
   number of vertices      =          36
   number of leaf elements =          85
   number of levels        =           4
   degrees of freedom      =          58
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.3147493762E+00
      reduced by              9.0733794465E-01
   energy error estimate      1.4758185996E+00
      reduced by              5.3747428005E-01
      effectivity             1.1225094503E+00
  Component           1
   Linf norm of error         1.1594612198E-01
      reduced by              1.0000000000E+00
   Linf error estimate        2.3865121854E-01
      reduced by              3.3246204065E-01
      effectivity             2.0582940978E+00
  Component           2
   Linf norm of error         2.2617097730E-01
      reduced by              8.2575716814E-01
   Linf error estimate        4.2968750000E-01
      reduced by              3.1428571429E-01
      effectivity             1.8998348291E+00

Total Grid:
   number of vertices      =          68
   number of leaf elements =         224
   number of levels        =           6
   degrees of freedom      =         122
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.2886533742E+00
      reduced by              9.8015134859E-01
   energy error estimate      1.3169384495E+00
      reduced by              8.9234439105E-01
      effectivity             1.0219493278E+00
  Component           1
   Linf norm of error         6.3510574978E-02
      reduced by              5.4775937213E-01
   Linf error estimate        2.1041964353E-01
      reduced by              8.8170362094E-01
      effectivity             3.3131434190E+00
  Component           2
   Linf norm of error         2.3353159162E-01
      reduced by              1.0325444689E+00
   Linf error estimate        1.4404296875E-01
      reduced by              3.3522727273E-01
      effectivity             6.1680292481E-01

Total Grid:
   number of vertices      =         149
   number of leaf elements =         544
   number of levels        =           7
   degrees of freedom      =         284
   min and max degree      =           1          1

Norms of error:
   energy norm of error       8.8085133314E-01
      reduced by              6.8354403969E-01
   energy error estimate      1.7467595228E+00
      reduced by              1.3263790144E+00
      effectivity             1.9830355669E+00
  Component           1
   Linf norm of error         5.6618731801E-02
      reduced by              8.9148510811E-01
   Linf error estimate        9.1972767215E-02
      reduced by              4.3709211589E-01
      effectivity             1.6244229478E+00
  Component           2
   Linf norm of error         9.0478284840E-02
      reduced by              3.8743488284E-01
   Linf error estimate        4.2968750000E-01
      reduced by              2.9830508475E+00
      effectivity             4.7490676990E+00

Total Grid:
   number of vertices      =         249
   number of leaf elements =         987
   number of levels        =           7
   degrees of freedom      =         484
   min and max degree      =           1          1

Norms of error:
   energy norm of error       8.0323270822E-01
      reduced by              9.1188226436E-01
   energy error estimate      1.0050239982E+00
      reduced by              5.7536483135E-01
      effectivity             1.2512239454E+00
  Component           1
   Linf norm of error         3.9228884275E-02
      reduced by              6.9286052561E-01
   Linf error estimate        6.6501532967E-02
      reduced by              7.2305678062E-01
      effectivity             1.6952185665E+00
  Component           2
   Linf norm of error         8.4472540611E-02
      reduced by              9.3362225820E-01
   Linf error estimate        1.4404296875E-01
      reduced by              3.3522727273E-01
      effectivity             1.7052046465E+00

Total Grid:
   number of vertices      =         457
   number of leaf elements =        1885
   number of levels        =           9
   degrees of freedom      =         900
   min and max degree      =           1          1

Norms of error:
   energy norm of error       6.9020941783E-01
      reduced by              8.5928948207E-01
   energy error estimate      1.0007621247E+00
      reduced by              9.9575943110E-01
      effectivity             1.4499398282E+00
  Component           1
   Linf norm of error         2.4361755772E-02
      reduced by              6.2101576994E-01
   Linf error estimate        6.6501532967E-02
      reduced by              1.0000000000E+00
      effectivity             2.7297512375E+00
  Component           2
   Linf norm of error         7.3632060781E-02
      reduced by              8.7166859488E-01
   Linf error estimate        8.4132188550E-02
      reduced by              5.8407702424E-01
      effectivity             1.1426026606E+00

Total Grid:
   number of vertices      =         457
   number of leaf elements =        1885
   number of levels        =           9
   degrees of freedom      =         900
   min and max degree      =           1          1

Norms of error:
   energy norm of error       6.9020941783E-01
   energy error estimate      1.0007621247E+00
      effectivity             1.4499398282E+00
  Component           1
   Linf norm of error         2.4361755772E-02
   Linf error estimate        6.6501532967E-02
      effectivity             2.7297512375E+00
  Component           2
   Linf norm of error         7.3632060781E-02
   Linf error estimate        8.4132188550E-02
      effectivity             1.1426026606E+00

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
Linf errors from query  2.436175577218E-02 7.363206078058E-02
