---------------------------------------------------------
           PHAML   Version 1.11.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  true
  pde_has_cross_derivative   false
  laplacian_operator         false
  isosceles_right_triangles  false
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    SLAVES
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    HIERARCHICAL_COEFFICIENT
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           false
  partition_method   RTK
  ignore_quad_err    true
  solver             LAPACK_INDEFINITE_SOLVER
---------------------------------------------------------

My Grid:
   number of vertices       =          14
   number of vertices I own =          14
   number of elements       =          24
   number of leaf elements  =          24
   leaf elements I own      =          24
   number of levels         =           1
   degrees of freedom       =          14
   degrees of freedom I own =          14
   min and max degree       =           1          1

Norms of error:
   energy norm of error       9.4905808970E+00
   Linf norm of error         1.3991324296E+00
   L2 norm of error           2.0755441062E+00

My Grid:
   number of vertices       =          33
   number of vertices I own =          33
   number of elements       =         126
   number of leaf elements  =          75
   leaf elements I own      =          75
   number of levels         =           4
   degrees of freedom       =          33
   degrees of freedom I own =          33
   min and max degree       =           1          1

Norms of error:
   energy norm of error       7.9368599451E+00
      reduced by              8.3628810831E-01
   Linf norm of error         1.3991324296E+00
      reduced by              1.0000000000E+00
   L2 norm of error           1.3481119397E+00
      reduced by              6.4952218347E-01

My Grid:
   number of vertices       =          70
   number of vertices I own =          70
   number of elements       =         436
   number of leaf elements  =         230
   leaf elements I own      =         230
   number of levels         =           6
   degrees of freedom       =          70
   degrees of freedom I own =          70
   min and max degree       =           1          1

Norms of error:
   energy norm of error       7.1228608218E+00
      reduced by              8.9744065929E-01
   Linf norm of error         9.1417006465E-01
      reduced by              6.5338351489E-01
   L2 norm of error           7.8333407517E-01
      reduced by              5.8106011236E-01

My Grid:
   number of vertices       =         115
   number of vertices I own =         115
   number of elements       =         736
   number of leaf elements  =         380
   leaf elements I own      =         380
   number of levels         =           7
   degrees of freedom       =         115
   degrees of freedom I own =         115
   min and max degree       =           1          1

Norms of error:
   energy norm of error       6.6881424444E+00
      reduced by              9.3896857059E-01
   Linf norm of error         8.8285836820E-01
      reduced by              9.6574849947E-01
   L2 norm of error           6.5625591150E-01
      reduced by              8.3777271065E-01

My Grid:
   number of vertices       =         241
   number of vertices I own =         241
   number of elements       =        1744
   number of leaf elements  =         884
   leaf elements I own      =         884
   number of levels         =           7
   degrees of freedom       =         241
   degrees of freedom I own =         241
   min and max degree       =           1          1

Norms of error:
   energy norm of error       5.3826466471E+00
      reduced by              8.0480442692E-01
   Linf norm of error         5.7327898988E-01
      reduced by              6.4934423293E-01
   L2 norm of error           4.5611929511E-01
      reduced by              6.9503266503E-01

My Grid:
   number of vertices       =         452
   number of vertices I own =         452
   number of elements       =        3758
   number of leaf elements  =        1891
   leaf elements I own      =        1891
   number of levels         =          10
   degrees of freedom       =         452
   degrees of freedom I own =         452
   min and max degree       =           1          1

Norms of error:
   energy norm of error       4.7210882692E+00
      reduced by              8.7709422125E-01
   Linf norm of error         5.2090048033E-01
      reduced by              9.0863347432E-01
   L2 norm of error           3.3682807769E-01
      reduced by              7.3846487377E-01

My Grid:
   number of vertices       =         926
   number of vertices I own =         926
   number of elements       =        8036
   number of leaf elements  =        4030
   leaf elements I own      =        4030
   number of levels         =          12
   degrees of freedom       =         926
   degrees of freedom I own =         926
   min and max degree       =           1          1

Norms of error:
   energy norm of error       4.0330136639E+00
      reduced by              8.5425508568E-01
   Linf norm of error         3.6041215309E-01
      reduced by              6.9190213237E-01
   L2 norm of error           2.5007194486E-01
      reduced by              7.4243200441E-01

My Grid:
   number of vertices       =         926
   number of vertices I own =         926
   number of elements       =        8036
   number of leaf elements  =        4030
   leaf elements I own      =        4030
   number of levels         =          12
   degrees of freedom       =         926
   degrees of freedom I own =         926
   min and max degree       =           1          1

Norms of error:
   energy norm of error       4.0330136639E+00
   Linf norm of error         3.6041215309E-01
   L2 norm of error           2.5007194486E-01

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
