---------------------------------------------------------
           PHAML   Version 1.11.0

Output from the master process
  PDE id is     0
  Number of slave processors is     1
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   true
  laplacian_operator         false
  isosceles_right_triangles  false
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    HIERARCHICAL_COEFFICIENT
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           false
  partition_method   RTK
  ignore_quad_err    true
  solver             LAPACK_INDEFINITE_SOLVER
---------------------------------------------------------

Total Grid:
   number of vertices      =          14
   number of leaf elements =          24
   number of levels        =           1
   degrees of freedom      =          14
   min and max degree      =           1          1

Norms of error:
   energy norm of error       9.6469097061E+00
   Linf norm of error         1.3991324296E+00
   L2 norm of error           2.0755441062E+00

Total Grid:
   number of vertices      =          33
   number of leaf elements =          75
   number of levels        =           4
   degrees of freedom      =          33
   min and max degree      =           1          1

Norms of error:
   energy norm of error       8.8778089653E+00
      reduced by              9.2027491039E-01
   Linf norm of error         1.3991324296E+00
      reduced by              1.0000000000E+00
   L2 norm of error           1.3875111991E+00
      reduced by              6.6850480071E-01

Total Grid:
   number of vertices      =          70
   number of leaf elements =         230
   number of levels        =           6
   degrees of freedom      =          70
   min and max degree      =           1          1

Norms of error:
   energy norm of error       7.2285180521E+00
      reduced by              8.1422320308E-01
   Linf norm of error         9.7369634246E-01
      reduced by              6.9592864968E-01
   L2 norm of error           8.1600545836E-01
      reduced by              5.8810729521E-01

Total Grid:
   number of vertices      =         124
   number of leaf elements =         416
   number of levels        =           7
   degrees of freedom      =         124
   min and max degree      =           1          1

Norms of error:
   energy norm of error       6.4887460473E+00
      reduced by              8.9765924364E-01
   Linf norm of error         9.2321803647E-01
      reduced by              9.4815806141E-01
   L2 norm of error           6.7123063688E-01
      reduced by              8.2258106242E-01

Total Grid:
   number of vertices      =         248
   number of leaf elements =         935
   number of levels        =           7
   degrees of freedom      =         248
   min and max degree      =           1          1

Norms of error:
   energy norm of error       5.1319091474E+00
      reduced by              7.9089381985E-01
   Linf norm of error         6.1731922769E-01
      reduced by              6.6866027667E-01
   L2 norm of error           4.5001300692E-01
      reduced by              6.7042977808E-01

Total Grid:
   number of vertices      =         453
   number of leaf elements =        1897
   number of levels        =           9
   degrees of freedom      =         453
   min and max degree      =           1          1

Norms of error:
   energy norm of error       4.5939964680E+00
      reduced by              8.9518273532E-01
   Linf norm of error         5.3689076851E-01
      reduced by              8.6971334186E-01
   L2 norm of error           3.6282748674E-01
      reduced by              8.0625999951E-01

Total Grid:
   number of vertices      =         919
   number of leaf elements =        4045
   number of levels        =          10
   degrees of freedom      =         919
   min and max degree      =           1          1

Norms of error:
   energy norm of error       3.8623506255E+00
      reduced by              8.4073870156E-01
   Linf norm of error         3.6872702490E-01
      reduced by              6.8678220324E-01
   L2 norm of error           2.6552420309E-01
      reduced by              7.3181942602E-01

Total Grid:
   number of vertices      =         919
   number of leaf elements =        4045
   number of levels        =          10
   degrees of freedom      =         919
   min and max degree      =           1          1

Norms of error:
   energy norm of error       3.8623506255E+00
   Linf norm of error         3.6872702490E-01
   L2 norm of error           2.6552420309E-01

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
