
------------------------------------------------------
          PHAML Version 1.11.0 WARNING
parallel not yet supported in 3D; setting nproc to 1
------------------------------------------------------

---------------------------------------------------------
           PHAML   Version 1.11.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         false
  isosceles_right_triangles  false
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    SLAVES
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    HIERARCHICAL_COEFFICIENT
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           false
  partition_method   RTK
  ignore_quad_err    true
  solver             PETSC_CG_SOLVER
  preconditioner     PETSC_SOR_PRECONDITION
  petsc_matrix_free  false
  petsc_rtol         default
  petsc_atol         default
  petsc_dtol         default
  petsc_maxits       default
  petsc_sor_omega    default
  petsc_sor_its      default
  petsc_sor_lits     default
---------------------------------------------------------

My Grid:
   number of vertices       =          14
   number of vertices I own =          14
   number of elements       =          24
   number of leaf elements  =          24
   leaf elements I own      =          24
   number of levels         =           1
   degrees of freedom       =          14
   degrees of freedom I own =          14
   min and max degree       =           1          1

Norms of error:
   energy norm of error       1.8581993201E+01
   Linf norm of error         1.3991324296E+00
   L2 norm of error           2.0755441062E+00

My Grid:
   number of vertices       =          33
   number of vertices I own =          33
   number of elements       =         126
   number of leaf elements  =          75
   leaf elements I own      =          75
   number of levels         =           4
   degrees of freedom       =          33
   degrees of freedom I own =          33
   min and max degree       =           1          1

Norms of error:
   energy norm of error       1.3249608884E+01
      reduced by              7.1303485802E-01
   Linf norm of error         1.3991324296E+00
      reduced by              1.0000000000E+00
   L2 norm of error           1.3491647772E+00
      reduced by              6.5002944200E-01

My Grid:
   number of vertices       =          73
   number of vertices I own =          73
   number of elements       =         456
   number of leaf elements  =         240
   leaf elements I own      =         240
   number of levels         =           6
   degrees of freedom       =          73
   degrees of freedom I own =          73
   min and max degree       =           1          1

Norms of error:
   energy norm of error       1.2453804127E+01
      reduced by              9.3993749068E-01
   Linf norm of error         8.4111227735E-01
      reduced by              6.0116702290E-01
   L2 norm of error           7.3489354467E-01
      reduced by              5.4470258718E-01

My Grid:
   number of vertices       =         123
   number of vertices I own =         123
   number of elements       =         774
   number of leaf elements  =         399
   leaf elements I own      =         399
   number of levels         =           7
   degrees of freedom       =         123
   degrees of freedom I own =         123
   min and max degree       =           1          1

Norms of error:
   energy norm of error       1.2307515041E+01
      reduced by              9.8825346178E-01
   Linf norm of error         7.9294693985E-01
      reduced by              9.4273613785E-01
   L2 norm of error           6.2728110593E-01
      reduced by              8.5356730982E-01

My Grid:
   number of vertices       =         231
   number of vertices I own =         231
   number of elements       =        1636
   number of leaf elements  =         830
   leaf elements I own      =         830
   number of levels         =           7
   degrees of freedom       =         231
   degrees of freedom I own =         231
   min and max degree       =           1          1

Norms of error:
   energy norm of error       1.0521289401E+01
      reduced by              8.5486707641E-01
   Linf norm of error         6.9307625607E-01
      reduced by              8.7405124005E-01
   L2 norm of error           4.8916638231E-01
      reduced by              7.7982004828E-01

My Grid:
   number of vertices       =         459
   number of vertices I own =         459
   number of elements       =        3770
   number of leaf elements  =        1897
   leaf elements I own      =        1897
   number of levels         =          10
   degrees of freedom       =         459
   degrees of freedom I own =         459
   min and max degree       =           1          1

Norms of error:
   energy norm of error       8.9554016030E+00
      reduced by              8.5116959167E-01
   Linf norm of error         5.7996902204E-01
      reduced by              8.3680405577E-01
   L2 norm of error           3.4650171667E-01
      reduced by              7.0835145097E-01

My Grid:
   number of vertices       =         910
   number of vertices I own =         910
   number of elements       =        7994
   number of leaf elements  =        4009
   leaf elements I own      =        4009
   number of levels         =          12
   degrees of freedom       =         910
   degrees of freedom I own =         910
   min and max degree       =           1          1

Norms of error:
   energy norm of error       7.6247676013E+00
      reduced by              8.5141548523E-01
   Linf norm of error         4.3950056340E-01
      reduced by              7.5780006639E-01
   L2 norm of error           2.6543299534E-01
      reduced by              7.6603659540E-01

My Grid:
   number of vertices       =         910
   number of vertices I own =         910
   number of elements       =        7994
   number of leaf elements  =        4009
   leaf elements I own      =        4009
   number of levels         =          12
   degrees of freedom       =         910
   degrees of freedom I own =         910
   min and max degree       =           1          1

Norms of error:
   energy norm of error       7.6247676013E+00
   Linf norm of error         4.3950056340E-01
   L2 norm of error           2.6543299534E-01

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
