
My Grid:
   number of vertices       =         176
   number of vertices I own =         176
   number of elements       =         638
   number of leaf elements  =         323
   leaf elements I own      =         323
   number of levels         =          10
   degrees of freedom       =        2639
   degrees of freedom I own =        2639
   min and max degree       =           4          4

Norms of error:
   energy error estimate      4.1086137077E-04
   Linf error estimate        7.0733325986E-05
time =  1.000000000000E-02

My Grid:
   number of vertices       =         176
   number of vertices I own =         176
   number of elements       =         638
   number of leaf elements  =         323
   leaf elements I own      =         323
   number of levels         =          10
   degrees of freedom       =        2639
   degrees of freedom I own =        2639
   min and max degree       =           4          4

Norms of error:
   energy error estimate      4.7483620780E-04
   Linf error estimate        5.4992718826E-05
time =  2.000000000000E-02

My Grid:
   number of vertices       =         176
   number of vertices I own =         176
   number of elements       =         638
   number of leaf elements  =         323
   leaf elements I own      =         323
   number of levels         =          10
   degrees of freedom       =        2639
   degrees of freedom I own =        2639
   min and max degree       =           4          4

Norms of error:
   energy error estimate      5.3421954454E-04
   Linf error estimate        6.3932269095E-05
time =  3.000000000000E-02

My Grid:
   number of vertices       =         176
   number of vertices I own =         176
   number of elements       =         638
   number of leaf elements  =         323
   leaf elements I own      =         323
   number of levels         =          10
   degrees of freedom       =        2639
   degrees of freedom I own =        2639
   min and max degree       =           4          4

Norms of error:
   energy error estimate      6.1652786607E-04
   Linf error estimate        8.8118342803E-05
time =  4.000000000000E-02

My Grid:
   number of vertices       =         176
   number of vertices I own =         176
   number of elements       =         638
   number of leaf elements  =         323
   leaf elements I own      =         323
   number of levels         =          10
   degrees of freedom       =        2639
   degrees of freedom I own =        2639
   min and max degree       =           4          4

Norms of error:
   energy error estimate      6.9419170208E-04
   Linf error estimate        8.8752374921E-05
time =  5.000000000000E-02
