
My Grid:
   number of vertices       =         655
   number of vertices I own =         655
   number of elements       =        2510
   number of leaf elements  =        1259
   leaf elements I own      =        1259
   number of levels         =          14
   degrees of freedom       =         655
   degrees of freedom I own =         655
   min and max degree       =           1          1

Norms of error:
   energy error estimate      6.0213089165E-02
   Linf error estimate        3.9310766666E-03
time =  1.000000000000E-02

My Grid:
   number of vertices       =         655
   number of vertices I own =         655
   number of elements       =        2508
   number of leaf elements  =        1258
   leaf elements I own      =        1258
   number of levels         =          14
   degrees of freedom       =         655
   degrees of freedom I own =         655
   min and max degree       =           1          1

Norms of error:
   energy error estimate      6.2476254371E-02
   Linf error estimate        3.4955488330E-03
time =  2.000000000000E-02

My Grid:
   number of vertices       =         656
   number of vertices I own =         656
   number of elements       =        2508
   number of leaf elements  =        1258
   leaf elements I own      =        1258
   number of levels         =          14
   degrees of freedom       =         656
   degrees of freedom I own =         656
   min and max degree       =           1          1

Norms of error:
   energy error estimate      6.5290660987E-02
   Linf error estimate        3.7035061808E-03
time =  3.000000000000E-02

My Grid:
   number of vertices       =         657
   number of vertices I own =         657
   number of elements       =        2508
   number of leaf elements  =        1258
   leaf elements I own      =        1258
   number of levels         =          14
   degrees of freedom       =         657
   degrees of freedom I own =         657
   min and max degree       =           1          1

Norms of error:
   energy error estimate      6.6357178822E-02
   Linf error estimate        3.8697429655E-03
time =  4.000000000000E-02

My Grid:
   number of vertices       =         659
   number of vertices I own =         659
   number of elements       =        2516
   number of leaf elements  =        1262
   leaf elements I own      =        1262
   number of levels         =          14
   degrees of freedom       =         659
   degrees of freedom I own =         659
   min and max degree       =           1          1

Norms of error:
   energy error estimate      6.6799978339E-02
   Linf error estimate        2.9552750315E-03
time =  5.000000000000E-02
