
Total Grid:
   number of vertices      =         183
   number of leaf elements =         337
   number of levels        =          10
   degrees of freedom      =        2751
   min and max degree      =           4          4

Norms of error:
   energy error estimate      4.2123676506E-04
   Linf error estimate        7.0732006411E-05
time =  1.000000000000E-02

Total Grid:
   number of vertices      =         183
   number of leaf elements =         337
   number of levels        =          10
   degrees of freedom      =        2751
   min and max degree      =           4          4

Norms of error:
   energy error estimate      4.7672293115E-04
   Linf error estimate        5.4992160644E-05
time =  2.000000000000E-02

Total Grid:
   number of vertices      =         183
   number of leaf elements =         337
   number of levels        =          10
   degrees of freedom      =        2751
   min and max degree      =           4          4

Norms of error:
   energy error estimate      5.3547485965E-04
   Linf error estimate        6.3932727006E-05
time =  3.000000000000E-02

Total Grid:
   number of vertices      =         183
   number of leaf elements =         337
   number of levels        =          10
   degrees of freedom      =        2751
   min and max degree      =           4          4

Norms of error:
   energy error estimate      6.1753274842E-04
   Linf error estimate        8.8118930117E-05
time =  4.000000000000E-02

Total Grid:
   number of vertices      =         183
   number of leaf elements =         337
   number of levels        =          10
   degrees of freedom      =        2751
   min and max degree      =           4          4

Norms of error:
   energy error estimate      6.9486705786E-04
   Linf error estimate        8.8752988227E-05
time =  5.000000000000E-02
