---------------------------------------------------------
           PHAML   Version 1.11.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    FREQUENTLY
  print_grid_who     MASTER_ALL
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree                      4
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  postbalance        BALANCE_EQUATIONS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Individual Grids:
   number of vertices       =           9          9          9          9
   number of vertices I own =           9          9          9          9
   number of elements       =           8          8          8          8
   number of leaf elements  =           8          8          8          8
   leaf elements I own      =           8          8          8          8
   number of levels         =           1          1          1          1
   degrees of freedom       =          81         81         81         81
   degrees of freedom I own =          81         81         81         81
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =          81
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =          17         17         17         17
   number of vertices I own =          17         17         17         17
   number of elements       =          36         36         36         36
   number of leaf elements  =          22         22         22         22
   leaf elements I own      =          22         22         22         22
   number of levels         =           3          3          3          3
   degrees of freedom       =         197        197        197        197
   degrees of freedom I own =         197        197        197        197
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =          17
   number of leaf elements =          22
   number of levels        =           3
   degrees of freedom      =         197
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =          17         17         17         17
   number of vertices I own =          17         17         17         17
   number of elements       =          36         36         36         36
   number of leaf elements  =          22         22         22         22
   leaf elements I own      =          22         22         22         22
   number of levels         =           3          3          3          3
   degrees of freedom       =         197        197        197        197
   degrees of freedom I own =         197        197        197        197
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =          17
   number of leaf elements =          22
   number of levels        =           3
   degrees of freedom      =         197
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =          30         30         30         30
   number of vertices I own =          30         30         30         30
   number of elements       =          80         80         80         80
   number of leaf elements  =          44         44         44         44
   leaf elements I own      =          44         44         44         44
   number of levels         =           4          4          4          4
   degrees of freedom       =         381        381        381        381
   degrees of freedom I own =         381        381        381        381
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =          30
   number of leaf elements =          44
   number of levels        =           4
   degrees of freedom      =         381
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =          30         30         30         30
   number of vertices I own =          30         30         30         30
   number of elements       =          80         80         80         80
   number of leaf elements  =          44         44         44         44
   leaf elements I own      =          44         44         44         44
   number of levels         =           4          4          4          4
   degrees of freedom       =         381        381        381        381
   degrees of freedom I own =         381        381        381        381
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =          30
   number of leaf elements =          44
   number of levels        =           4
   degrees of freedom      =         381
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =          51         51         51         51
   number of vertices I own =          51         51         51         51
   number of elements       =         144        144        144        144
   number of leaf elements  =          76         76         76         76
   leaf elements I own      =          76         76         76         76
   number of levels         =           5          5          5          5
   degrees of freedom       =         657        657        657        657
   degrees of freedom I own =         657        657        657        657
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =          51
   number of leaf elements =          76
   number of levels        =           5
   degrees of freedom      =         657
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =          51         51         51         51
   number of vertices I own =          51         51         51         51
   number of elements       =         144        144        144        144
   number of leaf elements  =          76         76         76         76
   leaf elements I own      =          76         76         76         76
   number of levels         =           5          5          5          5
   degrees of freedom       =         657        657        657        657
   degrees of freedom I own =         657        657        657        657
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =          51
   number of leaf elements =          76
   number of levels        =           5
   degrees of freedom      =         657
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =         110        110        110        110
   number of vertices I own =         110        110        110        110
   number of elements       =         372        372        372        372
   number of leaf elements  =         190        190        190        190
   leaf elements I own      =         190        190        190        190
   number of levels         =           7          7          7          7
   degrees of freedom       =        1577       1577       1577       1577
   degrees of freedom I own =        1577       1577       1577       1577
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =         110
   number of leaf elements =         190
   number of levels        =           7
   degrees of freedom      =        1577
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =         110        110        110        110
   number of vertices I own =         110        110        110        110
   number of elements       =         372        372        372        372
   number of leaf elements  =         190        190        190        190
   leaf elements I own      =         190        190        190        190
   number of levels         =           7          7          7          7
   degrees of freedom       =        1577       1577       1577       1577
   degrees of freedom I own =        1577       1577       1577       1577
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =         110
   number of leaf elements =         190
   number of levels        =           7
   degrees of freedom      =        1577
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =          84         99         99         84
   number of vertices I own =          50         38         46         46
   number of elements       =         280        344        344        280
   number of leaf elements  =         144        176        176        144
   leaf elements I own      =          78         80         78         80
   number of levels         =           7          7          7          7
   degrees of freedom       =        1197       1449       1449       1197
   degrees of freedom I own =         674        623        658        658
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =         180
   number of leaf elements =         316
   number of levels        =           7
   degrees of freedom      =        2613
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =          84         99         99         84
   number of vertices I own =          50         38         46         46
   number of elements       =         280        344        344        280
   number of leaf elements  =         144        176        176        144
   leaf elements I own      =          78         80         78         80
   number of levels         =           7          7          7          7
   degrees of freedom       =        1197       1449       1449       1197
   degrees of freedom I own =         674        623        658        658
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =         180
   number of leaf elements =         316
   number of levels        =           7
   degrees of freedom      =        2613
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =         150        165        164        150
   number of vertices I own =         104         76         89         97
   number of elements       =         532        604        600        532
   number of leaf elements  =         270        306        304        270
   leaf elements I own      =         176        163        158        179
   number of levels         =           9          9          9          9
   degrees of freedom       =        2217       2493       2477       2217
   degrees of freedom I own =        1478       1273       1310       1456
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =         366
   number of leaf elements =         676
   number of levels        =           9
   degrees of freedom      =        5517
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =         150        165        164        150
   number of vertices I own =         104         76         89         97
   number of elements       =         532        604        600        532
   number of leaf elements  =         270        306        304        270
   leaf elements I own      =         176        163        158        179
   number of levels         =           9          9          9          9
   degrees of freedom       =        2217       2493       2477       2217
   degrees of freedom I own =        1478       1273       1310       1456
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =         366
   number of leaf elements =         676
   number of levels        =           9
   degrees of freedom      =        5517
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =         247        280        281        255
   number of vertices I own =         183        155        176        172
   number of elements       =         906       1050       1054        938
   number of leaf elements  =         457        529        531        473
   leaf elements I own      =         319        324        319        328
   number of levels         =           9          9          9          9
   degrees of freedom       =        3727       4291       4307       3855
   degrees of freedom I own =        2652       2555       2624       2650
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =         686
   number of leaf elements =        1290
   number of levels        =           9
   degrees of freedom      =       10481
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =         247        280        281        255
   number of vertices I own =         183        155        176        172
   number of elements       =         906       1050       1054        938
   number of leaf elements  =         457        529        531        473
   leaf elements I own      =         319        324        319        328
   number of levels         =           9          9          9          9
   degrees of freedom       =        3727       4291       4307       3855
   degrees of freedom I own =        2652       2555       2624       2650
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =         686
   number of leaf elements =        1290
   number of levels        =           9
   degrees of freedom      =       10481
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =         468        461        458        474
   number of vertices I own =         380        287        314        366
   number of elements       =        1762       1768       1756       1786
   number of leaf elements  =         885        888        882        897
   leaf elements I own      =         694        598        584        708
   number of levels         =          11         11         11         11
   degrees of freedom       =        7179       7169       7121       7275
   degrees of freedom I own =        5690       4727       4766       5706
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =        1347
   number of leaf elements =        2584
   number of levels        =          11
   degrees of freedom      =       20889
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =         468        461        458        474
   number of vertices I own =         380        287        314        366
   number of elements       =        1762       1768       1756       1786
   number of leaf elements  =         885        888        882        897
   leaf elements I own      =         694        598        584        708
   number of levels         =          11         11         11         11
   degrees of freedom       =        7179       7169       7121       7275
   degrees of freedom I own =        5690       4727       4766       5706
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =        1347
   number of leaf elements =        2584
   number of levels        =          11
   degrees of freedom      =       20889
   min and max degree      =           4          4

Individual Grids:
   number of vertices       =         468        461        458        474
   number of vertices I own =         380        287        314        366
   number of elements       =        1762       1768       1756       1786
   number of leaf elements  =         885        888        882        897
   leaf elements I own      =         694        598        584        708
   number of levels         =          11         11         11         11
   degrees of freedom       =        7179       7169       7121       7275
   degrees of freedom I own =        5690       4727       4766       5706
   min degree               =           4          4          4          4
   max degree               =           4          4          4          4

Total Grid:
   number of vertices      =        1347
   number of leaf elements =        2584
   number of levels        =          11
   degrees of freedom      =       20889
   min and max degree      =           4          4

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           8
termination condition:
  maximum vertices achieved
---------------------------------------------------------
