---------------------------------------------------------
           PHAML   Version 1.11.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                 1000
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     MASTER_ALL
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  postbalance        BALANCE_EQUATIONS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                  10
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Individual Grids:
   number of vertices       =           9          9          9          9
   number of vertices I own =           9          9          9          9
   number of elements       =           8          8          8          8
   number of leaf elements  =           8          8          8          8
   leaf elements I own      =           8          8          8          8
   number of levels         =           1          1          1          1
   degrees of freedom       =           9          9          9          9
   degrees of freedom I own =           9          9          9          9
   min degree               =           1          1          1          1
   max degree               =           1          1          1          1

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Individual Grids:
   number of vertices       =          29         29         29         29
   number of vertices I own =          29         29         29         29
   number of elements       =          72         72         72         72
   number of leaf elements  =          40         40         40         40
   leaf elements I own      =          40         40         40         40
   number of levels         =           5          5          5          5
   degrees of freedom       =          29         29         29         29
   degrees of freedom I own =          29         29         29         29
   min degree               =           1          1          1          1
   max degree               =           1          1          1          1

Total Grid:
   number of vertices      =          29
   number of leaf elements =          40
   number of levels        =           5
   degrees of freedom      =          29
   min and max degree      =           1          1

Individual Grids:
   number of vertices       =          36         36         36         36
   number of vertices I own =          36         36         36         36
   number of elements       =          88         88         88         88
   number of leaf elements  =          48         48         48         48
   leaf elements I own      =          48         48         48         48
   number of levels         =           6          6          6          6
   degrees of freedom       =          36         36         36         36
   degrees of freedom I own =          36         36         36         36
   min degree               =           1          1          1          1
   max degree               =           1          1          1          1

Total Grid:
   number of vertices      =          36
   number of leaf elements =          48
   number of levels        =           6
   degrees of freedom      =          36
   min and max degree      =           1          1

Individual Grids:
   number of vertices       =          98         98         98         98
   number of vertices I own =          98         98         98         98
   number of elements       =         300        300        300        300
   number of leaf elements  =         154        154        154        154
   leaf elements I own      =         154        154        154        154
   number of levels         =           8          8          8          8
   degrees of freedom       =          98         98         98         98
   degrees of freedom I own =          98         98         98         98
   min degree               =           1          1          1          1
   max degree               =           1          1          1          1

Total Grid:
   number of vertices      =          98
   number of leaf elements =         154
   number of levels        =           8
   degrees of freedom      =          98
   min and max degree      =           1          1

Individual Grids:
   number of vertices       =         167        167        167        167
   number of vertices I own =         167        167        167        167
   number of elements       =         568        568        568        568
   number of leaf elements  =         288        288        288        288
   leaf elements I own      =         288        288        288        288
   number of levels         =           9          9          9          9
   degrees of freedom       =         167        167        167        167
   degrees of freedom I own =         167        167        167        167
   min degree               =           1          1          1          1
   max degree               =           1          1          1          1

Total Grid:
   number of vertices      =         167
   number of leaf elements =         288
   number of levels        =           9
   degrees of freedom      =         167
   min and max degree      =           1          1

Individual Grids:
   number of vertices       =         111        147        136        112
   number of vertices I own =          78         78         79         79
   number of elements       =         372        512        468        376
   number of leaf elements  =         190        260        238        192
   leaf elements I own      =         129        150        132        141
   number of levels         =           9         10         10          9
   degrees of freedom       =         111        147        136        112
   degrees of freedom I own =          78         78         79         79
   min degree               =           1          1          1          1
   max degree               =           1          1          1          1

Total Grid:
   number of vertices      =         314
   number of leaf elements =         552
   number of levels        =          10
   degrees of freedom      =         314
   min and max degree      =           1          1

Individual Grids:
   number of vertices       =         189        243        220        195
   number of vertices I own =         146        146        141        153
   number of elements       =         676        888        800        700
   number of leaf elements  =         342        448        404        354
   leaf elements I own      =         256        292        249        287
   number of levels         =          10         11         11         10
   degrees of freedom       =         189        243        220        195
   degrees of freedom I own =         146        146        141        153
   min degree               =           1          1          1          1
   max degree               =           1          1          1          1

Total Grid:
   number of vertices      =         586
   number of leaf elements =        1084
   number of levels        =          11
   degrees of freedom      =         586
   min and max degree      =           1          1

Individual Grids:
   number of vertices       =         342        440        389        355
   number of vertices I own =         281        300        283        299
   number of elements       =        1248       1644       1446       1300
   number of leaf elements  =         628        826        727        654
   leaf elements I own      =         504        594        513        561
   number of levels         =          11         12         12         11
   degrees of freedom       =         342        440        389        355
   degrees of freedom I own =         281        300        283        299
   min degree               =           1          1          1          1
   max degree               =           1          1          1          1

Total Grid:
   number of vertices      =        1163
   number of leaf elements =        2172
   number of levels        =          12
   degrees of freedom      =        1163
   min and max degree      =           1          1

Individual Grids:
   number of vertices       =         342        440        389        355
   number of vertices I own =         281        300        283        299
   number of elements       =        1248       1644       1446       1300
   number of leaf elements  =         628        826        727        654
   leaf elements I own      =         504        594        513        561
   number of levels         =          11         12         12         11
   degrees of freedom       =         342        440        389        355
   degrees of freedom I own =         281        300        283        299
   min degree               =           1          1          1          1
   max degree               =           1          1          1          1

Total Grid:
   number of vertices      =        1163
   number of leaf elements =        2172
   number of levels        =          12
   degrees of freedom      =        1163
   min and max degree      =           1          1

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           7
termination condition:
  maximum vertices achieved
---------------------------------------------------------
