
My Grid:
   number of vertices       =         654
   number of vertices I own =         654
   number of elements       =        2506
   number of leaf elements  =        1257
   leaf elements I own      =        1257
   number of levels         =          14
   degrees of freedom       =         654
   degrees of freedom I own =         654
   min and max degree       =           1          1

Norms of error:
   energy error estimate      1.6579721538E-02
   Linf error estimate        1.0399257243E-03
time =  1.000000000000E-02

My Grid:
   number of vertices       =         658
   number of vertices I own =         658
   number of elements       =        2522
   number of leaf elements  =        1265
   leaf elements I own      =        1265
   number of levels         =          14
   degrees of freedom       =         658
   degrees of freedom I own =         658
   min and max degree       =           1          1

Norms of error:
   energy error estimate      1.7991694115E-02
   Linf error estimate        9.7143205680E-04
time =  2.000000000000E-02

My Grid:
   number of vertices       =         668
   number of vertices I own =         668
   number of elements       =        2554
   number of leaf elements  =        1281
   leaf elements I own      =        1281
   number of levels         =          14
   degrees of freedom       =         668
   degrees of freedom I own =         668
   min and max degree       =           1          1

Norms of error:
   energy error estimate      1.8477236754E-02
   Linf error estimate        9.9284517220E-04
time =  3.000000000000E-02

My Grid:
   number of vertices       =         669
   number of vertices I own =         669
   number of elements       =        2556
   number of leaf elements  =        1282
   leaf elements I own      =        1282
   number of levels         =          14
   degrees of freedom       =         669
   degrees of freedom I own =         669
   min and max degree       =           1          1

Norms of error:
   energy error estimate      1.9303111989E-02
   Linf error estimate        1.0881424425E-03
time =  4.000000000000E-02

My Grid:
   number of vertices       =         673
   number of vertices I own =         673
   number of elements       =        2572
   number of leaf elements  =        1290
   leaf elements I own      =        1290
   number of levels         =          14
   degrees of freedom       =         673
   degrees of freedom I own =         673
   min and max degree       =           1          1

Norms of error:
   energy error estimate      1.9426842880E-02
   Linf error estimate        8.3289904878E-04
time =  5.000000000000E-02
