---------------------------------------------------------
           PHAML   Version 1.11.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                    500
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    21
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    SLAVES
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  ENERGY_LINF_L2_ERREST
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EQUILIBRATED_RESIDUAL
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                   5
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

Norms of error:
   energy norm of error       4.0333158308E+00
   energy error estimate      6.4269376842E+00
      effectivity             1.5934625390E+00
   Linf norm of error         1.0536246503E+00
   Linf error estimate        2.6992192949E+00
      effectivity             2.5618414433E+00
   L2 norm of error           4.5345860840E-01
   L2 error estimate          1.6852937196E+00
      effectivity             3.7165326414E+00

My Grid:
   number of vertices       =          21
   number of vertices I own =          21
   number of elements       =          48
   number of leaf elements  =          28
   leaf elements I own      =          28
   number of levels         =           4
   degrees of freedom       =          21
   degrees of freedom I own =          21
   min and max degree       =           1          1

Norms of error:
   energy norm of error       3.2340348066E+00
      reduced by              8.0183029107E-01
   energy error estimate      3.6617038671E+00
      reduced by              5.6974317273E-01
      effectivity             1.1322400921E+00
   Linf norm of error         6.6378510206E-01
      reduced by              6.3000149234E-01
   Linf error estimate        1.0421523223E+00
      reduced by              3.8609398070E-01
      effectivity             1.5700146314E+00
   L2 norm of error           2.3798939042E-01
      reduced by              5.2483156348E-01
   L2 error estimate          3.5543086359E-01
      reduced by              2.1090143483E-01
      effectivity             1.4934735660E+00

My Grid:
   number of vertices       =          49
   number of vertices I own =          49
   number of elements       =         140
   number of leaf elements  =          74
   leaf elements I own      =          74
   number of levels         =           6
   degrees of freedom       =          49
   degrees of freedom I own =          49
   min and max degree       =           1          1

Norms of error:
   energy norm of error       2.4118252651E+00
      reduced by              7.4576354595E-01
   energy error estimate      3.0903602083E+00
      reduced by              8.4396781403E-01
      effectivity             1.2813366926E+00
   Linf norm of error         4.7081845371E-01
      reduced by              7.0929349310E-01
   Linf error estimate        6.4899585039E-01
      reduced by              6.2274567401E-01
      effectivity             1.3784418289E+00
   L2 norm of error           9.8439691691E-02
      reduced by              4.1363058881E-01
   L2 error estimate          1.4761518655E-01
      reduced by              4.1531336098E-01
      effectivity             1.4995494604E+00

My Grid:
   number of vertices       =          72
   number of vertices I own =          72
   number of elements       =         220
   number of leaf elements  =         114
   leaf elements I own      =         114
   number of levels         =           7
   degrees of freedom       =          72
   degrees of freedom I own =          72
   min and max degree       =           1          1

Norms of error:
   energy norm of error       1.6680031954E+00
      reduced by              6.9159371516E-01
   energy error estimate      2.0923646804E+00
      reduced by              6.7706174663E-01
      effectivity             1.2544128729E+00
   Linf norm of error         3.3135792323E-01
      reduced by              7.0379128224E-01
   Linf error estimate        3.1235675432E-01
      reduced by              4.8129237519E-01
      effectivity             9.4265666344E-01
   L2 norm of error           5.0157918598E-02
      reduced by              5.0952941580E-01
   L2 error estimate          6.4126256091E-02
      reduced by              4.3441503269E-01
      effectivity             1.2784871837E+00

My Grid:
   number of vertices       =         167
   number of vertices I own =         167
   number of elements       =         532
   number of leaf elements  =         270
   leaf elements I own      =         270
   number of levels         =           9
   degrees of freedom       =         167
   degrees of freedom I own =         167
   min and max degree       =           1          1

Norms of error:
   energy norm of error       9.1152903106E-01
      reduced by              5.4647918756E-01
   energy error estimate      1.1502612653E+00
      reduced by              5.4974224909E-01
      effectivity             1.2619030509E+00
   Linf norm of error         1.1718735117E-01
      reduced by              3.5365791174E-01
   Linf error estimate        1.2466592413E-01
      reduced by              3.9911390553E-01
      effectivity             1.0638172370E+00
   L2 norm of error           1.5998727486E-02
      reduced by              3.1896713287E-01
   L2 error estimate          2.2439007845E-02
      reduced by              3.4991919399E-01
      effectivity             1.4025495380E+00

My Grid:
   number of vertices       =         330
   number of vertices I own =         330
   number of elements       =        1152
   number of leaf elements  =         580
   leaf elements I own      =         580
   number of levels         =          11
   degrees of freedom       =         330
   degrees of freedom I own =         330
   min and max degree       =           1          1

Norms of error:
   energy norm of error       7.1923817148E-01
      reduced by              7.8904581968E-01
   energy error estimate      1.0565759572E+00
      reduced by              9.1855301837E-01
      effectivity             1.4690209712E+00
   Linf norm of error         3.8775744361E-02
      reduced by              3.3088677211E-01
   Linf error estimate        4.1017092162E-02
      reduced by              3.2901606792E-01
      effectivity             1.0578028311E+00
   L2 norm of error           8.8816065689E-03
      reduced by              5.5514456238E-01
   L2 error estimate          1.4060285998E-02
      reduced by              6.2660016409E-01
      effectivity             1.5830791297E+00

My Grid:
   number of vertices       =         553
   number of vertices I own =         553
   number of elements       =        2020
   number of leaf elements  =        1014
   leaf elements I own      =        1014
   number of levels         =          11
   degrees of freedom       =         553
   degrees of freedom I own =         553
   min and max degree       =           1          1

Norms of error:
   energy norm of error       4.9948768317E-01
      reduced by              6.9446770621E-01
   energy error estimate      6.3733915595E-01
      reduced by              6.0321186719E-01
      effectivity             1.2759857298E+00
   Linf norm of error         3.8927706099E-02
      reduced by              1.0039189896E+00
   Linf error estimate        3.6513705685E-02
      reduced by              8.9020707613E-01
      effectivity             9.3798760174E-01
   L2 norm of error           6.1204783491E-03
      reduced by              6.8911838209E-01
   L2 error estimate          9.2891905978E-03
      reduced by              6.6066868052E-01
      effectivity             1.5177229733E+00

My Grid:
   number of vertices       =         553
   number of vertices I own =         553
   number of elements       =        2020
   number of leaf elements  =        1014
   leaf elements I own      =        1014
   number of levels         =          11
   degrees of freedom       =         553
   degrees of freedom I own =         553
   min and max degree       =           1          1

Norms of error:
   energy norm of error       4.9948768317E-01
   energy error estimate      6.3733915595E-01
      effectivity             1.2759857298E+00
   Linf norm of error         3.8927706099E-02
   Linf error estimate        3.6513705685E-02
      effectivity             9.3798760174E-01
   L2 norm of error           6.1204783491E-03
   L2 error estimate          9.2891905978E-03
      effectivity             1.5177229733E+00

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum equations achieved
---------------------------------------------------------
