---------------------------------------------------------
           PHAML   Version 1.11.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                    500
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    21
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  ENERGY_LINF_L2_ERREST
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EQUILIBRATED_RESIDUAL
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                   5
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Norms of error:
   energy norm of error       4.0333158308E+00
   energy error estimate      6.4269376842E+00
      effectivity             1.5934625390E+00
   Linf norm of error         1.0536246503E+00
   Linf error estimate        2.6992192949E+00
      effectivity             2.5618414433E+00
   L2 norm of error           4.5345860840E-01
   L2 error estimate          1.6852937196E+00
      effectivity             3.7165326414E+00

Total Grid:
   number of vertices      =          21
   number of leaf elements =          28
   number of levels        =           4
   degrees of freedom      =          21
   min and max degree      =           1          1

Norms of error:
   energy norm of error       3.2340348066E+00
      reduced by              8.0183029107E-01
   energy error estimate      3.6617038671E+00
      reduced by              5.6974317273E-01
      effectivity             1.1322400921E+00
   Linf norm of error         6.6378510206E-01
      reduced by              6.3000149234E-01
   Linf error estimate        1.0421523223E+00
      reduced by              3.8609398070E-01
      effectivity             1.5700146314E+00
   L2 norm of error           2.3798939042E-01
      reduced by              5.2483156348E-01
   L2 error estimate          3.5543086359E-01
      reduced by              2.1090143483E-01
      effectivity             1.4934735660E+00

Total Grid:
   number of vertices      =          49
   number of leaf elements =          74
   number of levels        =           6
   degrees of freedom      =          49
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.4118252651E+00
      reduced by              7.4576354595E-01
   energy error estimate      3.0903602083E+00
      reduced by              8.4396781403E-01
      effectivity             1.2813366926E+00
   Linf norm of error         4.7081845371E-01
      reduced by              7.0929349310E-01
   Linf error estimate        6.4899585039E-01
      reduced by              6.2274567401E-01
      effectivity             1.3784418289E+00
   L2 norm of error           9.8439691691E-02
      reduced by              4.1363058881E-01
   L2 error estimate          1.4761518655E-01
      reduced by              4.1531336098E-01
      effectivity             1.4995494604E+00

Total Grid:
   number of vertices      =          72
   number of leaf elements =         114
   number of levels        =           7
   degrees of freedom      =          72
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.6680031954E+00
      reduced by              6.9159371516E-01
   energy error estimate      2.0923646804E+00
      reduced by              6.7706174663E-01
      effectivity             1.2544128729E+00
   Linf norm of error         3.3135792323E-01
      reduced by              7.0379128224E-01
   Linf error estimate        3.1235675432E-01
      reduced by              4.8129237519E-01
      effectivity             9.4265666344E-01
   L2 norm of error           5.0157918598E-02
      reduced by              5.0952941580E-01
   L2 error estimate          6.4126256091E-02
      reduced by              4.3441503269E-01
      effectivity             1.2784871837E+00

Total Grid:
   number of vertices      =         167
   number of leaf elements =         270
   number of levels        =           9
   degrees of freedom      =         167
   min and max degree      =           1          1

Norms of error:
   energy norm of error       9.1152903106E-01
      reduced by              5.4647918756E-01
   energy error estimate      1.1502612653E+00
      reduced by              5.4974224909E-01
      effectivity             1.2619030509E+00
   Linf norm of error         1.1718735117E-01
      reduced by              3.5365791174E-01
   Linf error estimate        1.2466592413E-01
      reduced by              3.9911390553E-01
      effectivity             1.0638172370E+00
   L2 norm of error           1.5998727486E-02
      reduced by              3.1896713287E-01
   L2 error estimate          2.2439007845E-02
      reduced by              3.4991919399E-01
      effectivity             1.4025495380E+00

Total Grid:
   number of vertices      =         330
   number of leaf elements =         580
   number of levels        =          11
   degrees of freedom      =         330
   min and max degree      =           1          1

Norms of error:
   energy norm of error       7.1897958279E-01
      reduced by              3.9438106648E-01
   energy error estimate      1.0497098359E+00
      reduced by              4.5629191711E-01
      effectivity             1.4599995062E+00
   Linf norm of error         3.8775167038E-02
      reduced by              3.3088184562E-01
   Linf error estimate        4.4119325207E-02
      reduced by              3.5390043841E-01
      effectivity             1.1378242462E+00
   L2 norm of error           8.9361799651E-03
      reduced by              2.7927783547E-01
   L2 error estimate          1.4154044438E-02
      reduced by              3.1538926623E-01
      effectivity             1.5839032443E+00

Total Grid:
   number of vertices      =         603
   number of leaf elements =        1070
   number of levels        =          11
   degrees of freedom      =         603
   min and max degree      =           1          1

Norms of error:
   energy norm of error       4.9615573908E-01
      reduced by              6.9008321092E-01
   energy error estimate      6.3199055470E-01
      reduced by              6.0206214433E-01
      effectivity             1.2737745529E+00
   Linf norm of error         3.8866875292E-02
      reduced by              1.0023651285E+00
   Linf error estimate        3.5247048127E-02
      reduced by              7.9890270221E-01
      effectivity             9.0686601025E-01
   L2 norm of error           5.8230580509E-03
      reduced by              6.5162721360E-01
   L2 error estimate          8.9881168081E-03
      reduced by              6.3502109572E-01
      effectivity             1.5435389326E+00

Total Grid:
   number of vertices      =         603
   number of leaf elements =        1070
   number of levels        =          11
   degrees of freedom      =         603
   min and max degree      =           1          1

Norms of error:
   energy norm of error       4.9615573908E-01
   energy error estimate      6.3199055470E-01
      effectivity             1.2737745529E+00
   Linf norm of error         3.8866875292E-02
   Linf error estimate        3.5247048127E-02
      effectivity             9.0686601025E-01
   L2 norm of error           5.8230580509E-03
   L2 error estimate          8.9881168081E-03
      effectivity             1.5435389326E+00

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum equations achieved
---------------------------------------------------------
