---------------------------------------------------------
           PHAML   Version 1.11.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                   1000
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  ENERGY_LINF_L2_ERREST
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    LOCAL_PROBLEM_H
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Norms of error:
   energy norm of error       4.0333158308E+00
   energy error estimate      2.2483194801E+00
      effectivity             5.5743700082E-01
   Linf norm of error         1.0536246503E+00
   Linf error estimate        6.8623959248E-01
      effectivity             6.5131315244E-01
   L2 norm of error           4.5345860840E-01
   L2 error estimate          3.9745048765E-01
      effectivity             8.7648680671E-01

Total Grid:
   number of vertices      =          21
   number of leaf elements =          28
   number of levels        =           5
   degrees of freedom      =          21
   min and max degree      =           1          1

Norms of error:
   energy norm of error       3.3114334195E+00
      reduced by              8.2102011309E-01
   energy error estimate      2.0947406984E+00
      reduced by              9.3169174445E-01
      effectivity             6.3257823217E-01
   Linf norm of error         6.0874900713E-01
      reduced by              5.7776648160E-01
   Linf error estimate        4.9682926490E-01
      reduced by              7.2398805074E-01
      effectivity             8.1614796752E-01
   L2 norm of error           2.2277027430E-01
      reduced by              4.9126925847E-01
   L2 error estimate          2.1130198865E-01
      reduced by              5.3164355111E-01
      effectivity             9.4851967711E-01

Total Grid:
   number of vertices      =          38
   number of leaf elements =          56
   number of levels        =           6
   degrees of freedom      =          38
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.3960937972E+00
      reduced by              7.2358205454E-01
   energy error estimate      1.3163894986E+00
      reduced by              6.2842599064E-01
      effectivity             5.4938980274E-01
   Linf norm of error         3.2885771006E-01
      reduced by              5.4021888530E-01
   Linf error estimate        2.5954558950E-01
      reduced by              5.2240398832E-01
      effectivity             7.8923370673E-01
   L2 norm of error           9.0396143241E-02
      reduced by              4.0578189135E-01
   L2 error estimate          5.7788131518E-02
      reduced by              2.7348598036E-01
      effectivity             6.3927651607E-01

Total Grid:
   number of vertices      =          75
   number of leaf elements =         120
   number of levels        =           8
   degrees of freedom      =          75
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.5026720905E+00
      reduced by              6.2713408479E-01
   energy error estimate      9.2413671425E-01
      reduced by              7.0202376672E-01
      effectivity             6.1499559356E-01
   Linf norm of error         2.3809964604E-01
      reduced by              7.2402026394E-01
   Linf error estimate        1.6166605298E-01
      reduced by              6.2288114121E-01
      effectivity             6.7898485223E-01
   L2 norm of error           3.4743030367E-02
      reduced by              3.8434195443E-01
   L2 error estimate          2.5250217279E-02
      reduced by              4.3694469116E-01
      effectivity             7.2677072243E-01

Total Grid:
   number of vertices      =         148
   number of leaf elements =         248
   number of levels        =          10
   degrees of freedom      =         148
   min and max degree      =           1          1

Norms of error:
   energy norm of error       9.5657732770E-01
      reduced by              6.3658421136E-01
   energy error estimate      7.5806519523E-01
      reduced by              8.2029550773E-01
      effectivity             7.9247664907E-01
   Linf norm of error         9.2064734639E-02
      reduced by              3.8666472702E-01
   Linf error estimate        7.8483094830E-02
      reduced by              4.8546428506E-01
      effectivity             8.5247728284E-01
   L2 norm of error           1.5326114805E-02
      reduced by              4.4112774976E-01
   L2 error estimate          1.2823315989E-02
      reduced by              5.0784972848E-01
      effectivity             8.3669711157E-01

Total Grid:
   number of vertices      =         302
   number of leaf elements =         530
   number of levels        =          11
   degrees of freedom      =         302
   min and max degree      =           1          1

Norms of error:
   energy norm of error       7.3965758373E-01
      reduced by              3.8661672314E-01
   energy error estimate      5.8013454106E-01
      reduced by              3.8264158855E-01
      effectivity             7.8432852420E-01
   Linf norm of error         4.3014263272E-02
      reduced by              4.6721758815E-01
   Linf error estimate        3.5161786351E-02
      reduced by              4.4801732688E-01
      effectivity             8.1744481195E-01
   L2 norm of error           9.9751075804E-03
      reduced by              3.2542845030E-01
   L2 error estimate          8.3031969605E-03
      reduced by              3.2375389359E-01
      effectivity             8.3239172045E-01

Total Grid:
   number of vertices      =         594
   number of leaf elements =        1098
   number of levels        =          12
   degrees of freedom      =         594
   min and max degree      =           1          1

Norms of error:
   energy norm of error       4.4832019035E-01
      reduced by              6.0611856109E-01
   energy error estimate      2.5435757011E-01
      reduced by              4.3844582956E-01
      effectivity             5.6735693726E-01
   Linf norm of error         2.7104891666E-02
      reduced by              6.3013729875E-01
   Linf error estimate        1.5605442963E-02
      reduced by              4.4381826358E-01
      effectivity             5.7574267978E-01
   L2 norm of error           4.1096957957E-03
      reduced by              4.1199513515E-01
   L2 error estimate          3.0525587823E-03
      reduced by              3.6763656177E-01
      effectivity             7.4277000878E-01

Total Grid:
   number of vertices      =        1099
   number of leaf elements =        2040
   number of levels        =          14
   degrees of freedom      =        1099
   min and max degree      =           1          1

Norms of error:
   energy norm of error       3.3926976857E-01
      reduced by              7.5675772778E-01
   energy error estimate      2.3601631580E-01
      reduced by              9.2789184806E-01
      effectivity             6.9565973058E-01
   Linf norm of error         9.7371349756E-03
      reduced by              3.5923902946E-01
   Linf error estimate        9.0239206850E-03
      reduced by              5.7825469656E-01
      effectivity             9.2675316791E-01
   L2 norm of error           2.4487449920E-03
      reduced by              5.9584580313E-01
   L2 error estimate          1.8657057671E-03
      reduced by              6.1119405070E-01
      effectivity             7.6190284134E-01

Total Grid:
   number of vertices      =        1099
   number of leaf elements =        2040
   number of levels        =          14
   degrees of freedom      =        1099
   min and max degree      =           1          1

Norms of error:
   energy norm of error       3.3926976857E-01
   energy error estimate      2.3601631580E-01
      effectivity             6.9565973058E-01
   Linf norm of error         9.7371349756E-03
   Linf error estimate        9.0239206850E-03
      effectivity             9.2675316791E-01
   L2 norm of error           2.4487449920E-03
   L2 error estimate          1.8657057671E-03
      effectivity             7.6190284134E-01

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           7
termination condition:
  maximum equations achieved
---------------------------------------------------------
