---------------------------------------------------------
           PHAML   Version 1.11.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                   1000
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    SLAVES
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  ENERGY_LINF_L2_ERREST
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    LOCAL_PROBLEM_H
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

Norms of error:
   energy norm of error       4.0333158308E+00
   energy error estimate      2.2483194801E+00
      effectivity             5.5743700082E-01
   Linf norm of error         1.0536246503E+00
   Linf error estimate        6.8623959248E-01
      effectivity             6.5131315244E-01
   L2 norm of error           4.5345860840E-01
   L2 error estimate          3.9745048765E-01
      effectivity             8.7648680671E-01

My Grid:
   number of vertices       =          21
   number of vertices I own =          21
   number of elements       =          48
   number of leaf elements  =          28
   leaf elements I own      =          28
   number of levels         =           5
   degrees of freedom       =          21
   degrees of freedom I own =          21
   min and max degree       =           1          1

Norms of error:
   energy norm of error       3.3114334195E+00
      reduced by              8.2102011309E-01
   energy error estimate      2.0947406984E+00
      reduced by              9.3169174445E-01
      effectivity             6.3257823217E-01
   Linf norm of error         6.0874900713E-01
      reduced by              5.7776648160E-01
   Linf error estimate        4.9682926490E-01
      reduced by              7.2398805074E-01
      effectivity             8.1614796752E-01
   L2 norm of error           2.2277027430E-01
      reduced by              4.9126925847E-01
   L2 error estimate          2.1130198865E-01
      reduced by              5.3164355111E-01
      effectivity             9.4851967711E-01

My Grid:
   number of vertices       =          38
   number of vertices I own =          38
   number of elements       =         104
   number of leaf elements  =          56
   leaf elements I own      =          56
   number of levels         =           6
   degrees of freedom       =          38
   degrees of freedom I own =          38
   min and max degree       =           1          1

Norms of error:
   energy norm of error       2.3960937972E+00
      reduced by              7.2358205454E-01
   energy error estimate      1.3163894986E+00
      reduced by              6.2842599064E-01
      effectivity             5.4938980274E-01
   Linf norm of error         3.2885771006E-01
      reduced by              5.4021888530E-01
   Linf error estimate        2.5954558950E-01
      reduced by              5.2240398832E-01
      effectivity             7.8923370673E-01
   L2 norm of error           9.0396143241E-02
      reduced by              4.0578189135E-01
   L2 error estimate          5.7788131518E-02
      reduced by              2.7348598036E-01
      effectivity             6.3927651607E-01

My Grid:
   number of vertices       =          75
   number of vertices I own =          75
   number of elements       =         232
   number of leaf elements  =         120
   leaf elements I own      =         120
   number of levels         =           8
   degrees of freedom       =          75
   degrees of freedom I own =          75
   min and max degree       =           1          1

Norms of error:
   energy norm of error       1.5026720905E+00
      reduced by              6.2713408479E-01
   energy error estimate      9.2413671425E-01
      reduced by              7.0202376672E-01
      effectivity             6.1499559356E-01
   Linf norm of error         2.3809964604E-01
      reduced by              7.2402026394E-01
   Linf error estimate        1.6166605298E-01
      reduced by              6.2288114121E-01
      effectivity             6.7898485223E-01
   L2 norm of error           3.4743030367E-02
      reduced by              3.8434195443E-01
   L2 error estimate          2.5250217279E-02
      reduced by              4.3694469116E-01
      effectivity             7.2677072243E-01

My Grid:
   number of vertices       =         148
   number of vertices I own =         148
   number of elements       =         488
   number of leaf elements  =         248
   leaf elements I own      =         248
   number of levels         =          10
   degrees of freedom       =         148
   degrees of freedom I own =         148
   min and max degree       =           1          1

Norms of error:
   energy norm of error       9.5657732770E-01
      reduced by              6.3658421136E-01
   energy error estimate      7.5806519523E-01
      reduced by              8.2029550773E-01
      effectivity             7.9247664907E-01
   Linf norm of error         9.2064734639E-02
      reduced by              3.8666472702E-01
   Linf error estimate        7.8483094830E-02
      reduced by              4.8546428506E-01
      effectivity             8.5247728284E-01
   L2 norm of error           1.5326114805E-02
      reduced by              4.4112774976E-01
   L2 error estimate          1.2823315989E-02
      reduced by              5.0784972848E-01
      effectivity             8.3669711157E-01

My Grid:
   number of vertices       =         308
   number of vertices I own =         308
   number of elements       =        1076
   number of leaf elements  =         542
   leaf elements I own      =         542
   number of levels         =          11
   degrees of freedom       =         308
   degrees of freedom I own =         308
   min and max degree       =           1          1

Norms of error:
   energy norm of error       7.2783033655E-01
      reduced by              7.6086931550E-01
   energy error estimate      5.6244473173E-01
      reduced by              7.4194770485E-01
      effectivity             7.7276901426E-01
   Linf norm of error         3.7578379426E-02
      reduced by              4.0817343984E-01
   Linf error estimate        3.5161786351E-02
      reduced by              4.4801732688E-01
      effectivity             9.3569192946E-01
   L2 norm of error           9.7067404317E-03
      reduced by              6.3334645179E-01
   L2 error estimate          7.8798601065E-03
      reduced by              6.1449473078E-01
      effectivity             8.1179260556E-01

My Grid:
   number of vertices       =         592
   number of vertices I own =         592
   number of elements       =        2180
   number of leaf elements  =        1094
   leaf elements I own      =        1094
   number of levels         =          12
   degrees of freedom       =         592
   degrees of freedom I own =         592
   min and max degree       =           1          1

Norms of error:
   energy norm of error       4.4630332215E-01
      reduced by              6.1319692206E-01
   energy error estimate      2.6476244486E-01
      reduced by              4.7073504279E-01
      effectivity             5.9323431334E-01
   Linf norm of error         2.2761924739E-02
      reduced by              6.0571863628E-01
   Linf error estimate        1.3857892509E-02
      reduced by              3.9411798851E-01
      effectivity             6.0881901103E-01
   L2 norm of error           3.8438828841E-03
      reduced by              3.9600140862E-01
   L2 error estimate          2.6305717646E-03
      reduced by              3.3383483070E-01
      effectivity             6.8435273496E-01

My Grid:
   number of vertices       =        1004
   number of vertices I own =        1004
   number of elements       =        3692
   number of leaf elements  =        1850
   leaf elements I own      =        1850
   number of levels         =          13
   degrees of freedom       =        1004
   degrees of freedom I own =        1004
   min and max degree       =           1          1

Norms of error:
   energy norm of error       3.4712536780E-01
      reduced by              7.7777903630E-01
   energy error estimate      2.0394556223E-01
      reduced by              7.7029641551E-01
      effectivity             5.8752710448E-01
   Linf norm of error         1.1037615117E-02
      reduced by              4.8491571971E-01
   Linf error estimate        6.6615261380E-03
      reduced by              4.8070268503E-01
      effectivity             6.0352948236E-01
   L2 norm of error           2.7505809197E-03
      reduced by              7.1557354962E-01
   L2 error estimate          1.9438548636E-03
      reduced by              7.3894766522E-01
      effectivity             7.0670702677E-01

My Grid:
   number of vertices       =        1004
   number of vertices I own =        1004
   number of elements       =        3692
   number of leaf elements  =        1850
   leaf elements I own      =        1850
   number of levels         =          13
   degrees of freedom       =        1004
   degrees of freedom I own =        1004
   min and max degree       =           1          1

Norms of error:
   energy norm of error       3.4712536780E-01
   energy error estimate      2.0394556223E-01
      effectivity             5.8752710448E-01
   Linf norm of error         1.1037615117E-02
   Linf error estimate        6.6615261380E-03
      effectivity             6.0352948236E-01
   L2 norm of error           2.7505809197E-03
   L2 error estimate          1.9438548636E-03
      effectivity             7.0670702677E-01

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           7
termination condition:
  maximum equations achieved
---------------------------------------------------------
