---------------------------------------------------------
           PHAML   Version 1.11.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                    500
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    21
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  ENERGY_LINF_L2_ERREST
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    LOCAL_PROBLEM_P
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                   5
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Norms of error:
   energy norm of error       4.0333158308E+00
   energy error estimate      5.3069652709E+00
      effectivity             1.3157822233E+00
   Linf norm of error         1.0536246503E+00
   Linf error estimate        1.4604995752E+00
      effectivity             1.3861668620E+00
   L2 norm of error           4.5345860840E-01
   L2 error estimate          1.0196667538E+00
      effectivity             2.2486435033E+00

Total Grid:
   number of vertices      =          29
   number of leaf elements =          40
   number of levels        =           5
   degrees of freedom      =          29
   min and max degree      =           1          1

Norms of error:
   energy norm of error       3.0143054217E+00
      reduced by              7.4735169478E-01
   energy error estimate      3.7727450909E+00
      reduced by              7.1090442434E-01
      effectivity             1.2516134111E+00
   Linf norm of error         5.2342002897E-01
      reduced by              4.9678035609E-01
   Linf error estimate        6.4194047687E-01
      reduced by              4.3953486038E-01
      effectivity             1.2264346822E+00
   L2 norm of error           1.6018458492E-01
      reduced by              3.5325073104E-01
   L2 error estimate          2.6265146329E-01
      reduced by              2.5758559088E-01
      effectivity             1.6396800193E+00

Total Grid:
   number of vertices      =          40
   number of leaf elements =          56
   number of levels        =           6
   degrees of freedom      =          40
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.7575962042E+00
      reduced by              9.1483636142E-01
   energy error estimate      3.5536475912E+00
      reduced by              9.4192623822E-01
      effectivity             1.2886758351E+00
   Linf norm of error         4.7526933682E-01
      reduced by              9.0800754751E-01
   Linf error estimate        5.8676983501E-01
      reduced by              9.1405645251E-01
      effectivity             1.2346048641E+00
   L2 norm of error           1.4348291702E-01
      reduced by              8.9573486175E-01
   L2 error estimate          2.2733030687E-01
      reduced by              8.6552080854E-01
      effectivity             1.5843719349E+00

Total Grid:
   number of vertices      =         110
   number of leaf elements =         178
   number of levels        =           8
   degrees of freedom      =         110
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.8203121359E+00
      reduced by              6.6010829764E-01
   energy error estimate      2.8405819445E+00
      reduced by              7.9934261110E-01
      effectivity             1.5604916808E+00
   Linf norm of error         2.5454057492E-01
      reduced by              5.3557121236E-01
   Linf error estimate        3.4959463972E-01
      reduced by              5.9579518043E-01
      effectivity             1.3734338419E+00
   L2 norm of error           5.3472595002E-02
      reduced by              3.7267568928E-01
   L2 error estimate          1.1498978529E-01
      reduced by              5.0582690390E-01
      effectivity             2.1504433305E+00

Total Grid:
   number of vertices      =         163
   number of leaf elements =         284
   number of levels        =           9
   degrees of freedom      =         163
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.2831961983E+00
      reduced by              3.5246597903E-01
   energy error estimate      2.3296355208E+00
      reduced by              4.1006307270E-01
      effectivity             1.8154944068E+00
   Linf norm of error         2.5246220063E-01
      reduced by              9.9183480165E-01
   Linf error estimate        2.1870962553E-01
      reduced by              6.2560920757E-01
      effectivity             8.6630642123E-01
   L2 norm of error           2.7523651421E-02
      reduced by              2.5736221909E-01
   L2 error estimate          6.5447132933E-02
      reduced by              2.8457802913E-01
      effectivity             2.3778506686E+00

Total Grid:
   number of vertices      =         337
   number of leaf elements =         596
   number of levels        =          11
   degrees of freedom      =         337
   min and max degree      =           1          1

Norms of error:
   energy norm of error       7.5452671323E-01
      reduced by              5.8800572683E-01
   energy error estimate      1.7057210329E+00
      reduced by              7.3218364747E-01
      effectivity             2.2606502898E+00
   Linf norm of error         3.7064823221E-02
      reduced by              1.4681335712E-01
   Linf error estimate        1.0578642958E-01
      reduced by              4.8368437979E-01
      effectivity             2.8540923815E+00
   L2 norm of error           9.3870395334E-03
      reduced by              3.4105356843E-01
   L2 error estimate          3.2839908309E-02
      reduced by              5.0177764612E-01
      effectivity             3.4984308090E+00

Total Grid:
   number of vertices      =         644
   number of leaf elements =        1204
   number of levels        =          12
   degrees of freedom      =         644
   min and max degree      =           1          1

Norms of error:
   energy norm of error       6.0245139584E-01
      reduced by              7.9844939255E-01
   energy error estimate      1.2038678017E+00
      reduced by              7.0578235156E-01
      effectivity             1.9982820357E+00
   Linf norm of error         3.1277160559E-02
      reduced by              8.4385025587E-01
   Linf error estimate        5.1854944764E-02
      reduced by              4.9018522481E-01
      effectivity             1.6579172737E+00
   L2 norm of error           5.4482745438E-03
      reduced by              5.8040392015E-01
   L2 error estimate          1.5510888735E-02
      reduced by              4.7231827169E-01
      effectivity             2.8469359630E+00

Total Grid:
   number of vertices      =         644
   number of leaf elements =        1204
   number of levels        =          12
   degrees of freedom      =         644
   min and max degree      =           1          1

Norms of error:
   energy norm of error       6.0245139584E-01
   energy error estimate      1.2038678017E+00
      effectivity             1.9982820357E+00
   Linf norm of error         3.1277160559E-02
   Linf error estimate        5.1854944764E-02
      effectivity             1.6579172737E+00
   L2 norm of error           5.4482745438E-03
   L2 error estimate          1.5510888735E-02
      effectivity             2.8469359630E+00

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum equations achieved
---------------------------------------------------------
