---------------------------------------------------------
           PHAML   Version 1.11.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                    500
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            HALVE_ERREST
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                   5
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

My Grid:
   number of vertices       =          12
   number of vertices I own =          12
   number of elements       =          20
   number of leaf elements  =          14
   leaf elements I own      =          14
   number of levels         =           2
   degrees of freedom       =          12
   degrees of freedom I own =          12
   min and max degree       =           1          1

My Grid:
   number of vertices       =          16
   number of vertices I own =          16
   number of elements       =          28
   number of leaf elements  =          18
   leaf elements I own      =          18
   number of levels         =           3
   degrees of freedom       =          16
   degrees of freedom I own =          16
   min and max degree       =           1          1

My Grid:
   number of vertices       =          29
   number of vertices I own =          29
   number of elements       =          72
   number of leaf elements  =          40
   leaf elements I own      =          40
   number of levels         =           5
   degrees of freedom       =          29
   degrees of freedom I own =          29
   min and max degree       =           1          1

My Grid:
   number of vertices       =          60
   number of vertices I own =          60
   number of elements       =         176
   number of leaf elements  =          92
   leaf elements I own      =          92
   number of levels         =           7
   degrees of freedom       =          60
   degrees of freedom I own =          60
   min and max degree       =           1          1

My Grid:
   number of vertices       =         123
   number of vertices I own =         123
   number of elements       =         392
   number of leaf elements  =         200
   leaf elements I own      =         200
   number of levels         =           9
   degrees of freedom       =         123
   degrees of freedom I own =         123
   min and max degree       =           1          1

My Grid:
   number of vertices       =         293
   number of vertices I own =         293
   number of elements       =        1008
   number of leaf elements  =         508
   leaf elements I own      =         508
   number of levels         =          10
   degrees of freedom       =         293
   degrees of freedom I own =         293
   min and max degree       =           1          1

My Grid:
   number of vertices       =         582
   number of vertices I own =         582
   number of elements       =        2036
   number of leaf elements  =        1022
   leaf elements I own      =        1022
   number of levels         =          12
   degrees of freedom       =         582
   degrees of freedom I own =         582
   min and max degree       =           1          1

My Grid:
   number of vertices       =         582
   number of vertices I own =         582
   number of elements       =        2036
   number of leaf elements  =        1022
   leaf elements I own      =        1022
   number of levels         =          12
   degrees of freedom       =         582
   degrees of freedom I own =         582
   min and max degree       =           1          1

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           7
termination condition:
  maximum equations achieved
---------------------------------------------------------
