---------------------------------------------------------
           PHAML   Version 1.11.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                    500
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    SLAVES
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  ENERGY_LINF_L2_ERREST
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    HIERARCHICAL_COEFFICIENT
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                   5
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

Norms of error:
   energy norm of error       4.0333158308E+00
   energy error estimate      1.4163714038E+00
      effectivity             3.5116798764E-01
   Linf norm of error         1.0536246503E+00
   Linf error estimate        8.5463149069E-01
      effectivity             8.1113467727E-01
   L2 norm of error           4.5345860840E-01
   L2 error estimate          1.6692097072E-01
      effectivity             3.6810630039E-01

My Grid:
   number of vertices       =          20
   number of vertices I own =          20
   number of elements       =          48
   number of leaf elements  =          28
   leaf elements I own      =          28
   number of levels         =           4
   degrees of freedom       =          20
   degrees of freedom I own =          20
   min and max degree       =           1          1

Norms of error:
   energy norm of error       3.2457894616E+00
      reduced by              8.0474468100E-01
   energy error estimate      2.2972100878E+00
      reduced by              1.6218980993E+00
      effectivity             7.0775079990E-01
   Linf norm of error         6.7766302055E-01
      reduced by              6.4317308859E-01
   Linf error estimate        6.2590704374E-01
      reduced by              7.3237067738E-01
      effectivity             9.2362579152E-01
   L2 norm of error           2.4227317665E-01
      reduced by              5.3427848135E-01
   L2 error estimate          1.4443786008E-01
      reduced by              8.6530685423E-01
      effectivity             5.9617767873E-01

My Grid:
   number of vertices       =          42
   number of vertices I own =          42
   number of elements       =         124
   number of leaf elements  =          66
   leaf elements I own      =          66
   number of levels         =           6
   degrees of freedom       =          42
   degrees of freedom I own =          42
   min and max degree       =           1          1

Norms of error:
   energy norm of error       2.7568619830E+00
      reduced by              8.4936562139E-01
   energy error estimate      2.0585977394E+00
      reduced by              8.9612950525E-01
      effectivity             7.4671773637E-01
   Linf norm of error         4.7525260949E-01
      reduced by              7.0131111640E-01
   Linf error estimate        4.2704419158E-01
      reduced by              6.8228053327E-01
      effectivity             8.9856253928E-01
   L2 norm of error           1.4319731141E-01
      reduced by              5.9105722470E-01
   L2 error estimate          7.5146672831E-02
      reduced by              5.2026991255E-01
      effectivity             5.2477712109E-01

My Grid:
   number of vertices       =          88
   number of vertices I own =          88
   number of elements       =         288
   number of leaf elements  =         148
   leaf elements I own      =         148
   number of levels         =           8
   degrees of freedom       =          88
   degrees of freedom I own =          88
   min and max degree       =           1          1

Norms of error:
   energy norm of error       2.0471058978E+00
      reduced by              7.4254928628E-01
   energy error estimate      1.6682477552E+00
      reduced by              8.1038064081E-01
      effectivity             8.1492987588E-01
   Linf norm of error         2.6368607649E-01
      reduced by              5.5483351638E-01
   Linf error estimate        4.3237684720E-01
      reduced by              1.0124873625E+00
      effectivity             1.6397409107E+00
   L2 norm of error           6.3836741726E-02
      reduced by              4.4579567239E-01
   L2 error estimate          3.7792886688E-02
      reduced by              5.0292162332E-01
      effectivity             5.9202405489E-01

My Grid:
   number of vertices       =         171
   number of vertices I own =         171
   number of elements       =         588
   number of leaf elements  =         298
   leaf elements I own      =         298
   number of levels         =           8
   degrees of freedom       =         171
   degrees of freedom I own =         171
   min and max degree       =           1          1

Norms of error:
   energy norm of error       1.2719601994E+00
      reduced by              6.2134557900E-01
   energy error estimate      1.2781011230E+00
      reduced by              7.6613387852E-01
      effectivity             1.0048279213E+00
   Linf norm of error         1.2443334837E-01
      reduced by              4.7189957858E-01
   Linf error estimate        2.5954558950E-01
      reduced by              6.0027633575E-01
      effectivity             2.0858201832E+00
   L2 norm of error           2.3568509729E-02
      reduced by              3.6919976007E-01
   L2 error estimate          1.7175868167E-02
      reduced by              4.5447357089E-01
      effectivity             7.2876343752E-01

My Grid:
   number of vertices       =         372
   number of vertices I own =         372
   number of elements       =        1324
   number of leaf elements  =         666
   leaf elements I own      =         666
   number of levels         =          11
   degrees of freedom       =         372
   degrees of freedom I own =         372
   min and max degree       =           1          1

Norms of error:
   energy norm of error       7.9508392374E-01
      reduced by              6.2508553659E-01
   energy error estimate      6.8514340599E-01
      reduced by              5.3606353491E-01
      effectivity             8.6172463754E-01
   Linf norm of error         9.2148509728E-02
      reduced by              7.4054512663E-01
   Linf error estimate        1.0758011026E-01
      reduced by              4.1449407971E-01
      effectivity             1.1674644612E+00
   L2 norm of error           1.0519470603E-02
      reduced by              4.4633584065E-01
   L2 error estimate          5.6844556919E-03
      reduced by              3.3095594567E-01
      effectivity             5.4037469248E-01

My Grid:
   number of vertices       =         575
   number of vertices I own =         575
   number of elements       =        2044
   number of leaf elements  =        1026
   leaf elements I own      =        1026
   number of levels         =          12
   degrees of freedom       =         575
   degrees of freedom I own =         575
   min and max degree       =           1          1

Norms of error:
   energy norm of error       5.5714326326E-01
      reduced by              7.0073516346E-01
   energy error estimate      5.8388338449E-01
      reduced by              8.5220609202E-01
      effectivity             1.0479950544E+00
   Linf norm of error         3.1775085901E-02
      reduced by              3.4482473992E-01
   Linf error estimate        3.8699118151E-02
      reduced by              3.5972372641E-01
      effectivity             1.2179075856E+00
   L2 norm of error           7.0562060643E-03
      reduced by              6.7077577673E-01
   L2 error estimate          3.5978261789E-03
      reduced by              6.3292360321E-01
      effectivity             5.0988110978E-01

My Grid:
   number of vertices       =         575
   number of vertices I own =         575
   number of elements       =        2044
   number of leaf elements  =        1026
   leaf elements I own      =        1026
   number of levels         =          12
   degrees of freedom       =         575
   degrees of freedom I own =         575
   min and max degree       =           1          1

Norms of error:
   energy norm of error       5.5714326326E-01
   energy error estimate      5.8388338449E-01
      effectivity             1.0479950544E+00
   Linf norm of error         3.1775085901E-02
   Linf error estimate        3.8699118151E-02
      effectivity             1.2179075856E+00
   L2 norm of error           7.0562060643E-03
   L2 error estimate          3.5978261789E-03
      effectivity             5.0988110978E-01

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum equations achieved
---------------------------------------------------------
