---------------------------------------------------------
           PHAML   Version 1.11.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    SLAVES
  print_error_what   ENERGY_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree                      4
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             CG_SOLVER
  preconditioner     MG_PRECONDITION
  mg_cycles                   2
  mg_tol             MG_NO_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_NONE
  krylov_iter               100
  krylov_tol         KRYLOV_ERREST_TOL
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =          81
   degrees of freedom I own =          81
   min and max degree       =           4          4

Norms of error:
   energy norm of error       8.6272013923E-02
   L2 norm of error           4.3478103113E-03

My Grid:
   number of vertices       =          17
   number of vertices I own =          17
   number of elements       =          36
   number of leaf elements  =          22
   leaf elements I own      =          22
   number of levels         =           3
   degrees of freedom       =         197
   degrees of freedom I own =         197
   min and max degree       =           4          4

Norms of error:
   energy norm of error       2.2078337281E-02
      reduced by              2.5591540382E-01
   L2 norm of error           8.6481314295E-04
      reduced by              1.9890774460E-01

My Grid:
   number of vertices       =          30
   number of vertices I own =          30
   number of elements       =          80
   number of leaf elements  =          44
   leaf elements I own      =          44
   number of levels         =           4
   degrees of freedom       =         381
   degrees of freedom I own =         381
   min and max degree       =           4          4

Norms of error:
   energy norm of error       3.9273114775E-03
      reduced by              1.7788076283E-01
   L2 norm of error           8.3499794768E-05
      reduced by              9.6552411868E-02

My Grid:
   number of vertices       =          51
   number of vertices I own =          51
   number of elements       =         144
   number of leaf elements  =          76
   leaf elements I own      =          76
   number of levels         =           5
   degrees of freedom       =         657
   degrees of freedom I own =         657
   min and max degree       =           4          4

Norms of error:
   energy norm of error       8.4877564832E-04
      reduced by              2.1612129651E-01
   L2 norm of error           1.6251387102E-05
      reduced by              1.9462786881E-01

My Grid:
   number of vertices       =         111
   number of vertices I own =         111
   number of elements       =         376
   number of leaf elements  =         192
   leaf elements I own      =         192
   number of levels         =           7
   degrees of freedom       =        1593
   degrees of freedom I own =        1593
   min and max degree       =           4          4

Norms of error:
   energy norm of error       1.9610591743E-04
      reduced by              2.3104564536E-01
   L2 norm of error           2.3152546632E-06
      reduced by              1.4246504921E-01

My Grid:
   number of vertices       =         182
   number of vertices I own =         182
   number of elements       =         632
   number of leaf elements  =         320
   leaf elements I own      =         320
   number of levels         =           7
   degrees of freedom       =        2645
   degrees of freedom I own =        2645
   min and max degree       =           4          4

Norms of error:
   energy norm of error       4.4301734903E-05
      reduced by              2.2590718058E-01
   L2 norm of error           3.9319005567E-07
      reduced by              1.6982583468E-01

My Grid:
   number of vertices       =         365
   number of vertices I own =         365
   number of elements       =        1340
   number of leaf elements  =         674
   leaf elements I own      =         674
   number of levels         =           9
   degrees of freedom       =        5501
   degrees of freedom I own =        5501
   min and max degree       =           4          4

Norms of error:
   energy norm of error       1.4273182247E-05
      reduced by              3.2218111273E-01
   L2 norm of error           8.9146912251E-08
      reduced by              2.2672728103E-01

My Grid:
   number of vertices       =         688
   number of vertices I own =         688
   number of elements       =        2580
   number of leaf elements  =        1294
   leaf elements I own      =        1294
   number of levels         =           9
   degrees of freedom       =       10513
   degrees of freedom I own =       10513
   min and max degree       =           4          4

Norms of error:
   energy norm of error       2.8920400517E-06
      reduced by              2.0262055102E-01
   L2 norm of error           1.4490658042E-08
      reduced by              1.6254806449E-01

My Grid:
   number of vertices       =         688
   number of vertices I own =         688
   number of elements       =        2580
   number of leaf elements  =        1294
   leaf elements I own      =        1294
   number of levels         =           9
   degrees of freedom       =       10513
   degrees of freedom I own =       10513
   min and max degree       =           4          4

Norms of error:
   energy norm of error       2.8920400517E-06
   L2 norm of error           1.4490658042E-08

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           7
termination condition:
  maximum vertices achieved
---------------------------------------------------------
