---------------------------------------------------------
           PHAML   Version 1.11.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree                      4
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =          81
   min and max degree      =           4          4

Norms of error:
   energy norm of error       8.6271876530E-02
   L2 norm of error           4.3500442367E-03

Total Grid:
   number of vertices      =          17
   number of leaf elements =          22
   number of levels        =           3
   degrees of freedom      =         197
   min and max degree      =           4          4

Norms of error:
   energy norm of error       2.2078932422E-02
      reduced by              2.5592270981E-01
   L2 norm of error           8.6507324604E-04
      reduced by              1.9886539055E-01

Total Grid:
   number of vertices      =          30
   number of leaf elements =          44
   number of levels        =           4
   degrees of freedom      =         381
   min and max degree      =           4          4

Norms of error:
   energy norm of error       3.9273313221E-03
      reduced by              1.7787686683E-01
   L2 norm of error           8.3487932148E-05
      reduced by              9.6509668436E-02

Total Grid:
   number of vertices      =          51
   number of leaf elements =          76
   number of levels        =           5
   degrees of freedom      =         657
   min and max degree      =           4          4

Norms of error:
   energy norm of error       8.4879453802E-04
      reduced by              2.1612501427E-01
   L2 norm of error           1.6257180446E-05
      reduced by              1.9472491446E-01

Total Grid:
   number of vertices      =         110
   number of leaf elements =         190
   number of levels        =           7
   degrees of freedom      =        1577
   min and max degree      =           4          4

Norms of error:
   energy norm of error       1.9812379961E-04
      reduced by              2.3341785407E-01
   L2 norm of error           2.3556367249E-06
      reduced by              1.4489823329E-01

Total Grid:
   number of vertices      =         180
   number of leaf elements =         316
   number of levels        =           7
   degrees of freedom      =        2613
   min and max degree      =           4          4

Norms of error:
   energy norm of error       4.4343614965E-05
      reduced by              1.1190885460E-01
   L2 norm of error           3.9329170025E-07
      reduced by              8.3478852255E-02

Total Grid:
   number of vertices      =         366
   number of leaf elements =         676
   number of levels        =           9
   degrees of freedom      =        5517
   min and max degree      =           4          4

Norms of error:
   energy norm of error       1.4195984874E-05
      reduced by              3.2013594031E-01
   L2 norm of error           8.8819854552E-08
      reduced by              2.2583709368E-01

Total Grid:
   number of vertices      =         683
   number of leaf elements =        1284
   number of levels        =           9
   degrees of freedom      =       10433
   min and max degree      =           4          4

Norms of error:
   energy norm of error       2.9259522778E-06
      reduced by              2.0611125638E-01
   L2 norm of error           1.4725660845E-08
      reduced by              1.6579244494E-01

Total Grid:
   number of vertices      =         683
   number of leaf elements =        1284
   number of levels        =           9
   degrees of freedom      =       10433
   min and max degree      =           4          4

Norms of error:
   energy norm of error       2.9259522778E-06
   L2 norm of error           1.4725660845E-08

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           7
termination condition:
  maximum vertices achieved
---------------------------------------------------------
