---------------------------------------------------------
           PHAML   Version 1.9.1

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    SLAVES
  print_error_what   ENERGY_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                 100
  mg_tol              1.0000000000E-08
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

Norms of error:
   energy norm of error       2.4822035936E+00
   L2 norm of error           3.5000011056E-01

My Grid:
   number of vertices       =          29
   number of vertices I own =          29
   number of elements       =          72
   number of leaf elements  =          40
   leaf elements I own      =          40
   number of levels         =           5
   degrees of freedom       =          29
   degrees of freedom I own =          29
   min and max degree       =           1          1

Norms of error:
   energy norm of error       1.4543374687E+00
      reduced by              5.8590579453E-01
   L2 norm of error           9.0456404888E-02
      reduced by              2.5844678947E-01

My Grid:
   number of vertices       =          36
   number of vertices I own =          36
   number of elements       =          88
   number of leaf elements  =          48
   leaf elements I own      =          48
   number of levels         =           6
   degrees of freedom       =          36
   degrees of freedom I own =          36
   min and max degree       =           1          1

Norms of error:
   energy norm of error       1.4268179201E+00
      reduced by              9.8107760463E-01
   L2 norm of error           9.0525935617E-02
      reduced by              1.0007686656E+00

My Grid:
   number of vertices       =          82
   number of vertices I own =          82
   number of elements       =         256
   number of leaf elements  =         132
   leaf elements I own      =         132
   number of levels         =           7
   degrees of freedom       =          82
   degrees of freedom I own =          82
   min and max degree       =           1          1

Norms of error:
   energy norm of error       8.2034400959E-01
      reduced by              5.7494652824E-01
   L2 norm of error           2.7306632097E-02
      reduced by              3.0164429576E-01

My Grid:
   number of vertices       =         145
   number of vertices I own =         145
   number of elements       =         484
   number of leaf elements  =         246
   leaf elements I own      =         246
   number of levels         =           8
   degrees of freedom       =         145
   degrees of freedom I own =         145
   min and max degree       =           1          1

Norms of error:
   energy norm of error       5.1482143541E-01
      reduced by              6.2756773913E-01
   L2 norm of error           1.3402251840E-02
      reduced by              4.9080574245E-01

My Grid:
   number of vertices       =         334
   number of vertices I own =         334
   number of elements       =        1168
   number of leaf elements  =         588
   leaf elements I own      =         588
   number of levels         =          10
   degrees of freedom       =         334
   degrees of freedom I own =         334
   min and max degree       =           1          1

Norms of error:
   energy norm of error       3.7046876667E-01
      reduced by              7.1960633568E-01
   L2 norm of error           5.8453986105E-03
      reduced by              4.3615048278E-01

My Grid:
   number of vertices       =         626
   number of vertices I own =         626
   number of elements       =        2324
   number of leaf elements  =        1166
   leaf elements I own      =        1166
   number of levels         =          11
   degrees of freedom       =         626
   degrees of freedom I own =         626
   min and max degree       =           1          1

Norms of error:
   energy norm of error       2.4614958090E-01
      reduced by              6.6442735001E-01
   L2 norm of error           3.3791829500E-03
      reduced by              5.7809281713E-01

My Grid:
   number of vertices       =         626
   number of vertices I own =         626
   number of elements       =        2324
   number of leaf elements  =        1166
   leaf elements I own      =        1166
   number of levels         =          11
   degrees of freedom       =         626
   degrees of freedom I own =         626
   min and max degree       =           1          1

Norms of error:
   energy norm of error       2.4614958090E-01
   L2 norm of error           3.3791829500E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
