---------------------------------------------------------
           PHAML   Version 1.11.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             GMRES_SOLVER
  preconditioner     MG_PRECONDITION
  mg_cycles                   2
  mg_tol             MG_NO_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_NONE
  krylov_iter               100
  krylov_restart             20
  krylov_tol         KRYLOV_ERREST_TOL
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.4822035936E+00
   L2 norm of error           3.5000011056E-01

Total Grid:
   number of vertices      =          29
   number of leaf elements =          40
   number of levels        =           5
   degrees of freedom      =          29
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.4543374685E+00
      reduced by              5.8590579445E-01
   L2 norm of error           9.0456392716E-02
      reduced by              2.5844675469E-01

Total Grid:
   number of vertices      =          36
   number of leaf elements =          48
   number of levels        =           6
   degrees of freedom      =          36
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.4268179201E+00
      reduced by              9.8107760475E-01
   L2 norm of error           9.0525933459E-02
      reduced by              1.0007687764E+00

Total Grid:
   number of vertices      =          98
   number of leaf elements =         154
   number of levels        =           8
   degrees of freedom      =          98
   min and max degree      =           1          1

Norms of error:
   energy norm of error       7.7955585332E-01
      reduced by              5.4635972983E-01
   L2 norm of error           2.5635726732E-02
      reduced by              2.8318654946E-01

Total Grid:
   number of vertices      =         167
   number of leaf elements =         288
   number of levels        =           9
   degrees of freedom      =         167
   min and max degree      =           1          1

Norms of error:
   energy norm of error       4.8553639374E-01
      reduced by              6.2283721130E-01
   L2 norm of error           1.2329096625E-02
      reduced by              4.8093415699E-01

Total Grid:
   number of vertices      =         314
   number of leaf elements =         552
   number of levels        =          10
   degrees of freedom      =         314
   min and max degree      =           1          1

Norms of error:
   energy norm of error       3.3434880044E-01
      reduced by              3.4430869112E-01
   L2 norm of error           8.0610675094E-03
      reduced by              3.2691233408E-01

Total Grid:
   number of vertices      =         586
   number of leaf elements =        1084
   number of levels        =          11
   degrees of freedom      =         586
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.4876295884E-01
      reduced by              7.4402228605E-01
   L2 norm of error           3.3707994818E-03
      reduced by              4.1815795215E-01

Total Grid:
   number of vertices      =         586
   number of leaf elements =        1084
   number of levels        =          11
   degrees of freedom      =         586
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.4876295884E-01
   L2 norm of error           3.3707994818E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
