---------------------------------------------------------
           PHAML   Version 1.11.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    SLAVES
  print_error_what   ENERGY_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree                      4
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =          81
   degrees of freedom I own =          81
   min and max degree       =           4          4

Norms of error:
   energy norm of error       8.6271869990E-02
   L2 norm of error           4.3500129634E-03

My Grid:
   number of vertices       =          17
   number of vertices I own =          17
   number of elements       =          36
   number of leaf elements  =          22
   leaf elements I own      =          22
   number of levels         =           3
   degrees of freedom       =         197
   degrees of freedom I own =         197
   min and max degree       =           4          4

Norms of error:
   energy norm of error       2.2078388260E-02
      reduced by              2.5591642168E-01
   L2 norm of error           8.6485937875E-04
      reduced by              1.9881765549E-01

My Grid:
   number of vertices       =          30
   number of vertices I own =          30
   number of elements       =          80
   number of leaf elements  =          44
   leaf elements I own      =          44
   number of levels         =           4
   degrees of freedom       =         381
   degrees of freedom I own =         381
   min and max degree       =           4          4

Norms of error:
   energy norm of error       3.9273158413E-03
      reduced by              1.7788054975E-01
   L2 norm of error           8.3500099485E-05
      reduced by              9.6547602461E-02

My Grid:
   number of vertices       =          51
   number of vertices I own =          51
   number of elements       =         144
   number of leaf elements  =          76
   leaf elements I own      =          76
   number of levels         =           5
   degrees of freedom       =         657
   degrees of freedom I own =         657
   min and max degree       =           4          4

Norms of error:
   energy norm of error       8.4878281254E-04
      reduced by              2.1612288057E-01
   L2 norm of error           1.6255159212E-05
      reduced by              1.9467233347E-01

My Grid:
   number of vertices       =         110
   number of vertices I own =         110
   number of elements       =         372
   number of leaf elements  =         190
   leaf elements I own      =         190
   number of levels         =           7
   degrees of freedom       =        1577
   degrees of freedom I own =        1577
   min and max degree       =           4          4

Norms of error:
   energy norm of error       1.9812113977E-04
      reduced by              2.3341794490E-01
   L2 norm of error           2.3550699784E-06
      reduced by              1.4488138490E-01

My Grid:
   number of vertices       =         180
   number of vertices I own =         180
   number of elements       =         624
   number of leaf elements  =         316
   leaf elements I own      =         316
   number of levels         =           7
   degrees of freedom       =        2613
   degrees of freedom I own =        2613
   min and max degree       =           4          4

Norms of error:
   energy norm of error       4.4343533803E-05
      reduced by              2.2382030436E-01
   L2 norm of error           3.9330178299E-07
      reduced by              1.6700216410E-01

My Grid:
   number of vertices       =         365
   number of vertices I own =         365
   number of elements       =        1340
   number of leaf elements  =         674
   leaf elements I own      =         674
   number of levels         =           9
   degrees of freedom       =        5501
   degrees of freedom I own =        5501
   min and max degree       =           4          4

Norms of error:
   energy norm of error       1.4273191848E-05
      reduced by              3.2187763634E-01
   L2 norm of error           8.9158368965E-08
      reduced by              2.2669200299E-01

My Grid:
   number of vertices       =         687
   number of vertices I own =         687
   number of elements       =        2576
   number of leaf elements  =        1292
   leaf elements I own      =        1292
   number of levels         =           9
   degrees of freedom       =       10497
   degrees of freedom I own =       10497
   min and max degree       =           4          4

Norms of error:
   energy norm of error       2.9095344986E-06
      reduced by              2.0384610041E-01
   L2 norm of error           1.4626149991E-08
      reduced by              1.6404685461E-01

My Grid:
   number of vertices       =         687
   number of vertices I own =         687
   number of elements       =        2576
   number of leaf elements  =        1292
   leaf elements I own      =        1292
   number of levels         =           9
   degrees of freedom       =       10497
   degrees of freedom I own =       10497
   min and max degree       =           4          4

Norms of error:
   energy norm of error       2.9095344986E-06
   L2 norm of error           1.4626149991E-08

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           7
termination condition:
  maximum vertices achieved
---------------------------------------------------------
