---------------------------------------------------------
           PHAML   Version 1.11.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree                      4
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             CG_SOLVER
  preconditioner     MG_PRECONDITION
  mg_cycles                   5
  mg_tol             MG_NO_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              2
  mg_postrelax_ho             2
  mg_comm            MGCOMM_NONE
  krylov_iter               100
  krylov_tol         KRYLOV_ERREST_TOL
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =          81
   min and max degree      =           4          4

Norms of error:
   energy norm of error       8.6272423246E-02
   L2 norm of error           4.3532036132E-03

Total Grid:
   number of vertices      =          17
   number of leaf elements =          22
   number of levels        =           3
   degrees of freedom      =         197
   min and max degree      =           4          4

Norms of error:
   energy norm of error       2.2078338437E-02
      reduced by              2.5591420301E-01
   L2 norm of error           8.6483281247E-04
      reduced by              1.9866583080E-01

Total Grid:
   number of vertices      =          30
   number of leaf elements =          44
   number of levels        =           4
   degrees of freedom      =         381
   min and max degree      =           4          4

Norms of error:
   energy norm of error       3.9273115298E-03
      reduced by              1.7788075588E-01
   L2 norm of error           8.3499453786E-05
      reduced by              9.6549821633E-02

Total Grid:
   number of vertices      =          51
   number of leaf elements =          76
   number of levels        =           5
   degrees of freedom      =         657
   min and max degree      =           4          4

Norms of error:
   energy norm of error       8.4877575316E-04
      reduced by              2.1612132033E-01
   L2 norm of error           1.6252225902E-05
      reduced by              1.9463870918E-01

Total Grid:
   number of vertices      =         111
   number of leaf elements =         192
   number of levels        =           7
   degrees of freedom      =        1593
   min and max degree      =           4          4

Norms of error:
   energy norm of error       1.9610591733E-04
      reduced by              2.3104561670E-01
   L2 norm of error           2.3152497408E-06
      reduced by              1.4245739351E-01

Total Grid:
   number of vertices      =         182
   number of leaf elements =         320
   number of levels        =           7
   degrees of freedom      =        2645
   min and max degree      =           4          4

Norms of error:
   energy norm of error       4.4301734863E-05
      reduced by              1.1295359025E-01
   L2 norm of error           3.9318929320E-07
      reduced by              8.4912933208E-02

Total Grid:
   number of vertices      =         366
   number of leaf elements =         676
   number of levels        =           9
   degrees of freedom      =        5517
   min and max degree      =           4          4

Norms of error:
   energy norm of error       1.4195975515E-05
      reduced by              3.2043836566E-01
   L2 norm of error           8.8809156025E-08
      reduced by              2.2586870385E-01

Total Grid:
   number of vertices      =         686
   number of leaf elements =        1290
   number of levels        =           9
   degrees of freedom      =       10481
   min and max degree      =           4          4

Norms of error:
   energy norm of error       2.8949346407E-06
      reduced by              2.0392643236E-01
   L2 norm of error           1.4503360169E-08
      reduced by              1.6330928947E-01

Total Grid:
   number of vertices      =         686
   number of leaf elements =        1290
   number of levels        =           9
   degrees of freedom      =       10481
   min and max degree      =           4          4

Norms of error:
   energy norm of error       2.8949346407E-06
   L2 norm of error           1.4503360169E-08

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           7
termination condition:
  maximum vertices achieved
---------------------------------------------------------
