---------------------------------------------------------
           PHAML   Version 1.11.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  PHASES
  print_solver_who   MASTER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             PETSC_GMRES_SOLVER
  preconditioner     PETSC_EISENSTAT_PRECONDITION
  petsc_matrix_free  false
  petsc_rtol         default
  petsc_atol         default
  petsc_dtol         default
  petsc_maxits       default
  petsc_gmres_max_steps  default
  petsc_eisenstat_nodiagscaling F
  petsc_eisenstat_omega  default
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Solver information:
   number of iterations =           0
   relative residual =   0.0000000000E+00

Norms of error:
   energy norm of error       2.4822035936E+00
   Linf norm of error         8.7914044620E-01
   L2 norm of error           3.5000011056E-01

Total Grid:
   number of vertices      =          29
   number of leaf elements =          40
   number of levels        =           5
   degrees of freedom      =          29
   min and max degree      =           1          1

Solver information:
   number of iterations =           5
   relative residual =   8.8882944970E-16

Norms of error:
   energy norm of error       1.4543374687E+00
      reduced by              5.8590579453E-01
   Linf norm of error         2.5755437366E-01
      reduced by              2.9296157943E-01
   L2 norm of error           9.0456404459E-02
      reduced by              2.5844678824E-01

Total Grid:
   number of vertices      =          36
   number of leaf elements =          48
   number of levels        =           6
   degrees of freedom      =          36
   min and max degree      =           1          1

Solver information:
   number of iterations =           5
   relative residual =   2.6322397352E-06

Norms of error:
   energy norm of error       1.4268179182E+00
      reduced by              9.8107760335E-01
   Linf norm of error         2.5755713265E-01
      reduced by              1.0000107123E+00
   L2 norm of error           9.0525902863E-02
      reduced by              1.0007683083E+00

Total Grid:
   number of vertices      =          98
   number of leaf elements =         154
   number of levels        =           8
   degrees of freedom      =          98
   min and max degree      =           1          1

Solver information:
   number of iterations =           9
   relative residual =   6.8913599815E-06

Norms of error:
   energy norm of error       7.7955585546E-01
      reduced by              5.4635973203E-01
   Linf norm of error         1.0000019078E-01
      reduced by              3.8826410959E-01
   L2 norm of error           2.5635820756E-02
      reduced by              2.8318768380E-01

Total Grid:
   number of vertices      =         167
   number of leaf elements =         288
   number of levels        =           9
   degrees of freedom      =         167
   min and max degree      =           1          1

Solver information:
   number of iterations =          11
   relative residual =   6.3140538961E-05

Norms of error:
   energy norm of error       4.8553639720E-01
      reduced by              6.2283721403E-01
   Linf norm of error         3.2559093528E-02
      reduced by              3.2559031413E-01
   L2 norm of error           1.2328535814E-02
      reduced by              4.8091051701E-01

Total Grid:
   number of vertices      =         314
   number of leaf elements =         552
   number of levels        =          10
   degrees of freedom      =         314
   min and max degree      =           1          1

Solver information:
   number of iterations =          20
   relative residual =   6.2318706506E-05

Norms of error:
   energy norm of error       3.3434878864E-01
      reduced by              3.4430867651E-01
   Linf norm of error         3.1415848240E-02
      reduced by              9.6488706643E-01
   L2 norm of error           8.0614481118E-03
      reduced by              3.2694264078E-01

Total Grid:
   number of vertices      =         586
   number of leaf elements =        1084
   number of levels        =          11
   degrees of freedom      =         586
   min and max degree      =           1          1

Solver information:
   number of iterations =          28
   relative residual =   1.1347884209E-04

Norms of error:
   energy norm of error       2.4876298529E-01
      reduced by              7.4402239143E-01
   Linf norm of error         1.0114309632E-02
      reduced by              3.2194927716E-01
   L2 norm of error           3.3721309918E-03
      reduced by              4.1830337988E-01

Total Grid:
   number of vertices      =         586
   number of leaf elements =        1084
   number of levels        =          11
   degrees of freedom      =         586
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.4876298529E-01
   Linf norm of error         1.0114309632E-02
   L2 norm of error           3.3721309918E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
