---------------------------------------------------------
           PHAML   Version 1.9.1

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             PETSC_GMRES_SOLVER
  preconditioner     COARSE_GRID_PRECONDITION
  coarse_size              5000
  coarse_method      LAPACK_INDEFINITE_SOLVER
  petsc_matrix_free  false
  petsc_rtol           1.0000000000E-10
  petsc_atol         default
  petsc_dtol         default
  petsc_maxits       default
  petsc_gmres_max_steps  default
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.4822035936E+00
   Linf norm of error         8.7914044620E-01
   L2 norm of error           3.5000011056E-01

Total Grid:
   number of vertices      =          29
   number of leaf elements =          40
   number of levels        =           5
   degrees of freedom      =          29
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.4543374687E+00
      reduced by              5.8590579453E-01
   Linf norm of error         2.5755437366E-01
      reduced by              2.9296157943E-01
   L2 norm of error           9.0456404459E-02
      reduced by              2.5844678824E-01

Total Grid:
   number of vertices      =          36
   number of leaf elements =          48
   number of levels        =           6
   degrees of freedom      =          36
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.4268179201E+00
      reduced by              9.8107760463E-01
   Linf norm of error         2.5755717454E-01
      reduced by              1.0000108749E+00
   L2 norm of error           9.0525935753E-02
      reduced by              1.0007686719E+00

Total Grid:
   number of vertices      =          82
   number of leaf elements =         132
   number of levels        =           7
   degrees of freedom      =          82
   min and max degree      =           1          1

Norms of error:
   energy norm of error       8.2034400959E-01
      reduced by              5.7494652824E-01
   Linf norm of error         1.0000467189E-01
      reduced by              3.8828144497E-01
   L2 norm of error           2.7306631880E-02
      reduced by              3.0164429291E-01

Total Grid:
   number of vertices      =         145
   number of leaf elements =         246
   number of levels        =           8
   degrees of freedom      =         145
   min and max degree      =           1          1

Norms of error:
   energy norm of error       5.1482143541E-01
      reduced by              6.2756773913E-01
   Linf norm of error         3.8245739747E-02
      reduced by              3.8243953030E-01
   L2 norm of error           1.3402251642E-02
      reduced by              4.9080573908E-01

Total Grid:
   number of vertices      =         334
   number of leaf elements =         588
   number of levels        =          10
   degrees of freedom      =         334
   min and max degree      =           1          1

Norms of error:
   energy norm of error       3.7046876667E-01
      reduced by              3.5980316784E-01
   Linf norm of error         3.0340740542E-02
      reduced by              7.9331033322E-01
   L2 norm of error           5.8453985686E-03
      reduced by              2.1807524306E-01

Total Grid:
   number of vertices      =         626
   number of leaf elements =        1166
   number of levels        =          11
   degrees of freedom      =         626
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.4614958090E-01
      reduced by              6.6442735001E-01
   Linf norm of error         1.0118994048E-02
      reduced by              3.3351176889E-01
   L2 norm of error           3.3791827111E-03
      reduced by              5.7809278041E-01

Total Grid:
   number of vertices      =         626
   number of leaf elements =        1166
   number of levels        =          11
   degrees of freedom      =         626
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.4614958090E-01
   Linf norm of error         1.0118994048E-02
   L2 norm of error           3.3791827111E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
