---------------------------------------------------------
           PHAML   Version 1.9.1

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree                      4
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             PETSC_CG_SOLVER
  preconditioner     PETSC_SOR_PRECONDITION
  petsc_matrix_free  false
  petsc_rtol           1.0000000000E-10
  petsc_atol         default
  petsc_dtol         default
  petsc_maxits       default
  petsc_sor_omega    default
  petsc_sor_its      default
  petsc_sor_lits     default
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =          81
   min and max degree      =           4          4

Norms of error:
   energy norm of error       8.6271852000E-02
   Linf norm of error         1.0764133984E-02
   L2 norm of error           4.3498770724E-03

Total Grid:
   number of vertices      =          19
   number of leaf elements =          24
   number of levels        =           3
   degrees of freedom      =         217
   min and max degree      =           4          4

Norms of error:
   energy norm of error       7.7771499750E-03
      reduced by              9.0147015448E-02
   Linf norm of error         7.0294452017E-04
      reduced by              6.5304326502E-02
   L2 norm of error           1.9281272898E-04
      reduced by              4.4326017901E-02

Total Grid:
   number of vertices      =          28
   number of leaf elements =          40
   number of levels        =           4
   degrees of freedom      =         349
   min and max degree      =           4          4

Norms of error:
   energy norm of error       3.9461930021E-03
      reduced by              5.0740862846E-01
   Linf norm of error         3.5674009935E-04
      reduced by              5.0749396163E-01
   L2 norm of error           8.4281399763E-05
      reduced by              4.3711533055E-01

Total Grid:
   number of vertices      =          51
   number of leaf elements =          76
   number of levels        =           5
   degrees of freedom      =         657
   min and max degree      =           4          4

Norms of error:
   energy norm of error       8.4877566754E-04
      reduced by              2.1508721623E-01
   Linf norm of error         5.8530713723E-05
      reduced by              1.6407102490E-01
   L2 norm of error           1.6251860808E-05
      reduced by              1.9282855830E-01

Total Grid:
   number of vertices      =         111
   number of leaf elements =         192
   number of levels        =           7
   degrees of freedom      =        1593
   min and max degree      =           4          4

Norms of error:
   energy norm of error       1.9610591726E-04
      reduced by              2.3104563993E-01
   Linf norm of error         1.4914720781E-05
      reduced by              2.5481870683E-01
   L2 norm of error           2.3152543982E-06
      reduced by              1.4246088037E-01

Total Grid:
   number of vertices      =         182
   number of leaf elements =         320
   number of levels        =           7
   degrees of freedom      =        2645
   min and max degree      =           4          4

Norms of error:
   energy norm of error       5.9709522785E-05
      reduced by              1.5223794269E-01
   Linf norm of error         7.7353198972E-06
      reduced by              5.1863658803E-01
   L2 norm of error           8.0766245864E-07
      reduced by              1.7442196833E-01

Total Grid:
   number of vertices      =         370
   number of leaf elements =         683
   number of levels        =           9
   degrees of freedom      =        5575
   min and max degree      =           4          4

Norms of error:
   energy norm of error       2.0235227844E-05
      reduced by              3.3889448283E-01
   Linf norm of error         3.5337764684E-06
      reduced by              4.5683650003E-01
   L2 norm of error           1.7284633194E-07
      reduced by              2.1400812938E-01

Total Grid:
   number of vertices      =         724
   number of leaf elements =        1357
   number of levels        =          13
   degrees of freedom      =       11035
   min and max degree      =           4          4

Norms of error:
   energy norm of error       2.9915963555E-06
      reduced by              1.4784100177E-01
   Linf norm of error         6.6519549438E-08
      reduced by              1.8823926763E-02
   L2 norm of error           1.5580596288E-08
      reduced by              9.0141318667E-02

Total Grid:
   number of vertices      =         724
   number of leaf elements =        1357
   number of levels        =          13
   degrees of freedom      =       11035
   min and max degree      =           4          4

Norms of error:
   energy norm of error       2.9915963555E-06
   Linf norm of error         6.6519549438E-08
   L2 norm of error           1.5580596288E-08

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           7
termination condition:
  maximum vertices achieved
---------------------------------------------------------
