---------------------------------------------------------
           PHAML   Version 1.11.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  PHASES
  print_solver_who   MASTER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             PETSC_CR_SOLVER
  preconditioner     PETSC_SOR_PRECONDITION
  petsc_matrix_free  false
  petsc_rtol           1.0000000000E-10
  petsc_atol         default
  petsc_dtol         default
  petsc_maxits       default
  petsc_sor_omega    default
  petsc_sor_its      default
  petsc_sor_lits     default
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Solver information:
   number of iterations =           0
   relative residual =   0.0000000000E+00

Norms of error:
   energy norm of error       2.4822035936E+00
   Linf norm of error         8.7914044620E-01
   L2 norm of error           3.5000011056E-01

Total Grid:
   number of vertices      =          29
   number of leaf elements =          40
   number of levels        =           5
   degrees of freedom      =          29
   min and max degree      =           1          1

Solver information:
   number of iterations =           5
   relative residual =   1.6165674751E-16

Norms of error:
   energy norm of error       1.4543374687E+00
      reduced by              5.8590579453E-01
   Linf norm of error         2.5755437366E-01
      reduced by              2.9296157943E-01
   L2 norm of error           9.0456404459E-02
      reduced by              2.5844678824E-01

Total Grid:
   number of vertices      =          36
   number of leaf elements =          48
   number of levels        =           6
   degrees of freedom      =          36
   min and max degree      =           1          1

Solver information:
   number of iterations =           6
   relative residual =   2.4933161624E-16

Norms of error:
   energy norm of error       1.4268179201E+00
      reduced by              9.8107760463E-01
   Linf norm of error         2.5755717454E-01
      reduced by              1.0000108749E+00
   L2 norm of error           9.0525935753E-02
      reduced by              1.0007686719E+00

Total Grid:
   number of vertices      =          98
   number of leaf elements =         154
   number of levels        =           8
   degrees of freedom      =          98
   min and max degree      =           1          1

Solver information:
   number of iterations =          13
   relative residual =   6.9681109029E-11

Norms of error:
   energy norm of error       7.7955585392E-01
      reduced by              5.4635973024E-01
   Linf norm of error         1.0000000778E-01
      reduced by              3.8826333592E-01
   L2 norm of error           2.5635825633E-02
      reduced by              2.8318763479E-01

Total Grid:
   number of vertices      =         167
   number of leaf elements =         288
   number of levels        =           9
   degrees of freedom      =         167
   min and max degree      =           1          1

Solver information:
   number of iterations =          17
   relative residual =   6.5542124613E-10

Norms of error:
   energy norm of error       4.8553639373E-01
      reduced by              6.2283721081E-01
   Linf norm of error         3.2559787378E-02
      reduced by              3.2559784845E-01
   L2 norm of error           1.2329106583E-02
      reduced by              4.8093269002E-01

Total Grid:
   number of vertices      =         314
   number of leaf elements =         552
   number of levels        =          10
   degrees of freedom      =         314
   min and max degree      =           1          1

Solver information:
   number of iterations =          36
   relative residual =   6.1970949959E-10

Norms of error:
   energy norm of error       3.3434878172E-01
      reduced by              3.4430867185E-01
   Linf norm of error         3.1415834339E-02
      reduced by              9.6486607773E-01
   L2 norm of error           8.0616212117E-03
      reduced by              3.2693452513E-01

Total Grid:
   number of vertices      =         586
   number of leaf elements =        1084
   number of levels        =          11
   degrees of freedom      =         586
   min and max degree      =           1          1

Solver information:
   number of iterations =          50
   relative residual =   9.6760581925E-10

Norms of error:
   energy norm of error       2.4876295109E-01
      reduced by              7.4402230451E-01
   Linf norm of error         1.0114544269E-02
      reduced by              3.2195688837E-01
   L2 norm of error           3.3724184313E-03
      reduced by              4.1833005331E-01

Total Grid:
   number of vertices      =         586
   number of leaf elements =        1084
   number of levels        =          11
   degrees of freedom      =         586
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.4876295109E-01
   Linf norm of error         1.0114544269E-02
   L2 norm of error           3.3724184313E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
