---------------------------------------------------------
           PHAML   Version 1.9.1

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                    500
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  ENERGY_LINF_L2_ERREST
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                   5
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Norms of error:
   energy norm of error       4.0333158308E+00
   energy error estimate      2.7431604171E+00
      effectivity             6.8012536884E-01
   Linf norm of error         1.0536246503E+00
   Linf error estimate        1.1645061848E+00
      effectivity             1.1052381742E+00
   L2 norm of error           4.5345860840E-01
   L2 error estimate          3.8794146656E-01
      effectivity             8.5551681976E-01

Total Grid:
   number of vertices      =          29
   number of leaf elements =          40
   number of levels        =           5
   degrees of freedom      =          29
   min and max degree      =           1          1

Norms of error:
   energy norm of error       3.0143054217E+00
      reduced by              7.4735169478E-01
   energy error estimate      1.0981752824E+00
      reduced by              4.0033214083E-01
      effectivity             3.6432117146E-01
   Linf norm of error         5.2342002897E-01
      reduced by              4.9678035609E-01
   Linf error estimate        1.9362275570E-01
      reduced by              1.6627026823E-01
      effectivity             3.6991850710E-01
   L2 norm of error           1.6018458492E-01
      reduced by              3.5325073104E-01
   L2 error estimate          5.2590615143E-02
      reduced by              1.3556327353E-01
      effectivity             3.2831258495E-01

Total Grid:
   number of vertices      =          36
   number of leaf elements =          48
   number of levels        =           6
   degrees of freedom      =          36
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.9236225954E+00
      reduced by              9.6991584673E-01
   energy error estimate      8.7510915694E-01
      reduced by              7.9687566364E-01
      effectivity             2.9932357149E-01
   Linf norm of error         4.7530075334E-01
      reduced by              9.0806756912E-01
   Linf error estimate        1.3917355990E-01
      reduced by              7.1878720761E-01
      effectivity             2.9281157020E-01
   L2 norm of error           1.6068325425E-01
      reduced by              1.0031130919E+00
   L2 error estimate          3.5588300732E-02
      reduced by              6.7670440125E-01
      effectivity             2.2148108027E-01

Total Grid:
   number of vertices      =          75
   number of leaf elements =         108
   number of levels        =           8
   degrees of freedom      =          75
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.0694813621E+00
      reduced by              7.0784832674E-01
   energy error estimate      5.2466983456E-01
      reduced by              5.9954787400E-01
      effectivity             2.5352720936E-01
   Linf norm of error         2.5521099956E-01
      reduced by              5.3694633928E-01
   Linf error estimate        5.3216400614E-02
      reduced by              3.8237435797E-01
      effectivity             2.0851922803E-01
   L2 norm of error           6.5141246413E-02
      reduced by              4.0540158785E-01
   L2 error estimate          1.2387422106E-02
      reduced by              3.4807568361E-01
      effectivity             1.9016249746E-01

Total Grid:
   number of vertices      =         170
   number of leaf elements =         290
   number of levels        =           9
   degrees of freedom      =         170
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.2083481139E+00
      reduced by              5.8388934349E-01
   energy error estimate      3.5146529662E-01
      reduced by              6.6987898572E-01
      effectivity             2.9086427377E-01
   Linf norm of error         1.0088007735E-01
      reduced by              3.9528107145E-01
   Linf error estimate        1.8331456009E-02
      reduced by              3.4447004678E-01
      effectivity             1.8171532468E-01
   L2 norm of error           2.0279034251E-02
      reduced by              3.1130866183E-01
   L2 error estimate          4.8904643732E-03
      reduced by              3.9479274472E-01
      effectivity             2.4115864260E-01

Total Grid:
   number of vertices      =         291
   number of leaf elements =         504
   number of levels        =          10
   degrees of freedom      =         291
   min and max degree      =           1          1

Norms of error:
   energy norm of error       7.7409903326E-01
      reduced by              3.2031292322E-01
   energy error estimate      2.5575221695E-01
      reduced by              3.6383708351E-01
      effectivity             3.3038694787E-01
   Linf norm of error         4.0589131665E-02
      reduced by              4.0235032259E-01
   Linf error estimate        9.2051169117E-03
      reduced by              5.0214870587E-01
      effectivity             2.2678772701E-01
   L2 norm of error           9.7511399399E-03
      reduced by              2.4042416959E-01
   L2 error estimate          2.5224239908E-03
      reduced by              2.5789207306E-01
      effectivity             2.5867990885E-01

Total Grid:
   number of vertices      =         524
   number of leaf elements =         958
   number of levels        =          12
   degrees of freedom      =         524
   min and max degree      =           1          1

Norms of error:
   energy norm of error       6.1752650672E-01
      reduced by              7.9773579373E-01
   energy error estimate      1.8169631563E-01
      reduced by              7.1043886850E-01
      effectivity             2.9423241537E-01
   Linf norm of error         3.1262197067E-02
      reduced by              7.7021103396E-01
   Linf error estimate        4.9960083355E-03
      reduced by              5.4274251847E-01
      effectivity             1.5980989195E-01
   L2 norm of error           7.8336662619E-03
      reduced by              8.0335902369E-01
   L2 error estimate          1.6854266133E-03
      reduced by              6.6817736410E-01
      effectivity             2.1515169998E-01

Total Grid:
   number of vertices      =         524
   number of leaf elements =         958
   number of levels        =          12
   degrees of freedom      =         524
   min and max degree      =           1          1

Norms of error:
   energy norm of error       6.1752650672E-01
   energy error estimate      1.8169631563E-01
      effectivity             2.9423241537E-01
   Linf norm of error         3.1262197067E-02
   Linf error estimate        4.9960083355E-03
      effectivity             1.5980989195E-01
   L2 norm of error           7.8336662619E-03
   L2 error estimate          1.6854266133E-03
      effectivity             2.1515169998E-01

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum equations achieved
---------------------------------------------------------
