---------------------------------------------------------
           PHAML   Version 1.9.1

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                    500
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  ENERGY_LINF_L2_ERREST
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    HIERARCHICAL_COEFFICIENT
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                   5
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Norms of error:
   energy norm of error       4.0333158308E+00
   energy error estimate      1.4163714038E+00
      effectivity             3.5116798764E-01
   Linf norm of error         1.0536246503E+00
   Linf error estimate        8.5463149069E-01
      effectivity             8.1113467727E-01
   L2 norm of error           4.5345860840E-01
   L2 error estimate          1.6692097072E-01
      effectivity             3.6810630039E-01

Total Grid:
   number of vertices      =          20
   number of leaf elements =          28
   number of levels        =           4
   degrees of freedom      =          20
   min and max degree      =           1          1

Norms of error:
   energy norm of error       3.2457948025E+00
      reduced by              8.0474600521E-01
   energy error estimate      2.2972296891E+00
      reduced by              1.6219119384E+00
      effectivity             7.0775567429E-01
   Linf norm of error         6.7765993687E-01
      reduced by              6.4317016186E-01
   Linf error estimate        6.2590258262E-01
      reduced by              7.3236545744E-01
      effectivity             9.2362341134E-01
   L2 norm of error           2.4226246048E-01
      reduced by              5.3425484926E-01
   L2 error estimate          1.4443843278E-01
      reduced by              8.6531028519E-01
      effectivity             5.9620641386E-01

Total Grid:
   number of vertices      =          42
   number of leaf elements =          66
   number of levels        =           6
   degrees of freedom      =          42
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.7568619842E+00
      reduced by              8.4936422416E-01
   energy error estimate      2.0585977533E+00
      reduced by              8.9612186499E-01
      effectivity             7.4671774106E-01
   Linf norm of error         4.7525260909E-01
      reduced by              7.0131430712E-01
   Linf error estimate        4.2704419529E-01
      reduced by              6.8228540214E-01
      effectivity             8.9856254783E-01
   L2 norm of error           1.4319730852E-01
      reduced by              5.9108335745E-01
   L2 error estimate          7.5146673483E-02
      reduced by              5.2026785419E-01
      effectivity             5.2477713623E-01

Total Grid:
   number of vertices      =          88
   number of leaf elements =         148
   number of levels        =           8
   degrees of freedom      =          88
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.0471058978E+00
      reduced by              7.4254928594E-01
   energy error estimate      1.6682477552E+00
      reduced by              8.1038063535E-01
      effectivity             8.1492987588E-01
   Linf norm of error         2.6368607649E-01
      reduced by              5.5483351685E-01
   Linf error estimate        4.3237684720E-01
      reduced by              1.0124873537E+00
      effectivity             1.6397409107E+00
   L2 norm of error           6.3836741725E-02
      reduced by              4.4579568138E-01
   L2 error estimate          3.7792886688E-02
      reduced by              5.0292161896E-01
      effectivity             5.9202405490E-01

Total Grid:
   number of vertices      =         171
   number of leaf elements =         298
   number of levels        =           8
   degrees of freedom      =         171
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.2719601994E+00
      reduced by              6.2134557900E-01
   energy error estimate      1.2781011230E+00
      reduced by              7.6613387851E-01
      effectivity             1.0048279213E+00
   Linf norm of error         1.2443334837E-01
      reduced by              4.7189957858E-01
   Linf error estimate        2.5954558950E-01
      reduced by              6.0027633575E-01
      effectivity             2.0858201832E+00
   L2 norm of error           2.3568509729E-02
      reduced by              3.6919976007E-01
   L2 error estimate          1.7175868167E-02
      reduced by              4.5447357089E-01
      effectivity             7.2876343752E-01

Total Grid:
   number of vertices      =         372
   number of leaf elements =         666
   number of levels        =          11
   degrees of freedom      =         372
   min and max degree      =           1          1

Norms of error:
   energy norm of error       7.9508392012E-01
      reduced by              3.1254276687E-01
   energy error estimate      6.8514446021E-01
      reduced by              2.6803217987E-01
      effectivity             8.6172596738E-01
   Linf norm of error         9.2148455389E-02
      reduced by              7.4054468994E-01
   Linf error estimate        1.0758011026E-01
      reduced by              4.1449407971E-01
      effectivity             1.1674651496E+00
   L2 norm of error           1.0519314936E-02
      reduced by              2.2316461790E-01
   L2 error estimate          5.6844578330E-03
      reduced by              1.6547803516E-01
      effectivity             5.4038289255E-01

Total Grid:
   number of vertices      =         575
   number of leaf elements =        1026
   number of levels        =          12
   degrees of freedom      =         575
   min and max degree      =           1          1

Norms of error:
   energy norm of error       5.5714326358E-01
      reduced by              7.0073516704E-01
   energy error estimate      5.8388336858E-01
      reduced by              8.5220475752E-01
      effectivity             1.0479950252E+00
   Linf norm of error         3.1775086374E-02
      reduced by              3.4482494839E-01
   Linf error estimate        3.8699118338E-02
      reduced by              3.5972372815E-01
      effectivity             1.2179075733E+00
   L2 norm of error           7.0562140645E-03
      reduced by              6.7078646350E-01
   L2 error estimate          3.5978261897E-03
      reduced by              6.3292336674E-01
      effectivity             5.0988053322E-01

Total Grid:
   number of vertices      =         575
   number of leaf elements =        1026
   number of levels        =          12
   degrees of freedom      =         575
   min and max degree      =           1          1

Norms of error:
   energy norm of error       5.5714326358E-01
   energy error estimate      5.8388336858E-01
      effectivity             1.0479950252E+00
   Linf norm of error         3.1775086374E-02
   Linf error estimate        3.8699118338E-02
      effectivity             1.2179075733E+00
   L2 norm of error           7.0562140645E-03
   L2 error estimate          3.5978261897E-03
      effectivity             5.0988053322E-01

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum equations achieved
---------------------------------------------------------
