---------------------------------------------------------
           PHAML   Version 1.11.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   true
  laplacian_operator         false
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    SLAVES
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             LAPACK_INDEFINITE_SOLVER
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

Norms of error:
   energy norm of error       1.0751899822E+00
   Linf norm of error         6.3153592173E-01
   L2 norm of error           1.8609467986E-01

My Grid:
   number of vertices       =          18
   number of vertices I own =          18
   number of elements       =          32
   number of leaf elements  =          20
   leaf elements I own      =          20
   number of levels         =           7
   degrees of freedom       =          18
   degrees of freedom I own =          18
   min and max degree       =           1          1

Norms of error:
   energy norm of error       2.7054097970E-01
      reduced by              2.5162155916E-01
   Linf norm of error         1.0462010432E-01
      reduced by              1.6565978389E-01
   L2 norm of error           9.0373658056E-03
      reduced by              4.8563267968E-02

My Grid:
   number of vertices       =          36
   number of vertices I own =          36
   number of elements       =          98
   number of leaf elements  =          53
   leaf elements I own      =          53
   number of levels         =           9
   degrees of freedom       =          36
   degrees of freedom I own =          36
   min and max degree       =           1          1

Norms of error:
   energy norm of error       1.7288414508E-01
      reduced by              6.3903126718E-01
   Linf norm of error         3.8476697340E-02
      reduced by              3.6777536776E-01
   L2 norm of error           6.8716012146E-03
      reduced by              7.6035443982E-01

My Grid:
   number of vertices       =          73
   number of vertices I own =          73
   number of elements       =         228
   number of leaf elements  =         118
   leaf elements I own      =         118
   number of levels         =          11
   degrees of freedom       =          73
   degrees of freedom I own =          73
   min and max degree       =           1          1

Norms of error:
   energy norm of error       9.3395844902E-02
      reduced by              5.4022215199E-01
   Linf norm of error         1.1969685066E-02
      reduced by              3.1108920188E-01
   L2 norm of error           2.0053199580E-03
      reduced by              2.9182717322E-01

My Grid:
   number of vertices       =         150
   number of vertices I own =         150
   number of elements       =         516
   number of leaf elements  =         262
   leaf elements I own      =         262
   number of levels         =          12
   degrees of freedom       =         150
   degrees of freedom I own =         150
   min and max degree       =           1          1

Norms of error:
   energy norm of error       6.1747506085E-02
      reduced by              6.6113761431E-01
   Linf norm of error         5.3528659941E-03
      reduced by              4.4720190752E-01
   L2 norm of error           8.6021819663E-04
      reduced by              4.2896805231E-01

My Grid:
   number of vertices       =         290
   number of vertices I own =         290
   number of elements       =        1044
   number of leaf elements  =         526
   leaf elements I own      =         526
   number of levels         =          13
   degrees of freedom       =         290
   degrees of freedom I own =         290
   min and max degree       =           1          1

Norms of error:
   energy norm of error       4.1672636354E-02
      reduced by              6.7488776465E-01
   Linf norm of error         2.5382332915E-03
      reduced by              4.7418210998E-01
   L2 norm of error           5.1207859839E-04
      reduced by              5.9528919569E-01

My Grid:
   number of vertices       =         653
   number of vertices I own =         653
   number of elements       =        2450
   number of leaf elements  =        1229
   leaf elements I own      =        1229
   number of levels         =          15
   degrees of freedom       =         653
   degrees of freedom I own =         653
   min and max degree       =           1          1

Norms of error:
   energy norm of error       2.6743457257E-02
      reduced by              6.4175102890E-01
   Linf norm of error         1.1038321515E-03
      reduced by              4.3488207138E-01
   L2 norm of error           2.0464512082E-04
      reduced by              3.9963615247E-01

My Grid:
   number of vertices       =         653
   number of vertices I own =         653
   number of elements       =        2450
   number of leaf elements  =        1229
   leaf elements I own      =        1229
   number of levels         =          15
   degrees of freedom       =         653
   degrees of freedom I own =         653
   min and max degree       =           1          1

Norms of error:
   energy norm of error       2.6743457257E-02
   Linf norm of error         1.1038321515E-03
   L2 norm of error           2.0464512082E-04

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
