---------------------------------------------------------
           PHAML   Version 1.11.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    SLAVES
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NVERT
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                   5
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           6
   degrees of freedom I own =           6
   min and max degree       =           1          1

Norms of error:
   energy norm of error       1.7088498885E+00
   Linf norm of error         5.8044584982E-01
   L2 norm of error           2.0010207062E-01

My Grid:
   number of vertices       =          18
   number of vertices I own =          18
   number of elements       =          36
   number of leaf elements  =          22
   leaf elements I own      =          22
   number of levels         =           4
   degrees of freedom       =          14
   degrees of freedom I own =          14
   min and max degree       =           1          1

Norms of error:
   energy norm of error       1.1069681096E+00
      reduced by              6.4778545916E-01
   Linf norm of error         2.4748552755E-01
      reduced by              4.2637143090E-01
   L2 norm of error           8.3225540651E-02
      reduced by              4.1591543953E-01

My Grid:
   number of vertices       =          44
   number of vertices I own =          44
   number of elements       =         128
   number of leaf elements  =          68
   leaf elements I own      =          68
   number of levels         =           6
   degrees of freedom       =          38
   degrees of freedom I own =          38
   min and max degree       =           1          1

Norms of error:
   energy norm of error       6.1055471357E-01
      reduced by              5.5155582916E-01
   Linf norm of error         7.5519112775E-02
      reduced by              3.0514557164E-01
   L2 norm of error           2.7584420598E-02
      reduced by              3.3144177115E-01

My Grid:
   number of vertices       =          77
   number of vertices I own =          77
   number of elements       =         244
   number of leaf elements  =         126
   leaf elements I own      =         126
   number of levels         =           7
   degrees of freedom       =          68
   degrees of freedom I own =          68
   min and max degree       =           1          1

Norms of error:
   energy norm of error       5.1443976404E-01
      reduced by              8.4257766357E-01
   Linf norm of error         6.4925263981E-02
      reduced by              8.5971963382E-01
   L2 norm of error           1.9408318944E-02
      reduced by              7.0359712197E-01

My Grid:
   number of vertices       =         156
   number of vertices I own =         156
   number of elements       =         532
   number of leaf elements  =         270
   leaf elements I own      =         270
   number of levels         =           8
   degrees of freedom       =         144
   degrees of freedom I own =         144
   min and max degree       =           1          1

Norms of error:
   energy norm of error       3.4705689849E-01
      reduced by              6.7463077847E-01
   Linf norm of error         2.4240543913E-02
      reduced by              3.7336072935E-01
   L2 norm of error           9.3311392002E-03
      reduced by              4.8078039252E-01

My Grid:
   number of vertices       =         290
   number of vertices I own =         290
   number of elements       =        1044
   number of leaf elements  =         526
   leaf elements I own      =         526
   number of levels         =           9
   degrees of freedom       =         274
   degrees of freedom I own =         274
   min and max degree       =           1          1

Norms of error:
   energy norm of error       2.5258132937E-01
      reduced by              7.2778074854E-01
   Linf norm of error         1.5386859160E-02
      reduced by              6.3475717440E-01
   L2 norm of error           4.9722349496E-03
      reduced by              5.3286472776E-01

My Grid:
   number of vertices       =         538
   number of vertices I own =         538
   number of elements       =        2000
   number of leaf elements  =        1004
   leaf elements I own      =        1004
   number of levels         =          10
   degrees of freedom       =         518
   degrees of freedom I own =         518
   min and max degree       =           1          1

Norms of error:
   energy norm of error       1.8432896051E-01
      reduced by              7.2978062541E-01
   Linf norm of error         7.8737883830E-03
      reduced by              5.1172161263E-01
   L2 norm of error           2.7264882689E-03
      reduced by              5.4834260581E-01

My Grid:
   number of vertices       =         538
   number of vertices I own =         538
   number of elements       =        2000
   number of leaf elements  =        1004
   leaf elements I own      =        1004
   number of levels         =          10
   degrees of freedom       =         518
   degrees of freedom I own =         518
   min and max degree       =           1          1

Norms of error:
   energy norm of error       1.8432896051E-01
   Linf norm of error         7.8737883830E-03
   L2 norm of error           2.7264882689E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
