---------------------------------------------------------
           PHAML   Version 1.9.1

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    SLAVES
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NVERT
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                   5
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           6
   degrees of freedom I own =           6
   min and max degree       =           1          1

Norms of error:
   energy norm of error       1.7088498885E+00
   Linf norm of error         5.8044584982E-01
   L2 norm of error           2.0010207062E-01

My Grid:
   number of vertices       =          18
   number of vertices I own =          18
   number of elements       =          36
   number of leaf elements  =          22
   leaf elements I own      =          22
   number of levels         =           4
   degrees of freedom       =          14
   degrees of freedom I own =          14
   min and max degree       =           1          1

Norms of error:
   energy norm of error       1.1069681096E+00
      reduced by              6.4778545916E-01
   Linf norm of error         2.4748552755E-01
      reduced by              4.2637143090E-01
   L2 norm of error           8.3225540651E-02
      reduced by              4.1591543953E-01

My Grid:
   number of vertices       =          44
   number of vertices I own =          44
   number of elements       =         128
   number of leaf elements  =          68
   leaf elements I own      =          68
   number of levels         =           6
   degrees of freedom       =          38
   degrees of freedom I own =          38
   min and max degree       =           1          1

Norms of error:
   energy norm of error       6.1055473460E-01
      reduced by              5.5155584816E-01
   Linf norm of error         7.5517958873E-02
      reduced by              3.0514090913E-01
   L2 norm of error           2.7583612318E-02
      reduced by              3.3143205922E-01

My Grid:
   number of vertices       =          76
   number of vertices I own =          76
   number of elements       =         244
   number of leaf elements  =         126
   leaf elements I own      =         126
   number of levels         =           7
   degrees of freedom       =          68
   degrees of freedom I own =          68
   min and max degree       =           1          1

Norms of error:
   energy norm of error       4.9220226179E-01
      reduced by              8.0615583484E-01
   Linf norm of error         6.4924781548E-02
      reduced by              8.5972638186E-01
   L2 norm of error           1.5865269408E-02
      reduced by              5.7517011278E-01

My Grid:
   number of vertices       =         158
   number of vertices I own =         158
   number of elements       =         540
   number of leaf elements  =         274
   leaf elements I own      =         274
   number of levels         =           8
   degrees of freedom       =         146
   degrees of freedom I own =         146
   min and max degree       =           1          1

Norms of error:
   energy norm of error       3.3631116420E-01
      reduced by              6.8327838026E-01
   Linf norm of error         2.1338435941E-02
      reduced by              3.2866396208E-01
   L2 norm of error           8.8117049781E-03
      reduced by              5.5540846812E-01

My Grid:
   number of vertices       =         338
   number of vertices I own =         338
   number of elements       =        1220
   number of leaf elements  =         614
   leaf elements I own      =         614
   number of levels         =           9
   degrees of freedom       =         318
   degrees of freedom I own =         318
   min and max degree       =           1          1

Norms of error:
   energy norm of error       2.3617571012E-01
      reduced by              7.0225355346E-01
   Linf norm of error         1.5377229919E-02
      reduced by              7.2063528751E-01
   L2 norm of error           4.4811105696E-03
      reduced by              5.0854069454E-01

My Grid:
   number of vertices       =         556
   number of vertices I own =         556
   number of elements       =        2064
   number of leaf elements  =        1036
   leaf elements I own      =        1036
   number of levels         =          10
   degrees of freedom       =         534
   degrees of freedom I own =         534
   min and max degree       =           1          1

Norms of error:
   energy norm of error       1.8193381185E-01
      reduced by              7.7033244340E-01
   Linf norm of error         7.4528774751E-03
      reduced by              4.8466970411E-01
   L2 norm of error           2.7504091817E-03
      reduced by              6.1377846830E-01

My Grid:
   number of vertices       =         556
   number of vertices I own =         556
   number of elements       =        2064
   number of leaf elements  =        1036
   leaf elements I own      =        1036
   number of levels         =          10
   degrees of freedom       =         534
   degrees of freedom I own =         534
   min and max degree       =           1          1

Norms of error:
   energy norm of error       1.8193381185E-01
   Linf norm of error         7.4528774751E-03
   L2 norm of error           2.7504091817E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
