---------------------------------------------------------
           PHAML   Version 1.9.1

Output from the master process
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             LAPACK_INDEFINITE_SOLVER
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.0751899822E+00
   Linf norm of error         6.3153592173E-01
   L2 norm of error           1.8609467986E-01

Total Grid:
   number of vertices      =          24
   number of leaf elements =          32
   number of levels        =           7
   degrees of freedom      =          24
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.6914482344E-01
      reduced by              2.5032303863E-01
   Linf norm of error         1.0424753359E-01
      reduced by              1.6506984005E-01
   L2 norm of error           8.9740998009E-03
      reduced by              4.8223301212E-02

Total Grid:
   number of vertices      =          36
   number of leaf elements =          53
   number of levels        =           9
   degrees of freedom      =          36
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.7288414508E-01
      reduced by              6.4234616469E-01
   Linf norm of error         3.8476697340E-02
      reduced by              3.6908976180E-01
   L2 norm of error           6.8716012146E-03
      reduced by              7.6571482010E-01

Total Grid:
   number of vertices      =          72
   number of leaf elements =         117
   number of levels        =          11
   degrees of freedom      =          72
   min and max degree      =           1          1

Norms of error:
   energy norm of error       9.4206538536E-02
      reduced by              5.4491138265E-01
   Linf norm of error         1.2671378722E-02
      reduced by              3.2932604923E-01
   L2 norm of error           2.1784366451E-03
      reduced by              3.1702023692E-01

Total Grid:
   number of vertices      =         151
   number of leaf elements =         264
   number of levels        =          12
   degrees of freedom      =         151
   min and max degree      =           1          1

Norms of error:
   energy norm of error       6.1187941069E-02
      reduced by              6.4950843137E-01
   Linf norm of error         5.3480774351E-03
      reduced by              4.2205963157E-01
   L2 norm of error           8.5767427001E-04
      reduced by              3.9371090820E-01

Total Grid:
   number of vertices      =         289
   number of leaf elements =         525
   number of levels        =          13
   degrees of freedom      =         289
   min and max degree      =           1          1

Norms of error:
   energy norm of error       4.1962919110E-02
      reduced by              6.8580374461E-01
   Linf norm of error         2.6598114069E-03
      reduced by              4.9733973362E-01
   L2 norm of error           5.1726539530E-04
      reduced by              6.0310238209E-01

Total Grid:
   number of vertices      =         614
   number of leaf elements =        1155
   number of levels        =          14
   degrees of freedom      =         614
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.7488392177E-02
      reduced by              6.5506386973E-01
   Linf norm of error         1.1446267452E-03
      reduced by              4.3034131751E-01
   L2 norm of error           2.1720617391E-04
      reduced by              4.1991243930E-01

Total Grid:
   number of vertices      =         614
   number of leaf elements =        1155
   number of levels        =          14
   degrees of freedom      =         614
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.7488392177E-02
   Linf norm of error         1.1446267452E-03
   L2 norm of error           2.1720617391E-04

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
