---------------------------------------------------------
           PHAML   Version 1.9.1

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                 100
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Norms of error:
   energy norm of error       3.9346234122E-01
   Linf norm of error         5.3440026367E-02
   L2 norm of error           2.0123009324E-02

Total Grid:
   number of vertices      =          21
   number of leaf elements =          28
   number of levels        =           4
   degrees of freedom      =          21
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.3280273006E-01
      reduced by              5.9167728565E-01
   Linf norm of error         4.2320290538E-02
      reduced by              7.9192121366E-01
   L2 norm of error           1.1608381927E-02
      reduced by              5.7687107031E-01

Total Grid:
   number of vertices      =          36
   number of leaf elements =          53
   number of levels        =           5
   degrees of freedom      =          36
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.4619585801E-01
      reduced by              6.2798171641E-01
   Linf norm of error         1.2822757751E-02
      reduced by              3.0299314084E-01
   L2 norm of error           4.2636688982E-03
      reduced by              3.6729226564E-01

Total Grid:
   number of vertices      =          72
   number of leaf elements =         119
   number of levels        =           7
   degrees of freedom      =          72
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.1104185496E-01
      reduced by              7.5954173033E-01
   Linf norm of error         1.2117330064E-02
      reduced by              9.4498627355E-01
   L2 norm of error           3.0509444948E-03
      reduced by              7.1556787537E-01

Total Grid:
   number of vertices      =         165
   number of leaf elements =         291
   number of levels        =           8
   degrees of freedom      =         165
   min and max degree      =           1          1

Norms of error:
   energy norm of error       7.0446849166E-02
      reduced by              6.3441707807E-01
   Linf norm of error         3.0471481547E-03
      reduced by              2.5147026107E-01
   L2 norm of error           1.0045361777E-03
      reduced by              3.2925416355E-01

Total Grid:
   number of vertices      =         299
   number of leaf elements =         546
   number of levels        =           9
   degrees of freedom      =         299
   min and max degree      =           1          1

Norms of error:
   energy norm of error       5.7857992974E-02
      reduced by              4.1064996987E-01
   Linf norm of error         3.3195854983E-03
      reduced by              1.0894073178E+00
   L2 norm of error           8.5531035152E-04
      reduced by              4.2572401598E-01

Total Grid:
   number of vertices      =         643
   number of leaf elements =        1211
   number of levels        =          11
   degrees of freedom      =         643
   min and max degree      =           1          1

Norms of error:
   energy norm of error       3.7464289444E-02
      reduced by              6.4752141438E-01
   Linf norm of error         2.0910310855E-03
      reduced by              6.2990728408E-01
   L2 norm of error           3.5673274844E-04
      reduced by              4.1707989130E-01

Total Grid:
   number of vertices      =         643
   number of leaf elements =        1211
   number of levels        =          11
   degrees of freedom      =         643
   min and max degree      =           1          1

Norms of error:
   energy norm of error       3.7464289444E-02
   Linf norm of error         2.0910310855E-03
   L2 norm of error           3.5673274844E-04

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
