---------------------------------------------------------
           PHAML   Version 1.9.1

Output from the master process
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             LAPACK_INDEFINITE_SOLVER
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.5203581956E+00
   Linf norm of error         8.4136285745E-01
   L2 norm of error           3.4264553346E-01

Total Grid:
   number of vertices      =          29
   number of leaf elements =          40
   number of levels        =           5
   degrees of freedom      =          29
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.4536153585E+00
      reduced by              5.7674951167E-01
   Linf norm of error         2.5719284116E-01
      reduced by              3.0568599372E-01
   L2 norm of error           8.5883795995E-02
      reduced by              2.5064910413E-01

Total Grid:
   number of vertices      =          36
   number of leaf elements =          48
   number of levels        =           6
   degrees of freedom      =          36
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.4261219608E+00
      reduced by              9.8108619482E-01
   Linf norm of error         2.5719334345E-01
      reduced by              1.0000019530E+00
   L2 norm of error           8.5787341950E-02
      reduced by              9.9887692383E-01

Total Grid:
   number of vertices      =          78
   number of leaf elements =         126
   number of levels        =           7
   degrees of freedom      =          78
   min and max degree      =           1          1

Norms of error:
   energy norm of error       8.2031572845E-01
      reduced by              5.7520727608E-01
   Linf norm of error         9.8420949753E-02
      reduced by              3.8267300558E-01
   L2 norm of error           2.6133588389E-02
      reduced by              3.0463221957E-01

Total Grid:
   number of vertices      =         159
   number of leaf elements =         274
   number of levels        =           8
   degrees of freedom      =         159
   min and max degree      =           1          1

Norms of error:
   energy norm of error       4.9639603769E-01
      reduced by              6.0512802629E-01
   Linf norm of error         3.8165053935E-02
      reduced by              3.8777368061E-01
   L2 norm of error           1.2094129148E-02
      reduced by              4.6278103748E-01

Total Grid:
   number of vertices      =         332
   number of leaf elements =         588
   number of levels        =          10
   degrees of freedom      =         332
   min and max degree      =           1          1

Norms of error:
   energy norm of error       3.5934449483E-01
      reduced by              7.2390685570E-01
   Linf norm of error         3.1392803948E-02
      reduced by              8.2255363772E-01
   L2 norm of error           6.2861097975E-03
      reduced by              5.1976539365E-01

Total Grid:
   number of vertices      =         608
   number of leaf elements =        1130
   number of levels        =          11
   degrees of freedom      =         608
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.4749948684E-01
      reduced by              6.8875268830E-01
   Linf norm of error         1.0107110433E-02
      reduced by              3.2195628177E-01
   L2 norm of error           3.1998760227E-03
      reduced by              5.0903915551E-01

Total Grid:
   number of vertices      =         608
   number of leaf elements =        1130
   number of levels        =          11
   degrees of freedom      =         608
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.4749948684E-01
   Linf norm of error         1.0107110433E-02
   L2 norm of error           3.1998760227E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
