---------------------------------------------------------
           PHAML   Version 1.9.1

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NVERT
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                   5
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           6
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.7088498885E+00
   Linf norm of error         5.8044584982E-01
   L2 norm of error           2.0010207062E-01

Total Grid:
   number of vertices      =          18
   number of leaf elements =          22
   number of levels        =           4
   degrees of freedom      =          14
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.1069681096E+00
      reduced by              6.4778545916E-01
   Linf norm of error         2.4748552755E-01
      reduced by              4.2637143090E-01
   L2 norm of error           8.3225540651E-02
      reduced by              4.1591543953E-01

Total Grid:
   number of vertices      =          44
   number of leaf elements =          68
   number of levels        =           6
   degrees of freedom      =          38
   min and max degree      =           1          1

Norms of error:
   energy norm of error       6.1055471357E-01
      reduced by              5.5155582916E-01
   Linf norm of error         7.5519112775E-02
      reduced by              3.0514557164E-01
   L2 norm of error           2.7584420598E-02
      reduced by              3.3144177115E-01

Total Grid:
   number of vertices      =          76
   number of leaf elements =         126
   number of levels        =           7
   degrees of freedom      =          68
   min and max degree      =           1          1

Norms of error:
   energy norm of error       4.9220226179E-01
      reduced by              8.0615586261E-01
   Linf norm of error         6.4924781548E-02
      reduced by              8.5971324559E-01
   L2 norm of error           1.5865269417E-02
      reduced by              5.7515325946E-01

Total Grid:
   number of vertices      =         158
   number of leaf elements =         274
   number of levels        =           8
   degrees of freedom      =         146
   min and max degree      =           1          1

Norms of error:
   energy norm of error       3.3631116404E-01
      reduced by              6.8327837995E-01
   Linf norm of error         2.1338819108E-02
      reduced by              3.2866986379E-01
   L2 norm of error           8.8117856235E-03
      reduced by              5.5541355093E-01

Total Grid:
   number of vertices      =         323
   number of leaf elements =         519
   number of levels        =           9
   degrees of freedom      =         268
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.5968657152E-01
      reduced by              3.8608080743E-01
   Linf norm of error         2.5896608843E-02
      reduced by              1.2135914697E+00
   L2 norm of error           5.3538497926E-03
      reduced by              3.0378915360E-01

Total Grid:
   number of vertices      =         553
   number of leaf elements =         958
   number of levels        =          10
   degrees of freedom      =         495
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.9284356259E-01
      reduced by              7.4260121139E-01
   Linf norm of error         8.8829861262E-03
      reduced by              3.4301734950E-01
   L2 norm of error           2.8241473266E-03
      reduced by              5.2749842375E-01

Total Grid:
   number of vertices      =         553
   number of leaf elements =         958
   number of levels        =          10
   degrees of freedom      =         495
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.9284356259E-01
   Linf norm of error         8.8829861262E-03
   L2 norm of error           2.8241473266E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
