---------------------------------------------------------
           PHAML   Version 1.11.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                  10
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Norms of error:
   energy norm of error       3.5283446257E-01
   Linf norm of error         1.1299483141E-01
   L2 norm of error           8.5230418101E-02

Total Grid:
   number of vertices      =          25
   number of leaf elements =          32
   number of levels        =           3
   degrees of freedom      =          25
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.7094276011E-01
      reduced by              4.8448430707E-01
   Linf norm of error         2.8314571728E-02
      reduced by              2.5058289280E-01
   L2 norm of error           1.9658654025E-02
      reduced by              2.3065302815E-01

Total Grid:
   number of vertices      =          41
   number of leaf elements =          64
   number of levels        =           4
   degrees of freedom      =          41
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.1803974419E-01
      reduced by              6.9052204442E-01
   Linf norm of error         1.6684072505E-02
      reduced by              5.8923979727E-01
   L2 norm of error           1.2451445823E-02
      reduced by              6.3338241812E-01

Total Grid:
   number of vertices      =          81
   number of leaf elements =         128
   number of levels        =           5
   degrees of freedom      =          81
   min and max degree      =           1          1

Norms of error:
   energy norm of error       8.4321069971E-02
      reduced by              7.1434473661E-01
   Linf norm of error         7.1057349359E-03
      reduced by              4.2589930809E-01
   L2 norm of error           4.6473177002E-03
      reduced by              3.7323518619E-01

Total Grid:
   number of vertices      =         145
   number of leaf elements =         256
   number of levels        =           6
   degrees of freedom      =         145
   min and max degree      =           1          1

Norms of error:
   energy norm of error       5.8951227544E-02
      reduced by              6.9912807753E-01
   Linf norm of error         4.1953122640E-03
      reduced by              5.9041215327E-01
   L2 norm of error           3.0361218616E-03
      reduced by              6.5330628493E-01

Total Grid:
   number of vertices      =         289
   number of leaf elements =         512
   number of levels        =           7
   degrees of freedom      =         289
   min and max degree      =           1          1

Norms of error:
   energy norm of error       4.1904500876E-02
      reduced by              3.5541669462E-01
   Linf norm of error         1.7939431458E-03
      reduced by              4.2760658394E-01
   L2 norm of error           1.1187207932E-03
      reduced by              1.8423515988E-01

Total Grid:
   number of vertices      =        1089
   number of leaf elements =        2048
   number of levels        =           9
   degrees of freedom      =        1089
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.0891760896E-02
      reduced by              4.9855649059E-01
   Linf norm of error         4.5388913193E-04
      reduced by              2.5301199371E-01
   L2 norm of error           2.7239003639E-04
      reduced by              2.4348348404E-01

Total Grid:
   number of vertices      =        1089
   number of leaf elements =        2048
   number of levels        =           9
   degrees of freedom      =        1089
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.0891760896E-02
   Linf norm of error         4.5388913193E-04
   L2 norm of error           2.7239003639E-04

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
