---------------------------------------------------------
           PHAML   Version 1.11.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         false
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                 100
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Norms of error:
   energy norm of error       3.9346234122E-01
   Linf norm of error         5.3440026367E-02
   L2 norm of error           2.0123009324E-02

Total Grid:
   number of vertices      =          18
   number of leaf elements =          23
   number of levels        =           4
   degrees of freedom      =          18
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.4364398834E-01
      reduced by              6.1923076954E-01
   Linf norm of error         4.3511561528E-02
      reduced by              8.1421295022E-01
   L2 norm of error           1.2204703920E-02
      reduced by              6.0650490807E-01

Total Grid:
   number of vertices      =          38
   number of leaf elements =          58
   number of levels        =           6
   degrees of freedom      =          38
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.4258744580E-01
      reduced by              5.8522866405E-01
   Linf norm of error         1.1771416428E-02
      reduced by              2.7053537071E-01
   L2 norm of error           4.2058916325E-03
      reduced by              3.4461234455E-01

Total Grid:
   number of vertices      =          80
   number of leaf elements =         133
   number of levels        =           7
   degrees of freedom      =          80
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.0873593491E-01
      reduced by              7.6259122463E-01
   Linf norm of error         1.2131576084E-02
      reduced by              1.0305961189E+00
   L2 norm of error           3.0244118121E-03
      reduced by              7.1908933381E-01

Total Grid:
   number of vertices      =         147
   number of leaf elements =         256
   number of levels        =           8
   degrees of freedom      =         147
   min and max degree      =           1          1

Norms of error:
   energy norm of error       7.4531026253E-02
      reduced by              6.8543141983E-01
   Linf norm of error         3.1876921832E-03
      reduced by              2.6275993829E-01
   L2 norm of error           1.0593273191E-03
      reduced by              3.5025895444E-01

Total Grid:
   number of vertices      =         313
   number of leaf elements =         571
   number of levels        =           9
   degrees of freedom      =         313
   min and max degree      =           1          1

Norms of error:
   energy norm of error       5.6975229941E-02
      reduced by              3.8222491226E-01
   Linf norm of error         3.1024397183E-03
      reduced by              9.7325574113E-01
   L2 norm of error           8.3004398862E-04
      reduced by              3.9177880795E-01

Total Grid:
   number of vertices      =         587
   number of leaf elements =        1101
   number of levels        =          11
   degrees of freedom      =         587
   min and max degree      =           1          1

Norms of error:
   energy norm of error       4.1995578758E-02
      reduced by              7.3708484900E-01
   Linf norm of error         3.2538825511E-03
      reduced by              1.0488141097E+00
   L2 norm of error           5.2733806624E-04
      reduced by              6.3531339720E-01

Total Grid:
   number of vertices      =         587
   number of leaf elements =        1101
   number of levels        =          11
   degrees of freedom      =         587
   min and max degree      =           1          1

Norms of error:
   energy norm of error       4.1995578758E-02
   Linf norm of error         3.2538825511E-03
   L2 norm of error           5.2733806624E-04

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
