---------------------------------------------------------
           PHAML   Version 1.9.1

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    SLAVES
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                 100
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

Norms of error:
   energy norm of error       3.9346234122E-01
   Linf norm of error         5.3440026367E-02
   L2 norm of error           2.0123009324E-02

My Grid:
   number of vertices       =          21
   number of vertices I own =          21
   number of elements       =          48
   number of leaf elements  =          28
   leaf elements I own      =          28
   number of levels         =           4
   degrees of freedom       =          21
   degrees of freedom I own =          21
   min and max degree       =           1          1

Norms of error:
   energy norm of error       2.3280273449E-01
      reduced by              5.9167729692E-01
   Linf norm of error         4.2319992871E-02
      reduced by              7.9191564353E-01
   L2 norm of error           1.1608269467E-02
      reduced by              5.7686548172E-01

My Grid:
   number of vertices       =          36
   number of vertices I own =          36
   number of elements       =          98
   number of leaf elements  =          53
   leaf elements I own      =          53
   number of levels         =           5
   degrees of freedom       =          36
   degrees of freedom I own =          36
   min and max degree       =           1          1

Norms of error:
   energy norm of error       1.4619585801E-01
      reduced by              6.2798170445E-01
   Linf norm of error         1.2822757749E-02
      reduced by              3.0299527196E-01
   L2 norm of error           4.2636688981E-03
      reduced by              3.6729582390E-01

My Grid:
   number of vertices       =          72
   number of vertices I own =          72
   number of elements       =         230
   number of leaf elements  =         119
   leaf elements I own      =         119
   number of levels         =           7
   degrees of freedom       =          72
   degrees of freedom I own =          72
   min and max degree       =           1          1

Norms of error:
   energy norm of error       1.1104185496E-01
      reduced by              7.5954173033E-01
   Linf norm of error         1.2117330064E-02
      reduced by              9.4498627373E-01
   L2 norm of error           3.0509444948E-03
      reduced by              7.1556787539E-01

My Grid:
   number of vertices       =         165
   number of vertices I own =         165
   number of elements       =         574
   number of leaf elements  =         291
   leaf elements I own      =         291
   number of levels         =           8
   degrees of freedom       =         165
   degrees of freedom I own =         165
   min and max degree       =           1          1

Norms of error:
   energy norm of error       7.0446849166E-02
      reduced by              6.3441707807E-01
   Linf norm of error         3.0471481547E-03
      reduced by              2.5147026107E-01
   L2 norm of error           1.0045361777E-03
      reduced by              3.2925416355E-01

My Grid:
   number of vertices       =         296
   number of vertices I own =         296
   number of elements       =        1072
   number of leaf elements  =         540
   leaf elements I own      =         540
   number of levels         =           9
   degrees of freedom       =         296
   degrees of freedom I own =         296
   min and max degree       =           1          1

Norms of error:
   energy norm of error       5.7958661906E-02
      reduced by              8.2272894519E-01
   Linf norm of error         3.3198995199E-03
      reduced by              1.0895103721E+00
   L2 norm of error           8.5526354245E-04
      reduced by              8.5140143427E-01

My Grid:
   number of vertices       =         643
   number of vertices I own =         643
   number of elements       =        2414
   number of leaf elements  =        1211
   leaf elements I own      =        1211
   number of levels         =          11
   degrees of freedom       =         643
   degrees of freedom I own =         643
   min and max degree       =           1          1

Norms of error:
   energy norm of error       3.7466221108E-02
      reduced by              6.4643005680E-01
   Linf norm of error         2.0911332432E-03
      reduced by              6.2987847394E-01
   L2 norm of error           3.5664442114E-04
      reduced by              4.1699944337E-01

My Grid:
   number of vertices       =         643
   number of vertices I own =         643
   number of elements       =        2414
   number of leaf elements  =        1211
   leaf elements I own      =        1211
   number of levels         =          11
   degrees of freedom       =         643
   degrees of freedom I own =         643
   min and max degree       =           1          1

Norms of error:
   energy norm of error       3.7466221108E-02
   Linf norm of error         2.0911332432E-03
   L2 norm of error           3.5664442114E-04

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
