---------------------------------------------------------
           PHAML   Version 1.11.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NVERT
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                   5
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           6
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.7088498885E+00
   Linf norm of error         5.8044584982E-01
   L2 norm of error           2.0010207062E-01

Total Grid:
   number of vertices      =          18
   number of leaf elements =          22
   number of levels        =           4
   degrees of freedom      =          14
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.1069681096E+00
      reduced by              6.4778545916E-01
   Linf norm of error         2.4748552755E-01
      reduced by              4.2637143090E-01
   L2 norm of error           8.3225540651E-02
      reduced by              4.1591543953E-01

Total Grid:
   number of vertices      =          44
   number of leaf elements =          68
   number of levels        =           6
   degrees of freedom      =          38
   min and max degree      =           1          1

Norms of error:
   energy norm of error       6.1055471357E-01
      reduced by              5.5155582916E-01
   Linf norm of error         7.5519112775E-02
      reduced by              3.0514557164E-01
   L2 norm of error           2.7584420598E-02
      reduced by              3.3144177115E-01

Total Grid:
   number of vertices      =          77
   number of leaf elements =         126
   number of levels        =           7
   degrees of freedom      =          68
   min and max degree      =           1          1

Norms of error:
   energy norm of error       5.1443976404E-01
      reduced by              8.4257766357E-01
   Linf norm of error         6.4925263981E-02
      reduced by              8.5971963382E-01
   L2 norm of error           1.9408318944E-02
      reduced by              7.0359712197E-01

Total Grid:
   number of vertices      =         156
   number of leaf elements =         270
   number of levels        =           8
   degrees of freedom      =         144
   min and max degree      =           1          1

Norms of error:
   energy norm of error       3.4705689849E-01
      reduced by              6.7463077847E-01
   Linf norm of error         2.4240543913E-02
      reduced by              3.7336072935E-01
   L2 norm of error           9.3311392002E-03
      reduced by              4.8078039252E-01

Total Grid:
   number of vertices      =         329
   number of leaf elements =         530
   number of levels        =           9
   degrees of freedom      =         276
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.5214449924E-01
      reduced by              3.6326103924E-01
   Linf norm of error         1.5383883096E-02
      reduced by              6.3463440220E-01
   L2 norm of error           4.9711644662E-03
      reduced by              2.6637500307E-01

Total Grid:
   number of vertices      =         594
   number of leaf elements =        1042
   number of levels        =          10
   degrees of freedom      =         537
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.8158439094E-01
      reduced by              7.2016003317E-01
   Linf norm of error         7.9329810688E-03
      reduced by              5.1566831466E-01
   L2 norm of error           2.6769797210E-03
      reduced by              5.3850154006E-01

Total Grid:
   number of vertices      =         594
   number of leaf elements =        1042
   number of levels        =          10
   degrees of freedom      =         537
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.8158439094E-01
   Linf norm of error         7.9329810688E-03
   L2 norm of error           2.6769797210E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
