---------------------------------------------------------
           PHAML   Version 1.9.1

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    SLAVES
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                  10
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

Norms of error:
   energy norm of error       3.5283446257E-01
   Linf norm of error         1.1299483141E-01
   L2 norm of error           8.5230418101E-02

My Grid:
   number of vertices       =          25
   number of vertices I own =          25
   number of elements       =          56
   number of leaf elements  =          32
   leaf elements I own      =          32
   number of levels         =           3
   degrees of freedom       =          25
   degrees of freedom I own =          25
   min and max degree       =           1          1

Norms of error:
   energy norm of error       1.7094373300E-01
      reduced by              4.8448706444E-01
   Linf norm of error         2.8308128653E-02
      reduced by              2.5052587183E-01
   L2 norm of error           1.9650660099E-02
      reduced by              2.3055923620E-01

My Grid:
   number of vertices       =          41
   number of vertices I own =          41
   number of elements       =         120
   number of leaf elements  =          64
   leaf elements I own      =          64
   number of levels         =           4
   degrees of freedom       =          41
   degrees of freedom I own =          41
   min and max degree       =           1          1

Norms of error:
   energy norm of error       1.1804008451E-01
      reduced by              6.9052010529E-01
   Linf norm of error         1.6683563868E-02
      reduced by              5.8935594340E-01
   L2 norm of error           1.2448101788E-02
      reduced by              6.3346990509E-01

My Grid:
   number of vertices       =          81
   number of vertices I own =          81
   number of elements       =         248
   number of leaf elements  =         128
   leaf elements I own      =         128
   number of levels         =           5
   degrees of freedom       =          81
   degrees of freedom I own =          81
   min and max degree       =           1          1

Norms of error:
   energy norm of error       8.4321144677E-02
      reduced by              7.1434330996E-01
   Linf norm of error         7.1048140387E-03
      reduced by              4.2585709474E-01
   L2 norm of error           4.6461799238E-03
      reduced by              3.7324404982E-01

My Grid:
   number of vertices       =         145
   number of vertices I own =         145
   number of elements       =         504
   number of leaf elements  =         256
   leaf elements I own      =         256
   number of levels         =           6
   degrees of freedom       =         145
   degrees of freedom I own =         145
   min and max degree       =           1          1

Norms of error:
   energy norm of error       5.8951263238E-02
      reduced by              6.9912788143E-01
   Linf norm of error         4.1952657584E-03
      reduced by              5.9048213444E-01
   L2 norm of error           3.0355123076E-03
      reduced by              6.5333507470E-01

My Grid:
   number of vertices       =         289
   number of vertices I own =         289
   number of elements       =        1016
   number of leaf elements  =         512
   leaf elements I own      =         512
   number of levels         =           7
   degrees of freedom       =         289
   degrees of freedom I own =         289
   min and max degree       =           1          1

Norms of error:
   energy norm of error       4.1904502916E-02
      reduced by              7.1083299347E-01
   Linf norm of error         1.7938935963E-03
      reduced by              4.2759951327E-01
   L2 norm of error           1.1186609122E-03
      reduced by              3.6852458459E-01

My Grid:
   number of vertices       =        1089
   number of vertices I own =        1089
   number of elements       =        4088
   number of leaf elements  =        2048
   leaf elements I own      =        2048
   number of levels         =           9
   degrees of freedom       =        1089
   degrees of freedom I own =        1089
   min and max degree       =           1          1

Norms of error:
   energy norm of error       2.0891761194E-02
      reduced by              4.9855647342E-01
   Linf norm of error         4.5387433586E-04
      reduced by              2.5301073419E-01
   L2 norm of error           2.7237308980E-04
      reduced by              2.4348136851E-01

My Grid:
   number of vertices       =        1089
   number of vertices I own =        1089
   number of elements       =        4088
   number of leaf elements  =        2048
   leaf elements I own      =        2048
   number of levels         =           9
   degrees of freedom       =        1089
   degrees of freedom I own =        1089
   min and max degree       =           1          1

Norms of error:
   energy norm of error       2.0891761194E-02
   Linf norm of error         4.5387433586E-04
   L2 norm of error           2.7237308980E-04

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
