---------------------------------------------------------
           PHAML   Version 1.11.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NVERT
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                   5
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           4
   min and max degree      =           1          1

Norms of error:
   energy norm of error       4.0521843865E+00
   Linf norm of error         1.5184935038E+00
   L2 norm of error           8.2092116132E-01

Total Grid:
   number of vertices      =          25
   number of leaf elements =          32
   number of levels        =           3
   degrees of freedom      =          16
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.7707506114E+00
      reduced by              6.8376716041E-01
   Linf norm of error         4.6345499881E-01
      reduced by              3.0520710010E-01
   L2 norm of error           2.3433384381E-01
      reduced by              2.8545231242E-01

Total Grid:
   number of vertices      =          49
   number of leaf elements =          72
   number of levels        =           5
   degrees of freedom      =          36
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.3686777451E+00
      reduced by              8.5488666331E-01
   Linf norm of error         3.6311712059E-01
      reduced by              7.8350027840E-01
   L2 norm of error           1.7338308060E-01
      reduced by              7.3989773644E-01

Total Grid:
   number of vertices      =          87
   number of leaf elements =         140
   number of levels        =           6
   degrees of freedom      =          70
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.5554085466E+00
      reduced by              6.5665688370E-01
   Linf norm of error         1.4425822646E-01
      reduced by              3.9727740247E-01
   L2 norm of error           7.1280912968E-02
      reduced by              4.1111804404E-01

Total Grid:
   number of vertices      =         173
   number of leaf elements =         296
   number of levels        =           7
   degrees of freedom      =         148
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.1672669305E+00
      reduced by              7.5045680638E-01
   Linf norm of error         1.1743841888E-01
      reduced by              8.1408472684E-01
   L2 norm of error           4.0783417339E-02
      reduced by              5.7215060303E-01

Total Grid:
   number of vertices      =         328
   number of leaf elements =         448
   number of levels        =           8
   degrees of freedom      =         224
   min and max degree      =           1          1

Norms of error:
   energy norm of error       9.4683238734E-01
      reduced by              4.0557663488E-01
   Linf norm of error         8.9359415526E-02
      reduced by              7.6090444996E-01
   L2 norm of error           2.7986264966E-02
      reduced by              3.4310838561E-01

Total Grid:
   number of vertices      =         556
   number of leaf elements =         888
   number of levels        =           9
   degrees of freedom      =         444
   min and max degree      =           1          1

Norms of error:
   energy norm of error       7.1013673110E-01
      reduced by              7.5001313918E-01
   Linf norm of error         3.3946720452E-02
      reduced by              3.7988968765E-01
   L2 norm of error           1.5059844209E-02
      reduced by              5.3811554445E-01

Total Grid:
   number of vertices      =         556
   number of leaf elements =         888
   number of levels        =           9
   degrees of freedom      =         444
   min and max degree      =           1          1

Norms of error:
   energy norm of error       7.1013673110E-01
   Linf norm of error         3.3946720452E-02
   L2 norm of error           1.5059844209E-02

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
