---------------------------------------------------------
           PHAML   Version 1.11.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         false
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    SLAVES
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                 100
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

Norms of error:
   energy norm of error       3.9346234122E-01
   Linf norm of error         5.3440026367E-02
   L2 norm of error           2.0123009324E-02

My Grid:
   number of vertices       =          18
   number of vertices I own =          18
   number of elements       =          38
   number of leaf elements  =          23
   leaf elements I own      =          23
   number of levels         =           4
   degrees of freedom       =          18
   degrees of freedom I own =          18
   min and max degree       =           1          1

Norms of error:
   energy norm of error       2.4364398272E-01
      reduced by              6.1923075526E-01
   Linf norm of error         4.3510768121E-02
      reduced by              8.1419810353E-01
   L2 norm of error           1.2204728165E-02
      reduced by              6.0650611290E-01

My Grid:
   number of vertices       =          38
   number of vertices I own =          38
   number of elements       =         108
   number of leaf elements  =          58
   leaf elements I own      =          58
   number of levels         =           6
   degrees of freedom       =          38
   degrees of freedom I own =          38
   min and max degree       =           1          1

Norms of error:
   energy norm of error       1.4258744579E-01
      reduced by              5.8522867752E-01
   Linf norm of error         1.1771445587E-02
      reduced by              2.7054097400E-01
   L2 norm of error           4.2058847496E-03
      reduced by              3.4461109602E-01

My Grid:
   number of vertices       =          80
   number of vertices I own =          80
   number of elements       =         258
   number of leaf elements  =         133
   leaf elements I own      =         133
   number of levels         =           7
   degrees of freedom       =          80
   degrees of freedom I own =          80
   min and max degree       =           1          1

Norms of error:
   energy norm of error       1.0873593496E-01
      reduced by              7.6259122500E-01
   Linf norm of error         1.2131588022E-02
      reduced by              1.0305945801E+00
   L2 norm of error           3.0244185936E-03
      reduced by              7.1909212298E-01

My Grid:
   number of vertices       =         147
   number of vertices I own =         147
   number of elements       =         504
   number of leaf elements  =         256
   leaf elements I own      =         256
   number of levels         =           8
   degrees of freedom       =         147
   degrees of freedom I own =         147
   min and max degree       =           1          1

Norms of error:
   energy norm of error       7.4531026251E-02
      reduced by              6.8543141952E-01
   Linf norm of error         3.1876905102E-03
      reduced by              2.6275954183E-01
   L2 norm of error           1.0593273244E-03
      reduced by              3.5025817083E-01

My Grid:
   number of vertices       =         313
   number of vertices I own =         313
   number of elements       =        1134
   number of leaf elements  =         571
   leaf elements I own      =         571
   number of levels         =           9
   degrees of freedom       =         313
   degrees of freedom I own =         313
   min and max degree       =           1          1

Norms of error:
   energy norm of error       5.6975229941E-02
      reduced by              7.6444982455E-01
   Linf norm of error         3.1024397920E-03
      reduced by              9.7325627505E-01
   L2 norm of error           8.3004398304E-04
      reduced by              7.8355760670E-01

My Grid:
   number of vertices       =         587
   number of vertices I own =         587
   number of elements       =        2194
   number of leaf elements  =        1101
   leaf elements I own      =        1101
   number of levels         =          11
   degrees of freedom       =         587
   degrees of freedom I own =         587
   min and max degree       =           1          1

Norms of error:
   energy norm of error       4.1995578758E-02
      reduced by              7.3708484900E-01
   Linf norm of error         3.2538825408E-03
      reduced by              1.0488140815E+00
   L2 norm of error           5.2733806477E-04
      reduced by              6.3531339971E-01

My Grid:
   number of vertices       =         587
   number of vertices I own =         587
   number of elements       =        2194
   number of leaf elements  =        1101
   leaf elements I own      =        1101
   number of levels         =          11
   degrees of freedom       =         587
   degrees of freedom I own =         587
   min and max degree       =           1          1

Norms of error:
   energy norm of error       4.1995578758E-02
   Linf norm of error         3.2538825408E-03
   L2 norm of error           5.2733806477E-04

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
