---------------------------------------------------------
           PHAML   Version 1.11.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  true
  pde_has_cross_derivative   false
  laplacian_operator         false
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    SLAVES
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             LAPACK_INDEFINITE_SOLVER
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

Norms of error:
   energy norm of error       2.5203581956E+00
   Linf norm of error         8.4136285745E-01
   L2 norm of error           3.4264553346E-01

My Grid:
   number of vertices       =          29
   number of vertices I own =          29
   number of elements       =          72
   number of leaf elements  =          40
   leaf elements I own      =          40
   number of levels         =           5
   degrees of freedom       =          29
   degrees of freedom I own =          29
   min and max degree       =           1          1

Norms of error:
   energy norm of error       1.4536153585E+00
      reduced by              5.7674951167E-01
   Linf norm of error         2.5719284116E-01
      reduced by              3.0568599372E-01
   L2 norm of error           8.5883795995E-02
      reduced by              2.5064910413E-01

My Grid:
   number of vertices       =          36
   number of vertices I own =          36
   number of elements       =          88
   number of leaf elements  =          48
   leaf elements I own      =          48
   number of levels         =           6
   degrees of freedom       =          36
   degrees of freedom I own =          36
   min and max degree       =           1          1

Norms of error:
   energy norm of error       1.4261219608E+00
      reduced by              9.8108619482E-01
   Linf norm of error         2.5719334345E-01
      reduced by              1.0000019530E+00
   L2 norm of error           8.5787341950E-02
      reduced by              9.9887692383E-01

My Grid:
   number of vertices       =          81
   number of vertices I own =          81
   number of elements       =         252
   number of leaf elements  =         130
   leaf elements I own      =         130
   number of levels         =           7
   degrees of freedom       =          81
   degrees of freedom I own =          81
   min and max degree       =           1          1

Norms of error:
   energy norm of error       8.1786715507E-01
      reduced by              5.7349033080E-01
   Linf norm of error         9.8446528962E-02
      reduced by              3.8277246075E-01
   L2 norm of error           2.5683491954E-02
      reduced by              2.9938556634E-01

My Grid:
   number of vertices       =         167
   number of vertices I own =         167
   number of elements       =         568
   number of leaf elements  =         288
   leaf elements I own      =         288
   number of levels         =           9
   degrees of freedom       =         167
   degrees of freedom I own =         167
   min and max degree       =           1          1

Norms of error:
   energy norm of error       4.8542376003E-01
      reduced by              5.9352396904E-01
   Linf norm of error         3.2156415690E-02
      reduced by              3.2663838968E-01
   L2 norm of error           1.1599378505E-02
      reduced by              4.5162778198E-01

My Grid:
   number of vertices       =         312
   number of vertices I own =         312
   number of elements       =        1088
   number of leaf elements  =         548
   leaf elements I own      =         548
   number of levels         =          10
   degrees of freedom       =         312
   degrees of freedom I own =         312
   min and max degree       =           1          1

Norms of error:
   energy norm of error       3.3449297489E-01
      reduced by              6.8907417072E-01
   Linf norm of error         3.1421707829E-02
      reduced by              9.7715205986E-01
   L2 norm of error           7.9095989268E-03
      reduced by              6.8189851065E-01

My Grid:
   number of vertices       =         586
   number of vertices I own =         586
   number of elements       =        2160
   number of leaf elements  =        1084
   leaf elements I own      =        1084
   number of levels         =          11
   degrees of freedom       =         586
   degrees of freedom I own =         586
   min and max degree       =           1          1

Norms of error:
   energy norm of error       2.4874341529E-01
      reduced by              7.4364316731E-01
   Linf norm of error         1.0113302954E-02
      reduced by              3.2185720167E-01
   L2 norm of error           3.1794705897E-03
      reduced by              4.0197620880E-01

My Grid:
   number of vertices       =         586
   number of vertices I own =         586
   number of elements       =        2160
   number of leaf elements  =        1084
   leaf elements I own      =        1084
   number of levels         =          11
   degrees of freedom       =         586
   degrees of freedom I own =         586
   min and max degree       =           1          1

Norms of error:
   energy norm of error       2.4874341529E-01
   Linf norm of error         1.0113302954E-02
   L2 norm of error           3.1794705897E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
