---------------------------------------------------------
           PHAML   Version 1.11.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                    500
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    21
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    SLAVES
  print_error_what   ENERGY_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          1.0000000000E+01
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            HP_ADAPTIVE
  edge_rule          MINIMUM_RULE
  hp_strategy        HP_REFSOLN_ELEM
  refsoln_pbias       4.0000000000E+00
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

Norms of error:
   energy norm of error       4.0333158308E+00
   L2 norm of error           4.5345860840E-01

My Grid:
   number of vertices       =          11
   number of vertices I own =          11
   number of elements       =          16
   number of leaf elements  =          12
   leaf elements I own      =          12
   number of levels         =           2
   degrees of freedom       =          14
   degrees of freedom I own =          14
   min and max degree       =           1          2

Norms of error:
   energy norm of error       3.7822859151E+00
      reduced by              9.3776090785E-01
   L2 norm of error           2.8094688516E-01
      reduced by              6.1956456433E-01

My Grid:
   number of vertices       =          16
   number of vertices I own =          16
   number of elements       =          32
   number of leaf elements  =          20
   leaf elements I own      =          20
   number of levels         =           3
   degrees of freedom       =          34
   degrees of freedom I own =          34
   min and max degree       =           1          2

Norms of error:
   energy norm of error       2.8783221240E+00
      reduced by              7.6100067224E-01
   L2 norm of error           1.6674053602E-01
      reduced by              5.9349487334E-01

My Grid:
   number of vertices       =          18
   number of vertices I own =          18
   number of elements       =          36
   number of leaf elements  =          22
   leaf elements I own      =          22
   number of levels         =           3
   degrees of freedom       =          61
   degrees of freedom I own =          61
   min and max degree       =           1          3

Norms of error:
   energy norm of error       1.3305259188E+00
      reduced by              4.6225747553E-01
   L2 norm of error           4.9663027422E-02
      reduced by              2.9784615431E-01

My Grid:
   number of vertices       =          22
   number of vertices I own =          22
   number of elements       =          48
   number of leaf elements  =          28
   leaf elements I own      =          28
   number of levels         =           4
   degrees of freedom       =         115
   degrees of freedom I own =         115
   min and max degree       =           1          3

Norms of error:
   energy norm of error       7.1974905489E-01
      reduced by              5.4095079601E-01
   L2 norm of error           1.9054567295E-02
      reduced by              3.8367711927E-01

My Grid:
   number of vertices       =          24
   number of vertices I own =          24
   number of elements       =          56
   number of leaf elements  =          32
   leaf elements I own      =          32
   number of levels         =           4
   degrees of freedom       =         180
   degrees of freedom I own =         180
   min and max degree       =           1          4

Norms of error:
   energy norm of error       5.6535332151E-01
      reduced by              7.8548671605E-01
   L2 norm of error           1.5076025231E-02
      reduced by              7.9120270734E-01

My Grid:
   number of vertices       =          27
   number of vertices I own =          27
   number of elements       =          68
   number of leaf elements  =          38
   leaf elements I own      =          38
   number of levels         =           4
   degrees of freedom       =         243
   degrees of freedom I own =         243
   min and max degree       =           1          5

Norms of error:
   energy norm of error       2.2830768477E-01
      reduced by              4.0383186246E-01
   L2 norm of error           4.0743855624E-03
      reduced by              2.7025595274E-01

My Grid:
   number of vertices       =          32
   number of vertices I own =          32
   number of elements       =          88
   number of leaf elements  =          48
   leaf elements I own      =          48
   number of levels         =           4
   degrees of freedom       =         366
   degrees of freedom I own =         366
   min and max degree       =           1          6

Norms of error:
   energy norm of error       5.0949373414E-02
      reduced by              2.2316100952E-01
   L2 norm of error           1.0469796952E-03
      reduced by              2.5696627852E-01

My Grid:
   number of vertices       =          34
   number of vertices I own =          34
   number of elements       =          96
   number of leaf elements  =          52
   leaf elements I own      =          52
   number of levels         =           4
   degrees of freedom       =         541
   degrees of freedom I own =         541
   min and max degree       =           1          8

Norms of error:
   energy norm of error       9.6877789972E-03
      reduced by              1.9014520391E-01
   L2 norm of error           1.0851702388E-04
      reduced by              1.0364768712E-01

My Grid:
   number of vertices       =          34
   number of vertices I own =          34
   number of elements       =          96
   number of leaf elements  =          52
   leaf elements I own      =          52
   number of levels         =           4
   degrees of freedom       =         541
   degrees of freedom I own =         541
   min and max degree       =           1          8

Norms of error:
   energy norm of error       9.6877789972E-03
   L2 norm of error           1.0851702388E-04

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           8
termination condition:
  maximum equations achieved
---------------------------------------------------------
