---------------------------------------------------------
           PHAML   Version 1.11.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                   5000
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            HP_ADAPTIVE
  edge_rule          MINIMUM_RULE
  hp_strategy        HP_T3S
  t3s_gamma           6.0000000000E+00
  t3s_eta             1.0000000000E-01
  t3s_nunif                    4
  t3s_maxref                   3
  t3s_maxdeginc                3
  refterm            DOUBLE_NEQ
  derefine           false
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.4815470230E+00
   L2 norm of error           9.1696901478E-02

Total Grid:
   number of vertices      =         124
   number of leaf elements =         198
   number of levels        =           8
   degrees of freedom      =         124
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.7801087694E+00
      reduced by              7.1733831878E-01
   L2 norm of error           4.8758583234E-02
      reduced by              5.3173643218E-01

Total Grid:
   number of vertices      =         124
   number of leaf elements =         198
   number of levels        =           8
   degrees of freedom      =         554
   min and max degree      =           1          4

Norms of error:
   energy norm of error       3.3651382288E-01
      reduced by              9.4520578929E-02
   L2 norm of error           7.0295570064E-03
      reduced by              7.2085328779E-02

Total Grid:
   number of vertices      =         397
   number of leaf elements =         738
   number of levels        =          11
   degrees of freedom      =        1415
   min and max degree      =           1          4

Norms of error:
   energy norm of error       1.3950849652E-01
      reduced by              4.1456988400E-01
   L2 norm of error           1.5469935577E-03
      reduced by              2.2006985025E-01

Total Grid:
   number of vertices      =         397
   number of leaf elements =         738
   number of levels        =          11
   degrees of freedom      =        5081
   min and max degree      =           1          7

Norms of error:
   energy norm of error       9.8177710872E-03
      reduced by              7.0374001099E-02
   L2 norm of error           2.1911221518E-04
      reduced by              1.4163744515E-01

Total Grid:
   number of vertices      =         397
   number of leaf elements =         738
   number of levels        =          11
   degrees of freedom      =        5081
   min and max degree      =           1          7

Norms of error:
   energy norm of error       9.8177710872E-03
   L2 norm of error           2.1911221518E-04

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           4
termination condition:
  maximum equations achieved
---------------------------------------------------------
