---------------------------------------------------------
           PHAML   Version 1.11.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                   5000
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree                      3
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            HP_ADAPTIVE
  edge_rule          MINIMUM_RULE
  hp_strategy        HP_PRIOR2P_E
  refterm            DOUBLE_NEQ
  derefine           false
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =          49
   min and max degree      =           3          3

Norms of error:
   energy norm of error       1.5715470748E+00
   L2 norm of error           8.2689297175E-02

Total Grid:
   number of vertices      =          21
   number of leaf elements =          26
   number of levels        =           3
   degrees of freedom      =         139
   min and max degree      =           3          3

Norms of error:
   energy norm of error       5.6882149358E-01
      reduced by              3.6195001900E-01
   L2 norm of error           1.3874161826E-02
      reduced by              1.6778667010E-01

Total Grid:
   number of vertices      =          28
   number of leaf elements =          40
   number of levels        =           4
   degrees of freedom      =         202
   min and max degree      =           3          3

Norms of error:
   energy norm of error       3.1933469478E-01
      reduced by              5.6139702593E-01
   L2 norm of error           5.8001516124E-03
      reduced by              4.1805419924E-01

Total Grid:
   number of vertices      =          59
   number of leaf elements =          92
   number of levels        =           6
   degrees of freedom      =         451
   min and max degree      =           3          3

Norms of error:
   energy norm of error       6.7971007660E-02
      reduced by              2.1285193489E-01
   L2 norm of error           6.0777282502E-04
      reduced by              1.0478567900E-01

Total Grid:
   number of vertices      =         108
   number of leaf elements =         172
   number of levels        =           8
   degrees of freedom      =         838
   min and max degree      =           3          3

Norms of error:
   energy norm of error       2.0233600737E-02
      reduced by              2.9767987019E-01
   L2 norm of error           1.5452351484E-04
      reduced by              2.5424551491E-01

Total Grid:
   number of vertices      =         193
   number of leaf elements =         342
   number of levels        =           9
   degrees of freedom      =        1613
   min and max degree      =           3          4

Norms of error:
   energy norm of error       1.1513338456E-02
      reduced by              2.8451036981E-01
   L2 norm of error           7.1676520166E-05
      reduced by              2.3192754914E-01

Total Grid:
   number of vertices      =         354
   number of leaf elements =         651
   number of levels        =           9
   degrees of freedom      =        3970
   min and max degree      =           3          6

Norms of error:
   energy norm of error       1.5171151112E-03
      reduced by              1.3177021738E-01
   L2 norm of error           6.5162703512E-06
      reduced by              9.0912202994E-02

Total Grid:
   number of vertices      =         451
   number of leaf elements =         837
   number of levels        =          11
   degrees of freedom      =        5320
   min and max degree      =           3          6

Norms of error:
   energy norm of error       8.5153570080E-04
      reduced by              5.6128615060E-01
   L2 norm of error           4.0468540253E-06
      reduced by              6.2103838656E-01

Total Grid:
   number of vertices      =         451
   number of leaf elements =         837
   number of levels        =          11
   degrees of freedom      =        5320
   min and max degree      =           3          6

Norms of error:
   energy norm of error       8.5153570080E-04
   L2 norm of error           4.0468540253E-06

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           7
termination condition:
  maximum equations achieved
---------------------------------------------------------
