---------------------------------------------------------
           PHAML   Version 1.11.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                   5000
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            HP_ADAPTIVE
  edge_rule          MINIMUM_RULE
  hp_strategy        HP_TYPEPARAM
  tp_gamma            2.0000000000E-01
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Norms of error:
   energy norm of error       4.0333158308E+00
   L2 norm of error           4.5345860840E-01

Total Grid:
   number of vertices      =          12
   number of leaf elements =          14
   number of levels        =           2
   degrees of freedom      =          32
   min and max degree      =           1          2

Norms of error:
   energy norm of error       2.1059295444E+00
      reduced by              5.2213355779E-01
   L2 norm of error           1.0099304273E-01
      reduced by              2.2271722460E-01

Total Grid:
   number of vertices      =          16
   number of leaf elements =          18
   number of levels        =           3
   degrees of freedom      =          44
   min and max degree      =           1          2

Norms of error:
   energy norm of error       1.9925834787E+00
      reduced by              9.4617765536E-01
   L2 norm of error           9.3204715763E-02
      reduced by              9.2288253962E-01

Total Grid:
   number of vertices      =          27
   number of leaf elements =          38
   number of levels        =           4
   degrees of freedom      =          86
   min and max degree      =           1          2

Norms of error:
   energy norm of error       1.1931560391E+00
      reduced by              5.9879852057E-01
   L2 norm of error           3.2006417294E-02
      reduced by              3.4339911915E-01

Total Grid:
   number of vertices      =          58
   number of leaf elements =          90
   number of levels        =           6
   degrees of freedom      =         196
   min and max degree      =           1          2

Norms of error:
   energy norm of error       4.7452184719E-01
      reduced by              3.9770309299E-01
   L2 norm of error           6.7019997787E-03
      reduced by              2.0939550082E-01

Total Grid:
   number of vertices      =          74
   number of leaf elements =         106
   number of levels        =           7
   degrees of freedom      =         352
   min and max degree      =           1          4

Norms of error:
   energy norm of error       1.7920770933E-01
      reduced by              3.7765955434E-01
   L2 norm of error           2.1393160691E-03
      reduced by              3.1920563111E-01

Total Grid:
   number of vertices      =         135
   number of leaf elements =         227
   number of levels        =           8
   degrees of freedom      =        1092
   min and max degree      =           1          4

Norms of error:
   energy norm of error       6.0518520569E-02
      reduced by              3.3770043038E-01
   L2 norm of error           1.1511668754E-03
      reduced by              5.3810042004E-01

Total Grid:
   number of vertices      =         157
   number of leaf elements =         271
   number of levels        =           8
   degrees of freedom      =        1247
   min and max degree      =           1          4

Norms of error:
   energy norm of error       3.9029120925E-02
      reduced by              3.2245600651E-01
   L2 norm of error           7.4462215037E-04
      reduced by              3.2342059449E-01

Total Grid:
   number of vertices      =         228
   number of leaf elements =         410
   number of levels        =           8
   degrees of freedom      =        2337
   min and max degree      =           1          7

Norms of error:
   energy norm of error       8.1531141000E-03
      reduced by              2.0889822540E-01
   L2 norm of error           5.0617215308E-05
      reduced by              6.7977047531E-02

Total Grid:
   number of vertices      =         303
   number of leaf elements =         528
   number of levels        =           9
   degrees of freedom      =        4744
   min and max degree      =           1         10

Norms of error:
   energy norm of error       1.0643425691E-03
      reduced by              1.3054429952E-01
   L2 norm of error           7.9684543917E-06
      reduced by              1.5742577586E-01

Total Grid:
   number of vertices      =         305
   number of leaf elements =         532
   number of levels        =           9
   degrees of freedom      =        5005
   min and max degree      =           1         10

Norms of error:
   energy norm of error       6.1421845486E-04
      reduced by              5.7708718292E-01
   L2 norm of error           6.3642266246E-06
      reduced by              7.9867767471E-01

Total Grid:
   number of vertices      =         305
   number of leaf elements =         532
   number of levels        =           9
   degrees of freedom      =        5005
   min and max degree      =           1         10

Norms of error:
   energy norm of error       6.1421845486E-04
   L2 norm of error           6.3642266246E-06

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =          10
termination condition:
  maximum equations achieved
---------------------------------------------------------
