---------------------------------------------------------
           PHAML   Version 1.11.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                   2000
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    SLAVES
  print_error_what   ENERGY_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            HP_ADAPTIVE
  edge_rule          MINIMUM_RULE
  hp_strategy        HP_APRIORI
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

Norms of error:
   energy norm of error       4.0333158308E+00
   L2 norm of error           4.5345860840E-01

My Grid:
   number of vertices       =          13
   number of vertices I own =          13
   number of elements       =          20
   number of leaf elements  =          14
   leaf elements I own      =          14
   number of levels         =           4
   degrees of freedom       =          19
   degrees of freedom I own =          19
   min and max degree       =           1          3

Norms of error:
   energy norm of error       3.3925768582E+00
      reduced by              8.4113840833E-01
   L2 norm of error           2.9367978425E-01
      reduced by              6.4764408218E-01

My Grid:
   number of vertices       =          16
   number of vertices I own =          16
   number of elements       =          28
   number of leaf elements  =          18
   leaf elements I own      =          18
   number of levels         =           6
   degrees of freedom       =          38
   degrees of freedom I own =          38
   min and max degree       =           1          4

Norms of error:
   energy norm of error       2.9076732501E+00
      reduced by              8.5706923427E-01
   L2 norm of error           2.0501256959E-01
      reduced by              6.9808199471E-01

My Grid:
   number of vertices       =          18
   number of vertices I own =          18
   number of elements       =          32
   number of leaf elements  =          20
   leaf elements I own      =          20
   number of levels         =           7
   degrees of freedom       =          89
   degrees of freedom I own =          89
   min and max degree       =           1          6

Norms of error:
   energy norm of error       1.3165541641E+00
      reduced by              4.5278614580E-01
   L2 norm of error           4.8815848589E-02
      reduced by              2.3811149085E-01

My Grid:
   number of vertices       =          21
   number of vertices I own =          21
   number of elements       =          40
   number of leaf elements  =          24
   leaf elements I own      =          24
   number of levels         =           9
   degrees of freedom       =         175
   degrees of freedom I own =         175
   min and max degree       =           1          7

Norms of error:
   energy norm of error       4.5155911666E-01
      reduced by              3.4298559753E-01
   L2 norm of error           1.0538853599E-02
      reduced by              2.1589000098E-01

My Grid:
   number of vertices       =          24
   number of vertices I own =          24
   number of elements       =          48
   number of leaf elements  =          28
   leaf elements I own      =          28
   number of levels         =          11
   degrees of freedom       =         344
   degrees of freedom I own =         344
   min and max degree       =           1          9

Norms of error:
   energy norm of error       6.1650985716E-02
      reduced by              1.3652915741E-01
   L2 norm of error           4.9425651501E-04
      reduced by              4.6898508491E-02

My Grid:
   number of vertices       =          30
   number of vertices I own =          30
   number of elements       =          64
   number of leaf elements  =          36
   leaf elements I own      =          36
   number of levels         =          15
   degrees of freedom       =         661
   degrees of freedom I own =         661
   min and max degree       =           1         10

Norms of error:
   energy norm of error       1.1175995875E-02
      reduced by              1.8127846206E-01
   L2 norm of error           1.3996817830E-04
      reduced by              2.8318934408E-01

My Grid:
   number of vertices       =          36
   number of vertices I own =          36
   number of elements       =          80
   number of leaf elements  =          44
   leaf elements I own      =          44
   number of levels         =          19
   degrees of freedom       =        1280
   degrees of freedom I own =        1280
   min and max degree       =           1         15

Norms of error:
   energy norm of error       2.8924498785E-04
      reduced by              2.5880913977E-02
   L2 norm of error           1.2328566753E-06
      reduced by              8.8081211769E-03

My Grid:
   number of vertices       =          48
   number of vertices I own =          48
   number of elements       =         112
   number of leaf elements  =          60
   leaf elements I own      =          60
   number of levels         =          27
   degrees of freedom       =        2059
   degrees of freedom I own =        2059
   min and max degree       =           1         15

Norms of error:
   energy norm of error       1.4679646784E-06
      reduced by              5.0751602968E-03
   L2 norm of error           2.3943660780E-08
      reduced by              1.9421284939E-02

My Grid:
   number of vertices       =          48
   number of vertices I own =          48
   number of elements       =         112
   number of leaf elements  =          60
   leaf elements I own      =          60
   number of levels         =          27
   degrees of freedom       =        2059
   degrees of freedom I own =        2059
   min and max degree       =           1         15

Norms of error:
   energy norm of error       1.4679646784E-06
   L2 norm of error           2.3943660780E-08

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           8
termination condition:
  maximum equations achieved
---------------------------------------------------------
