---------------------------------------------------------
           PHAML   Version 1.11.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                   2000
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            HP_ADAPTIVE
  edge_rule          MINIMUM_RULE
  hp_strategy        HP_APRIORI
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Norms of error:
   energy norm of error       4.0333158308E+00
   L2 norm of error           4.5345860840E-01

Total Grid:
   number of vertices      =          13
   number of leaf elements =          14
   number of levels        =           4
   degrees of freedom      =          19
   min and max degree      =           1          3

Norms of error:
   energy norm of error       3.3925768582E+00
      reduced by              8.4113840833E-01
   L2 norm of error           2.9367978425E-01
      reduced by              6.4764408218E-01

Total Grid:
   number of vertices      =          16
   number of leaf elements =          18
   number of levels        =           6
   degrees of freedom      =          38
   min and max degree      =           1          4

Norms of error:
   energy norm of error       2.9076732501E+00
      reduced by              8.5706923427E-01
   L2 norm of error           2.0501256959E-01
      reduced by              6.9808199471E-01

Total Grid:
   number of vertices      =          18
   number of leaf elements =          20
   number of levels        =           7
   degrees of freedom      =          89
   min and max degree      =           1          6

Norms of error:
   energy norm of error       1.3165539282E+00
      reduced by              4.5278606464E-01
   L2 norm of error           4.8815822893E-02
      reduced by              2.3811136551E-01

Total Grid:
   number of vertices      =          21
   number of leaf elements =          24
   number of levels        =           9
   degrees of freedom      =         175
   min and max degree      =           1          7

Norms of error:
   energy norm of error       4.5155864012E-01
      reduced by              3.4298529704E-01
   L2 norm of error           1.0537968314E-02
      reduced by              2.1587197939E-01

Total Grid:
   number of vertices      =          24
   number of leaf elements =          28
   number of levels        =          11
   degrees of freedom      =         344
   min and max degree      =           1          9

Norms of error:
   energy norm of error       6.1652507222E-02
      reduced by              1.3653267094E-01
   L2 norm of error           4.9424169644E-04
      reduced by              4.6901042187E-02

Total Grid:
   number of vertices      =          30
   number of leaf elements =          36
   number of levels        =          15
   degrees of freedom      =         661
   min and max degree      =           1         10

Norms of error:
   energy norm of error       1.1179492640E-02
      reduced by              1.8133070566E-01
   L2 norm of error           1.3993452177E-04
      reduced by              2.8312973750E-01

Total Grid:
   number of vertices      =          36
   number of leaf elements =          44
   number of levels        =          19
   degrees of freedom      =        1180
   min and max degree      =           1         14

Norms of error:
   energy norm of error       2.8924703238E-04
      reduced by              2.5873001726E-02
   L2 norm of error           1.2324960521E-06
      reduced by              8.8076625872E-03

Total Grid:
   number of vertices      =          49
   number of leaf elements =          62
   number of levels        =          28
   degrees of freedom      =        2243
   min and max degree      =           1         15

Norms of error:
   energy norm of error       1.2260986963E-06
      reduced by              4.2389326738E-03
   L2 norm of error           1.6941444616E-08
      reduced by              1.3745638039E-02

Total Grid:
   number of vertices      =          49
   number of leaf elements =          62
   number of levels        =          28
   degrees of freedom      =        2243
   min and max degree      =           1         15

Norms of error:
   energy norm of error       1.2260986963E-06
   L2 norm of error           1.6941444616E-08

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           8
termination condition:
  maximum equations achieved
---------------------------------------------------------
