---------------------------------------------------------
           PHAML   Version 1.9.1

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                   5000
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree                      3
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            HP_ADAPTIVE
  edge_rule          MINIMUM_RULE
  hp_strategy        HP_PRIOR2P_E
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           false
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =          49
   min and max degree      =           3          3

Total Grid:
   number of vertices      =          21
   number of leaf elements =          26
   number of levels        =           3
   degrees of freedom      =         139
   min and max degree      =           3          3

Total Grid:
   number of vertices      =          28
   number of leaf elements =          40
   number of levels        =           4
   degrees of freedom      =         202
   min and max degree      =           3          3

Total Grid:
   number of vertices      =          59
   number of leaf elements =          92
   number of levels        =           6
   degrees of freedom      =         451
   min and max degree      =           3          3

Total Grid:
   number of vertices      =         108
   number of leaf elements =         172
   number of levels        =           8
   degrees of freedom      =         838
   min and max degree      =           3          3

Total Grid:
   number of vertices      =         205
   number of leaf elements =         364
   number of levels        =           9
   degrees of freedom      =        1715
   min and max degree      =           3          4

Total Grid:
   number of vertices      =         341
   number of leaf elements =         624
   number of levels        =           9
   degrees of freedom      =        3872
   min and max degree      =           3          7

Total Grid:
   number of vertices      =         441
   number of leaf elements =         814
   number of levels        =          10
   degrees of freedom      =        5422
   min and max degree      =           3          7

Total Grid:
   number of vertices      =         441
   number of leaf elements =         814
   number of levels        =          10
   degrees of freedom      =        5422
   min and max degree      =           3          7

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           7
termination condition:
  maximum equations achieved
---------------------------------------------------------
