---------------------------------------------------------
           PHAML   Version 1.9.1

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                   5000
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree                      3
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            HP_ADAPTIVE
  edge_rule          MINIMUM_RULE
  hp_strategy        HP_PRIOR2P_E
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           false
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =          49
   degrees of freedom I own =          49
   min and max degree       =           3          3

My Grid:
   number of vertices       =          21
   number of vertices I own =          21
   number of elements       =          44
   number of leaf elements  =          26
   leaf elements I own      =          26
   number of levels         =           3
   degrees of freedom       =         139
   degrees of freedom I own =         139
   min and max degree       =           3          3

My Grid:
   number of vertices       =          28
   number of vertices I own =          28
   number of elements       =          72
   number of leaf elements  =          40
   leaf elements I own      =          40
   number of levels         =           4
   degrees of freedom       =         202
   degrees of freedom I own =         202
   min and max degree       =           3          3

My Grid:
   number of vertices       =          59
   number of vertices I own =          59
   number of elements       =         176
   number of leaf elements  =          92
   leaf elements I own      =          92
   number of levels         =           6
   degrees of freedom       =         451
   degrees of freedom I own =         451
   min and max degree       =           3          3

My Grid:
   number of vertices       =         108
   number of vertices I own =         108
   number of elements       =         336
   number of leaf elements  =         172
   leaf elements I own      =         172
   number of levels         =           8
   degrees of freedom       =         838
   degrees of freedom I own =         838
   min and max degree       =           3          3

My Grid:
   number of vertices       =         203
   number of vertices I own =         203
   number of elements       =         712
   number of leaf elements  =         360
   leaf elements I own      =         360
   number of levels         =           9
   degrees of freedom       =        1687
   degrees of freedom I own =        1687
   min and max degree       =           3          3

My Grid:
   number of vertices       =         345
   number of vertices I own =         345
   number of elements       =        1256
   number of leaf elements  =         632
   leaf elements I own      =         632
   number of levels         =           9
   degrees of freedom       =        3971
   degrees of freedom I own =        3971
   min and max degree       =           3          7

My Grid:
   number of vertices       =         431
   number of vertices I own =         431
   number of elements       =        1588
   number of leaf elements  =         798
   leaf elements I own      =         798
   number of levels         =          10
   degrees of freedom       =        5185
   degrees of freedom I own =        5185
   min and max degree       =           3          7

My Grid:
   number of vertices       =         431
   number of vertices I own =         431
   number of elements       =        1588
   number of leaf elements  =         798
   leaf elements I own      =         798
   number of levels         =          10
   degrees of freedom       =        5185
   degrees of freedom I own =        5185
   min and max degree       =           3          7

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           7
termination condition:
  maximum equations achieved
---------------------------------------------------------
