---------------------------------------------------------
           PHAML   Version 1.11.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                   4000
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree                      3
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            HP_ADAPTIVE
  edge_rule          MINIMUM_RULE
  hp_strategy        HP_SMOOTH_PRED
  sp_gamma_h          4.0000000000E+00
  sp_gamma_p          4.0000000000E-01
  refterm            DOUBLE_NEQ
  derefine           false
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =          49
   min and max degree      =           3          3

Norms of error:
   energy norm of error       1.5715470748E+00
   L2 norm of error           8.2689297175E-02

Total Grid:
   number of vertices      =          13
   number of leaf elements =          16
   number of levels        =           2
   degrees of freedom      =         121
   min and max degree      =           3          4

Norms of error:
   energy norm of error       3.2677094289E-01
      reduced by              2.0792946526E-01
   L2 norm of error           1.2882472065E-02
      reduced by              1.5579370614E-01

Total Grid:
   number of vertices      =          19
   number of leaf elements =          24
   number of levels        =           3
   degrees of freedom      =         277
   min and max degree      =           3          5

Norms of error:
   energy norm of error       6.6816724498E-02
      reduced by              2.0447572207E-01
   L2 norm of error           1.4138791795E-03
      reduced by              1.0975216343E-01

Total Grid:
   number of vertices      =          24
   number of leaf elements =          32
   number of levels        =           4
   degrees of freedom      =         436
   min and max degree      =           3          6

Norms of error:
   energy norm of error       2.1761953552E-02
      reduced by              3.2569620429E-01
   L2 norm of error           3.4564894094E-04
      reduced by              2.4446851326E-01

Total Grid:
   number of vertices      =          34
   number of leaf elements =          52
   number of levels        =           5
   degrees of freedom      =         868
   min and max degree      =           3          7

Norms of error:
   energy norm of error       1.4147595212E-03
      reduced by              6.5010685637E-02
   L2 norm of error           1.6634375321E-05
      reduced by              4.8125057973E-02

Total Grid:
   number of vertices      =          54
   number of leaf elements =          84
   number of levels        =           7
   degrees of freedom      =        1579
   min and max degree      =           3          7

Norms of error:
   energy norm of error       8.8101341451E-05
      reduced by              6.2273015398E-02
   L2 norm of error           7.3324014349E-07
      reduced by              4.4079812397E-02

Total Grid:
   number of vertices      =          83
   number of leaf elements =         140
   number of levels        =           7
   degrees of freedom      =        3142
   min and max degree      =           3          8

Norms of error:
   energy norm of error       2.5639164054E-05
      reduced by              2.9101899734E-01
   L2 norm of error           1.5098549464E-07
      reduced by              2.0591547800E-01

Total Grid:
   number of vertices      =         103
   number of leaf elements =         178
   number of levels        =           7
   degrees of freedom      =        4182
   min and max degree      =           3          8

Norms of error:
   energy norm of error       4.3683677070E-06
      reduced by              1.7037871039E-01
   L2 norm of error           4.5989638204E-08
      reduced by              3.0459640056E-01

Total Grid:
   number of vertices      =         103
   number of leaf elements =         178
   number of levels        =           7
   degrees of freedom      =        4182
   min and max degree      =           3          8

Norms of error:
   energy norm of error       4.3683677070E-06
   L2 norm of error           4.5989638204E-08

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           7
termination condition:
  maximum equations achieved
---------------------------------------------------------
