---------------------------------------------------------
           PHAML   Version 1.11.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                   5000
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    SLAVES
  print_error_what   ENERGY_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            HP_ADAPTIVE
  edge_rule          MINIMUM_RULE
  hp_strategy        HP_COEF_ROOT
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

Norms of error:
   energy norm of error       4.0333158308E+00
   L2 norm of error           4.5345860840E-01

My Grid:
   number of vertices       =          10
   number of vertices I own =          10
   number of elements       =          12
   number of leaf elements  =          10
   leaf elements I own      =          10
   number of levels         =           2
   degrees of freedom       =          28
   degrees of freedom I own =          28
   min and max degree       =           1          3

Norms of error:
   energy norm of error       2.4036432137E+00
      reduced by              5.9594718454E-01
   L2 norm of error           1.4376135605E-01
      reduced by              3.1703302877E-01

My Grid:
   number of vertices       =          14
   number of vertices I own =          14
   number of elements       =          24
   number of leaf elements  =          16
   leaf elements I own      =          16
   number of levels         =           3
   degrees of freedom       =          46
   degrees of freedom I own =          46
   min and max degree       =           1          3

Norms of error:
   energy norm of error       1.8046528109E+00
      reduced by              7.5079895411E-01
   L2 norm of error           8.6170854983E-02
      reduced by              5.9940207405E-01

My Grid:
   number of vertices       =          21
   number of vertices I own =          21
   number of elements       =          48
   number of leaf elements  =          28
   leaf elements I own      =          28
   number of levels         =           4
   degrees of freedom       =          82
   degrees of freedom I own =          82
   min and max degree       =           1          3

Norms of error:
   energy norm of error       1.2872213638E+00
      reduced by              7.1327922803E-01
   L2 norm of error           5.3405151716E-02
      reduced by              6.1975887006E-01

My Grid:
   number of vertices       =          38
   number of vertices I own =          38
   number of elements       =         100
   number of leaf elements  =          54
   leaf elements I own      =          54
   number of levels         =           6
   degrees of freedom       =         160
   degrees of freedom I own =         160
   min and max degree       =           1          3

Norms of error:
   energy norm of error       5.4241122202E-01
      reduced by              4.2138146340E-01
   L2 norm of error           1.0114035287E-02
      reduced by              1.8938313930E-01

My Grid:
   number of vertices       =          66
   number of vertices I own =          66
   number of elements       =         196
   number of leaf elements  =         102
   leaf elements I own      =         102
   number of levels         =           7
   degrees of freedom       =         303
   degrees of freedom I own =         303
   min and max degree       =           1          3

Norms of error:
   energy norm of error       1.6739361965E-01
      reduced by              3.0861017040E-01
   L2 norm of error           2.1741317995E-03
      reduced by              2.1496185626E-01

My Grid:
   number of vertices       =          93
   number of vertices I own =          93
   number of elements       =         288
   number of leaf elements  =         148
   leaf elements I own      =         148
   number of levels         =           8
   degrees of freedom       =         643
   degrees of freedom I own =         643
   min and max degree       =           1          4

Norms of error:
   energy norm of error       5.9778481398E-02
      reduced by              3.5711326108E-01
   L2 norm of error           1.1122225224E-03
      reduced by              5.1157088205E-01

My Grid:
   number of vertices       =         153
   number of vertices I own =         153
   number of elements       =         516
   number of leaf elements  =         262
   leaf elements I own      =         262
   number of levels         =           8
   degrees of freedom       =        1225
   degrees of freedom I own =        1225
   min and max degree       =           1          5

Norms of error:
   energy norm of error       1.6287250547E-02
      reduced by              2.7246009209E-01
   L2 norm of error           1.2372494991E-04
      reduced by              1.1124118368E-01

My Grid:
   number of vertices       =         269
   number of vertices I own =         269
   number of elements       =         920
   number of leaf elements  =         464
   leaf elements I own      =         464
   number of levels         =           9
   degrees of freedom       =        2383
   degrees of freedom I own =        2383
   min and max degree       =           1          5

Norms of error:
   energy norm of error       4.1635626160E-03
      reduced by              2.5563323927E-01
   L2 norm of error           2.7195195203E-05
      reduced by              2.1980364691E-01

My Grid:
   number of vertices       =         488
   number of vertices I own =         488
   number of elements       =        1780
   number of leaf elements  =         894
   leaf elements I own      =         894
   number of levels         =          10
   degrees of freedom       =        5415
   degrees of freedom I own =        5415
   min and max degree       =           1          7

Norms of error:
   energy norm of error       1.4704965652E-03
      reduced by              3.5318228660E-01
   L2 norm of error           4.5954386081E-06
      reduced by              1.6897979859E-01

My Grid:
   number of vertices       =         488
   number of vertices I own =         488
   number of elements       =        1780
   number of leaf elements  =         894
   leaf elements I own      =         894
   number of levels         =          10
   degrees of freedom       =        5415
   degrees of freedom I own =        5415
   min and max degree       =           1          7

Norms of error:
   energy norm of error       1.4704965652E-03
   L2 norm of error           4.5954386081E-06

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           9
termination condition:
  maximum equations achieved
---------------------------------------------------------
