---------------------------------------------------------
           PHAML   Version 1.11.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                   5000
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            HP_ADAPTIVE
  edge_rule          MINIMUM_RULE
  hp_strategy        HP_SMOOTH_PRED
  sp_gamma_h          4.0000000000E+00
  sp_gamma_p          4.0000000000E-01
  refterm            DOUBLE_NEQ
  derefine           false
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Norms of error:
   energy norm of error       4.0333158308E+00
   L2 norm of error           4.5345860840E-01

Total Grid:
   number of vertices      =          12
   number of leaf elements =          14
   number of levels        =           2
   degrees of freedom      =          37
   min and max degree      =           1          3

Norms of error:
   energy norm of error       1.6262129043E+00
      reduced by              4.0319503170E-01
   L2 norm of error           8.4857068366E-02
      reduced by              1.8713299691E-01

Total Grid:
   number of vertices      =          12
   number of leaf elements =          14
   number of levels        =           2
   degrees of freedom      =          50
   min and max degree      =           1          4

Norms of error:
   energy norm of error       1.4617132211E+00
      reduced by              8.9884492819E-01
   L2 norm of error           7.7520283899E-02
      reduced by              9.1353950109E-01

Total Grid:
   number of vertices      =          14
   number of leaf elements =          18
   number of levels        =           3
   degrees of freedom      =         110
   min and max degree      =           1          5

Norms of error:
   energy norm of error       3.1577899327E-01
      reduced by              2.1603347955E-01
   L2 norm of error           9.2940221747E-03
      reduced by              1.1989148784E-01

Total Grid:
   number of vertices      =          22
   number of leaf elements =          30
   number of levels        =           4
   degrees of freedom      =         274
   min and max degree      =           1          5

Norms of error:
   energy norm of error       7.3273771039E-02
      reduced by              2.3204130927E-01
   L2 norm of error           1.5518008645E-03
      reduced by              1.6696763095E-01

Total Grid:
   number of vertices      =          22
   number of leaf elements =          30
   number of levels        =           4
   degrees of freedom      =         302
   min and max degree      =           1          6

Norms of error:
   energy norm of error       2.8742126083E-02
      reduced by              3.9225667897E-01
   L2 norm of error           4.9486250791E-04
      reduced by              3.1889562586E-01

Total Grid:
   number of vertices      =          31
   number of leaf elements =          46
   number of levels        =           5
   degrees of freedom      =         577
   min and max degree      =           1          6

Norms of error:
   energy norm of error       7.2425754554E-03
      reduced by              2.5198468041E-01
   L2 norm of error           8.2579759656E-05
      reduced by              1.6687414855E-01

Total Grid:
   number of vertices      =          61
   number of leaf elements =         100
   number of levels        =           6
   degrees of freedom      =        1405
   min and max degree      =           1          6

Norms of error:
   energy norm of error       1.0643320191E-03
      reduced by              1.4695490930E-01
   L2 norm of error           1.1634084215E-05
      reduced by              1.4088299922E-01

Total Grid:
   number of vertices      =          91
   number of leaf elements =         154
   number of levels        =           7
   degrees of freedom      =        2535
   min and max degree      =           1          7

Norms of error:
   energy norm of error       4.8120206228E-05
      reduced by              4.5211649525E-02
   L2 norm of error           7.7000017618E-07
      reduced by              6.6184854945E-02

Total Grid:
   number of vertices      =         144
   number of leaf elements =         250
   number of levels        =           8
   degrees of freedom      =        4701
   min and max degree      =           1          8

Norms of error:
   energy norm of error       8.3273242998E-06
      reduced by              1.7305254804E-01
   L2 norm of error           1.9008067869E-07
      reduced by              2.4685796779E-01

Total Grid:
   number of vertices      =         155
   number of leaf elements =         270
   number of levels        =           8
   degrees of freedom      =        5033
   min and max degree      =           1          8

Norms of error:
   energy norm of error       6.7857646498E-06
      reduced by              4.0743967723E-01
   L2 norm of error           4.0394682018E-08
      reduced by              1.0625667558E-01

Total Grid:
   number of vertices      =         155
   number of leaf elements =         270
   number of levels        =           8
   degrees of freedom      =        5033
   min and max degree      =           1          8

Norms of error:
   energy norm of error       6.7857646498E-06
   L2 norm of error           4.0394682018E-08

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =          10
termination condition:
  maximum equations achieved
---------------------------------------------------------
