---------------------------------------------------------
           PHAML   Version 1.11.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                   5000
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            HP_ADAPTIVE
  edge_rule          MINIMUM_RULE
  hp_strategy        HP_ALTERNATE
  t3s_gamma           6.0000000000E+00
  t3s_eta             1.0000000000E-01
  t3s_nunif                    0
  t3s_maxref                   3
  t3s_maxdeginc                3
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Norms of error:
   energy norm of error       4.0333158308E+00
   L2 norm of error           4.5345860840E-01

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =          20
   min and max degree      =           1          2

Norms of error:
   energy norm of error       2.8483533609E+00
      reduced by              7.0620637718E-01
   L2 norm of error           2.4731239847E-01
      reduced by              5.4539134088E-01

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =          31
   min and max degree      =           1          3

Norms of error:
   energy norm of error       1.9858430947E+00
      reduced by              6.9718986484E-01
   L2 norm of error           1.2372545264E-01
      reduced by              5.0028002399E-01

Total Grid:
   number of vertices      =          12
   number of leaf elements =          14
   number of levels        =           2
   degrees of freedom      =          52
   min and max degree      =           1          3

Norms of error:
   energy norm of error       1.1963401941E+00
      reduced by              6.0243440044E-01
   L2 norm of error           5.6531548450E-02
      reduced by              4.5691122759E-01

Total Grid:
   number of vertices      =          18
   number of leaf elements =          20
   number of levels        =           3
   degrees of freedom      =          82
   min and max degree      =           1          3

Norms of error:
   energy norm of error       9.8645168965E-01
      reduced by              8.2455784275E-01
   L2 norm of error           3.6221047795E-02
      reduced by              6.4072272541E-01

Total Grid:
   number of vertices      =          18
   number of leaf elements =          20
   number of levels        =           3
   degrees of freedom      =         138
   min and max degree      =           1          4

Norms of error:
   energy norm of error       3.3146186312E-01
      reduced by              3.3601428898E-01
   L2 norm of error           1.0992719866E-02
      reduced by              3.0348983631E-01

Total Grid:
   number of vertices      =          18
   number of leaf elements =          20
   number of levels        =           3
   degrees of freedom      =         169
   min and max degree      =           1          5

Norms of error:
   energy norm of error       1.5549451924E-01
      reduced by              4.6911737531E-01
   L2 norm of error           3.7106423624E-03
      reduced by              3.3755452768E-01

Total Grid:
   number of vertices      =          27
   number of leaf elements =          38
   number of levels        =           4
   degrees of freedom      =         355
   min and max degree      =           1          5

Norms of error:
   energy norm of error       6.1474456469E-02
      reduced by              3.9534805966E-01
   L2 norm of error           1.2597601113E-03
      reduced by              3.3949919941E-01

Total Grid:
   number of vertices      =          27
   number of leaf elements =          38
   number of levels        =           4
   degrees of freedom      =         489
   min and max degree      =           1          6

Norms of error:
   energy norm of error       1.1304072441E-02
      reduced by              1.8388243004E-01
   L2 norm of error           1.2459448039E-04
      reduced by              9.8903338239E-02

Total Grid:
   number of vertices      =          40
   number of leaf elements =          60
   number of levels        =           5
   degrees of freedom      =         692
   min and max degree      =           1          6

Norms of error:
   energy norm of error       2.0171230054E-03
      reduced by              1.7844215135E-01
   L2 norm of error           2.8430380722E-05
      reduced by              2.2818330822E-01

Total Grid:
   number of vertices      =          40
   number of leaf elements =          60
   number of levels        =           5
   degrees of freedom      =         937
   min and max degree      =           1          7

Norms of error:
   energy norm of error       4.7831669257E-04
      reduced by              2.3712817279E-01
   L2 norm of error           1.0103426670E-05
      reduced by              3.5537430080E-01

Total Grid:
   number of vertices      =          58
   number of leaf elements =          90
   number of levels        =           5
   degrees of freedom      =        1360
   min and max degree      =           1          7

Norms of error:
   energy norm of error       1.5431150692E-04
      reduced by              3.2261367692E-01
   L2 norm of error           1.3616548362E-06
      reduced by              1.3477158598E-01

Total Grid:
   number of vertices      =          58
   number of leaf elements =          90
   number of levels        =           5
   degrees of freedom      =        1774
   min and max degree      =           1          8

Norms of error:
   energy norm of error       2.0252448575E-05
      reduced by              1.3124392975E-01
   L2 norm of error           3.3033030238E-07
      reduced by              2.4259474105E-01

Total Grid:
   number of vertices      =         109
   number of leaf elements =         188
   number of levels        =           6
   degrees of freedom      =        3595
   min and max degree      =           1          8

Norms of error:
   energy norm of error       7.4135536087E-06
      reduced by              3.6605715014E-01
   L2 norm of error           1.3202907166E-07
      reduced by              3.9968804166E-01

Total Grid:
   number of vertices      =         109
   number of leaf elements =         188
   number of levels        =           6
   degrees of freedom      =        4202
   min and max degree      =           1          9

Norms of error:
   energy norm of error       1.3820669309E-06
      reduced by              9.3212176228E-02
   L2 norm of error           2.8311468154E-08
      reduced by              1.0721679627E-01

Total Grid:
   number of vertices      =         184
   number of leaf elements =         328
   number of levels        =           7
   degrees of freedom      =        7144
   min and max degree      =           1          9

Norms of error:
   energy norm of error       5.1004880592E-07
      reduced by              3.6904783301E-01
   L2 norm of error           6.5803117477E-09
      reduced by              2.3242566270E-01

Total Grid:
   number of vertices      =         184
   number of leaf elements =         328
   number of levels        =           7
   degrees of freedom      =        7144
   min and max degree      =           1          9

Norms of error:
   energy norm of error       5.1004880592E-07
   L2 norm of error           6.5803117477E-09

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =          15
termination condition:
  maximum equations achieved
---------------------------------------------------------
