---------------------------------------------------------
           PHAML   Version 1.11.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                   4000
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    SLAVES
  print_error_what   ENERGY_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree                      3
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            HP_ADAPTIVE
  edge_rule          MINIMUM_RULE
  hp_strategy        HP_PRIOR2P_H1
  refterm            DOUBLE_NEQ
  derefine           false
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =          49
   degrees of freedom I own =          49
   min and max degree       =           3          3

Norms of error:
   energy norm of error       1.5715465300E+00
   L2 norm of error           8.2688878518E-02

My Grid:
   number of vertices       =          21
   number of vertices I own =          21
   number of elements       =          44
   number of leaf elements  =          26
   leaf elements I own      =          26
   number of levels         =           3
   degrees of freedom       =         139
   degrees of freedom I own =         139
   min and max degree       =           3          3

Norms of error:
   energy norm of error       5.6881840336E-01
      reduced by              3.6194817812E-01
   L2 norm of error           1.3874689858E-02
      reduced by              1.6779390538E-01

My Grid:
   number of vertices       =          28
   number of vertices I own =          28
   number of elements       =          72
   number of leaf elements  =          40
   leaf elements I own      =          40
   number of levels         =           4
   degrees of freedom       =         202
   degrees of freedom I own =         202
   min and max degree       =           3          3

Norms of error:
   energy norm of error       3.1933423606E-01
      reduced by              5.6139926938E-01
   L2 norm of error           5.8001579690E-03
      reduced by              4.1803874741E-01

My Grid:
   number of vertices       =          59
   number of vertices I own =          59
   number of elements       =         176
   number of leaf elements  =          92
   leaf elements I own      =          92
   number of levels         =           6
   degrees of freedom       =         451
   degrees of freedom I own =         451
   min and max degree       =           3          3

Norms of error:
   energy norm of error       6.7970984461E-02
      reduced by              2.1285216800E-01
   L2 norm of error           6.0788014422E-04
      reduced by              1.0480406697E-01

My Grid:
   number of vertices       =         108
   number of vertices I own =         108
   number of elements       =         336
   number of leaf elements  =         172
   leaf elements I own      =         172
   number of levels         =           8
   degrees of freedom       =         838
   degrees of freedom I own =         838
   min and max degree       =           3          3

Norms of error:
   energy norm of error       2.0233582100E-02
      reduced by              2.9767969761E-01
   L2 norm of error           1.5457713923E-04
      reduced by              2.5428884412E-01

My Grid:
   number of vertices       =         191
   number of vertices I own =         191
   number of elements       =         668
   number of leaf elements  =         338
   leaf elements I own      =         338
   number of levels         =           8
   degrees of freedom       =        1585
   degrees of freedom I own =        1585
   min and max degree       =           3          3

Norms of error:
   energy norm of error       1.1745231394E-02
      reduced by              5.8048205876E-01
   L2 norm of error           7.2359297368E-05
      reduced by              4.6811124676E-01

My Grid:
   number of vertices       =         290
   number of vertices I own =         290
   number of elements       =        1046
   number of leaf elements  =         527
   leaf elements I own      =         527
   number of levels         =           9
   degrees of freedom       =        3191
   degrees of freedom I own =        3191
   min and max degree       =           3          6

Norms of error:
   energy norm of error       3.1968367053E-03
      reduced by              2.7218167085E-01
   L2 norm of error           1.3498445581E-05
      reduced by              1.8654749385E-01

My Grid:
   number of vertices       =         367
   number of vertices I own =         367
   number of elements       =        1346
   number of leaf elements  =         677
   leaf elements I own      =         677
   number of levels         =          10
   degrees of freedom       =        4342
   degrees of freedom I own =        4342
   min and max degree       =           3          6

Norms of error:
   energy norm of error       1.3110109613E-03
      reduced by              4.1009631774E-01
   L2 norm of error           6.1215823708E-06
      reduced by              4.5350276328E-01

My Grid:
   number of vertices       =         367
   number of vertices I own =         367
   number of elements       =        1346
   number of leaf elements  =         677
   leaf elements I own      =         677
   number of levels         =          10
   degrees of freedom       =        4342
   degrees of freedom I own =        4342
   min and max degree       =           3          6

Norms of error:
   energy norm of error       1.3110109613E-03
   L2 norm of error           6.1215823708E-06

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           7
termination condition:
  maximum equations achieved
---------------------------------------------------------
