---------------------------------------------------------
           PHAML   Version 1.11.0

Output from the master process
  PDE id is     0
  Number of slave processors is     1
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                    500
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    21
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          1.0000000000E+01
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            HP_ADAPTIVE
  edge_rule          MINIMUM_RULE
  hp_strategy        HP_REFSOLN_EDGE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Norms of error:
   energy norm of error       4.0333158308E+00
   L2 norm of error           4.5345860840E-01

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           2
   degrees of freedom      =          20
   min and max degree      =           1          2

Norms of error:
   energy norm of error       2.8483585999E+00
      reduced by              7.0620767611E-01
   L2 norm of error           2.4731509305E-01
      reduced by              5.4539728315E-01

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           2
   degrees of freedom      =          37
   min and max degree      =           1          3

Norms of error:
   energy norm of error       1.5848860994E+00
      reduced by              5.5642084515E-01
   L2 norm of error           8.5177958710E-02
      reduced by              3.4441067733E-01

Total Grid:
   number of vertices      =          12
   number of leaf elements =          14
   number of levels        =           2
   degrees of freedom      =          54
   min and max degree      =           1          3

Norms of error:
   energy norm of error       8.9745785872E-01
      reduced by              5.6626016156E-01
   L2 norm of error           3.2492485768E-02
      reduced by              3.8146588930E-01

Total Grid:
   number of vertices      =          20
   number of leaf elements =          24
   number of levels        =           3
   degrees of freedom      =          88
   min and max degree      =           1          3

Norms of error:
   energy norm of error       5.7131521407E-01
      reduced by              6.3659280324E-01
   L2 norm of error           1.3978884621E-02
      reduced by              4.3021899651E-01

Total Grid:
   number of vertices      =          20
   number of leaf elements =          24
   number of levels        =           4
   degrees of freedom      =         139
   min and max degree      =           1          4

Norms of error:
   energy norm of error       1.4769144033E-01
      reduced by              2.5851130286E-01
   L2 norm of error           3.7821126319E-03
      reduced by              2.7055897050E-01

Total Grid:
   number of vertices      =          20
   number of leaf elements =          24
   number of levels        =           4
   degrees of freedom      =         204
   min and max degree      =           1          5

Norms of error:
   energy norm of error       3.1016084956E-02
      reduced by              2.1000597520E-01
   L2 norm of error           9.7372138193E-04
      reduced by              2.5745435863E-01

Total Grid:
   number of vertices      =          20
   number of leaf elements =          24
   number of levels        =           4
   degrees of freedom      =         283
   min and max degree      =           1          6

Norms of error:
   energy norm of error       1.1779326175E-02
      reduced by              3.7978120682E-01
   L2 norm of error           8.6289115293E-04
      reduced by              8.8617870465E-01

Total Grid:
   number of vertices      =          20
   number of leaf elements =          24
   number of levels        =           4
   degrees of freedom      =         395
   min and max degree      =           1          7

Norms of error:
   energy norm of error       6.0546974284E-03
      reduced by              5.1401050775E-01
   L2 norm of error           2.1223537035E-04
      reduced by              2.4595844983E-01

Total Grid:
   number of vertices      =          20
   number of leaf elements =          24
   number of levels        =           4
   degrees of freedom      =         422
   min and max degree      =           1          7

Norms of error:
   energy norm of error       2.6762919821E-03
      reduced by              4.4201911223E-01
   L2 norm of error           6.1457541393E-05
      reduced by              2.8957256886E-01

Total Grid:
   number of vertices      =          27
   number of leaf elements =          38
   number of levels        =           4
   degrees of freedom      =         473
   min and max degree      =           1          8

Norms of error:
   energy norm of error       1.7260592825E-03
      reduced by              6.4494430878E-01
   L2 norm of error           4.0358416236E-05
      reduced by              6.5668777698E-01

Total Grid:
   number of vertices      =          34
   number of leaf elements =          50
   number of levels        =           5
   degrees of freedom      =         489
   min and max degree      =           1          8

Norms of error:
   energy norm of error       9.0831872476E-04
      reduced by              5.2623842875E-01
   L2 norm of error           1.4698241859E-05
      reduced by              3.6419273177E-01

Total Grid:
   number of vertices      =          34
   number of leaf elements =          50
   number of levels        =           6
   degrees of freedom      =         646
   min and max degree      =           1          9

Norms of error:
   energy norm of error       2.8800267970E-04
      reduced by              3.1707226974E-01
   L2 norm of error           1.0183547256E-05
      reduced by              6.9284118156E-01

Total Grid:
   number of vertices      =          34
   number of leaf elements =          50
   number of levels        =           6
   degrees of freedom      =         646
   min and max degree      =           1          9

Norms of error:
   energy norm of error       2.8800267970E-04
   L2 norm of error           1.0183547256E-05

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =          12
termination condition:
  maximum equations achieved
---------------------------------------------------------
