---------------------------------------------------------
           PHAML   Version 1.9.1

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                   5000
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            HP_ADAPTIVE
  edge_rule          MINIMUM_RULE
  hp_strategy        HP_COEF_DECAY
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           false
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =          31
   degrees of freedom I own =          31
   min and max degree       =           1          3

My Grid:
   number of vertices       =          12
   number of vertices I own =          12
   number of elements       =          20
   number of leaf elements  =          14
   leaf elements I own      =          14
   number of levels         =           2
   degrees of freedom       =          52
   degrees of freedom I own =          52
   min and max degree       =           1          3

My Grid:
   number of vertices       =          16
   number of vertices I own =          16
   number of elements       =          28
   number of leaf elements  =          18
   leaf elements I own      =          18
   number of levels         =           3
   degrees of freedom       =          76
   degrees of freedom I own =          76
   min and max degree       =           1          3

My Grid:
   number of vertices       =          27
   number of vertices I own =          27
   number of elements       =          68
   number of leaf elements  =          38
   leaf elements I own      =          38
   number of levels         =           4
   degrees of freedom       =         157
   degrees of freedom I own =         157
   min and max degree       =           1          3

My Grid:
   number of vertices       =          45
   number of vertices I own =          45
   number of elements       =         120
   number of leaf elements  =          64
   leaf elements I own      =          64
   number of levels         =           6
   degrees of freedom       =         348
   degrees of freedom I own =         348
   min and max degree       =           1          5

My Grid:
   number of vertices       =          71
   number of vertices I own =          71
   number of elements       =         224
   number of leaf elements  =         116
   leaf elements I own      =         116
   number of levels         =           7
   degrees of freedom       =         667
   degrees of freedom I own =         667
   min and max degree       =           1          5

My Grid:
   number of vertices       =          99
   number of vertices I own =          99
   number of elements       =         336
   number of leaf elements  =         172
   leaf elements I own      =         172
   number of levels         =           7
   degrees of freedom       =        1273
   degrees of freedom I own =        1273
   min and max degree       =           1          7

My Grid:
   number of vertices       =         182
   number of vertices I own =         182
   number of elements       =         664
   number of leaf elements  =         336
   leaf elements I own      =         336
   number of levels         =           8
   degrees of freedom       =        2440
   degrees of freedom I own =        2440
   min and max degree       =           1          7

My Grid:
   number of vertices       =         295
   number of vertices I own =         295
   number of elements       =        1076
   number of leaf elements  =         542
   leaf elements I own      =         542
   number of levels         =           9
   degrees of freedom       =        4874
   degrees of freedom I own =        4874
   min and max degree       =           1          7

My Grid:
   number of vertices       =         304
   number of vertices I own =         304
   number of elements       =        1108
   number of leaf elements  =         558
   leaf elements I own      =         558
   number of levels         =           9
   degrees of freedom       =        5031
   degrees of freedom I own =        5031
   min and max degree       =           1          7

My Grid:
   number of vertices       =         304
   number of vertices I own =         304
   number of elements       =        1108
   number of leaf elements  =         558
   leaf elements I own      =         558
   number of levels         =           9
   degrees of freedom       =        5031
   degrees of freedom I own =        5031
   min and max degree       =           1          7

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =          10
termination condition:
  maximum equations achieved
---------------------------------------------------------
