---------------------------------------------------------
           PHAML   Version 1.9.1

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                   5000
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            HP_ADAPTIVE
  edge_rule          MINIMUM_RULE
  hp_strategy        HP_SMOOTH_PRED
  sp_gamma_h          4.0000000000E+00
  sp_gamma_p          4.0000000000E-01
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           false
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Total Grid:
   number of vertices      =          16
   number of leaf elements =          18
   number of levels        =           3
   degrees of freedom      =          29
   min and max degree      =           1          2

Total Grid:
   number of vertices      =          16
   number of leaf elements =          18
   number of levels        =           3
   degrees of freedom      =          50
   min and max degree      =           1          3

Total Grid:
   number of vertices      =          20
   number of leaf elements =          24
   number of levels        =           3
   degrees of freedom      =         104
   min and max degree      =           1          4

Total Grid:
   number of vertices      =          26
   number of leaf elements =          36
   number of levels        =           4
   degrees of freedom      =         259
   min and max degree      =           1          5

Total Grid:
   number of vertices      =          30
   number of leaf elements =          42
   number of levels        =           5
   degrees of freedom      =         336
   min and max degree      =           1          6

Total Grid:
   number of vertices      =          57
   number of leaf elements =          90
   number of levels        =           6
   degrees of freedom      =         773
   min and max degree      =           1          7

Total Grid:
   number of vertices      =          75
   number of leaf elements =         126
   number of levels        =           7
   degrees of freedom      =        1169
   min and max degree      =           1          7

Total Grid:
   number of vertices      =         149
   number of leaf elements =         266
   number of levels        =           9
   degrees of freedom      =        2453
   min and max degree      =           1          8

Total Grid:
   number of vertices      =         217
   number of leaf elements =         396
   number of levels        =          11
   degrees of freedom      =        4926
   min and max degree      =           1          8

Total Grid:
   number of vertices      =         221
   number of leaf elements =         404
   number of levels        =          11
   degrees of freedom      =        5046
   min and max degree      =           1          8

Total Grid:
   number of vertices      =         221
   number of leaf elements =         404
   number of levels        =          11
   degrees of freedom      =        5046
   min and max degree      =           1          8

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =          10
termination condition:
  maximum equations achieved
---------------------------------------------------------
