---------------------------------------------------------
           PHAML   Version 1.11.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                   5000
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    SLAVES
  print_error_what   ENERGY_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            HP_ADAPTIVE
  edge_rule          MINIMUM_RULE
  hp_strategy        HP_COEF_DECAY
  refterm            DOUBLE_NEQ
  derefine           false
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

Norms of error:
   energy norm of error       4.0333158308E+00
   L2 norm of error           4.5345860840E-01

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =          31
   degrees of freedom I own =          31
   min and max degree       =           1          3

Norms of error:
   energy norm of error       1.9858496516E+00
      reduced by              4.9236155434E-01
   L2 norm of error           1.2372573259E-01
      reduced by              2.7284901046E-01

My Grid:
   number of vertices       =          12
   number of vertices I own =          12
   number of elements       =          20
   number of leaf elements  =          14
   leaf elements I own      =          14
   number of levels         =           2
   degrees of freedom       =          52
   degrees of freedom I own =          52
   min and max degree       =           1          3

Norms of error:
   energy norm of error       1.1963405933E+00
      reduced by              6.0243261232E-01
   L2 norm of error           5.6534525799E-02
      reduced by              4.5693425786E-01

My Grid:
   number of vertices       =          16
   number of vertices I own =          16
   number of elements       =          28
   number of leaf elements  =          18
   leaf elements I own      =          18
   number of levels         =           3
   degrees of freedom       =          76
   degrees of freedom I own =          76
   min and max degree       =           1          3

Norms of error:
   energy norm of error       1.1237172760E+00
      reduced by              9.3929545003E-01
   L2 norm of error           5.2558796843E-02
      reduced by              9.2967608908E-01

My Grid:
   number of vertices       =          25
   number of vertices I own =          25
   number of elements       =          60
   number of leaf elements  =          34
   leaf elements I own      =          34
   number of levels         =           4
   degrees of freedom       =         151
   degrees of freedom I own =         151
   min and max degree       =           1          3

Norms of error:
   energy norm of error       4.0226728296E-01
      reduced by              3.5797908564E-01
   L2 norm of error           8.4658821166E-03
      reduced by              1.6107450370E-01

My Grid:
   number of vertices       =          44
   number of vertices I own =          44
   number of elements       =         116
   number of leaf elements  =          62
   leaf elements I own      =          62
   number of levels         =           5
   degrees of freedom       =         299
   degrees of freedom I own =         299
   min and max degree       =           1          4

Norms of error:
   energy norm of error       1.1506608182E-01
      reduced by              2.8604384869E-01
   L2 norm of error           1.3619796842E-03
      reduced by              1.6087864979E-01

My Grid:
   number of vertices       =          83
   number of vertices I own =          83
   number of elements       =         272
   number of leaf elements  =         140
   leaf elements I own      =         140
   number of levels         =           7
   degrees of freedom       =         789
   degrees of freedom I own =         789
   min and max degree       =           1          4

Norms of error:
   energy norm of error       1.7389181948E-02
      reduced by              1.5112343857E-01
   L2 norm of error           1.7962551337E-04
      reduced by              1.3188560406E-01

My Grid:
   number of vertices       =         102
   number of vertices I own =         102
   number of elements       =         342
   number of leaf elements  =         175
   leaf elements I own      =         175
   number of levels         =           7
   degrees of freedom       =        1184
   degrees of freedom I own =        1184
   min and max degree       =           1          6

Norms of error:
   energy norm of error       7.9124821090E-03
      reduced by              4.5502325139E-01
   L2 norm of error           1.0625111434E-04
      reduced by              5.9151460362E-01

My Grid:
   number of vertices       =         189
   number of vertices I own =         189
   number of elements       =         682
   number of leaf elements  =         345
   leaf elements I own      =         345
   number of levels         =           8
   degrees of freedom       =        2363
   degrees of freedom I own =        2363
   min and max degree       =           1          6

Norms of error:
   energy norm of error       1.2199071976E-03
      reduced by              1.5417503392E-01
   L2 norm of error           7.6107869248E-06
      reduced by              7.1630184511E-02

My Grid:
   number of vertices       =         325
   number of vertices I own =         325
   number of elements       =        1192
   number of leaf elements  =         600
   leaf elements I own      =         600
   number of levels         =           9
   degrees of freedom       =        5214
   degrees of freedom I own =        5214
   min and max degree       =           1          6

Norms of error:
   energy norm of error       3.0091606162E-04
      reduced by              2.4667127321E-01
   L2 norm of error           1.9322115837E-06
      reduced by              2.5387802902E-01

My Grid:
   number of vertices       =         325
   number of vertices I own =         325
   number of elements       =        1192
   number of leaf elements  =         600
   leaf elements I own      =         600
   number of levels         =           9
   degrees of freedom       =        5214
   degrees of freedom I own =        5214
   min and max degree       =           1          6

Norms of error:
   energy norm of error       3.0091606162E-04
   L2 norm of error           1.9322115837E-06

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           9
termination condition:
  maximum equations achieved
---------------------------------------------------------
