---------------------------------------------------------
           PHAML   Version 1.11.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                   3000
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    19
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    SLAVES
  print_error_what   ENERGY_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            HP_ADAPTIVE
  edge_rule          MINIMUM_RULE
  hp_strategy        HP_NEXT3P
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

Norms of error:
   energy norm of error       4.0333158308E+00
   L2 norm of error           4.5345860840E-01

My Grid:
   number of vertices       =          10
   number of vertices I own =          10
   number of elements       =          12
   number of leaf elements  =          10
   leaf elements I own      =          10
   number of levels         =           2
   degrees of freedom       =          28
   degrees of freedom I own =          28
   min and max degree       =           1          3

Norms of error:
   energy norm of error       2.4036432137E+00
      reduced by              5.9594718454E-01
   L2 norm of error           1.4376135605E-01
      reduced by              3.1703302877E-01

My Grid:
   number of vertices       =          14
   number of vertices I own =          14
   number of elements       =          24
   number of leaf elements  =          16
   leaf elements I own      =          16
   number of levels         =           3
   degrees of freedom       =          46
   degrees of freedom I own =          46
   min and max degree       =           1          3

Norms of error:
   energy norm of error       1.8046528109E+00
      reduced by              7.5079895411E-01
   L2 norm of error           8.6170854983E-02
      reduced by              5.9940207405E-01

My Grid:
   number of vertices       =          18
   number of vertices I own =          18
   number of elements       =          32
   number of leaf elements  =          20
   leaf elements I own      =          20
   number of levels         =           3
   degrees of freedom       =         117
   degrees of freedom I own =         117
   min and max degree       =           1          5

Norms of error:
   energy norm of error       8.5962896673E-01
      reduced by              4.7634035840E-01
   L2 norm of error           3.2845063910E-02
      reduced by              3.8116209845E-01

My Grid:
   number of vertices       =          18
   number of vertices I own =          18
   number of elements       =          32
   number of leaf elements  =          20
   leaf elements I own      =          20
   number of levels         =           3
   degrees of freedom       =         149
   degrees of freedom I own =         149
   min and max degree       =           1          5

Norms of error:
   energy norm of error       2.4682123120E-01
      reduced by              2.8712530726E-01
   L2 norm of error           9.4093575351E-03
      reduced by              2.8647706580E-01

My Grid:
   number of vertices       =          23
   number of vertices I own =          23
   number of elements       =          52
   number of leaf elements  =          30
   leaf elements I own      =          30
   number of levels         =           4
   degrees of freedom       =         396
   degrees of freedom I own =         396
   min and max degree       =           1          6

Norms of error:
   energy norm of error       1.4194329934E-02
      reduced by              5.7508545211E-02
   L2 norm of error           2.1446436651E-04
      reduced by              2.2792668438E-02

My Grid:
   number of vertices       =          36
   number of vertices I own =          36
   number of elements       =         104
   number of leaf elements  =          56
   leaf elements I own      =          56
   number of levels         =           5
   degrees of freedom       =         697
   degrees of freedom I own =         697
   min and max degree       =           1          6

Norms of error:
   energy norm of error       5.4167703920E-03
      reduced by              3.8161508273E-01
   L2 norm of error           7.7704160973E-05
      reduced by              3.6231735014E-01

My Grid:
   number of vertices       =          48
   number of vertices I own =          48
   number of elements       =         144
   number of leaf elements  =          76
   leaf elements I own      =          76
   number of levels         =           6
   degrees of freedom       =        1190
   degrees of freedom I own =        1190
   min and max degree       =           1          7

Norms of error:
   energy norm of error       1.1942893129E-03
      reduced by              2.2047995882E-01
   L2 norm of error           1.3671678119E-05
      reduced by              1.7594525116E-01

My Grid:
   number of vertices       =          90
   number of vertices I own =          90
   number of elements       =         292
   number of leaf elements  =         150
   leaf elements I own      =         150
   number of levels         =           7
   degrees of freedom       =        2484
   degrees of freedom I own =        2484
   min and max degree       =           1          8

Norms of error:
   energy norm of error       4.8448091022E-05
      reduced by              4.0566461156E-02
   L2 norm of error           4.4177781406E-07
      reduced by              3.2313356870E-02

My Grid:
   number of vertices       =         118
   number of vertices I own =         118
   number of elements       =         400
   number of leaf elements  =         204
   leaf elements I own      =         204
   number of levels         =           7
   degrees of freedom       =        3703
   degrees of freedom I own =        3703
   min and max degree       =           1          8

Norms of error:
   energy norm of error       1.4124982522E-05
      reduced by              2.9154879427E-01
   L2 norm of error           2.2407321402E-07
      reduced by              5.0720793778E-01

My Grid:
   number of vertices       =         118
   number of vertices I own =         118
   number of elements       =         400
   number of leaf elements  =         204
   leaf elements I own      =         204
   number of levels         =           7
   degrees of freedom       =        3703
   degrees of freedom I own =        3703
   min and max degree       =           1          8

Norms of error:
   energy norm of error       1.4124982522E-05
   L2 norm of error           2.2407321402E-07

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           9
termination condition:
  maximum equations achieved
---------------------------------------------------------
