---------------------------------------------------------
           PHAML   Version 1.9.1

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                   2000
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            HP_ADAPTIVE
  edge_rule          MINIMUM_RULE
  hp_strategy        HP_APRIORI
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Total Grid:
   number of vertices      =          12
   number of leaf elements =          12
   number of levels        =           3
   degrees of freedom      =          18
   min and max degree      =           1          3

Total Grid:
   number of vertices      =          15
   number of leaf elements =          16
   number of levels        =           5
   degrees of freedom      =          47
   min and max degree      =           1          6

Total Grid:
   number of vertices      =          18
   number of leaf elements =          20
   number of levels        =           7
   degrees of freedom      =         104
   min and max degree      =           1          7

Total Grid:
   number of vertices      =          18
   number of leaf elements =          20
   number of levels        =           7
   degrees of freedom      =         179
   min and max degree      =           1          7

Total Grid:
   number of vertices      =          21
   number of leaf elements =          24
   number of levels        =           9
   degrees of freedom      =         292
   min and max degree      =           1          7

Total Grid:
   number of vertices      =          25
   number of leaf elements =          30
   number of levels        =          12
   degrees of freedom      =         610
   min and max degree      =           1         11

Total Grid:
   number of vertices      =          33
   number of leaf elements =          40
   number of levels        =          17
   degrees of freedom      =        1202
   min and max degree      =           1         14

Total Grid:
   number of vertices      =          43
   number of leaf elements =          54
   number of levels        =          24
   degrees of freedom      =        2074
   min and max degree      =           1         15

Total Grid:
   number of vertices      =          43
   number of leaf elements =          54
   number of levels        =          24
   degrees of freedom      =        2074
   min and max degree      =           1         15

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           8
termination condition:
  maximum equations achieved
---------------------------------------------------------
