---------------------------------------------------------
           PHAML   Version 1.9.1

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                   5000
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            HP_ADAPTIVE
  edge_rule          MINIMUM_RULE
  hp_strategy        HP_T3S
  t3s_gamma           6.0000000000E+00
  t3s_eta             1.0000000000E-01
  t3s_nunif                    4
  t3s_maxref                   3
  t3s_maxdeginc                3
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           false
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

My Grid:
   number of vertices       =         129
   number of vertices I own =         129
   number of elements       =         408
   number of leaf elements  =         208
   leaf elements I own      =         208
   number of levels         =           8
   degrees of freedom       =         129
   degrees of freedom I own =         129
   min and max degree       =           1          1

My Grid:
   number of vertices       =         129
   number of vertices I own =         129
   number of elements       =         408
   number of leaf elements  =         208
   leaf elements I own      =         208
   number of levels         =           8
   degrees of freedom       =         975
   degrees of freedom I own =         975
   min and max degree       =           1          4

My Grid:
   number of vertices       =         207
   number of vertices I own =         207
   number of elements       =         720
   number of leaf elements  =         364
   leaf elements I own      =         364
   number of levels         =          11
   degrees of freedom       =        1325
   degrees of freedom I own =        1325
   min and max degree       =           1          4

My Grid:
   number of vertices       =         207
   number of vertices I own =         207
   number of elements       =         720
   number of leaf elements  =         364
   leaf elements I own      =         364
   number of levels         =          11
   degrees of freedom       =        3360
   degrees of freedom I own =        3360
   min and max degree       =           1          7

My Grid:
   number of vertices       =         287
   number of vertices I own =         287
   number of elements       =        1036
   number of leaf elements  =         522
   leaf elements I own      =         522
   number of levels         =          11
   degrees of freedom       =        3582
   degrees of freedom I own =        3582
   min and max degree       =           1          7

My Grid:
   number of vertices       =         287
   number of vertices I own =         287
   number of elements       =        1036
   number of leaf elements  =         522
   leaf elements I own      =         522
   number of levels         =          11
   degrees of freedom       =        7030
   degrees of freedom I own =        7030
   min and max degree       =           1         10

My Grid:
   number of vertices       =         287
   number of vertices I own =         287
   number of elements       =        1036
   number of leaf elements  =         522
   leaf elements I own      =         522
   number of levels         =          11
   degrees of freedom       =        7030
   degrees of freedom I own =        7030
   min and max degree       =           1         10

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum equations achieved
---------------------------------------------------------
