---------------------------------------------------------
           PHAML   Version 1.9.1

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq                   5000
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            HP_ADAPTIVE
  edge_rule          MINIMUM_RULE
  hp_strategy        HP_ALTERNATE
  t3s_gamma           6.0000000000E+00
  t3s_eta             1.0000000000E-01
  t3s_nunif                    0
  t3s_maxref                   3
  t3s_maxdeginc                3
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles          infinity
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

My Grid:
   number of vertices       =          12
   number of vertices I own =          12
   number of elements       =          20
   number of leaf elements  =          14
   leaf elements I own      =          14
   number of levels         =           2
   degrees of freedom       =          12
   degrees of freedom I own =          12
   min and max degree       =           1          1

My Grid:
   number of vertices       =          16
   number of vertices I own =          16
   number of elements       =          28
   number of leaf elements  =          18
   leaf elements I own      =          18
   number of levels         =           3
   degrees of freedom       =          16
   degrees of freedom I own =          16
   min and max degree       =           1          1

My Grid:
   number of vertices       =          27
   number of vertices I own =          27
   number of elements       =          68
   number of leaf elements  =          38
   leaf elements I own      =          38
   number of levels         =           4
   degrees of freedom       =          27
   degrees of freedom I own =          27
   min and max degree       =           1          1

My Grid:
   number of vertices       =          27
   number of vertices I own =          27
   number of elements       =          68
   number of leaf elements  =          38
   leaf elements I own      =          38
   number of levels         =           4
   degrees of freedom       =          59
   degrees of freedom I own =          59
   min and max degree       =           1          2

My Grid:
   number of vertices       =          27
   number of vertices I own =          27
   number of elements       =          68
   number of leaf elements  =          38
   leaf elements I own      =          38
   number of levels         =           4
   degrees of freedom       =         113
   degrees of freedom I own =         113
   min and max degree       =           1          3

My Grid:
   number of vertices       =          43
   number of vertices I own =          43
   number of elements       =         112
   number of leaf elements  =          60
   leaf elements I own      =          60
   number of levels         =           5
   degrees of freedom       =         227
   degrees of freedom I own =         227
   min and max degree       =           1          3

My Grid:
   number of vertices       =          43
   number of vertices I own =          43
   number of elements       =         112
   number of leaf elements  =          60
   leaf elements I own      =          60
   number of levels         =           5
   degrees of freedom       =         408
   degrees of freedom I own =         408
   min and max degree       =           1          4

My Grid:
   number of vertices       =          43
   number of vertices I own =          43
   number of elements       =         112
   number of leaf elements  =          60
   leaf elements I own      =          60
   number of levels         =           5
   degrees of freedom       =         426
   degrees of freedom I own =         426
   min and max degree       =           1          4

My Grid:
   number of vertices       =          72
   number of vertices I own =          72
   number of elements       =         228
   number of leaf elements  =         118
   leaf elements I own      =         118
   number of levels         =           6
   degrees of freedom       =         717
   degrees of freedom I own =         717
   min and max degree       =           1          4

My Grid:
   number of vertices       =          72
   number of vertices I own =          72
   number of elements       =         228
   number of leaf elements  =         118
   leaf elements I own      =         118
   number of levels         =           6
   degrees of freedom       =        1150
   degrees of freedom I own =        1150
   min and max degree       =           1          5

My Grid:
   number of vertices       =          72
   number of vertices I own =          72
   number of elements       =         228
   number of leaf elements  =         118
   leaf elements I own      =         118
   number of levels         =           6
   degrees of freedom       =        1280
   degrees of freedom I own =        1280
   min and max degree       =           1          5

My Grid:
   number of vertices       =         108
   number of vertices I own =         108
   number of elements       =         360
   number of leaf elements  =         184
   leaf elements I own      =         184
   number of levels         =           7
   degrees of freedom       =        1990
   degrees of freedom I own =        1990
   min and max degree       =           1          5

My Grid:
   number of vertices       =         108
   number of vertices I own =         108
   number of elements       =         360
   number of leaf elements  =         184
   leaf elements I own      =         184
   number of levels         =           7
   degrees of freedom       =        2598
   degrees of freedom I own =        2598
   min and max degree       =           1          6

My Grid:
   number of vertices       =         172
   number of vertices I own =         172
   number of elements       =         604
   number of leaf elements  =         306
   leaf elements I own      =         306
   number of levels         =           8
   degrees of freedom       =        3978
   degrees of freedom I own =        3978
   min and max degree       =           1          6

My Grid:
   number of vertices       =         172
   number of vertices I own =         172
   number of elements       =         604
   number of leaf elements  =         306
   leaf elements I own      =         306
   number of levels         =           8
   degrees of freedom       =        5231
   degrees of freedom I own =        5231
   min and max degree       =           1          7

My Grid:
   number of vertices       =         172
   number of vertices I own =         172
   number of elements       =         604
   number of leaf elements  =         306
   leaf elements I own      =         306
   number of levels         =           8
   degrees of freedom       =        5231
   degrees of freedom I own =        5231
   min and max degree       =           1          7

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =          15
termination condition:
  maximum equations achieved
---------------------------------------------------------
