
My Grid:
   number of vertices       =         734
   number of vertices I own =         734
   number of elements       =        2636
   number of leaf elements  =        1322
   leaf elements I own      =        1322
   number of levels         =          12
   degrees of freedom       =         734
   degrees of freedom I own =         734
   min and max degree       =           1          1

Norms of error:
   energy norm of error       4.6454550777E-01
   energy error estimate      1.5324283622E-01
      effectivity             3.2987690907E-01
   Linf norm of error         3.0902548786E-02
   Linf error estimate        3.4344293830E-03
      effectivity             1.1113741481E-01
