---------------------------------------------------------
           PHAML   Version 1.11.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  PHASES
  print_linsys_who   MASTER
  print_solver_when  PHASES
  print_solver_who   MASTER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  ENERGY_LINF_L2_ERREST
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            RELATIVE ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                   5
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Total Linear System:
   number of equations =           9
   number of nonzeroes =          41
   condensed matrix number of equations =           9
   condensed matrix number of nonzeroes =          41

Solver information:
   number of iterations =           1
   relative residual =   1.8361992673E-16

Norms of error:
   energy norm of error       4.4483523205E-01
   energy error estimate      2.3031879598E+00
      effectivity             5.1776203723E+00
   Linf norm of error         5.2681232515E-01
   Linf error estimate        2.8987654858E+00
      effectivity             5.5024633012E+00
   L2 norm of error           1.0241656586E+00
   L2 error estimate          1.6041113582E+00
      effectivity             1.5662616148E+00

Total Grid:
   number of vertices      =          29
   number of leaf elements =          40
   number of levels        =           5
   degrees of freedom      =          29
   min and max degree      =           1          1

Total Linear System:
   number of equations =          29
   number of nonzeroes =         165
   condensed matrix number of equations =          29
   condensed matrix number of nonzeroes =         165

Solver information:
   number of iterations =           3
   relative residual =   1.8623819943E-05

Norms of error:
   energy norm of error       3.3277387084E-01
      reduced by              7.4808344048E-01
   energy error estimate      7.7530102926E-01
      reduced by              3.3662082418E-01
      effectivity             2.3298134175E+00
   Linf norm of error         2.6171001448E-01
      reduced by              4.9678035609E-01
   Linf error estimate        4.8405688925E-01
      reduced by              1.6698725427E-01
      effectivity             1.8495925355E+00
   L2 norm of error           3.4694269174E-01
      reduced by              3.3875641977E-01
   L2 error estimate          3.6729415366E-01
      reduced by              2.2897048373E-01
      effectivity             1.0586594340E+00

Total Grid:
   number of vertices      =          36
   number of leaf elements =          48
   number of levels        =           6
   degrees of freedom      =          36
   min and max degree      =           1          1

Total Linear System:
   number of equations =          36
   number of nonzeroes =         202
   condensed matrix number of equations =          36
   condensed matrix number of nonzeroes =         202

Solver information:
   number of iterations =           2
   relative residual =   1.8251165643E-04

Norms of error:
   energy norm of error       3.2276342473E-01
      reduced by              9.6991817270E-01
   energy error estimate      6.2008669659E-01
      reduced by              7.9980120391E-01
      effectivity             1.9211801867E+00
   Linf norm of error         2.3765059229E-01
      reduced by              9.0806839301E-01
   Linf error estimate        3.3424532552E-01
      reduced by              6.9050835333E-01
      effectivity             1.4064569429E+00
   L2 norm of error           3.4798077837E-01
      reduced by              1.0029920983E+00
   L2 error estimate          2.4643134769E-01
      reduced by              6.7093729980E-01
      effectivity             7.0817517233E-01

Total Grid:
   number of vertices      =          74
   number of leaf elements =         106
   number of levels        =           7
   degrees of freedom      =          74
   min and max degree      =           1          1

Total Linear System:
   number of equations =          74
   number of nonzeroes =         432
   condensed matrix number of equations =          74
   condensed matrix number of nonzeroes =         432

Solver information:
   number of iterations =           3
   relative residual =   3.0054558645E-05

Norms of error:
   energy norm of error       2.3101521539E-01
      reduced by              7.1574161659E-01
   energy error estimate      3.1574309677E-01
      reduced by              5.0919185737E-01
      effectivity             1.3667632075E+00
   Linf norm of error         1.2757900655E-01
      reduced by              5.3683437237E-01
   Linf error estimate        1.3374913926E-01
      reduced by              4.0015260961E-01
      effectivity             1.0483632290E+00
   L2 norm of error           1.4018554956E-01
      reduced by              4.0285429044E-01
   L2 error estimate          1.0351551912E-01
      reduced by              4.2005824378E-01
      effectivity             7.3841790006E-01

Total Grid:
   number of vertices      =         198
   number of leaf elements =         320
   number of levels        =          10
   degrees of freedom      =         198
   min and max degree      =           1          1

Total Linear System:
   number of equations =         198
   number of nonzeroes =        1232
   condensed matrix number of equations =         198
   condensed matrix number of nonzeroes =        1232

Solver information:
   number of iterations =           4
   relative residual =   3.4975669339E-06

Norms of error:
   energy norm of error       1.3282997378E-01
      reduced by              5.7498365880E-01
   energy error estimate      1.7099663028E-01
      reduced by              5.4156886415E-01
      effectivity             1.2873346686E+00
   Linf norm of error         5.0441752824E-02
      reduced by              3.9537659202E-01
   Linf error estimate        3.8445301415E-02
      reduced by              2.8744335574E-01
      effectivity             7.6217219392E-01
   L2 norm of error           4.3859294086E-02
      reduced by              3.1286601383E-01
   L2 error estimate          4.0329263619E-02
      reduced by              3.8959630363E-01
      effectivity             9.1951465383E-01

Total Grid:
   number of vertices      =         297
   number of leaf elements =         516
   number of levels        =          10
   degrees of freedom      =         297
   min and max degree      =           1          1

Total Linear System:
   number of equations =         297
   number of nonzeroes =        1921
   condensed matrix number of equations =         297
   condensed matrix number of nonzeroes =        1921

Solver information:
   number of iterations =           5
   relative residual =   5.7900301769E-07

Norms of error:
   energy norm of error       1.6932748763E-01
      reduced by              6.3738432978E-01
   energy error estimate      2.5578375876E-01
      reduced by              7.4792046586E-01
      effectivity             1.5105861567E+00
   Linf norm of error         1.9731975724E-02
      reduced by              3.9118338716E-01
   Linf error estimate        1.9545555945E-02
      reduced by              5.0839908195E-01
      effectivity             9.9055240176E-01
   L2 norm of error           4.1733193169E-02
      reduced by              4.7576225335E-01
   L2 error estimate          4.6887985020E-02
      reduced by              5.8131466847E-01
      effectivity             1.1235177915E+00

Total Grid:
   number of vertices      =         582
   number of leaf elements =        1022
   number of levels        =          12
   degrees of freedom      =         582
   min and max degree      =           1          1

Total Linear System:
   number of equations =         582
   number of nonzeroes =        3788
   condensed matrix number of equations =         582
   condensed matrix number of nonzeroes =        3788

Solver information:
   number of iterations =           4
   relative residual =   1.7187377332E-06

Norms of error:
   energy norm of error       1.3440827931E-01
      reduced by              7.9377708363E-01
   energy error estimate      1.7428438509E-01
      reduced by              6.8137393058E-01
      effectivity             1.2966789396E+00
   Linf norm of error         1.5631097107E-02
      reduced by              7.9217090705E-01
   Linf error estimate        1.0978757182E-02
      reduced by              5.6170094177E-01
      effectivity             7.0236638583E-01
   L2 norm of error           3.3332160496E-02
      reduced by              7.9869662407E-01
   L2 error estimate          3.0867575484E-02
      reduced by              6.5832591165E-01
      effectivity             9.2605984804E-01

Total Grid:
   number of vertices      =         582
   number of leaf elements =        1022
   number of levels        =          12
   degrees of freedom      =         582
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.3440827931E-01
   energy error estimate      1.7428438509E-01
      effectivity             1.2966789396E+00
   Linf norm of error         1.5631097107E-02
   Linf error estimate        1.0978757182E-02
      effectivity             7.0236638583E-01
   L2 norm of error           3.3332160496E-02
   L2 error estimate          3.0867575484E-02
      effectivity             9.2605984804E-01

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
