---------------------------------------------------------
           PHAML   Version 1.11.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  PHASES
  print_linsys_who   SLAVES
  print_solver_when  PHASES
  print_solver_who   SLAVES
  print_error_when   PHASES
  print_error_who    SLAVES
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  ENERGY_LINF_L2_ERREST
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                   5
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

My Linear System:
   number of equations =           9
   number of equations I own =           9
   number of nonzeroes =          41
   condensed matrix number of equations =           9
   condensed matrix number of equations I own =           9
   condensed matrix number of nonzeroes =          41

Solver information:
   number of iterations =           1
   relative residual =   1.8361992673E-16

Norms of error:
   energy norm of error       4.0333158308E+00
   energy error estimate      1.3702907531E+01
      effectivity             3.3974298334E+00
   Linf norm of error         1.0536246503E+00
   Linf error estimate        5.7975309716E+00
      effectivity             5.5024633012E+00
   L2 norm of error           4.5345860840E-01
   L2 error estimate          1.9378837674E+00
      effectivity             4.2735626394E+00

My Grid:
   number of vertices       =          29
   number of vertices I own =          29
   number of elements       =          72
   number of leaf elements  =          40
   leaf elements I own      =          40
   number of levels         =           5
   degrees of freedom       =          29
   degrees of freedom I own =          29
   min and max degree       =           1          1

My Linear System:
   number of equations =          29
   number of equations I own =          29
   number of nonzeroes =         165
   condensed matrix number of equations =          29
   condensed matrix number of equations I own =          29
   condensed matrix number of nonzeroes =         165

Solver information:
   number of iterations =           3
   relative residual =   1.8623819943E-05

Norms of error:
   energy norm of error       3.0143054217E+00
      reduced by              7.4735169478E-01
   energy error estimate      5.4179551886E+00
      reduced by              3.9538726919E-01
      effectivity             1.7974141404E+00
   Linf norm of error         5.2342002897E-01
      reduced by              4.9678035609E-01
   Linf error estimate        9.6811377851E-01
      reduced by              1.6698725427E-01
      effectivity             1.8495925355E+00
   L2 norm of error           1.6018458492E-01
      reduced by              3.5325073104E-01
   L2 error estimate          2.5923472838E-01
      reduced by              1.3377207279E-01
      effectivity             1.6183500336E+00

My Grid:
   number of vertices       =          36
   number of vertices I own =          36
   number of elements       =          88
   number of leaf elements  =          48
   leaf elements I own      =          48
   number of levels         =           6
   degrees of freedom       =          36
   degrees of freedom I own =          36
   min and max degree       =           1          1

My Linear System:
   number of equations =          36
   number of equations I own =          36
   number of nonzeroes =         202
   condensed matrix number of equations =          36
   condensed matrix number of equations I own =          36
   condensed matrix number of nonzeroes =         202

Solver information:
   number of iterations =           3
   relative residual =   1.0129595913E-05

Norms of error:
   energy norm of error       2.9236225954E+00
      reduced by              9.6991584673E-01
   energy error estimate      4.3054800409E+00
      reduced by              7.9466881711E-01
      effectivity             1.4726524715E+00
   Linf norm of error         4.7530075334E-01
      reduced by              9.0806756912E-01
   Linf error estimate        6.6848758998E-01
      reduced by              6.9050519146E-01
      effectivity             1.4064517788E+00
   L2 norm of error           1.6068325425E-01
      reduced by              1.0031130919E+00
   L2 error estimate          1.7330590236E-01
      reduced by              6.6852887898E-01
      effectivity             1.0785560896E+00

My Grid:
   number of vertices       =          74
   number of vertices I own =          74
   number of elements       =         204
   number of leaf elements  =         106
   leaf elements I own      =         106
   number of levels         =           7
   degrees of freedom       =          74
   degrees of freedom I own =          74
   min and max degree       =           1          1

My Linear System:
   number of equations =          74
   number of equations I own =          74
   number of nonzeroes =         432
   condensed matrix number of equations =          74
   condensed matrix number of equations I own =          74
   condensed matrix number of nonzeroes =         432

Solver information:
   number of iterations =           3
   relative residual =   3.0073624640E-05

Norms of error:
   energy norm of error       2.0925857190E+00
      reduced by              7.1575097357E-01
   energy error estimate      2.5429897758E+00
      reduced by              5.9064024259E-01
      effectivity             1.2152380439E+00
   Linf norm of error         2.5515801529E-01
      reduced by              5.3683486403E-01
   Linf error estimate        2.6749827851E-01
      reduced by              4.0015444194E-01
      effectivity             1.0483632200E+00
   L2 norm of error           6.4737991356E-02
      reduced by              4.0289196070E-01
   L2 error estimate          5.8429564840E-02
      reduced by              3.3714699871E-01
      effectivity             9.0255449105E-01

My Grid:
   number of vertices       =         198
   number of vertices I own =         198
   number of elements       =         632
   number of leaf elements  =         320
   leaf elements I own      =         320
   number of levels         =          10
   degrees of freedom       =         198
   degrees of freedom I own =         198
   min and max degree       =           1          1

My Linear System:
   number of equations =         198
   number of equations I own =         198
   number of nonzeroes =        1232
   condensed matrix number of equations =         198
   condensed matrix number of equations I own =         198
   condensed matrix number of nonzeroes =        1232

Solver information:
   number of iterations =           4
   relative residual =   3.4975673989E-06

Norms of error:
   energy norm of error       1.2032026285E+00
      reduced by              5.7498367573E-01
   energy error estimate      1.4911960641E+00
      reduced by              5.8639483269E-01
      effectivity             1.2393557235E+00
   Linf norm of error         1.0088350565E-01
      reduced by              3.9537658864E-01
   Linf error estimate        7.6890602830E-02
      reduced by              2.8744335574E-01
      effectivity             7.6217219392E-01
   L2 norm of error           2.0254377625E-02
      reduced by              3.1286694568E-01
   L2 error estimate          1.9963375873E-02
      reduced by              3.4166566067E-01
      effectivity             9.8563264907E-01

My Grid:
   number of vertices       =         297
   number of vertices I own =         297
   number of elements       =        1024
   number of leaf elements  =         516
   leaf elements I own      =         516
   number of levels         =          10
   degrees of freedom       =         297
   degrees of freedom I own =         297
   min and max degree       =           1          1

My Linear System:
   number of equations =         297
   number of equations I own =         297
   number of nonzeroes =        1921
   condensed matrix number of equations =         297
   condensed matrix number of equations I own =         297
   condensed matrix number of nonzeroes =        1921

Solver information:
   number of iterations =           4
   relative residual =   6.0165593840E-06

Norms of error:
   energy norm of error       7.6690250746E-01
      reduced by              6.3738433519E-01
   energy error estimate      1.1411063840E+00
      reduced by              7.6522894032E-01
      effectivity             1.4879419129E+00
   Linf norm of error         3.9463959658E-02
      reduced by              3.9118346854E-01
   Linf error estimate        3.9091104867E-02
      reduced by              5.0839899062E-01
      effectivity             9.9055201773E-01
   L2 norm of error           9.6365858884E-03
      reduced by              4.7577793142E-01
   L2 error estimate          1.1157988145E-02
      reduced by              5.5892291043E-01
      effectivity             1.1578777250E+00

My Grid:
   number of vertices       =         582
   number of vertices I own =         582
   number of elements       =        2036
   number of leaf elements  =        1022
   leaf elements I own      =        1022
   number of levels         =          12
   degrees of freedom       =         582
   degrees of freedom I own =         582
   min and max degree       =           1          1

My Linear System:
   number of equations =         582
   number of equations I own =         582
   number of nonzeroes =        3788
   condensed matrix number of equations =         582
   condensed matrix number of equations I own =         582
   condensed matrix number of nonzeroes =        3788

Solver information:
   number of iterations =           4
   relative residual =   1.6728674463E-06

Norms of error:
   energy norm of error       6.0874963178E-01
      reduced by              7.9377707839E-01
   energy error estimate      7.8142399508E-01
      reduced by              6.8479504283E-01
      effectivity             1.2836541565E+00
   Linf norm of error         3.1262194220E-02
      reduced by              7.9217074239E-01
   Linf error estimate        2.1957512244E-02
      reduced by              5.6170098846E-01
      effectivity             7.0236631790E-01
   L2 norm of error           7.6965153354E-03
      reduced by              7.9867656705E-01
   L2 error estimate          7.2592983106E-03
      reduced by              6.5059204367E-01
      effectivity             9.4319285992E-01

My Grid:
   number of vertices       =         582
   number of vertices I own =         582
   number of elements       =        2036
   number of leaf elements  =        1022
   leaf elements I own      =        1022
   number of levels         =          12
   degrees of freedom       =         582
   degrees of freedom I own =         582
   min and max degree       =           1          1

Norms of error:
   energy norm of error       6.0874963178E-01
   energy error estimate      7.8142399508E-01
      effectivity             1.2836541565E+00
   Linf norm of error         3.1262194220E-02
   Linf error estimate        2.1957512244E-02
      effectivity             7.0236631790E-01
   L2 norm of error           7.6965153354E-03
   L2 error estimate          7.2592983106E-03
      effectivity             9.4319285992E-01

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
