---------------------------------------------------------
           PHAML   Version 1.9.1

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  PHASES
  print_linsys_who   MASTER
  print_solver_when  PHASES
  print_solver_who   MASTER
  print_error_when   TOO_MUCH
  print_error_who    MASTER
  print_error_what   ENERGY_ERR
  print_errest_what  ENERGY_ERREST
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                   5
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Total Linear System:
   number of equations =           9
   number of nonzeroes =          41
   condensed matrix number of equations =           9
   condensed matrix number of nonzeroes =          41

L2 norm of linear system residual

      iteration    absolute residual    relative residual      reduction

           0  2.8370442961E+00  5.8652389456E-01
           1  8.8817841970E-16  1.8361992673E-16  3.1306469938E-16
After solution, condensed matrix:

L2 norm of linear system residual

      iteration    absolute residual    relative residual      reduction

           0  8.8817841970E-16  1.8361992673E-16

Solver information:
   number of iterations =           1
   relative residual =   1.8361992673E-16
After solution, full matrix:

L2 norm of linear system residual

      iteration    absolute residual    relative residual      reduction

           0  8.8817841970E-16  1.8361992673E-16

Norms of error:
   energy norm of error       4.0333158308E+00
   energy error estimate      2.7431604171E+00
      effectivity             6.8012536884E-01

Norms of error:
   energy norm of error       4.0333158308E+00
      reduced by              1.0000000000E+00
   energy error estimate      2.7431604171E+00
      reduced by              1.0000000000E+00
      effectivity             6.8012536884E-01

Total Grid:
   number of vertices      =          29
   number of leaf elements =          40
   number of levels        =           5
   degrees of freedom      =          29
   min and max degree      =           1          1

Total Linear System:
   number of equations =          29
   number of nonzeroes =         165
   condensed matrix number of equations =          29
   condensed matrix number of nonzeroes =         165

L2 norm of linear system residual

      iteration    absolute residual    relative residual      reduction

           0  2.2619968672E+00  5.5062264617E-01
           1  2.0823235471E-02  5.0688598131E-03  9.2056871403E-03
           2  9.8150651112E-04  2.3892151233E-04  4.7135158822E-02
           3  4.9747551850E-05  1.2109711131E-05  5.0684892343E-02
After solution, condensed matrix:

L2 norm of linear system residual

      iteration    absolute residual    relative residual      reduction

           0  4.9747551850E-05  1.2109711131E-05

Solver information:
   number of iterations =           3
   relative residual =   1.2109711131E-05
After solution, full matrix:

L2 norm of linear system residual

      iteration    absolute residual    relative residual      reduction

           0  4.9747551850E-05  1.2109711131E-05

Norms of error:
   energy norm of error       3.0143042418E+00
      reduced by              7.4735140224E-01
   energy error estimate      1.0981744617E+00
      reduced by              4.0033184163E-01
      effectivity             3.6432104179E-01

Total Grid:
   number of vertices      =          36
   number of leaf elements =          48
   number of levels        =           6
   degrees of freedom      =          36
   min and max degree      =           1          1

Total Linear System:
   number of equations =          36
   number of nonzeroes =         202
   condensed matrix number of equations =          36
   condensed matrix number of nonzeroes =         202

L2 norm of linear system residual

      iteration    absolute residual    relative residual      reduction

           0  3.4985670214E+00  8.8146938793E-01
           1  2.1287715040E-02  5.3634728254E-03  6.0846955082E-03
           2  7.3492194661E-04  1.8516472444E-04  3.4523289382E-02
           3  2.4388700000E-05  6.1447707961E-06  3.3185428891E-02
After solution, condensed matrix:

L2 norm of linear system residual

      iteration    absolute residual    relative residual      reduction

           0  2.4388700000E-05  6.1447707961E-06

Solver information:
   number of iterations =           3
   relative residual =   6.1447707961E-06
After solution, full matrix:

L2 norm of linear system residual

      iteration    absolute residual    relative residual      reduction

           0  2.4388700000E-05  6.1447707961E-06

Norms of error:
   energy norm of error       2.9236222992E+00
      reduced by              9.6991612813E-01
   energy error estimate      8.7510892718E-01
      reduced by              7.9687604997E-01
      effectivity             2.9932352323E-01

Total Grid:
   number of vertices      =          75
   number of leaf elements =         108
   number of levels        =           8
   degrees of freedom      =          75
   min and max degree      =           1          1

Total Linear System:
   number of equations =          75
   number of nonzeroes =         439
   condensed matrix number of equations =          75
   condensed matrix number of nonzeroes =         439

L2 norm of linear system residual

      iteration    absolute residual    relative residual      reduction

           0  6.7412312681E+00  1.8598051573E+00
           1  5.8945749277E-02  1.6262253014E-02  8.7440627584E-03
           2  3.3899993918E-03  9.3525026827E-04  5.7510497930E-02
           3  2.0013997050E-04  5.5215632651E-05  5.9038349973E-02
           4  1.1771683048E-05  3.2476317711E-06  5.8817251840E-02
After solution, condensed matrix:

L2 norm of linear system residual

      iteration    absolute residual    relative residual      reduction

           0  1.1771683048E-05  3.2476317711E-06

Solver information:
   number of iterations =           4
   relative residual =   3.2476317711E-06
After solution, full matrix:

L2 norm of linear system residual

      iteration    absolute residual    relative residual      reduction

           0  1.1771683048E-05  3.2476317712E-06

Norms of error:
   energy norm of error       2.0694813748E+00
      reduced by              7.0784840278E-01
   energy error estimate      5.2467006054E-01
      reduced by              5.9954828964E-01
      effectivity             2.5352731700E-01

Total Grid:
   number of vertices      =         170
   number of leaf elements =         290
   number of levels        =           9
   degrees of freedom      =         170
   min and max degree      =           1          1

Total Linear System:
   number of equations =         170
   number of nonzeroes =        1088
   condensed matrix number of equations =         170
   condensed matrix number of nonzeroes =        1088

L2 norm of linear system residual

      iteration    absolute residual    relative residual      reduction

           0  1.0079041485E+01  3.4447084960E+00
           1  2.5147995702E-01  8.5948167372E-02  2.4950781023E-02
           2  9.5651877609E-03  3.2690889897E-03  3.8035586908E-02
           3  7.0078342589E-04  2.3950636819E-04  7.3263948749E-02
           4  4.8809551635E-05  1.6681613767E-05  6.9649980053E-02
           5  3.7028500068E-06  1.2655210217E-06  7.5863225184E-02
After solution, condensed matrix:

L2 norm of linear system residual

      iteration    absolute residual    relative residual      reduction

           0  3.7028500068E-06  1.2655210217E-06

Solver information:
   number of iterations =           5
   relative residual =   1.2655210217E-06
After solution, full matrix:

L2 norm of linear system residual

      iteration    absolute residual    relative residual      reduction

           0  3.7028500068E-06  1.2655210217E-06

Norms of error:
   energy norm of error       1.2083481054E+00
      reduced by              5.8388933581E-01
   energy error estimate      3.5146556620E-01
      reduced by              6.6987921102E-01
      effectivity             2.9086449891E-01

Total Grid:
   number of vertices      =         291
   number of leaf elements =         504
   number of levels        =          10
   degrees of freedom      =         291
   min and max degree      =           1          1

Total Linear System:
   number of equations =         291
   number of nonzeroes =        1879
   condensed matrix number of equations =         291
   condensed matrix number of nonzeroes =        1879

L2 norm of linear system residual

      iteration    absolute residual    relative residual      reduction

           0  9.3734500562E+00  4.0161649275E+00
           1  6.8792414729E-01  2.9474919230E-01  7.3390709202E-02
           2  3.9358990801E-02  1.6863822551E-02  5.7214143385E-02
           3  2.9846710970E-03  1.2788174373E-03  7.5832002708E-02
           4  2.3673749465E-04  1.0143296410E-04  7.9317783086E-02
           5  1.9636869682E-05  8.4136477849E-06  8.2947864725E-02
After solution, condensed matrix:

L2 norm of linear system residual

      iteration    absolute residual    relative residual      reduction

           0  1.9636869682E-05  8.4136477849E-06

Solver information:
   number of iterations =           5
   relative residual =   8.4136477849E-06
After solution, full matrix:

L2 norm of linear system residual

      iteration    absolute residual    relative residual      reduction

           0  1.9636869682E-05  8.4136477848E-06

Norms of error:
   energy norm of error       7.7409901505E-01
      reduced by              3.2031291793E-01
   energy error estimate      2.5575291028E-01
      reduced by              3.6383779078E-01
      effectivity             3.3038785131E-01

Total Grid:
   number of vertices      =         734
   number of leaf elements =        1322
   number of levels        =          12
   degrees of freedom      =         734
   min and max degree      =           1          1

Total Linear System:
   number of equations =         734
   number of nonzeroes =        4844
   condensed matrix number of equations =         734
   condensed matrix number of nonzeroes =        4844

L2 norm of linear system residual

      iteration    absolute residual    relative residual      reduction

           0  1.2953404411E+01  8.4256173733E+00
           1  1.2127831194E+00  7.8886184644E-01  9.3626592745E-02
           2  7.6691603504E-02  4.9884500350E-02  6.3236041362E-02
           3  5.9679973157E-03  3.8819186271E-03  7.7818131882E-02
           4  4.9039087401E-04  3.1897760131E-04  8.2170089574E-02
           5  4.1388244052E-05  2.6921224496E-05  8.4398479346E-02
After solution, condensed matrix:

L2 norm of linear system residual

      iteration    absolute residual    relative residual      reduction

           0  4.1388244052E-05  2.6921224496E-05

Solver information:
   number of iterations =           5
   relative residual =   2.6921224496E-05
After solution, full matrix:

L2 norm of linear system residual

      iteration    absolute residual    relative residual      reduction

           0  4.1388244052E-05  2.6921224496E-05

Norms of error:
   energy norm of error       4.6454551050E-01
      reduced by              6.0011122798E-01
   energy error estimate      1.5324414417E-01
      reduced by              5.9918827123E-01
      effectivity             3.2987972267E-01

Total Grid:
   number of vertices      =         734
   number of leaf elements =        1322
   number of levels        =          12
   degrees of freedom      =         734
   min and max degree      =           1          1

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
