---------------------------------------------------------
           PHAML   Version 1.11.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     2
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     EVERYONE
  print_linsys_when  PHASES
  print_linsys_who   EVERYONE
  print_solver_when  PHASES
  print_solver_who   EVERYONE
  print_error_when   PHASES
  print_error_who    EVERYONE
  print_error_what   LINF_ERR
  print_errest_what  LINF_ERREST
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                   5
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

My Linear System:
   number of equations =           9
   number of equations I own =           9
   number of nonzeroes =          41
   condensed matrix number of equations =           9
   condensed matrix number of equations I own =           9
   condensed matrix number of nonzeroes =          41

Solver information:
   number of iterations =           1
   relative residual =   1.8361992673E-16

Norms of error:
   Linf norm of error         1.0536246503E+00
   Linf error estimate        5.7975309716E+00
      effectivity             5.5024633012E+00

My Grid:
   number of vertices       =          29
   number of vertices I own =          29
   number of elements       =          72
   number of leaf elements  =          40
   leaf elements I own      =          40
   number of levels         =           5
   degrees of freedom       =          29
   degrees of freedom I own =          29
   min and max degree       =           1          1

My Linear System:
   number of equations =          29
   number of equations I own =          29
   number of nonzeroes =         165
   condensed matrix number of equations =          29
   condensed matrix number of equations I own =          29
   condensed matrix number of nonzeroes =         165

Solver information:
   number of iterations =           3
   relative residual =   1.8623819943E-05

Norms of error:
   Linf norm of error         5.2342002897E-01
      reduced by              4.9678035609E-01
   Linf error estimate        9.6811377851E-01
      reduced by              1.6698725427E-01
      effectivity             1.8495925355E+00

My Grid:
   number of vertices       =          36
   number of vertices I own =          36
   number of elements       =          88
   number of leaf elements  =          48
   leaf elements I own      =          48
   number of levels         =           6
   degrees of freedom       =          36
   degrees of freedom I own =          36
   min and max degree       =           1          1

My Linear System:
   number of equations =          36
   number of equations I own =          36
   number of nonzeroes =         202
   condensed matrix number of equations =          36
   condensed matrix number of equations I own =          36
   condensed matrix number of nonzeroes =         202

Solver information:
   number of iterations =           3
   relative residual =   1.0129595913E-05

Norms of error:
   Linf norm of error         4.7530075334E-01
      reduced by              9.0806756912E-01
   Linf error estimate        6.6848758998E-01
      reduced by              6.9050519146E-01
      effectivity             1.4064517788E+00

My Grid:
   number of vertices       =          74
   number of vertices I own =          74
   number of elements       =         204
   number of leaf elements  =         106
   leaf elements I own      =         106
   number of levels         =           7
   degrees of freedom       =          74
   degrees of freedom I own =          74
   min and max degree       =           1          1

My Linear System:
   number of equations =          74
   number of equations I own =          74
   number of nonzeroes =         432
   condensed matrix number of equations =          74
   condensed matrix number of equations I own =          74
   condensed matrix number of nonzeroes =         432

Solver information:
   number of iterations =           3
   relative residual =   3.0073624640E-05

Norms of error:
   Linf norm of error         2.5515801529E-01
      reduced by              5.3683486403E-01
   Linf error estimate        2.6749827851E-01
      reduced by              4.0015444194E-01
      effectivity             1.0483632200E+00

My Grid:
   number of vertices       =         198
   number of vertices I own =         198
   number of elements       =         632
   number of leaf elements  =         320
   leaf elements I own      =         320
   number of levels         =          10
   degrees of freedom       =         198
   degrees of freedom I own =         198
   min and max degree       =           1          1

My Linear System:
   number of equations =         198
   number of equations I own =         198
   number of nonzeroes =        1232
   condensed matrix number of equations =         198
   condensed matrix number of equations I own =         198
   condensed matrix number of nonzeroes =        1232

Solver information:
   number of iterations =           4
   relative residual =   3.4975673989E-06

Norms of error:
   Linf norm of error         1.0088350565E-01
      reduced by              3.9537658864E-01
   Linf error estimate        7.6890602830E-02
      reduced by              2.8744335574E-01
      effectivity             7.6217219392E-01

My Grid:
   number of vertices       =         178
   number of vertices I own =         145
   number of elements       =         608
   number of leaf elements  =         308
   leaf elements I own      =         258
   number of levels         =          10
   degrees of freedom       =         178
   degrees of freedom I own =         145
   min and max degree       =           1          1

My Linear System:
   number of equations =         178
   number of equations I own =         145
   number of nonzeroes =        1148
   condensed matrix number of equations =         178
   condensed matrix number of equations I own =         145
   condensed matrix number of nonzeroes =        1148

Solver information:
   number of iterations =           4
   relative residual =   6.0606977925E-06

Norms of error:
   Linf norm of error         3.9463953247E-02
      reduced by              3.9118340499E-01
   Linf error estimate        3.9091105459E-02
      reduced by              5.0839899833E-01
      effectivity             9.9055219368E-01

My Grid:
   number of vertices       =         329
   number of vertices I own =         286
   number of elements       =        1146
   number of leaf elements  =         577
   leaf elements I own      =         511
   number of levels         =          12
   degrees of freedom       =         329
   degrees of freedom I own =         286
   min and max degree       =           1          1

My Linear System:
   number of equations =         329
   number of equations I own =         286
   number of nonzeroes =        2139
   condensed matrix number of equations =         329
   condensed matrix number of equations I own =         286
   condensed matrix number of nonzeroes =        2139

Solver information:
   number of iterations =           4
   relative residual =   1.7009772942E-06

Norms of error:
   Linf norm of error         3.1262194217E-02
      reduced by              7.9217087100E-01
   Linf error estimate        2.1957514439E-02
      reduced by              5.6170103610E-01
      effectivity             7.0236638820E-01

My Grid:
   number of vertices       =         329
   number of vertices I own =         286
   number of elements       =        1146
   number of leaf elements  =         577
   leaf elements I own      =         511
   number of levels         =          12
   degrees of freedom       =         329
   degrees of freedom I own =         286
   min and max degree       =           1          1

Norms of error:
   Linf norm of error         3.1262194217E-02
   Linf error estimate        2.1957514439E-02
      effectivity             7.0236638820E-01

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
