---------------------------------------------------------
           PHAML   Version 1.9.1

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  PHASES
  print_linsys_who   MASTER
  print_solver_when  PHASES
  print_solver_who   MASTER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  ENERGY_LINF_L2_ERREST
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            RELATIVE ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                   5
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Total Linear System:
   number of equations =           9
   number of nonzeroes =          41
   condensed matrix number of equations =           9
   condensed matrix number of nonzeroes =          41

Solver information:
   number of iterations =           1
   relative residual =   1.8361992673E-16

Norms of error:
   energy norm of error       8.8967046410E-01
   energy error estimate      9.2214211182E-01
      effectivity             1.0364985116E+00
   Linf norm of error         5.2681232515E-01
   Linf error estimate        5.8225309239E-01
      effectivity             1.1052381742E+00
   L2 norm of error           2.0483313171E+00
   L2 error estimate          6.4224833636E-01
      effectivity             3.1354709611E-01

Total Grid:
   number of vertices      =          29
   number of leaf elements =          40
   number of levels        =           5
   degrees of freedom      =          29
   min and max degree      =           1          1

Total Linear System:
   number of equations =          29
   number of nonzeroes =         165
   condensed matrix number of equations =          29
   condensed matrix number of nonzeroes =         165

Solver information:
   number of iterations =           3
   relative residual =   1.8623819943E-05

Norms of error:
   energy norm of error       6.6554774168E-01
      reduced by              7.4808344048E-01
   energy error estimate      3.1429437753E-01
      reduced by              3.4083073910E-01
      effectivity             4.7223415819E-01
   Linf norm of error         2.6171001448E-01
      reduced by              4.9678035609E-01
   Linf error estimate        9.6811377851E-02
      reduced by              1.6627026823E-01
      effectivity             3.6991850710E-01
   L2 norm of error           6.9388538348E-01
      reduced by              3.3875641977E-01
   L2 error estimate          1.4902498288E-01
      reduced by              2.3203638599E-01
      effectivity             2.1476887455E-01

Total Grid:
   number of vertices      =          36
   number of leaf elements =          48
   number of levels        =           6
   degrees of freedom      =          36
   min and max degree      =           1          1

Total Linear System:
   number of equations =          36
   number of nonzeroes =         202
   condensed matrix number of equations =          36
   condensed matrix number of nonzeroes =         202

Solver information:
   number of iterations =           3
   relative residual =   1.0129595913E-05

Norms of error:
   energy norm of error       6.4552530612E-01
      reduced by              9.6991585381E-01
   energy error estimate      2.5209177545E-01
      reduced by              8.0208808515E-01
      effectivity             3.9052190992E-01
   Linf norm of error         2.3765037667E-01
      reduced by              9.0806756912E-01
   Linf error estimate        6.9586779951E-02
      reduced by              7.1878720761E-01
      effectivity             2.9281157020E-01
   L2 norm of error           6.9604364201E-01
      reduced by              1.0031103963E+00
   L2 error estimate          1.0120434972E-01
      reduced by              6.7910995704E-01
      effectivity             1.4539943132E-01

Total Grid:
   number of vertices      =          75
   number of leaf elements =         108
   number of levels        =           8
   degrees of freedom      =          75
   min and max degree      =           1          1

Total Linear System:
   number of equations =          75
   number of nonzeroes =         439
   condensed matrix number of equations =          75
   condensed matrix number of nonzeroes =         439

Solver information:
   number of iterations =           4
   relative residual =   2.1361444499E-06

Norms of error:
   energy norm of error       4.5692912673E-01
      reduced by              7.0784076534E-01
   energy error estimate      1.3070058039E-01
      reduced by              5.1846427819E-01
      effectivity             2.8604125399E-01
   Linf norm of error         1.2760549978E-01
      reduced by              5.3694633928E-01
   Linf error estimate        2.6608200307E-02
      reduced by              3.8237435797E-01
      effectivity             2.0851922803E-01
   L2 norm of error           2.8211755033E-01
      reduced by              4.0531589301E-01
   L2 error estimate          4.3882207647E-02
      reduced by              4.3360001589E-01
      effectivity             1.5554582689E-01

Total Grid:
   number of vertices      =         170
   number of leaf elements =         290
   number of levels        =           9
   degrees of freedom      =         170
   min and max degree      =           1          1

Total Linear System:
   number of equations =         170
   number of nonzeroes =        1088
   condensed matrix number of equations =         170
   condensed matrix number of nonzeroes =        1088

Solver information:
   number of iterations =           4
   relative residual =   3.9390784188E-06

Norms of error:
   energy norm of error       2.6679603999E-01
      reduced by              5.8388932633E-01
   energy error estimate      8.0561391326E-02
      reduced by              6.1638128219E-01
      effectivity             3.0195872221E-01
   Linf norm of error         5.0440038676E-02
      reduced by              3.9528107145E-01
   Linf error estimate        9.1657280046E-03
      reduced by              3.4447004678E-01
      effectivity             1.8171532468E-01
   L2 norm of error           8.7825372294E-02
      reduced by              3.1130772329E-01
   L2 error estimate          1.9759069094E-02
      reduced by              4.5027518336E-01
      effectivity             2.2498133031E-01

Total Grid:
   number of vertices      =         291
   number of leaf elements =         504
   number of levels        =          10
   degrees of freedom      =         291
   min and max degree      =           1          1

Total Linear System:
   number of equations =         291
   number of nonzeroes =        1879
   condensed matrix number of equations =         291
   condensed matrix number of nonzeroes =        1879

Solver information:
   number of iterations =           5
   relative residual =   5.8592332664E-07

Norms of error:
   energy norm of error       1.7091643894E-01
      reduced by              3.2031292321E-01
   energy error estimate      5.7343790062E-02
      reduced by              3.5590118987E-01
      effectivity             3.3550775115E-01
   Linf norm of error         2.0294565832E-02
      reduced by              4.0235032259E-01
   Linf error estimate        4.6025584558E-03
      reduced by              5.0214870587E-01
      effectivity             2.2678772701E-01
   L2 norm of error           4.2230683427E-02
      reduced by              2.4042416402E-01
   L2 error estimate          1.0594320073E-02
      reduced by              2.6808753040E-01
      effectivity             2.5086783384E-01

Total Grid:
   number of vertices      =         734
   number of leaf elements =        1322
   number of levels        =          12
   degrees of freedom      =         734
   min and max degree      =           1          1

Total Linear System:
   number of equations =         734
   number of nonzeroes =        4844
   condensed matrix number of equations =         734
   condensed matrix number of nonzeroes =        4844

Solver information:
   number of iterations =           5
   relative residual =   3.2608428049E-07

Norms of error:
   energy norm of error       1.0256887099E-01
      reduced by              3.0005038811E-01
   energy error estimate      3.4027787681E-02
      reduced by              2.9669397271E-01
      effectivity             3.3175550587E-01
   Linf norm of error         1.5451274397E-02
      reduced by              4.2498678211E-01
   Linf error estimate        1.7172146915E-03
      reduced by              1.9414663483E-01
      effectivity             1.1113741478E-01
   L2 norm of error           1.5600477595E-02
      reduced by              1.8379335356E-01
   L2 error estimate          4.2642480190E-03
      reduced by              2.0036433722E-01
      effectivity             2.7334086364E-01

Total Grid:
   number of vertices      =         734
   number of leaf elements =        1322
   number of levels        =          12
   degrees of freedom      =         734
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.0256887099E-01
   energy error estimate      3.4027787681E-02
      effectivity             3.3175550587E-01
   Linf norm of error         1.5451274397E-02
   Linf error estimate        1.7172146915E-03
      effectivity             1.1113741478E-01
   L2 norm of error           1.5600477595E-02
   L2 error estimate          4.2642480190E-03
      effectivity             2.7334086364E-01

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
