---------------------------------------------------------
           PHAML   Version 1.9.1

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  PHASES
  print_linsys_who   SLAVES
  print_solver_when  PHASES
  print_solver_who   SLAVES
  print_error_when   TOO_MUCH
  print_error_who    SLAVES
  print_error_what   ENERGY_ERR
  print_errest_what  ENERGY_ERREST
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                   5
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

My Linear System:
   number of equations =           9
   number of equations I own =           9
   number of nonzeroes =          41
   condensed matrix number of equations =           9
   condensed matrix number of equations I own =           9
   condensed matrix number of nonzeroes =          41

Solver information:
   number of iterations =           1
   relative residual =   1.8361992673E-16

Norms of error:
   energy norm of error       4.0333158308E+00
   energy error estimate      2.7431604171E+00
      effectivity             6.8012536884E-01

Norms of error:
   energy norm of error       4.0333158308E+00
      reduced by              1.0000000000E+00
   energy error estimate      2.7431604171E+00
      reduced by              1.0000000000E+00
      effectivity             6.8012536884E-01

My Grid:
   number of vertices       =          29
   number of vertices I own =          29
   number of elements       =          72
   number of leaf elements  =          40
   leaf elements I own      =          40
   number of levels         =           5
   degrees of freedom       =          29
   degrees of freedom I own =          29
   min and max degree       =           1          1

My Linear System:
   number of equations =          29
   number of equations I own =          29
   number of nonzeroes =         165
   condensed matrix number of equations =          29
   condensed matrix number of equations I own =          29
   condensed matrix number of nonzeroes =         165

Solver information:
   number of iterations =           3
   relative residual =   1.2109711131E-05

Norms of error:
   energy norm of error       3.0143042418E+00
      reduced by              7.4735140224E-01
   energy error estimate      1.0981744617E+00
      reduced by              4.0033184163E-01
      effectivity             3.6432104179E-01

My Grid:
   number of vertices       =          36
   number of vertices I own =          36
   number of elements       =          88
   number of leaf elements  =          48
   leaf elements I own      =          48
   number of levels         =           6
   degrees of freedom       =          36
   degrees of freedom I own =          36
   min and max degree       =           1          1

My Linear System:
   number of equations =          36
   number of equations I own =          36
   number of nonzeroes =         202
   condensed matrix number of equations =          36
   condensed matrix number of equations I own =          36
   condensed matrix number of nonzeroes =         202

Solver information:
   number of iterations =           3
   relative residual =   6.1447707961E-06

Norms of error:
   energy norm of error       2.9236222992E+00
      reduced by              9.6991612813E-01
   energy error estimate      8.7510892718E-01
      reduced by              7.9687604997E-01
      effectivity             2.9932352323E-01

My Grid:
   number of vertices       =          75
   number of vertices I own =          75
   number of elements       =         208
   number of leaf elements  =         108
   leaf elements I own      =         108
   number of levels         =           8
   degrees of freedom       =          75
   degrees of freedom I own =          75
   min and max degree       =           1          1

My Linear System:
   number of equations =          75
   number of equations I own =          75
   number of nonzeroes =         439
   condensed matrix number of equations =          75
   condensed matrix number of equations I own =          75
   condensed matrix number of nonzeroes =         439

Solver information:
   number of iterations =           4
   relative residual =   3.2476317711E-06

Norms of error:
   energy norm of error       2.0694813748E+00
      reduced by              7.0784840278E-01
   energy error estimate      5.2467006054E-01
      reduced by              5.9954828964E-01
      effectivity             2.5352731700E-01

My Grid:
   number of vertices       =         170
   number of vertices I own =         170
   number of elements       =         572
   number of leaf elements  =         290
   leaf elements I own      =         290
   number of levels         =           9
   degrees of freedom       =         170
   degrees of freedom I own =         170
   min and max degree       =           1          1

My Linear System:
   number of equations =         170
   number of equations I own =         170
   number of nonzeroes =        1088
   condensed matrix number of equations =         170
   condensed matrix number of equations I own =         170
   condensed matrix number of nonzeroes =        1088

Solver information:
   number of iterations =           5
   relative residual =   1.2655210217E-06

Norms of error:
   energy norm of error       1.2083481054E+00
      reduced by              5.8388933581E-01
   energy error estimate      3.5146556620E-01
      reduced by              6.6987921102E-01
      effectivity             2.9086449891E-01

My Grid:
   number of vertices       =         291
   number of vertices I own =         291
   number of elements       =        1000
   number of leaf elements  =         504
   leaf elements I own      =         504
   number of levels         =          10
   degrees of freedom       =         291
   degrees of freedom I own =         291
   min and max degree       =           1          1

My Linear System:
   number of equations =         291
   number of equations I own =         291
   number of nonzeroes =        1879
   condensed matrix number of equations =         291
   condensed matrix number of equations I own =         291
   condensed matrix number of nonzeroes =        1879

Solver information:
   number of iterations =           5
   relative residual =   7.3235095052E-06

Norms of error:
   energy norm of error       7.7409901733E-01
      reduced by              6.4062583774E-01
   energy error estimate      2.5575286730E-01
      reduced by              7.2767545927E-01
      effectivity             3.3038779481E-01

My Grid:
   number of vertices       =         734
   number of vertices I own =         734
   number of elements       =        2636
   number of leaf elements  =        1322
   leaf elements I own      =        1322
   number of levels         =          12
   degrees of freedom       =         734
   degrees of freedom I own =         734
   min and max degree       =           1          1

My Linear System:
   number of equations =         734
   number of equations I own =         734
   number of nonzeroes =        4844
   condensed matrix number of equations =         734
   condensed matrix number of equations I own =         734
   condensed matrix number of nonzeroes =        4844

Solver information:
   number of iterations =           5
   relative residual =   2.4465444231E-05

Norms of error:
   energy norm of error       4.6454550966E-01
      reduced by              6.0011122514E-01
   energy error estimate      1.5324405115E-01
      reduced by              5.9918800820E-01
      effectivity             3.2987952302E-01

My Grid:
   number of vertices       =         734
   number of vertices I own =         734
   number of elements       =        2636
   number of leaf elements  =        1322
   leaf elements I own      =        1322
   number of levels         =          12
   degrees of freedom       =         734
   degrees of freedom I own =         734
   min and max degree       =           1          1

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
