---------------------------------------------------------
           PHAML   Version 1.11.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  PHASES
  print_linsys_who   SLAVES
  print_solver_when  PHASES
  print_solver_who   SLAVES
  print_error_when   PHASES
  print_error_who    SLAVES
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  ENERGY_LINF_L2_ERREST
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            RELATIVE ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                   5
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

My Linear System:
   number of equations =           9
   number of equations I own =           9
   number of nonzeroes =          41
   condensed matrix number of equations =           9
   condensed matrix number of equations I own =           9
   condensed matrix number of nonzeroes =          41

Solver information:
   number of iterations =           1
   relative residual =   1.8361992673E-16

Norms of error:
   energy norm of error       8.8967049138E-01
   energy error estimate      4.6063760926E+00
      effectivity             5.1776204081E+00
   Linf norm of error         5.2681232515E-01
   Linf error estimate        2.8987654858E+00
      effectivity             5.5024633012E+00
   L2 norm of error           2.0483312139E+00
   L2 error estimate          3.2082225894E+00
      effectivity             1.5662616317E+00

My Grid:
   number of vertices       =          29
   number of vertices I own =          29
   number of elements       =          72
   number of leaf elements  =          40
   leaf elements I own      =          40
   number of levels         =           5
   degrees of freedom       =          29
   degrees of freedom I own =          29
   min and max degree       =           1          1

My Linear System:
   number of equations =          29
   number of equations I own =          29
   number of nonzeroes =         165
   condensed matrix number of equations =          29
   condensed matrix number of equations I own =          29
   condensed matrix number of nonzeroes =         165

Solver information:
   number of iterations =           3
   relative residual =   1.8623819943E-05

Norms of error:
   energy norm of error       6.6554777687E-01
      reduced by              7.4808345710E-01
   energy error estimate      1.5506020835E+00
      reduced by              3.3662081696E-01
      effectivity             2.3298133318E+00
   Linf norm of error         2.6171001448E-01
      reduced by              4.9678035609E-01
   Linf error estimate        4.8405688925E-01
      reduced by              1.6698725427E-01
      effectivity             1.8495925355E+00
   L2 norm of error           6.9388537942E-01
      reduced by              3.3875643485E-01
   L2 error estimate          7.3458832028E-01
      reduced by              2.2897049684E-01
      effectivity             1.0586594588E+00

My Grid:
   number of vertices       =          36
   number of vertices I own =          36
   number of elements       =          88
   number of leaf elements  =          48
   leaf elements I own      =          48
   number of levels         =           6
   degrees of freedom       =          36
   degrees of freedom I own =          36
   min and max degree       =           1          1

My Linear System:
   number of equations =          36
   number of equations I own =          36
   number of nonzeroes =         202
   condensed matrix number of equations =          36
   condensed matrix number of equations I own =          36
   condensed matrix number of nonzeroes =         202

Solver information:
   number of iterations =           3
   relative residual =   1.0129595913E-05

Norms of error:
   energy norm of error       6.4552533554E-01
      reduced by              9.6991584673E-01
   energy error estimate      1.2402750919E+00
      reduced by              7.9986677762E-01
      effectivity             1.9213422365E+00
   Linf norm of error         2.3765037667E-01
      reduced by              9.0806756912E-01
   Linf error estimate        3.3424379499E-01
      reduced by              6.9050519146E-01
      effectivity             1.4064517788E+00
   L2 norm of error           6.9604362137E-01
      reduced by              1.0031103724E+00
   L2 error estimate          4.9283923220E-01
      reduced by              6.7090534738E-01
      effectivity             7.0805796802E-01

My Grid:
   number of vertices       =          74
   number of vertices I own =          74
   number of elements       =         204
   number of leaf elements  =         106
   leaf elements I own      =         106
   number of levels         =           7
   degrees of freedom       =          74
   degrees of freedom I own =          74
   min and max degree       =           1          1

My Linear System:
   number of equations =          74
   number of equations I own =          74
   number of nonzeroes =         432
   condensed matrix number of equations =          74
   condensed matrix number of equations I own =          74
   condensed matrix number of nonzeroes =         432

Solver information:
   number of iterations =           3
   relative residual =   3.0073624640E-05

Norms of error:
   energy norm of error       4.6203042565E-01
      reduced by              7.1574328723E-01
   energy error estimate      6.3148619968E-01
      reduced by              5.0915011016E-01
      effectivity             1.3667632360E+00
   Linf norm of error         1.2757900764E-01
      reduced by              5.3683486403E-01
   Linf error estimate        1.3374913926E-01
      reduced by              4.0015444194E-01
      effectivity             1.0483632200E+00
   L2 norm of error           2.8037110995E-01
      reduced by              4.0280680885E-01
   L2 error estimate          2.0703103518E-01
      reduced by              4.2007823577E-01
      effectivity             7.3841786060E-01

My Grid:
   number of vertices       =         198
   number of vertices I own =         198
   number of elements       =         632
   number of leaf elements  =         320
   leaf elements I own      =         320
   number of levels         =          10
   degrees of freedom       =         198
   degrees of freedom I own =         198
   min and max degree       =           1          1

My Linear System:
   number of equations =         198
   number of equations I own =         198
   number of nonzeroes =        1232
   condensed matrix number of equations =         198
   condensed matrix number of equations I own =         198
   condensed matrix number of nonzeroes =        1232

Solver information:
   number of iterations =           4
   relative residual =   3.4975673989E-06

Norms of error:
   energy norm of error       2.6565995244E-01
      reduced by              5.7498367573E-01
   energy error estimate      3.4199327338E-01
      reduced by              5.4156887919E-01
      effectivity             1.2873346933E+00
   Linf norm of error         5.0441752824E-02
      reduced by              3.9537658864E-01
   Linf error estimate        3.8445301415E-02
      reduced by              2.8744335574E-01
      effectivity             7.6217219392E-01
   L2 norm of error           8.7718586763E-02
      reduced by              3.1286599671E-01
   L2 error estimate          8.0658525502E-02
      reduced by              3.8959630102E-01
      effectivity             9.1951464882E-01

My Grid:
   number of vertices       =         297
   number of vertices I own =         297
   number of elements       =        1024
   number of leaf elements  =         516
   leaf elements I own      =         516
   number of levels         =          10
   degrees of freedom       =         297
   degrees of freedom I own =         297
   min and max degree       =           1          1

My Linear System:
   number of equations =         297
   number of equations I own =         297
   number of nonzeroes =        1921
   condensed matrix number of equations =         297
   condensed matrix number of equations I own =         297
   condensed matrix number of nonzeroes =        1921

Solver information:
   number of iterations =           4
   relative residual =   6.0165593840E-06

Norms of error:
   energy norm of error       1.6932749217E-01
      reduced by              6.3738433519E-01
   energy error estimate      2.5578384923E-01
      reduced by              7.4792070236E-01
      effectivity             1.5105866505E+00
   Linf norm of error         1.9731979829E-02
      reduced by              3.9118346854E-01
   Linf error estimate        1.9545552433E-02
      reduced by              5.0839899062E-01
      effectivity             9.9055201773E-01
   L2 norm of error           4.1734567757E-02
      reduced by              4.7577793142E-01
   L2 error estimate          4.6887903267E-02
      reduced by              5.8131366740E-01
      effectivity             1.1234788279E+00

My Grid:
   number of vertices       =         582
   number of vertices I own =         582
   number of elements       =        2036
   number of leaf elements  =        1022
   leaf elements I own      =        1022
   number of levels         =          12
   degrees of freedom       =         582
   degrees of freedom I own =         582
   min and max degree       =           1          1

My Linear System:
   number of equations =         582
   number of equations I own =         582
   number of nonzeroes =        3788
   condensed matrix number of equations =         582
   condensed matrix number of equations I own =         582
   condensed matrix number of nonzeroes =        3788

Solver information:
   number of iterations =           4
   relative residual =   1.6728674463E-06

Norms of error:
   energy norm of error       1.3440828203E-01
      reduced by              7.9377707839E-01
   energy error estimate      1.7428440554E-01
      reduced by              6.8137376956E-01
      effectivity             1.2966790656E+00
   Linf norm of error         1.5631097110E-02
      reduced by              7.9217074239E-01
   Linf error estimate        1.0978756122E-02
      reduced by              5.6170098846E-01
      effectivity             7.0236631790E-01
   L2 norm of error           3.3332421303E-02
      reduced by              7.9867656705E-01
   L2 error estimate          3.0867568466E-02
      reduced by              6.5832690983E-01
      effectivity             9.2605239162E-01

My Grid:
   number of vertices       =         582
   number of vertices I own =         582
   number of elements       =        2036
   number of leaf elements  =        1022
   leaf elements I own      =        1022
   number of levels         =          12
   degrees of freedom       =         582
   degrees of freedom I own =         582
   min and max degree       =           1          1

Norms of error:
   energy norm of error       1.3440828203E-01
   energy error estimate      1.7428440554E-01
      effectivity             1.2966790656E+00
   Linf norm of error         1.5631097110E-02
   Linf error estimate        1.0978756122E-02
      effectivity             7.0236631790E-01
   L2 norm of error           3.3332421303E-02
   L2 error estimate          3.0867568466E-02
      effectivity             9.2605239162E-01

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
