---------------------------------------------------------
           PHAML   Version 1.11.0

Output from slave number     1
  PDE id is     0
  Number of slave processors is     1
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     SLAVES
  print_linsys_when  PHASES
  print_linsys_who   SLAVES
  print_solver_when  PHASES
  print_solver_who   SLAVES
  print_error_when   TOO_MUCH
  print_error_who    SLAVES
  print_error_what   ENERGY_ERR
  print_errest_what  ENERGY_ERREST
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                   5
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

My Grid:
   number of vertices       =           9
   number of vertices I own =           9
   number of elements       =           8
   number of leaf elements  =           8
   leaf elements I own      =           8
   number of levels         =           1
   degrees of freedom       =           9
   degrees of freedom I own =           9
   min and max degree       =           1          1

My Linear System:
   number of equations =           9
   number of equations I own =           9
   number of nonzeroes =          41
   condensed matrix number of equations =           9
   condensed matrix number of equations I own =           9
   condensed matrix number of nonzeroes =          41

Solver information:
   number of iterations =           1
   relative residual =   1.8361992673E-16

Norms of error:
   energy norm of error       4.0333158308E+00
   energy error estimate      1.3702907531E+01
      effectivity             3.3974298334E+00

Norms of error:
   energy norm of error       4.0333158308E+00
      reduced by              1.0000000000E+00
   energy error estimate      1.3702907531E+01
      reduced by              1.0000000000E+00
      effectivity             3.3974298334E+00

My Grid:
   number of vertices       =          29
   number of vertices I own =          29
   number of elements       =          72
   number of leaf elements  =          40
   leaf elements I own      =          40
   number of levels         =           5
   degrees of freedom       =          29
   degrees of freedom I own =          29
   min and max degree       =           1          1

My Linear System:
   number of equations =          29
   number of equations I own =          29
   number of nonzeroes =         165
   condensed matrix number of equations =          29
   condensed matrix number of equations I own =          29
   condensed matrix number of nonzeroes =         165

Solver information:
   number of iterations =           3
   relative residual =   1.2109711131E-05

Norms of error:
   energy norm of error       3.0143042418E+00
      reduced by              7.4735140224E-01
   energy error estimate      5.4179531092E+00
      reduced by              3.9538711744E-01
      effectivity             1.7974141542E+00

My Grid:
   number of vertices       =          36
   number of vertices I own =          36
   number of elements       =          88
   number of leaf elements  =          48
   leaf elements I own      =          48
   number of levels         =           6
   degrees of freedom       =          36
   degrees of freedom I own =          36
   min and max degree       =           1          1

My Linear System:
   number of equations =          36
   number of equations I own =          36
   number of nonzeroes =         202
   condensed matrix number of equations =          36
   condensed matrix number of equations I own =          36
   condensed matrix number of nonzeroes =         202

Solver information:
   number of iterations =           3
   relative residual =   6.1447707962E-06

Norms of error:
   energy norm of error       2.9236222992E+00
      reduced by              9.6991612813E-01
   energy error estimate      4.3054794572E+00
      reduced by              7.9466901437E-01
      effectivity             1.4726524210E+00

My Grid:
   number of vertices       =          74
   number of vertices I own =          74
   number of elements       =         204
   number of leaf elements  =         106
   leaf elements I own      =         106
   number of levels         =           7
   degrees of freedom       =          74
   degrees of freedom I own =          74
   min and max degree       =           1          1

My Linear System:
   number of equations =          74
   number of equations I own =          74
   number of nonzeroes =         432
   condensed matrix number of equations =          74
   condensed matrix number of equations I own =          74
   condensed matrix number of nonzeroes =         432

Solver information:
   number of iterations =           3
   relative residual =   1.4657628864E-05

Norms of error:
   energy norm of error       2.0925858344E+00
      reduced by              7.1575108555E-01
   energy error estimate      2.5429959249E+00
      reduced by              5.9064175088E-01
      effectivity             1.2152409154E+00

My Grid:
   number of vertices       =         198
   number of vertices I own =         198
   number of elements       =         632
   number of leaf elements  =         320
   leaf elements I own      =         320
   number of levels         =          10
   degrees of freedom       =         198
   degrees of freedom I own =         198
   min and max degree       =           1          1

My Linear System:
   number of equations =         198
   number of equations I own =         198
   number of nonzeroes =        1232
   condensed matrix number of equations =         198
   condensed matrix number of equations I own =         198
   condensed matrix number of nonzeroes =        1232

Solver information:
   number of iterations =           5
   relative residual =   1.5382960827E-06

Norms of error:
   energy norm of error       1.2032026194E+00
      reduced by              5.7498363969E-01
   energy error estimate      1.4911968160E+00
      reduced by              5.8639371042E-01
      effectivity             1.2393563577E+00

My Grid:
   number of vertices       =         297
   number of vertices I own =         297
   number of elements       =        1024
   number of leaf elements  =         516
   leaf elements I own      =         516
   number of levels         =          10
   degrees of freedom       =         297
   degrees of freedom I own =         297
   min and max degree       =           1          1

My Linear System:
   number of equations =         297
   number of equations I own =         297
   number of nonzeroes =        1921
   condensed matrix number of equations =         297
   condensed matrix number of equations I own =         297
   condensed matrix number of nonzeroes =        1921

Solver information:
   number of iterations =           5
   relative residual =   7.0007895052E-06

Norms of error:
   energy norm of error       7.6690248511E-01
      reduced by              6.3738432142E-01
   energy error estimate      1.1411091446E+00
      reduced by              7.6523040580E-01
      effectivity             1.4879455560E+00

My Grid:
   number of vertices       =         582
   number of vertices I own =         582
   number of elements       =        2036
   number of leaf elements  =        1022
   leaf elements I own      =        1022
   number of levels         =          12
   degrees of freedom       =         582
   degrees of freedom I own =         582
   min and max degree       =           1          1

My Linear System:
   number of equations =         582
   number of equations I own =         582
   number of nonzeroes =        3788
   condensed matrix number of equations =         582
   condensed matrix number of equations I own =         582
   condensed matrix number of nonzeroes =        3788

Solver information:
   number of iterations =           5
   relative residual =   1.1524781886E-05

Norms of error:
   energy norm of error       6.0874961498E-01
      reduced by              7.9377707961E-01
   energy error estimate      7.8142536814E-01
      reduced by              6.8479458938E-01
      effectivity             1.2836564474E+00

My Grid:
   number of vertices       =         582
   number of vertices I own =         582
   number of elements       =        2036
   number of leaf elements  =        1022
   leaf elements I own      =        1022
   number of levels         =          12
   degrees of freedom       =         582
   degrees of freedom I own =         582
   min and max degree       =           1          1

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
