
Total Grid:
   number of vertices      =         582
   number of leaf elements =        1022
   number of levels        =          12
   degrees of freedom      =         582
   min and max degree      =           1          1

Norms of error:
   energy norm of error       6.0874963065E-01
   energy error estimate      7.8142402311E-01
      effectivity             1.2836542049E+00
   Linf norm of error         3.1262194214E-02
   Linf error estimate        2.1957514363E-02
      effectivity             7.0236638583E-01
