---------------------------------------------------------
           PHAML   Version 1.11.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  PHASES
  print_linsys_who   MASTER
  print_solver_when  PHASES
  print_solver_who   MASTER
  print_error_when   TOO_MUCH
  print_error_who    MASTER
  print_error_what   ENERGY_ERR
  print_errest_what  ENERGY_ERREST
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                   5
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Total Linear System:
   number of equations =           9
   number of nonzeroes =          41
   condensed matrix number of equations =           9
   condensed matrix number of nonzeroes =          41

L2 norm of linear system residual

      iteration    absolute residual    relative residual      reduction

           0  2.8370442961E+00  5.8652389456E-01
           1  8.8817841970E-16  1.8361992673E-16  3.1306469938E-16
After solution, condensed matrix:

L2 norm of linear system residual

      iteration    absolute residual    relative residual      reduction

           0  8.8817841970E-16  1.8361992673E-16

Solver information:
   number of iterations =           1
   relative residual =   1.8361992673E-16
After solution, full matrix:

L2 norm of linear system residual

      iteration    absolute residual    relative residual      reduction

           0  8.8817841970E-16  1.8361992673E-16

Norms of error:
   energy norm of error       4.0333158308E+00
   energy error estimate      1.3702907531E+01
      effectivity             3.3974298334E+00

Norms of error:
   energy norm of error       4.0333158308E+00
      reduced by              1.0000000000E+00
   energy error estimate      1.3702907531E+01
      reduced by              1.0000000000E+00
      effectivity             3.3974298334E+00

Total Grid:
   number of vertices      =          29
   number of leaf elements =          40
   number of levels        =           5
   degrees of freedom      =          29
   min and max degree      =           1          1

Total Linear System:
   number of equations =          29
   number of nonzeroes =         165
   condensed matrix number of equations =          29
   condensed matrix number of nonzeroes =         165

L2 norm of linear system residual

      iteration    absolute residual    relative residual      reduction

           0  2.2619968672E+00  5.5062264617E-01
           1  2.0823235471E-02  5.0688598131E-03  9.2056871403E-03
           2  9.8150651112E-04  2.3892151233E-04  4.7135158822E-02
           3  4.9747551850E-05  1.2109711131E-05  5.0684892343E-02
After solution, condensed matrix:

L2 norm of linear system residual

      iteration    absolute residual    relative residual      reduction

           0  4.9747551850E-05  1.2109711131E-05

Solver information:
   number of iterations =           3
   relative residual =   1.2109711131E-05
After solution, full matrix:

L2 norm of linear system residual

      iteration    absolute residual    relative residual      reduction

           0  4.9747551850E-05  1.2109711131E-05

Norms of error:
   energy norm of error       3.0143042418E+00
      reduced by              7.4735140224E-01
   energy error estimate      5.4179531092E+00
      reduced by              3.9538711744E-01
      effectivity             1.7974141542E+00

Total Grid:
   number of vertices      =          36
   number of leaf elements =          48
   number of levels        =           6
   degrees of freedom      =          36
   min and max degree      =           1          1

Total Linear System:
   number of equations =          36
   number of nonzeroes =         202
   condensed matrix number of equations =          36
   condensed matrix number of nonzeroes =         202

L2 norm of linear system residual

      iteration    absolute residual    relative residual      reduction

           0  3.4985670214E+00  8.8146938793E-01
           1  2.1287715040E-02  5.3634728254E-03  6.0846955082E-03
           2  7.3492194661E-04  1.8516472444E-04  3.4523289382E-02
After solution, condensed matrix:

L2 norm of linear system residual

      iteration    absolute residual    relative residual      reduction

           0  7.3492194661E-04  1.8516472444E-04

Solver information:
   number of iterations =           2
   relative residual =   1.8516472444E-04
After solution, full matrix:

L2 norm of linear system residual

      iteration    absolute residual    relative residual      reduction

           0  7.3492194661E-04  1.8516472444E-04

Norms of error:
   energy norm of error       2.9236246434E+00
      reduced by              9.6991690580E-01
   energy error estimate      4.3054820597E+00
      reduced by              7.9466949473E-01
      effectivity             1.4726521305E+00

Total Grid:
   number of vertices      =          74
   number of leaf elements =         106
   number of levels        =           7
   degrees of freedom      =          74
   min and max degree      =           1          1

Total Linear System:
   number of equations =          74
   number of nonzeroes =         432
   condensed matrix number of equations =          74
   condensed matrix number of nonzeroes =         432

L2 norm of linear system residual

      iteration    absolute residual    relative residual      reduction

           0  5.7472119894E+00  1.5618412442E+00
           1  2.6721700235E-02  7.2617912164E-03  4.6495066276E-03
           2  1.0726926566E-03  2.9151102074E-04  4.0143128886E-02
           3  5.3936660115E-05  1.4657628864E-05  5.0281559945E-02
After solution, condensed matrix:

L2 norm of linear system residual

      iteration    absolute residual    relative residual      reduction

           0  5.3936660115E-05  1.4657628864E-05

Solver information:
   number of iterations =           3
   relative residual =   1.4657628864E-05
After solution, full matrix:

L2 norm of linear system residual

      iteration    absolute residual    relative residual      reduction

           0  5.3936660115E-05  1.4657628864E-05

Norms of error:
   energy norm of error       2.0925858344E+00
      reduced by              7.1575051166E-01
   energy error estimate      2.5429959249E+00
      reduced by              5.9064139385E-01
      effectivity             1.2152409154E+00

Total Grid:
   number of vertices      =         198
   number of leaf elements =         320
   number of levels        =          10
   degrees of freedom      =         198
   min and max degree      =           1          1

Total Linear System:
   number of equations =         198
   number of nonzeroes =        1232
   condensed matrix number of equations =         198
   condensed matrix number of nonzeroes =        1232

L2 norm of linear system residual

      iteration    absolute residual    relative residual      reduction

           0  1.0959787663E+01  3.7865021338E+00
           1  3.1387012444E-01  1.0843913518E-01  2.8638339911E-02
           2  1.3849360326E-02  4.7848219363E-03  4.4124493692E-02
           3  9.1680754392E-04  3.1674826448E-04  6.6198547971E-02
           4  6.1531849335E-05  2.1258667227E-05  6.7115339248E-02
After solution, condensed matrix:

L2 norm of linear system residual

      iteration    absolute residual    relative residual      reduction

           0  6.1531849335E-05  2.1258667227E-05

Solver information:
   number of iterations =           4
   relative residual =   2.1258667227E-05
After solution, full matrix:

L2 norm of linear system residual

      iteration    absolute residual    relative residual      reduction

           0  6.1531849334E-05  2.1258667227E-05

Norms of error:
   energy norm of error       1.2032025935E+00
      reduced by              5.7498362730E-01
   energy error estimate      1.4911994532E+00
      reduced by              5.8639474747E-01
      effectivity             1.2393585763E+00

Total Grid:
   number of vertices      =         297
   number of leaf elements =         516
   number of levels        =          10
   degrees of freedom      =         297
   min and max degree      =           1          1

Total Linear System:
   number of equations =         297
   number of nonzeroes =        1921
   condensed matrix number of equations =         297
   condensed matrix number of nonzeroes =        1921

L2 norm of linear system residual

      iteration    absolute residual    relative residual      reduction

           0  1.0417381502E+01  4.5066697194E+00
           1  6.5079263904E-01  2.8153979764E-01  6.2471806270E-02
           2  3.8055133704E-02  1.6463054434E-02  5.8475052453E-02
           3  2.8962719735E-03  1.2529579722E-03  7.6107260482E-02
           4  2.2934017336E-04  9.9214991262E-05  7.9184612306E-02
           5  1.8937935251E-05  8.1927516361E-06  8.2575743160E-02
After solution, condensed matrix:

L2 norm of linear system residual

      iteration    absolute residual    relative residual      reduction

           0  1.8937935251E-05  8.1927516361E-06

Solver information:
   number of iterations =           5
   relative residual =   8.1927516361E-06
After solution, full matrix:

L2 norm of linear system residual

      iteration    absolute residual    relative residual      reduction

           0  1.8937935251E-05  8.1927516361E-06

Norms of error:
   energy norm of error       7.6690248327E-01
      reduced by              3.1869216681E-01
   energy error estimate      1.1411092739E+00
      reduced by              3.8261456958E-01
      effectivity             1.4879457282E+00

Total Grid:
   number of vertices      =         582
   number of leaf elements =        1022
   number of levels        =          12
   degrees of freedom      =         582
   min and max degree      =           1          1

Total Linear System:
   number of equations =         582
   number of nonzeroes =        3788
   condensed matrix number of equations =         582
   condensed matrix number of nonzeroes =        3788

L2 norm of linear system residual

      iteration    absolute residual    relative residual      reduction

           0  1.4360347597E+01  8.3340632317E+00
           1  7.5619253918E-01  4.3885820967E-01  5.2658372929E-02
           2  4.2675188279E-02  2.4766651025E-02  5.6434288978E-02
           3  3.2363184938E-03  1.8782054391E-03  7.5836068316E-02
           4  2.5784653405E-04  1.4964187352E-04  7.9672793191E-02
           5  2.0942325147E-05  1.2153930175E-05  8.1220114996E-02
After solution, condensed matrix:

L2 norm of linear system residual

      iteration    absolute residual    relative residual      reduction

           0  2.0942325147E-05  1.2153930175E-05

Solver information:
   number of iterations =           5
   relative residual =   1.2153930175E-05
After solution, full matrix:

L2 norm of linear system residual

      iteration    absolute residual    relative residual      reduction

           0  2.0942325147E-05  1.2153930175E-05

Norms of error:
   energy norm of error       6.0874961325E-01
      reduced by              7.9377707927E-01
   energy error estimate      7.8142534423E-01
      reduced by              6.8479449086E-01
      effectivity             1.2836564118E+00

Total Grid:
   number of vertices      =         582
   number of leaf elements =        1022
   number of levels        =          12
   degrees of freedom      =         582
   min and max degree      =           1          1

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
