---------------------------------------------------------
           PHAML   Version 1.11.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  PHASES
  print_linsys_who   MASTER
  print_solver_when  PHASES
  print_solver_who   MASTER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  ENERGY_LINF_L2_ERREST
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                   5
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Total Linear System:
   number of equations =           9
   number of nonzeroes =          41
   condensed matrix number of equations =           9
   condensed matrix number of nonzeroes =          41

Solver information:
   number of iterations =           1
   relative residual =   1.8361992673E-16

Norms of error:
   energy norm of error       4.0333158308E+00
   energy error estimate      1.3702907531E+01
      effectivity             3.3974298334E+00
   Linf norm of error         1.0536246503E+00
   Linf error estimate        5.7975309716E+00
      effectivity             5.5024633012E+00
   L2 norm of error           4.5345860840E-01
   L2 error estimate          1.9378837674E+00
      effectivity             4.2735626394E+00

Total Grid:
   number of vertices      =          29
   number of leaf elements =          40
   number of levels        =           5
   degrees of freedom      =          29
   min and max degree      =           1          1

Total Linear System:
   number of equations =          29
   number of nonzeroes =         165
   condensed matrix number of equations =          29
   condensed matrix number of nonzeroes =         165

Solver information:
   number of iterations =           3
   relative residual =   1.8623819943E-05

Norms of error:
   energy norm of error       3.0143054217E+00
      reduced by              7.4735169478E-01
   energy error estimate      5.4179551886E+00
      reduced by              3.9538726919E-01
      effectivity             1.7974141404E+00
   Linf norm of error         5.2342002897E-01
      reduced by              4.9678035609E-01
   Linf error estimate        9.6811377851E-01
      reduced by              1.6698725427E-01
      effectivity             1.8495925355E+00
   L2 norm of error           1.6018458492E-01
      reduced by              3.5325073104E-01
   L2 error estimate          2.5923472838E-01
      reduced by              1.3377207279E-01
      effectivity             1.6183500336E+00

Total Grid:
   number of vertices      =          36
   number of leaf elements =          48
   number of levels        =           6
   degrees of freedom      =          36
   min and max degree      =           1          1

Total Linear System:
   number of equations =          36
   number of nonzeroes =         202
   condensed matrix number of equations =          36
   condensed matrix number of nonzeroes =         202

Solver information:
   number of iterations =           2
   relative residual =   1.8251165643E-04

Norms of error:
   energy norm of error       2.9236295852E+00
      reduced by              9.6991816562E-01
   energy error estimate      4.3054922881E+00
      reduced by              7.9467107760E-01
      effectivity             1.4726531397E+00
   Linf norm of error         4.7530118457E-01
      reduced by              9.0806839301E-01
   Linf error estimate        6.6849065103E-01
      reduced by              6.9050835333E-01
      effectivity             1.4064569429E+00
   L2 norm of error           1.6066430468E-01
      reduced by              1.0029947935E+00
   L2 error estimate          1.7330679090E-01
      reduced by              6.6853230652E-01
      effectivity             1.0786888304E+00

Total Grid:
   number of vertices      =          74
   number of leaf elements =         106
   number of levels        =           7
   degrees of freedom      =          74
   min and max degree      =           1          1

Total Linear System:
   number of equations =          74
   number of nonzeroes =         432
   condensed matrix number of equations =          74
   condensed matrix number of nonzeroes =         432

Solver information:
   number of iterations =           3
   relative residual =   3.0054558645E-05

Norms of error:
   energy norm of error       2.0925857191E+00
      reduced by              7.1574926238E-01
   energy error estimate      2.5429897789E+00
      reduced by              5.9063856319E-01
      effectivity             1.2152380453E+00
   Linf norm of error         2.5515801311E-01
      reduced by              5.3683437237E-01
   Linf error estimate        2.6749827851E-01
      reduced by              4.0015260961E-01
      effectivity             1.0483632290E+00
   L2 norm of error           6.4737988500E-02
      reduced by              4.0293946207E-01
   L2 error estimate          5.8429564971E-02
      reduced by              3.3714527093E-01
      effectivity             9.0255453289E-01

Total Grid:
   number of vertices      =         198
   number of leaf elements =         320
   number of levels        =          10
   degrees of freedom      =         198
   min and max degree      =           1          1

Total Linear System:
   number of equations =         198
   number of nonzeroes =        1232
   condensed matrix number of equations =         198
   condensed matrix number of nonzeroes =        1232

Solver information:
   number of iterations =           4
   relative residual =   3.4975669339E-06

Norms of error:
   energy norm of error       1.2032026285E+00
      reduced by              5.7498367570E-01
   energy error estimate      1.4911960641E+00
      reduced by              5.8639483198E-01
      effectivity             1.2393557235E+00
   Linf norm of error         1.0088350565E-01
      reduced by              3.9537659202E-01
   Linf error estimate        7.6890602830E-02
      reduced by              2.8744335574E-01
      effectivity             7.6217219392E-01
   L2 norm of error           2.0254377625E-02
      reduced by              3.1286695948E-01
   L2 error estimate          1.9963375873E-02
      reduced by              3.4166565990E-01
      effectivity             9.8563264908E-01

Total Grid:
   number of vertices      =         297
   number of leaf elements =         516
   number of levels        =          10
   degrees of freedom      =         297
   min and max degree      =           1          1

Total Linear System:
   number of equations =         297
   number of nonzeroes =        1921
   condensed matrix number of equations =         297
   condensed matrix number of nonzeroes =        1921

Solver information:
   number of iterations =           5
   relative residual =   5.7900301769E-07

Norms of error:
   energy norm of error       7.6690250097E-01
      reduced by              3.1869216490E-01
   energy error estimate      1.1411075213E+00
      reduced by              3.8261485150E-01
      effectivity             1.4879434085E+00
   Linf norm of error         3.9463951448E-02
      reduced by              3.9118338716E-01
   Linf error estimate        3.9091111889E-02
      reduced by              5.0839908195E-01
      effectivity             9.9055240176E-01
   L2 norm of error           9.6362685544E-03
      reduced by              2.3788113200E-01
   L2 error estimate          1.1157994354E-02
      reduced by              2.7946161073E-01
      effectivity             1.1579164997E+00

Total Grid:
   number of vertices      =         582
   number of leaf elements =        1022
   number of levels        =          12
   degrees of freedom      =         582
   min and max degree      =           1          1

Total Linear System:
   number of equations =         582
   number of nonzeroes =        3788
   condensed matrix number of equations =         582
   condensed matrix number of nonzeroes =        3788

Solver information:
   number of iterations =           4
   relative residual =   1.7187377332E-06

Norms of error:
   energy norm of error       6.0874963065E-01
      reduced by              7.9377708363E-01
   energy error estimate      7.8142402311E-01
      reduced by              6.8479438488E-01
      effectivity             1.2836542049E+00
   Linf norm of error         3.1262194214E-02
      reduced by              7.9217090705E-01
   Linf error estimate        2.1957514363E-02
      reduced by              5.6170094177E-01
      effectivity             7.0236638583E-01
   L2 norm of error           7.6964551680E-03
      reduced by              7.9869662458E-01
   L2 error estimate          7.2592989727E-03
      reduced by              6.5059174097E-01
      effectivity             9.4320031941E-01

Total Grid:
   number of vertices      =         582
   number of leaf elements =        1022
   number of levels        =          12
   degrees of freedom      =         582
   min and max degree      =           1          1

Norms of error:
   energy norm of error       6.0874963065E-01
   energy error estimate      7.8142402311E-01
      effectivity             1.2836542049E+00
   Linf norm of error         3.1262194214E-02
   Linf error estimate        2.1957514363E-02
      effectivity             7.0236638583E-01
   L2 norm of error           7.6964551680E-03
   L2 error estimate          7.2592989727E-03
      effectivity             9.4320031941E-01

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
