---------------------------------------------------------
           PHAML   Version 1.9.1

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree                      4
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             HYPRE_PCG_SOLVER
  preconditioner     HYPRE_DS_PRECONDITION
  hypre_PCG_Tol                    default
  hypre_PCG_MaxIter                default
  hypre_PCG_TwoNorm                default
  hypre_PCG_RelChange              default
  hypre_PCG_Logging                default
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =          81
   min and max degree      =           4          4

Norms of error:
   energy norm of error       8.6271851999E-02
   Linf norm of error         1.0764133692E-02
   L2 norm of error           4.3498770589E-03

Total Grid:
   number of vertices      =          19
   number of leaf elements =          24
   number of levels        =           3
   degrees of freedom      =         217
   min and max degree      =           4          4

Norms of error:
   energy norm of error       7.7771499751E-03
      reduced by              9.0147015450E-02
   Linf norm of error         7.0294450970E-04
      reduced by              6.5304327299E-02
   L2 norm of error           1.9281272958E-04
      reduced by              4.4326018176E-02

Total Grid:
   number of vertices      =          28
   number of leaf elements =          40
   number of levels        =           4
   degrees of freedom      =         349
   min and max degree      =           4          4

Norms of error:
   energy norm of error       3.9461930021E-03
      reduced by              5.0740862845E-01
   Linf norm of error         3.5674009990E-04
      reduced by              5.0749396997E-01
   L2 norm of error           8.4281401347E-05
      reduced by              4.3711533742E-01

Total Grid:
   number of vertices      =          51
   number of leaf elements =          76
   number of levels        =           5
   degrees of freedom      =         657
   min and max degree      =           4          4

Norms of error:
   energy norm of error       8.4877566763E-04
      reduced by              2.1508721625E-01
   Linf norm of error         5.8530721542E-05
      reduced by              1.6407104656E-01
   L2 norm of error           1.6251869739E-05
      reduced by              1.9282866065E-01

Total Grid:
   number of vertices      =         111
   number of leaf elements =         192
   number of levels        =           7
   degrees of freedom      =        1593
   min and max degree      =           4          4

Norms of error:
   energy norm of error       1.9610591733E-04
      reduced by              2.3104563998E-01
   Linf norm of error         1.4914711549E-05
      reduced by              2.5481851506E-01
   L2 norm of error           2.3152497489E-06
      reduced by              1.4246051599E-01

Total Grid:
   number of vertices      =         182
   number of leaf elements =         320
   number of levels        =           7
   degrees of freedom      =        2645
   min and max degree      =           4          4

Norms of error:
   energy norm of error       4.4415211909E-05
      reduced by              1.1324291616E-01
   Linf norm of error         2.7347764131E-06
      reduced by              1.8336099925E-01
   L2 norm of error           4.0315663306E-07
      reduced by              8.7065473875E-02

Total Grid:
   number of vertices      =         350
   number of leaf elements =         644
   number of levels        =           9
   degrees of freedom      =        5261
   min and max degree      =           4          4

Norms of error:
   energy norm of error       1.6188316225E-05
      reduced by              3.6447684317E-01
   Linf norm of error         9.0443516821E-07
      reduced by              3.3071631153E-01
   L2 norm of error           1.2694432811E-07
      reduced by              3.1487595067E-01

Total Grid:
   number of vertices      =         710
   number of leaf elements =        1336
   number of levels        =           9
   degrees of freedom      =       10853
   min and max degree      =           4          4

Norms of error:
   energy norm of error       4.6135427180E-06
      reduced by              2.8499212974E-01
   Linf norm of error         6.6187588034E-07
      reduced by              7.3181130456E-01
   L2 norm of error           7.4959738197E-08
      reduced by              5.9049300836E-01

Total Grid:
   number of vertices      =         710
   number of leaf elements =        1336
   number of levels        =           9
   degrees of freedom      =       10853
   min and max degree      =           4          4

Norms of error:
   energy norm of error       4.6135427180E-06
   Linf norm of error         6.6187588034E-07
   L2 norm of error           7.4959738197E-08

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           7
termination condition:
  maximum vertices achieved
---------------------------------------------------------
