---------------------------------------------------------
           PHAML   Version 1.11.0

Output from the master process
  PDE id is     0
  Number of slave processors is     4
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         true
  isosceles_right_triangles  true
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_LINF_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree                      4
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             HYPRE_PCG_SOLVER
  preconditioner     HYPRE_DS_PRECONDITION
  hypre_PCG_Tol                    default
  hypre_PCG_MaxIter                default
  hypre_PCG_TwoNorm                default
  hypre_PCG_RelChange              default
  hypre_PCG_Logging                default
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =          81
   min and max degree      =           4          4

Norms of error:
   energy norm of error       8.6271851999E-02
   Linf norm of error         1.0764133692E-02
   L2 norm of error           4.3498770589E-03

Total Grid:
   number of vertices      =          17
   number of leaf elements =          22
   number of levels        =           3
   degrees of freedom      =         197
   min and max degree      =           4          4

Norms of error:
   energy norm of error       2.2078337577E-02
      reduced by              2.5591588758E-01
   Linf norm of error         5.0395031072E-03
      reduced by              4.6817544742E-01
   L2 norm of error           8.6482540229E-04
      reduced by              1.9881605631E-01

Total Grid:
   number of vertices      =          30
   number of leaf elements =          44
   number of levels        =           4
   degrees of freedom      =         381
   min and max degree      =           4          4

Norms of error:
   energy norm of error       3.9273114865E-03
      reduced by              1.7788076085E-01
   Linf norm of error         3.5673998139E-04
      reduced by              7.0788721388E-02
   L2 norm of error           8.3499752053E-05
      reduced by              9.6550993798E-02

Total Grid:
   number of vertices      =          51
   number of leaf elements =          76
   number of levels        =           5
   degrees of freedom      =         657
   min and max degree      =           4          4

Norms of error:
   energy norm of error       8.4877566763E-04
      reduced by              2.1612130093E-01
   Linf norm of error         5.8530721542E-05
      reduced by              1.6407110107E-01
   L2 norm of error           1.6251869739E-05
      reduced by              1.9463374848E-01

Total Grid:
   number of vertices      =         111
   number of leaf elements =         192
   number of levels        =           7
   degrees of freedom      =        1593
   min and max degree      =           4          4

Norms of error:
   energy norm of error       1.9610591733E-04
      reduced by              2.3104563998E-01
   Linf norm of error         1.4914711546E-05
      reduced by              2.5481851501E-01
   L2 norm of error           2.3152497490E-06
      reduced by              1.4246051600E-01

Total Grid:
   number of vertices      =         182
   number of leaf elements =         320
   number of levels        =           7
   degrees of freedom      =        2645
   min and max degree      =           4          4

Norms of error:
   energy norm of error       4.4415211909E-05
      reduced by              1.1324291616E-01
   Linf norm of error         2.7347764131E-06
      reduced by              1.8336099929E-01
   L2 norm of error           4.0315663307E-07
      reduced by              8.7065473876E-02

Total Grid:
   number of vertices      =         349
   number of leaf elements =         642
   number of levels        =           9
   degrees of freedom      =        5245
   min and max degree      =           4          4

Norms of error:
   energy norm of error       1.6451885598E-05
      reduced by              3.7041105716E-01
   Linf norm of error         9.0458365892E-07
      reduced by              3.3077060874E-01
   L2 norm of error           1.2877022825E-07
      reduced by              3.1940495997E-01

Total Grid:
   number of vertices      =         713
   number of leaf elements =        1344
   number of levels        =           9
   degrees of freedom      =       10913
   min and max degree      =           4          4

Norms of error:
   energy norm of error       4.4783657888E-06
      reduced by              2.7220987906E-01
   Linf norm of error         6.5998370775E-07
      reduced by              7.2959941432E-01
   L2 norm of error           7.4538581861E-08
      reduced by              5.7884949708E-01

Total Grid:
   number of vertices      =         713
   number of leaf elements =        1344
   number of levels        =           9
   degrees of freedom      =       10913
   min and max degree      =           4          4

Norms of error:
   energy norm of error       4.4783657888E-06
   Linf norm of error         6.5998370775E-07
   L2 norm of error           7.4538581861E-08

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           7
termination condition:
  maximum vertices achieved
---------------------------------------------------------
