---------------------------------------------------------
           PHAML   Version 1.9.1

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree                      4
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    true
  solver             CG_SOLVER
  preconditioner     MG_PRECONDITION
  mg_cycles                   2
  mg_tol             MG_NO_TOL
  mg_prerelax                 1
  mg_postrelax                2
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_NONE
  krylov_iter               100
  krylov_tol         KRYLOV_ERREST_TOL
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =          81
   min and max degree      =           4          4

Norms of error:
   energy norm of error       8.6275682465E-02
   L2 norm of error           4.3625765349E-03

Total Grid:
   number of vertices      =          19
   number of leaf elements =          24
   number of levels        =           3
   degrees of freedom      =         217
   min and max degree      =           4          4

Norms of error:
   energy norm of error       7.7771489676E-03
      reduced by              9.0143001428E-02
   L2 norm of error           1.9279268390E-04
      reduced by              4.4192390061E-02

Total Grid:
   number of vertices      =          28
   number of leaf elements =          40
   number of levels        =           4
   degrees of freedom      =         349
   min and max degree      =           4          4

Norms of error:
   energy norm of error       3.9461995661E-03
      reduced by              5.0740953819E-01
   L2 norm of error           8.4257815339E-05
      reduced by              4.3703844790E-01

Total Grid:
   number of vertices      =          51
   number of leaf elements =          76
   number of levels        =           5
   degrees of freedom      =         657
   min and max degree      =           4          4

Norms of error:
   energy norm of error       8.4877561841E-04
      reduced by              2.1508684601E-01
   L2 norm of error           1.6251368200E-05
      reduced by              1.9287668609E-01

Total Grid:
   number of vertices      =         111
   number of leaf elements =         192
   number of levels        =           7
   degrees of freedom      =        1593
   min and max degree      =           4          4

Norms of error:
   energy norm of error       1.9610591519E-04
      reduced by              2.3104565086E-01
   L2 norm of error           2.3151333562E-06
      reduced by              1.4245775049E-01

Total Grid:
   number of vertices      =         182
   number of leaf elements =         320
   number of levels        =           7
   degrees of freedom      =        2645
   min and max degree      =           4          4

Norms of error:
   energy norm of error       4.4301736095E-05
      reduced by              1.1295359462E-01
   L2 norm of error           3.9316644135E-07
      reduced by              8.4912266566E-02

Total Grid:
   number of vertices      =         363
   number of leaf elements =         670
   number of levels        =           9
   degrees of freedom      =        5469
   min and max degree      =           4          4

Norms of error:
   energy norm of error       1.4419188250E-05
      reduced by              3.2547682148E-01
   L2 norm of error           8.9767156952E-08
      reduced by              2.2831846137E-01

Total Grid:
   number of vertices      =         712
   number of leaf elements =        1340
   number of levels        =           9
   degrees of freedom      =       10885
   min and max degree      =           4          4

Norms of error:
   energy norm of error       2.5555687496E-06
      reduced by              1.7723388483E-01
   L2 norm of error           1.1681990718E-08
      reduced by              1.3013657906E-01

Total Grid:
   number of vertices      =         712
   number of leaf elements =        1340
   number of levels        =           9
   degrees of freedom      =       10885
   min and max degree      =           4          4

Norms of error:
   energy norm of error       2.5555687496E-06
   L2 norm of error           1.1681990718E-08

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           7
termination condition:
  maximum vertices achieved
---------------------------------------------------------
