---------------------------------------------------------
           PHAML   Version 1.9.1

Output from the master process
  PDE id is     0
  Number of slave processors is     4

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   PHASES
  print_error_who    MASTER
  print_error_what   ENERGY_L2_ERR
  print_errest_what  NEVER
  print_time_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    EXPLICIT_ERRIND
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ_SMOOTH
  derefine           true
  partition_method   RTK
  prebalance         BALANCE_ELEMENTS
  ignore_quad_err    false
  solver             MG_SOLVER
  mg_cycles                   1
  mg_tol             MG_ERREST_TOL
  mg_prerelax                 5
  mg_postrelax                5
  mg_prerelax_ho              1
  mg_postrelax_ho             1
  mg_comm            MGCOMM_FUDOP
---------------------------------------------------------

Total Grid:
   number of vertices      =           9
   number of leaf elements =           8
   number of levels        =           1
   degrees of freedom      =           9
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.4822035936E+00
   L2 norm of error           3.5000011056E-01

Total Grid:
   number of vertices      =          29
   number of leaf elements =          40
   number of levels        =           5
   degrees of freedom      =          29
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.4543841263E+00
      reduced by              5.8592459137E-01
   L2 norm of error           9.0122660850E-02
      reduced by              2.5749323538E-01

Total Grid:
   number of vertices      =          36
   number of leaf elements =          48
   number of levels        =           6
   degrees of freedom      =          36
   min and max degree      =           1          1

Norms of error:
   energy norm of error       1.4268183054E+00
      reduced by              9.8104639593E-01
   L2 norm of error           9.0508407781E-02
      reduced by              1.0042802435E+00

Total Grid:
   number of vertices      =          82
   number of leaf elements =         132
   number of levels        =           7
   degrees of freedom      =          82
   min and max degree      =           1          1

Norms of error:
   energy norm of error       8.2034531693E-01
      reduced by              5.7494728925E-01
   L2 norm of error           2.7384432804E-02
      reduced by              3.0256230858E-01

Total Grid:
   number of vertices      =         145
   number of leaf elements =         246
   number of levels        =           8
   degrees of freedom      =         145
   min and max degree      =           1          1

Norms of error:
   energy norm of error       5.1482463638E-01
      reduced by              6.2757064099E-01
   L2 norm of error           1.3469130486E-02
      reduced by              4.9185354989E-01

Total Grid:
   number of vertices      =         334
   number of leaf elements =         588
   number of levels        =          10
   degrees of freedom      =         334
   min and max degree      =           1          1

Norms of error:
   energy norm of error       3.7047010437E-01
      reduced by              3.5980222992E-01
   L2 norm of error           5.8870553585E-03
      reduced by              2.1853880488E-01

Total Grid:
   number of vertices      =         626
   number of leaf elements =        1166
   number of levels        =          11
   degrees of freedom      =         626
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.4614984834E-01
      reduced by              6.6442567278E-01
   L2 norm of error           3.3872238386E-03
      reduced by              5.7536809700E-01

Total Grid:
   number of vertices      =         626
   number of leaf elements =        1166
   number of levels        =          11
   degrees of freedom      =         626
   min and max degree      =           1          1

Norms of error:
   energy norm of error       2.4614984834E-01
   L2 norm of error           3.3872238386E-03

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           6
termination condition:
  maximum vertices achieved
---------------------------------------------------------
