
------------------------------------------------------
          PHAML Version 1.11.0 WARNING
parallel not yet supported in 3D; setting nproc to 1
------------------------------------------------------

---------------------------------------------------------
           PHAML   Version 1.11.0

Output from the master process
  PDE id is     0
  Number of slave processors is     1
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert           infinity
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               REFINE_ONLY
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         false
  isosceles_right_triangles  false
  print_grid_when    NEVER
  print_linsys_when  NEVER
  print_solver_when  NEVER
  print_error_when   NEVER
  print_time_when    NEVER
  print_eval_when    NEVER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    HIERARCHICAL_COEFFICIENT
  errtype            ABSOLUTE_ERROR
  reftype            H_UNIFORM
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           false
  partition_method   RTK
  ignore_quad_err    true
  solver             default
  preconditioner     default
  eigensolver        SLEPC_KRYLOV_SCHUR
  num_eval                    1
  lambda0            -infinity
  scale_evec         SCALE_LINF
  transformation     ST_NONE
  eigen_ncv          default
  eigen_maxit        default
  eigen_tol          1.0000000000E-10
  harmonic_extraction  false
  true_residual        false
---------------------------------------------------------

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           1
termination condition:
  one trip refinement
---------------------------------------------------------
---------------------------------------------------------
           PHAML   Version 1.11.0

Output from the master process
  PDE id is     0
  Number of slave processors is     1
  Number of OpenMP threads is       1

Subroutine phaml_solve_pde parameters:
  max_elem           infinity
  max_vert                  500
  max_eq             infinity
  max_lev            infinity
  stop_on_maxlev     false
  max_deg                    22
  stop_on_maxdeg     false
  max_refsolveloop   infinity
  task               BALANCE_REFINE_SOLVE
  solve_init         true
  system_size                 1
  pde_has_first_order_terms  false
  pde_has_cross_derivative   false
  laplacian_operator         false
  isosceles_right_triangles  false
  print_grid_when    PHASES
  print_grid_who     MASTER
  print_linsys_when  NEVER
  print_solver_when  PHASES
  print_solver_who   MASTER
  print_error_when   NEVER
  print_time_when    NEVER
  print_eval_when    PHASES
  print_eval_who     MASTER
  pause_after_draw   false
  pause_after_phases false
  pause_at_start     false
  pause_at_end       false
  degree             existing
  sequential_vert           100
  inc_factor          2.0000000000E+00
  error_estimator    HIERARCHICAL_COEFFICIENT
  errtype            ABSOLUTE_ERROR
  reftype            H_ADAPTIVE
  edge_rule          MINIMUM_RULE
  refterm            DOUBLE_NEQ
  derefine           false
  partition_method   RTK
  ignore_quad_err    true
  solver             default
  preconditioner     default
  eigensolver        SLEPC_LANCZOS
  num_eval                    5
  lambda0             3.5000000000E+01
  scale_evec         SCALE_LINF
  transformation     ST_SHIFT_INVERT
  st_shift           lambda0
  eigen_ncv          default
  eigen_maxit        default
  eigen_tol          1.0000000000E-10
  harmonic_extraction  false
  true_residual        false
---------------------------------------------------------

Total Grid:
   number of vertices      =          38
   number of leaf elements =          89
   number of levels        =           4
   degrees of freedom      =          38
   min and max degree      =           1          1

Solver information:
   number of column vectors   =          20
   maximum iterations allowed =         100
   number of iterations used  =           1
   number of converged eigens =           5
   eigensolver L2 residual    =   1.5493723364E-13
                                  5.0129387807E-11
                                  2.8111390167E-10
                                  1.2461614881E-09
                                  1.2633048819E-09
   eigensolver eval errest    =   9.7757717687E-15
                                  1.0349312528E-12
                                  5.4219383593E-12
                                  1.8104234663E-11
                                  1.7369340008E-11

Eigenvalues and error estimates:
     8.9781598142E+01  2.8333599620E+00
     1.9632195068E+02  4.1450255603E+00
     2.1242615058E+02  4.8191443918E+00
     2.6649538300E+02  6.1802354659E+00
     2.7609609308E+02  4.5397821490E+00

Total Grid:
   number of vertices      =          89
   number of leaf elements =         298
   number of levels        =           6
   degrees of freedom      =          89
   min and max degree      =           1          1

Solver information:
   number of column vectors   =          20
   maximum iterations allowed =         100
   number of iterations used  =         100
   number of converged eigens =           4
   eigensolver L2 residual    =   1.0804801010E-13
                                  9.6311107085E-14
                                  9.8797257517E-13
                                  6.9602258440E-09
   eigensolver eval errest    =   4.3417584014E-15
                                  2.5841339314E-15
                                  2.4771471560E-14
                                  1.3780463273E-10

Eigenvalues and error estimates:
     7.2942602284E+01  2.0142109437E+00
     8.1300700001E+01  2.8104382543E+00
     9.7965024426E+01  3.9574788311E+00
     1.1899570606E+02  2.9376604250E+00
     0.0000000000E+00  0.0000000000E+00

Total Grid:
   number of vertices      =         167
   number of leaf elements =         673
   number of levels        =           7
   degrees of freedom      =         167
   min and max degree      =           1          1

Solver information:
   number of column vectors   =          20
   maximum iterations allowed =         100
   number of iterations used  =         100
   number of converged eigens =           2
   eigensolver L2 residual    =   1.4945994811E-12
                                  1.5018822149E-09
   eigensolver eval errest    =   9.7325347880E-14
                                  4.3737721242E-11

Eigenvalues and error estimates:
     4.1435029215E+01  1.4259427544E+00
     6.4087782363E+01  1.7433546657E+00
     0.0000000000E+00  0.0000000000E+00
     0.0000000000E+00  0.0000000000E+00
     0.0000000000E+00  0.0000000000E+00

Total Grid:
   number of vertices      =         328
   number of leaf elements =        1404
   number of levels        =           9
   degrees of freedom      =         328
   min and max degree      =           1          1

Solver information:
   number of column vectors   =          20
   maximum iterations allowed =         100
   number of iterations used  =         100
   number of converged eigens =           2
   eigensolver L2 residual    =   4.0043685692E-14
                                  1.9714178613E-14
   eigensolver eval errest    =   2.5835373321E-15
                                  5.2909406511E-16

Eigenvalues and error estimates:
     2.5242111522E+01  6.6112844718E-01
     4.3341192078E+01  1.1159387963E+00
     0.0000000000E+00  0.0000000000E+00
     0.0000000000E+00  0.0000000000E+00
     0.0000000000E+00  0.0000000000E+00

Total Grid:
   number of vertices      =         628
   number of leaf elements =        2976
   number of levels        =          10
   degrees of freedom      =         628
   min and max degree      =           1          1

Solver information:
   number of column vectors   =          20
   maximum iterations allowed =         100
   number of iterations used  =         100
   number of converged eigens =           5
   eigensolver L2 residual    =   1.8930539441E-13
                                  1.3075530438E-13
                                  8.8819466639E-12
                                  1.0300092920E-11
                                  9.4756037350E-10
   eigensolver eval errest    =   1.0006595185E-14
                                  3.7831499486E-15
                                  2.1895722243E-13
                                  2.1388931098E-13
                                  1.8297509387E-11

Eigenvalues and error estimates:
     1.9835577343E+01  1.4065881592E-01
     3.3907144034E+01  6.0363784484E-01
     3.8564293013E+01  8.7161693099E-01
     4.4390086652E+01  6.6602036747E-01
     4.6956733574E+01  8.7048412027E-01

Total Grid:
   number of vertices      =         628
   number of leaf elements =        2976
   number of levels        =          10
   degrees of freedom      =         628
   min and max degree      =           1          1

Eigenvalues and error estimates:
     1.9835577343E+01  1.4065881592E-01
     3.3907144034E+01  6.0363784484E-01
     3.8564293013E+01  8.7161693099E-01
     4.4390086652E+01  6.6602036747E-01
     4.6956733574E+01  8.7048412027E-01

---------------------------------------------------------
phaml_solve_pde complete

number of loops through phases =           4
termination condition:
  maximum vertices achieved
---------------------------------------------------------
